source/shared/cpp/ObjectModel/Container.cpp

Add inputs to container/column parseable items

---

source/android/adaptivecards/src/main/cpp/objectmodel_wrap.cpp
source/android/adaptivecards/src/main/java/com/microsoft/adaptivecards/objectmodel/AdaptiveCardObjectModel.java
source/android/adaptivecards/src/main/java/com/microsoft/adaptivecards/objectmodel/AdaptiveCardObjectModelJNI.java
source/android/adaptivecards/src/main/java/com/microsoft/adaptivecards/objectmodel/AdaptiveCardSchemaKey.java
source/android/adaptivecards/src/main/java/com/microsoft/adaptivecards/objectmodel/Column.java
source/android/adaptivecards/src/main/java/com/microsoft/adaptivecards/objectmodel/Container.java
source/android/adaptivecards/src/main/java/com/microsoft/adaptivecards/objectmodel/ContainerStyle.java
source/android/adaptivecards/src/main/java/com/microsoft/adaptivecards/objectmodel/ShowCardOptions.java
source/shared/cpp/ObjectModel/Column.cpp
source/shared/cpp/ObjectModel/Column.h
source/shared/cpp/ObjectModel/Container.cpp
source/shared/cpp/ObjectModel/Container.h
source/shared/cpp/ObjectModel/Enums.cpp
source/shared/cpp/ObjectModel/Enums.h
source/shared/cpp/ObjectModel/HostOptions.h
source/uwp/Renderer/XamlCardRenderer.vcxproj
source/uwp/Renderer/XamlCardRenderer.vcxproj.filters
source/uwp/Renderer/idl/AdaptiveCards.XamlCardRenderer.idl
source/uwp/Renderer/lib/AdaptiveColumn.h
source/uwp/Renderer/lib/AdaptiveContainer.cpp
source/uwp/Renderer/lib/AdaptiveContainer.h
source/uwp/Renderer/lib/AdaptiveContainerOptions.cpp
source/uwp/Renderer/lib/AdaptiveContainerOptions.h
source/uwp/Renderer/lib/AdaptiveContainerStyleConfig.cpp
source/uwp/Renderer/lib/AdaptiveContainerStyleConfig.h
source/uwp/Renderer/lib/XamlBuilder.cpp
source/uwp/Renderer/lib/XamlBuilder.h

As a result of schema changes and the addition of hostConfig, Column is no longer a Container subclass.

Add emphasis property to container in shared model and add renderer support in UWP.

---

source/html/README.md

Notice a small typo while reading the docs.
```diff
- pacakge
+ package
```

Fix /source/html/README.md type [pacakge > package]

---

source/html/renderer/src/card-elements.ts
source/website/wwwroot/visualizer/built/visualizer-with-renderer.js

Single line inputs now use input["text"] instead of textarea

Fix single line text input showing scrollbar and accepting Enter

---

source/html/renderer/src/card-elements.ts

https://github.com/Microsoft/AdaptiveCards/issues/342

Set default value of date input in html renderer

---

source/html/renderer/src/card-elements.ts
source/html/renderer/src/enums.ts
source/html/visualizer/src/app.ts

It is now possible to explicitly select the button style ("link" or "button") in ActionSet elements and on the card itself.

Some minor fixes, and introduce actionStyle

---

source/html/renderer/src/schema.ts
source/html/renderer/src/utils.ts
source/tools/hostConfig/json-to-scss/.npmignore
source/tools/hostConfig/json-to-scss/index.js
source/tools/hostConfig/json-to-scss/index.ts
source/tools/hostConfig/scss-to-json/.npmignore
source/tools/hostConfig/scss-to-json/index.js
source/tools/hostConfig/scss-to-json/index.ts
source/tools/hostConfig/scss-to-json/package.json
source/tools/hostConfig/scss-to-json/readme.md

Also a few updates to some tooling are in here too.

Add HorizontalAlignment and Separation to ICardElement

---

source/shared/cpp/ObjectModel/BaseInputElement.cpp
source/shared/cpp/ObjectModel/BaseInputElement.h
source/shared/cpp/ObjectModel/ChoiceSetInput.cpp
source/shared/cpp/ObjectModel/ChoiceSetInput.h
source/uwp/Renderer/idl/AdaptiveCards.XamlCardRenderer.idl
source/uwp/Renderer/lib/AdaptiveChoiceSetInput.h
source/uwp/Renderer/lib/AdaptiveDateInput.cpp
source/uwp/Renderer/lib/AdaptiveDateInput.h
source/uwp/Renderer/lib/AdaptiveNumberInput.cpp
source/uwp/Renderer/lib/AdaptiveNumberInput.h
source/uwp/Renderer/lib/AdaptiveTextInput.cpp
source/uwp/Renderer/lib/AdaptiveTextInput.h
source/uwp/Renderer/lib/AdaptiveTimeInput.cpp
source/uwp/Renderer/lib/AdaptiveTimeInput.h
source/uwp/Renderer/lib/AdaptiveToggleInput.cpp
source/uwp/Renderer/lib/AdaptiveToggleInput.h

Add IsRequired property to inputs

---

source/android/adaptivecards/src/main/cpp/objectmodel_wrap.cpp
source/android/adaptivecards/src/main/java/com/microsoft/adaptivecards/objectmodel/AdaptiveCard.java
source/android/adaptivecards/src/main/java/com/microsoft/adaptivecards/objectmodel/AdaptiveCardObjectModelJNI.java
source/android/adaptivecards/src/main/java/com/microsoft/adaptivecards/objectmodel/BaseActionElement.java
source/android/adaptivecards/src/main/java/com/microsoft/adaptivecards/objectmodel/BaseCardElement.java
source/android/adaptivecards/src/main/java/com/microsoft/adaptivecards/objectmodel/BaseInputElement.java
source/android/adaptivecards/src/main/java/com/microsoft/adaptivecards/objectmodel/ChoiceInput.java
source/android/adaptivecards/src/main/java/com/microsoft/adaptivecards/objectmodel/ChoiceSetInput.java
source/android/adaptivecards/src/main/java/com/microsoft/adaptivecards/objectmodel/Column.java
source/android/adaptivecards/src/main/java/com/microsoft/adaptivecards/objectmodel/ColumnSet.java
source/android/adaptivecards/src/main/java/com/microsoft/adaptivecards/objectmodel/Container.java
source/android/adaptivecards/src/main/java/com/microsoft/adaptivecards/objectmodel/Fact.java
source/android/adaptivecards/src/main/java/com/microsoft/adaptivecards/objectmodel/FactSet.java
source/android/adaptivecards/src/main/java/com/microsoft/adaptivecards/objectmodel/Image.java
source/android/adaptivecards/src/main/java/com/microsoft/adaptivecards/objectmodel/ImageSet.java
source/android/adaptivecards/src/main/java/com/microsoft/adaptivecards/objectmodel/TextBlock.java

Updating auto-generated wrappers to latest.

Re-generate swig wrappers

---

source/ios/AdaptiveCards/ADCIOSFramework/ADCIOSFramework.xcodeproj/project.pbxproj
source/ios/AdaptiveCards/ADCIOSFramework/ADCIOSFramework/ACRColumnRenderer.mm
source/ios/AdaptiveCards/ADCIOSFramework/ADCIOSFramework/ACRColumnSetRenderer.mm
source/ios/AdaptiveCards/ADCIOSFramework/ADCIOSFramework/ACRImageRenderer.mm
source/ios/AdaptiveCards/ADCIOSFramework/ADCIOSFramework/ACRRegistration.mm
source/ios/AdaptiveCards/ADCIOSFramework/ADCIOSFramework/ACRSeparator.h
source/ios/AdaptiveCards/ADCIOSFramework/ADCIOSFramework/ACRSeparator.mm
source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer/ViewController.m

- Implemented Separator
- Visualizer Viewing Area Adjustment

Implemented Separator

---

source/html/renderer/src/card-elements.ts
source/html/renderer/src/enums.ts

This is the implementation of the design specified here: https://github.com/Microsoft/AdaptiveCards/issues/477
This will not be merged until the design is approved.

Enhanced background image support

---

source/html/renderer/src/card-elements.ts

This change is aimed at making it possible to align content to the bottom of a fixed-height card.

Add height property to all elements

---

source/html/renderer/src/card-elements.ts
source/html/visualizer/src/app.ts

Adding the ability to show info bar in action card pane on HttpAction is executed.
Demo this info bar in visualizer.

Qinmen/js renderer/showinfobaronhttpaction

---

source/html/renderer/src/card-elements.ts
source/html/renderer/src/utils.ts
source/html/visualizer/src/app.ts

This will not be merged until the associated issue is reviewed and approved.

Add ability for renderers to toggle the visibility of rendered elements

---

schemas/adaptive-card.json
source/website/wwwroot/explorer/index.html
source/website/wwwroot/schemas/adaptive-card.json
source/website/wwwroot/visualizer/schemas/adaptive-card.json

Action.ShowCard takes an AdaptiveCard, not a Container. Fixed. in the
schema and website docs I could find.
Closes #446

Fixed documentation and schema for Action.ShowCard

---

source/uwp/AdaptiveCardsNuget/AdaptiveCards.UWP.Beta.nuspec

changed to avoid packaging naming conflict

update nuget package name

---

source/uwp/Renderer/lib/AdaptiveActionEventArgs.h
source/uwp/Renderer/lib/XamlCardRendererComponent.cpp

Create Default HostConfig in UWP renderer instantiation

---

source/shared/cpp/ObjectModel/BaseActionElement.cpp
source/shared/cpp/ObjectModel/BaseActionElement.h
source/shared/cpp/ObjectModel/BaseCardElement.cpp
source/shared/cpp/ObjectModel/BaseCardElement.h
source/shared/cpp/ObjectModel/BaseInputElement.cpp
source/shared/cpp/ObjectModel/BaseInputElement.h
source/shared/cpp/ObjectModel/Enums.cpp
source/shared/cpp/ObjectModel/Enums.h
source/shared/cpp/ObjectModel/SharedAdaptiveCard.cpp
source/shared/cpp/ObjectModel/SharedAdaptiveCard.h
source/uwp/Renderer/lib/AdaptiveCard.cpp

Add support for backgroundImage key to Adaptive Card in addition to the existing backgroundImageUrl key

---

source/dotnet/Library/AdaptiveCards.Html/Rendering/HtmlRenderer.cs

Implements ShowCard, OpenUrl, Submit and Http action render in dotnet html renderer. These actions will be rendered as <button> tags. The needed information, such as url, http method, will be transmitted via attibutes on the button tag.
For showcard action, each button will have a 1:1 mapping with the corresponding AdaptiveCard html element through a customized attribute ac-cardId. The consumer can then toggle the visibility of the corresponding card.
Also add name attribute to all input controls so submit action can pi it up.

Implement action renderers in dotnet html renderer

---

source/android/adaptivecards/build.gradle
source/android/adaptivecards/src/main/java/com/microsoft/adaptivecards/renderer/action/HttpActionRenderer.java
source/android/adaptivecards/src/main/java/com/microsoft/adaptivecards/renderer/action/SubmitActionRenderer.java
source/android/adaptivecards/src/main/java/com/microsoft/adaptivecards/renderer/readonly/ColumnRenderer.java
source/android/adaptivecards/src/main/java/com/microsoft/adaptivecards/renderer/readonly/ImageRenderer.java
source/android/adaptivecards/src/main/java/com/microsoft/adaptivecards/renderer/registration/ActionRendererRegistration.java
source/android/mobile/build.gradle
source/android/mobile/src/main/AndroidManifest.xml

Android lint fix

---

source/html/renderer/src/card-elements.ts

if parent of status card is not set, it cannot find its host config file

set parent of status card

---

source/shared/cpp/ObjectModel/Column.cpp
source/shared/cpp/ObjectModel/ParseUtil.cpp
source/shared/cpp/ObjectModel/ParseUtil.h

Do not merge until we have a decision on #584

force column size parsing to lowercase in Shared Model

---

source/shared/cpp/ObjectModel/SharedAdaptiveCard.cpp
source/shared/cpp/ObjectModel/SharedAdaptiveCard.h
source/uwp/Renderer/idl/AdaptiveCards.XamlCardRenderer.idl
source/uwp/Renderer/lib/AdaptiveCard.cpp
source/uwp/Renderer/lib/AdaptiveCard.h
source/uwp/Renderer/lib/XamlBuilder.cpp

Also fixes the Property name for Adaptive Card Background Image in the WinRT projection

Add speak property to AdaptiveCard in shared model and UWP renderer

---

source/android/README.md
source/android/adaptivecards/build.gradle

added task that upload android aar to maven central

gradle updated

---

source/android/adaptivecards/gradle.properties

added dummy props

---

source/dotnet/Library/AdaptiveCards.Html/Rendering/HtmlRenderer.cs
source/dotnet/Library/AdaptiveCards.Xaml.Shared/Rendering/XamlColumnSet.cs
source/dotnet/Library/AdaptiveCards/Column.cs
source/dotnet/Library/AdaptiveCards/Enums.cs

ref: https://github.com/Microsoft/AdaptiveCards/issues/552

Rename Column size to width in dotnet

---

source/dotnet/Library/AdaptiveCards.Html/Rendering/HtmlRenderer.cs
source/dotnet/Library/AdaptiveCards.Html/Rendering/RenderContext.cs
source/dotnet/Library/AdaptiveCards.Xaml.Shared/Rendering/XamlTextBlock.cs
source/dotnet/Library/AdaptiveCards.Xaml.WPF/Rendering/XamlTextBlock.Wpf.cs
source/dotnet/Library/AdaptiveCards/Container.cs
source/dotnet/Library/AdaptiveCards/Enums.cs
source/dotnet/Library/AdaptiveCards/Image.cs
source/dotnet/Library/AdaptiveCards/Rendering/Config/FactSetConfig.cs
source/dotnet/Library/AdaptiveCards/Rendering/Config/HostConfig.cs
source/dotnet/Library/AdaptiveCards/Rendering/Config/TextBlockConfig.cs
source/dotnet/Library/AdaptiveCards/TextBlock.cs

ContainerStyle, TextSize, TextWeight, and ImageStyle
ref: https://github.com/Microsoft/AdaptiveCards/issues/630

Rename Normal to Default in dotnet

---

source/dotnet/Library/AdaptiveCards.Html/Rendering/HtmlRenderer.cs
source/dotnet/Library/AdaptiveCards.Xaml.Shared/Rendering/XamlColumnSet.cs
source/dotnet/Library/AdaptiveCards/ContainerSet.cs

ref: https://github.com/Microsoft/AdaptiveCards/issues/344

Add SelectAction to ColumnSet in dotnet

---

source/uwp/Renderer/lib/XamlBuilder.cpp
source/uwp/Renderer/lib/XamlBuilder.h

Add tapped event handler to toggle and choiceset inputs

---

source/uwp/Renderer/lib/AdaptiveHostConfig.cpp

We missed initializing one of the values in AdaptiveHostConfig

Initialize ImageConfig in AdaptiveHostConfig

---

CONTRIBUTING.md

Pointing to slightly updated process and information about the CLA.

Updating CONTRIBUTING.MD

---

source/nodejs/adaptivecards-visualizer/src/containers/host-container.ts
source/nodejs/adaptivecards-visualizer/src/containers/outlook.ts
source/nodejs/adaptivecards/src/card-elements.ts
source/nodejs/adaptivecards/src/text-formatters.ts

Updated DATE and TIME functions

---

source/nodejs/adaptivecards/src/card-elements.ts
source/nodejs/adaptivecards/src/host-config.ts

fix some properties in host config don't accept 0 or false as value;
clear the array in parse function to avoid append due to multiple parse

fix some properties in host config don't accept 0 or false as value;

---

source/shared/cpp/AdaptiveCardsSharedModel/AdaptiveCardsSharedModel/AdaptiveCardsSharedModel.vcxproj
source/shared/cpp/AdaptiveCardsSharedModel/AdaptiveCardsSharedModel/AdaptiveCardsSharedModel.vcxproj.filters
source/shared/cpp/AdaptiveCardsSharedModel/AdaptiveCardsSharedModelUnitTest/DateAndTimeUnitTest.cpp
source/shared/cpp/ObjectModel/TextBlock.cpp

Make space in Date modifier optional

---

source/nodejs/adaptivecards/src/card-elements.ts
source/nodejs/adaptivecards/src/rendercard.ts

Note there was a bug in the onExecuteAction handler where both the card's handler and the global handler were called

Add other handles to RenderOptions and rename to IRenderOptions

---

source/shared/cpp/ObjectModel/Enums.cpp

Add padding to spacing mapping

---

source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer/ViewController.m
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards.xcodeproj/project.pbxproj
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRTextBlockRenderer.mm
source/shared/cpp/ObjectModel/MarkDownHtmlGenerator.cpp

- Added mark down support for iOS
- Fixed Compiler Warning of implicit type conversion
- Fixed vertical scroll issue with sample app

fixed compiler warning added md support to iOS

---

source/shared/cpp/AdaptiveCardsSharedModel/AdaptiveCardsSharedModelUnitTest/MarkDownUnitTest.cpp
source/shared/cpp/ObjectModel/MarkDownParser.cpp
source/shared/cpp/ObjectModel/MarkDownParser.h

Escape text in MarkdownParser

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRInputNumberRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRInputRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRNumericTextField.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRTextField.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRTextField.mm

Added dismiss view to inputs where user can dismiss inputs such as keyboard/numpad

implemented input dismiss view

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRColumnSetRenderer.mm

- fixes issues where column expands to remove image

fixes cases interger is being truncated

---

source/android/adaptivecards/src/main/cpp/objectmodel_wrap.cpp
source/android/adaptivecards/src/main/java/com/microsoft/adaptivecards/objectmodel/AdaptiveCardObjectModelJNI.java
source/android/adaptivecards/src/main/java/com/microsoft/adaptivecards/objectmodel/AdaptiveCardParseException.java
source/android/adaptivecards/src/main/java/com/microsoft/adaptivecards/objectmodel/ChoiceSetInput.java
source/android/adaptivecards/src/main/java/com/microsoft/adaptivecards/renderer/input/ChoiceSetInputRenderer.java
source/shared/cpp/ObjectModel/ChoiceSetInput.cpp
source/shared/cpp/ObjectModel/ChoiceSetInput.h

Also updating the Android renderer to support default value for multi-select and re-run swig.
Closes #1095

Adding value property to ChoiceSetInput

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRChoiceSetViewDataSource.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRChoiceSetViewDataSource.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRChoiceSetViewDataSourceCompactStyle.mm

- added default values for choice set

added default values for choice set

---

source/xamarin/AdaptiveCards.Rendering.Xamarin.Android.Sample/MainActivity.cs

Consolidate the actions in to ICardActionHandler and handle method signature changes.
Addresses issue #1181

Fix Xamarin Android build break caused by changes in Android ActionHandler

---

source/uwp/Renderer/idl/AdaptiveCards.Rendering.Uwp.idl
source/uwp/Renderer/lib/AdaptiveCardRendererComponent.cpp
source/uwp/Renderer/lib/AsyncOperations.h
source/uwp/Renderer/lib/RenderedAdaptiveCard.cpp
source/uwp/Renderer/lib/RenderedAdaptiveCard.h
source/uwp/Renderer/lib/XamlBuilder.cpp
source/uwp/Renderer/lib/XamlBuilder.h

Change to return FrameworkElement instead of UIElement

---

source/android/adaptivecards/src/main/cpp/objectmodel_wrap.cpp
source/android/adaptivecards/src/main/java/com/microsoft/adaptivecards/objectmodel/AdaptiveCardObjectModelJNI.java
source/android/adaptivecards/src/main/java/com/microsoft/adaptivecards/objectmodel/BaseActionElement.java
source/android/adaptivecards/src/main/java/com/microsoft/adaptivecards/objectmodel/BaseCardElement.java
source/android/adaptivecards/src/main/java/com/microsoft/adaptivecards/objectmodel/ContainerStyleDefinition.java
source/shared/cpp/ObjectModel/BaseActionElement.cpp
source/shared/cpp/ObjectModel/BaseActionElement.h
source/shared/cpp/ObjectModel/BaseCardElement.cpp
source/shared/cpp/ObjectModel/BaseCardElement.h

Objectmodel_wrap.cpp and files in source/android/adaptivecards/src/main/java/com/microsoft/adaptivecards/objectmodel are auto-generated by SWIG

Adding Type string to BaseCardElement and BaseActionElement

---

source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer.xcodeproj/project.pbxproj
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards.xcodeproj/project.pbxproj
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRTextBlockRenderer.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRTextBlockRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRViewController.mm

- added native ios date-time rendering for compact and long

rebased native-date-time

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACOHostConfig.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACOHostConfig.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRActionShowCardRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRColumnRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRColumnSetRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRContainerRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRImageRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRLongPressGestureRecognizerFactory.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRLongPressGestureRecognizerFactory.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRRendererPrivate.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRShowCardTarget.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRShowCardTarget.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRViewController.mm

- fixes issue 1191 fallback iOS system font when request font is not supported by the system.
- refactored the usage of HostConfig.

fixes issue #1191 & refactorred HostConfig Uses

---

README.md

TODO:Need to add the adaptive 1.0 png to the content folder

Updated for 1.0 details

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/ColumnRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/ContainerRenderer.java
source/shared/cpp/ObjectModel/Column.cpp

Also Added check in Android for empty items list

Allowing empty items in Column

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/AdaptiveCardRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/AdaptiveWarning.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/ChoiceSetInputRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/DateInputRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/NumberInputRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/TextInputRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/TimeInputRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/ToggleInputRenderer.java

Also fixed a visual bug where the space between the body and the actions has no background color

Check the supporstInteractivity option in the host config before rendering input/actions

---

source/shared/cpp/ObjectModel/jsoncpp.cpp
source/uwp/Renderer/lib/AdaptiveCard.cpp
source/uwp/Renderer/lib/AdaptiveChoiceInput.cpp
source/uwp/Renderer/lib/AdaptiveChoiceSetInput.cpp
source/uwp/Renderer/lib/AdaptiveColumn.cpp
source/uwp/Renderer/lib/AdaptiveColumnSet.cpp
source/uwp/Renderer/lib/AdaptiveContainer.cpp
source/uwp/Renderer/lib/AdaptiveDateInput.cpp
source/uwp/Renderer/lib/AdaptiveFact.cpp
source/uwp/Renderer/lib/AdaptiveFactSet.cpp
source/uwp/Renderer/lib/AdaptiveImage.cpp
source/uwp/Renderer/lib/AdaptiveImageSet.cpp
source/uwp/Renderer/lib/AdaptiveOpenUrlAction.cpp
source/uwp/Renderer/lib/AdaptiveShowCardAction.cpp
source/uwp/Renderer/lib/AdaptiveSubmitAction.cpp
source/uwp/Renderer/lib/AdaptiveTextBlock.cpp
source/uwp/Renderer/lib/AdaptiveTextInput.cpp
source/uwp/Renderer/lib/AdaptiveTimeInput.cpp
source/uwp/Renderer/lib/AdaptiveToggleInput.cpp
source/uwp/Renderer/lib/XamlBuilder.h

Fixes the annotation issues for UWP

Fix annotations for UWP

---

source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer/ViewController.h
source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer/ViewController.m
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards.xcodeproj/project.pbxproj
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRActionOpenURLRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRActionShowCardRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRActionSubmitRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRButton.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRColumnView.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRContentStackView.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRRenderer.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRRendererPrivate.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRShowCardTarget.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRView.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRView.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRViewController.mm

return adaptive card with intrinsic content height

---

source/nodejs/adaptivecards-visualizer/src/containers/host-container.ts
source/nodejs/adaptivecards-visualizer/src/containers/outlook.ts
source/nodejs/adaptivecards/src/card-elements.ts

Fix lingering visualizer bug introduced by previous change in renderer

Fix undesirable separation when hiding first element in Container

---

source/shared/cpp/AdaptiveCardsSharedModel/AdaptiveCardsSharedModelUnitTest/AdaptiveCardsSharedModelUnitTest.vcxproj
source/shared/cpp/AdaptiveCardsSharedModel/AdaptiveCardsSharedModelUnitTest/AdaptiveCardsSharedModelUnitTest.vcxproj.filters
source/shared/cpp/AdaptiveCardsSharedModel/AdaptiveCardsSharedModelUnitTest/GatherImagesTest.cpp
source/shared/cpp/ObjectModel/BaseActionElement.cpp
source/shared/cpp/ObjectModel/BaseActionElement.h
source/shared/cpp/ObjectModel/BaseCardElement.cpp
source/shared/cpp/ObjectModel/BaseCardElement.h
source/shared/cpp/ObjectModel/Column.cpp
source/shared/cpp/ObjectModel/Column.h
source/shared/cpp/ObjectModel/ColumnSet.cpp
source/shared/cpp/ObjectModel/ColumnSet.h
source/shared/cpp/ObjectModel/Container.cpp
source/shared/cpp/ObjectModel/Container.h
source/shared/cpp/ObjectModel/Image.cpp
source/shared/cpp/ObjectModel/Image.h
source/shared/cpp/ObjectModel/ImageSet.cpp
source/shared/cpp/ObjectModel/ImageSet.h
source/shared/cpp/ObjectModel/SharedAdaptiveCard.cpp
source/shared/cpp/ObjectModel/SharedAdaptiveCard.h
source/shared/cpp/ObjectModel/ShowCardAction.cpp
source/shared/cpp/ObjectModel/ShowCardAction.h

While we're waiting for the approval that's blocking the UWP implementation, sending out the shared model implementation.

Add functionality to get resource URIs to the shared model

---

source/shared/cpp/AdaptiveCardsSharedModel/AdaptiveCardsSharedModelUnitTest/ExplicitDimensionTest.cpp
source/shared/cpp/ObjectModel/Column.cpp
source/shared/cpp/ObjectModel/Column.h
source/shared/cpp/ObjectModel/Image.cpp
source/shared/cpp/ObjectModel/Util.cpp
source/shared/cpp/ObjectModel/Util.h

Explicit Column Width Changes for Shared Models.

initial commit for the feature

---

source/uwp/Renderer/lib/XamlBuilder.cpp

Don't add a warning for SelectActions if there isn't a SelectAction

---

source/dotnet/Library/AdaptiveCards/AdaptiveTextBlock.cs
source/dotnet/Library/AdaptiveCards/Rendering/TextBlockConfig.cs

Couple of small changes that I missed in my previous review.

Missing changes from code review feedback for FactSets

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/AdaptiveCardRenderer.java

I have tested for `Action.OpenUrl`, `Action.Submit`, and `Action.ShowCard`

added on click listener for the whole card if it has selectAction

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/AdaptiveCardRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/action/ActionElementRenderer.java

Fix for this https://github.com/Microsoft/AdaptiveCards/issues/1426

[Android] Add horizontal scroll bar for horizontal layout actions

---

source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer/ViewController.m

updated app to show the usage of didLoadElements delegate
- view appears only after all elements have been fully loaded

updated sample app to use didLoadElements delegate

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/AdaptiveCardRenderer.java

In one of the merged PR we forgot to remove an extra button rendering, so this PR removes it

[Android] Fix double button rendering

---

source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer/ViewController.m

update sample app to render custom renderer correctly.

fixed custom renderer not being rendered

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRFactSetRenderer.mm

factset fix

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRImageSetUICollectionView.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRView.mm

changed ImageSetUICollectionView to use custom Image renderer when it's overriden

image set fix

---

source/nodejs/adaptivecards/src/card-elements.ts
source/nodejs/adaptivecards/src/enums.ts

TS, not my strong suit. Can you guys please check?
This takes care of https://github.com/Microsoft/AdaptiveCards/issues/1528

added InputTextStyle enum, connected to email input type

---

source/ios/.gitignore
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards.xcodeproj/project.pbxproj
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRImageRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRUIImageView.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRUIImageView.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRView.mm

fixed portrait mode fix when auto size used

image portrait mode fix when auto size used

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRSeparator.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRTextBlockRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRView.mm

fixes issues where there are large gap between UILables

adjust hugging priority for UILabel

---

samples/Tests/LongFactSet.json
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/FactSetRenderer.java

Changes the GridLayout used in the factset rendering for a TableLayout which fixes this issue: 
https://github.com/Microsoft/AdaptiveCards/issues/1472

[Android] Fix for cropped factsets

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/GenericImageLoaderAsync.java

I wasn't very happy with the way I handled exceptions from the other PR. Today while working on a different issue, I just figured out a better way. It would be much cleaner and more straight forward now

cleaned up exception handling in loading image

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRAggregateTarget.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRView.h

updated button's selected state

adjusted showcard location and button width

---

samples/Tests/InputsFormWithHeightStretch.json

Adds a missing file that was included in the solution but wasn't added to the commit. This missing file may make the build process to fail

[iOS] Add missing test for Vertical Stretch

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRRenderer.mm

made adjustment so that show card will appear below the buttons.
made adjustment so that buttons will have variable widths.

updated showcard rendering position

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRChoiceSetViewDataSourceCompactStyle.mm

fixes issue when compact style choice set doesn't have default values.

handles cases where compact style lacking defaults

---

source/ios/AdaptiveCards/ADCIOSVisualizer/resources/sample.json
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRSeparator.mm

fixes issue where separator is hard to see.

fixed separator issue

---

source/shared/cpp/ObjectModel/Column.cpp
source/shared/cpp/ObjectModel/Container.cpp
source/shared/cpp/ObjectModel/Enums.cpp
source/shared/cpp/ObjectModel/Enums.h
source/shared/cpp/ObjectModel/SharedAdaptiveCard.cpp
source/uwp/Renderer/idl/AdaptiveCards.Rendering.Uwp.idl

Remove Stretch from vertical content alignment

[Shared model][UWP] Remove Stretch from vertical content alignment

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRImageSetUICollectionView.mm

Fixes extra spacing issue in UICollectionView by more accurately calculating its intrinsic content size.

fixes extra spacing issue in UICollectionView

---

source/nodejs/adaptivecards/src/__tests__/inputs/text_input.spec.ts
source/nodejs/adaptivecards/src/card-elements.ts

As per https://github.com/Microsoft/AdaptiveCards/issues/1633 there were a couple of issues related to parse/toJSON roundtrips.

[TS] Fixed Input.Text style and horizontalAlignment roundtrip; added test

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/AdaptiveCardRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/action/ActionElementRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/ChoiceSetInputRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/DateInputRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/NumberInputRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/TimeInputRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/ToggleInputRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/ColumnRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/ColumnSetRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/ContainerRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/FactSetRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/ImageRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/ImageSetRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/TextBlockRenderer.java

This PR fixes this: https://github.com/Microsoft/AdaptiveCards/issues/1539

[Android] Change private for protected in all Renderers constructors

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/TextInputRenderer.java

This PR fixes this: https://github.com/Microsoft/AdaptiveCards/issues/1555

[Android] Add vertical scroll support for multiline text input

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards.xcodeproj/project.pbxproj
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRCellForCompactMode.xib
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRChoiceSetViewDataSource.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRDateTextField.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRInputChoiceSetRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRInputRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRTextField.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRTextField.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRTextView.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRTextView.mm

- allows multiline input
- enforces input limit
- placeholder text for UITextView

multiline input and input limit for textview and textfield

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/AdaptiveCardRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/action/ActionElementRenderer.java

This PR fixes this: https://github.com/Microsoft/AdaptiveCards/issues/1635
And maybe this: https://github.com/Microsoft/AdaptiveCards/issues/1381

[Android] Refocus when a show card changes visibility

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/AdaptiveCardRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/action/ActionElementRenderer.java

Reverts Microsoft/AdaptiveCards#1651

Revert "[Android] Refocus when a show card changes visibility"

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/AdaptiveCardRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/GenericImageLoaderAsync.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/IOnlineImageLoader.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/OnlineImageLoader.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/ImageRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/registration/CardRendererRegistration.java

Adds a new interface IOnlineImageLoader that allows overriding the way the application downloads images from online sources, trying to fix this: https://github.com/Microsoft/AdaptiveCards/issues/1540

[Android] Custom image downloading fix

---

source/ios/AdaptiveCards/ADCIOSVisualizer/resources/sample.json
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRFactSetRenderer.mm

maxwidth is a mandatory attribute, so priority is needed to be upgraded to "required"

factset's title maxwidth's priority changed to required.

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/TextInputRenderer.java

Fix for this https://github.com/Microsoft/AdaptiveCards/issues/1555

[Android] Fix for vertical scroll in input text

---

.vscode/settings.json
source/shared/cpp/ObjectModel/DateTimePreparsedToken.cpp
source/shared/cpp/ObjectModel/MediaSource.h
source/shared/cpp/ObjectModel/SharedAdaptiveCard.cpp

Only one little bit was breaking, the others are just removing warnings for unused and reorder.
@paulcam206 and @RebeccaAnne keep the awesome work, you have an avid reader here.

[CPP] Fix/cpp small fixes

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRChoiceSetViewDataSourceCompactStyle.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRContainerRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRContentStackView.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRImageSetUICollectionView.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRRenderer.mm

Fixes UI Issues

---

source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer/ViewController.h
source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer/ViewController.m
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards.xcodeproj/project.pbxproj
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACOAdaptiveCard.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACOAdaptiveCardPrivate.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRActionSetRenderer.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRActionSetRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRDateTextField.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRIBaseActionElementRenderer.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRInputRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRRegistration.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRRegistration.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRRendererPrivate.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRShowCardTarget.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRTextView.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRView.h

Added ActionsSet renderer
Adjusted inline showcard padding
Fixed UIScrollView interfering with ACRTextView's scrolling

allows action set view to be accessed

---

source/uwp/Renderer/lib/AdaptiveCard.cpp

Update version of UWP renderer

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/ImageRenderer.java

Add support for explicit image size for android

[Android] Add support for explicit image size

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/ColumnRenderer.java

Add support for explicit column width for android
Solves this: https://github.com/Microsoft/AdaptiveCards/issues/1663

[Android] Add support for explicit column width

---

samples/Tests/Image.BackgroundColor.json
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/ImageRenderer.java

Add support for background image color in Android
Fixes this: https://github.com/Microsoft/AdaptiveCards/issues/1413

[Android] Add support for background image color

---

source/shared/cpp/ObjectModel/Enums.cpp
source/shared/cpp/ObjectModel/Enums.h
source/shared/cpp/ObjectModel/HostConfig.cpp
source/shared/cpp/ObjectModel/HostConfig.h

added `iconSize` to actions config inside host config

added iconSize to shared object model

---

source/shared/cpp/AdaptiveCardsSharedModel/AdaptiveCardsSharedModelUnitTest/ResourceInformationTests.cpp
source/shared/cpp/ObjectModel/BaseActionElement.cpp

gathers images in actions

---

source/dotnet/Library/AdaptiveCards.Rendering.Wpf/AdaptiveActionRenderer.cs
source/dotnet/Library/AdaptiveCards.Rendering.Wpf/AdaptiveCardRenderer.cs
source/dotnet/Library/AdaptiveCards.Rendering.Wpf/AdaptiveRenderContext.cs
source/dotnet/Library/AdaptiveCards.Rendering.Wpf/Helpers/SelectActionHelper.cs

I was trying the card payload from [this issue](1023) and found out some `selectAction` bugs in the .NET WPF renderer:
- `backgroundColor` of the component needs to be handled better
- There are still extra spacing around components with `selectAction` that causes it to not align well with similar components
**Before:**
**After:**
The payload (with 2 `selectAction`) is:
```
{
"id": "4a0721fb-6143-4941-94e5-ae50ce9e4e87",
"minVersion": "1.0",
"fallbackText": "",
"speak": "",
"backgroundImage": "https://goo.gl/eYUNCW",
"body": [
{
"id": "93967c2b-fd15-495e-808e-e7ab98511c00",
"columns": [
{
"id": "2e817002-808e-4b9d-a299-d198cde16e03",
"width": "1",
"items": []
},
{
"id": …
```

fixed background color and removed extra spacing for selectAction button

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRButton.mm

add support for icon size hostconfig property for actions

apply hostconfig's iconsize to button images

---

source/shared/cpp/AdaptiveCardsSharedModel/AdaptiveCardsSharedModelUnitTest/AdaptiveCardsSharedModelUnitTest.vcxproj
source/shared/cpp/AdaptiveCardsSharedModel/AdaptiveCardsSharedModelUnitTest/AdaptiveCardsSharedModelUnitTest.vcxproj.filters
source/shared/cpp/AdaptiveCardsSharedModel/AdaptiveCardsSharedModelUnitTest/FactUnitTest.cpp

Additional unit test to bring full code coverage to `Fact`.

Fact Unit Test

---

source/dotnet/Library/AdaptiveCards.Rendering.Html/AdaptiveCardRenderer.cs
source/dotnet/Library/AdaptiveCards.Rendering.Wpf/AdaptiveImageRenderer.cs
source/dotnet/Library/AdaptiveCards.Rendering.Wpf/Helpers/ImageExtensions.cs
source/dotnet/Library/AdaptiveCards/AdaptiveImage.cs
source/dotnet/Library/AdaptiveCards/StringSizeWithUnitConverter.cs
source/dotnet/Test/AdaptiveCards.Test/AdaptiveCardApiTests.cs
source/dotnet/Test/AdaptiveCards.Test/AllPayloadTests.cs
source/dotnet/Test/AdaptiveCards.Test/SerializationTests.cs

wpf changes for explicity image size changes

wpf changes for explicit image size

---

source/nodejs/adaptivecards/src/card-elements.ts

Like in other card-elements, add CSS class names to FactSets and Facts

Add CSS class-names to FactSets and Fact card-elements

---

source/nodejs/adaptivecards/src/card-elements.ts
source/nodejs/adaptivecards/src/utils.ts

Also make CheckBox and RadioButton labels clickable

Fix CheckBox and RadioButton text not being truncated

---

source/dotnet/Library/AdaptiveCards.Rendering.Wpf/AdaptiveImageRenderer.cs

- corrected logic for checking the flag for explicit image

reversed logic

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRView.mm
source/shared/cpp/AdaptiveCardsSharedModel/AdaptiveCardsSharedModelUnitTest/MarkDownUnitTest.cpp
source/shared/cpp/ObjectModel/MarkDownParser.cpp
source/shared/cpp/ObjectModel/MarkDownParser.h

allows escaped chars to be renderered as html text

---

source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer/ViewController.h
source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer/ViewController.m
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRActionDelegate.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRChoiceSetViewDataSourceCompactStyle.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRShowCardTarget.mm

adds a new delegate that notifies superView of layout changes

notifies superview compactView's layout changes

---

source/uwp/Renderer/lib/AdaptiveCardRendererComponent.cpp

Fix ref counting issue in AdaptiveCardRenderer::get_HostConfig

---

samples/v1.1/Elements/MediaSource.json
schemas/adaptive-card.json
schemas/host-config.json
source/nodejs/adaptivecards-designer/index.html
source/nodejs/adaptivecards-site/schema-explorer-toc.yml
source/nodejs/adaptivecards-site/themes/adaptivecards/_config.yml
source/nodejs/adaptivecards-site/themes/adaptivecards/layout/_partial/header.ejs
source/nodejs/adaptivecards-site/themes/adaptivecards/scripts/generator-explorer.js

Merging my site updates with @matthidinger's

Update designer site. Add Media to schema.

---

source/dotnet/Library/AdaptiveCards/AdaptiveTypedElementConverter.cs
source/dotnet/Test/AdaptiveCards.Test/AdaptiveCardApiTests.cs

Fix issue with know properties being treated as additional in error cases

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/inputhandler/CheckBoxSetInputHandler.java
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRChoiceSetViewDataSource.mm

Fix choiceset separators on android and ios

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/TextBlockRenderer.java

Add markdown ordered list support to android

---

schemas/adaptive-card.json

Tweaks to adaptive-card.json schema so that it passes validation.

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRToggleInputDataSource.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRToggleInputDataSource.mm

This is the last request from Teams
It allows customization of UISwitch object without modifying customizing data source.

exposed toggle switch for customization

---

source/uwp/Build/CopySignFiles.cmd
source/uwp/Build/SignConfig.xml
source/uwp/Build/SignNugetConfig.xml
source/uwp/NuGet/AdaptiveCards.Rendering.Uwp.nuspec

Code copied and modified from the dotnet nuget signing scripts.
Validated through the build machines that the packages are properly signed.

Adding configurations to sign our uwp binaries as well as the nuget package

---

source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer.xcodeproj/project.pbxproj

Cherry-picking the change to the release/1.1 branch

fixes ios compilation build (#1989)

---

THIRD-PARTY-NOTICES.TXT

The sentence started with a period (.) 
Corrected that in this PR.

Minor change in THIRD-PARTY-NOTICES.TXT

---

source/android/adaptivecards/build.gradle

added a new task to create pom

updated gradle task

---

source/android/adaptivecards/build.gradle

* updated gradle task
* -CR Fix
* -CR Fix

updated gradle task (#2014)

---

schemas/adaptive-card.json

Fix actions definitions and subcard versioning

---

source/android/adaptivecards/build.gradle

updated gradle versioning for daily builds.

update versionning in build gradle task

---

source/dotnet/Library/AdaptiveCards.Rendering.Wpf/AdaptiveActionRenderer.cs
source/dotnet/Library/AdaptiveCards.Rendering.Wpf/AdaptiveCardRenderer.cs
source/dotnet/Library/AdaptiveCards.Rendering.Wpf/AdaptiveCards.Rendering.Wpf.csproj
source/dotnet/Library/AdaptiveCards.Rendering.Wpf/Properties/AssemblyInfo.cs
source/dotnet/Library/AdaptiveCards.Rendering.Wpf/Themes/generic.xaml
source/dotnet/Library/AdaptiveCards/AdaptiveAction.cs
source/dotnet/Library/AdaptiveCards/AdaptiveSentiment.cs
source/dotnet/Test/AdaptiveCards.Test/AdaptiveActionTests.cs

Solves half this issue: https://github.com/microsoft/adaptivecards/issues/1972
We're still misssing the HTML one

[.Net][WPF] Add primary and destructive button styling support

---

source/uwp/Renderer/lib/Vector.h

The vector implementation in vector.h didn't compile when specialized for a HSTRING vector due to HString not having a copy constructor. Updated the code to address this issue.

Fix HSTRING issues in vector.h

---

source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer.xcodeproj/project.pbxproj
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards.xcodeproj/project.pbxproj
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRView.mm

Solves this issue: https://github.com/Microsoft/AdaptiveCards/issues/2130

[iOS] Add data Uri support

---

source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer.xcodeproj/project.pbxproj
source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer/ViewController.m
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACOBaseActionElement.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACOBaseActionElement.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRActionOpenURLRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRActionShowCardRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRActionSubmitRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRButton.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRButton.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRButton.xib
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRInputRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRView.mm

Solves this issue: https://github.com/Microsoft/AdaptiveCards/issues/1971

[iOS] Add primary and destructive button styling support

---

samples/v1.0/Scenarios/FoodOrder.json
source/uwp/AdaptiveCardTestApp/Expected/SourceCards/v1.0.Scenarios.FoodOrder.ac548fb.json
source/uwp/AdaptiveCardTestApp/Expected/microsoft-teams.v1.0.Scenarios.FoodOrder.json
source/uwp/AdaptiveCardTestApp/Expected/outlook-desktop.v1.0.Scenarios.FoodOrder.json
source/uwp/AdaptiveCardTestApp/Expected/sample.v1.0.Scenarios.FoodOrder.json
source/uwp/AdaptiveCardTestApp/Expected/sampleDifferentFont.v1.0.Scenarios.FoodOrder.json
source/uwp/AdaptiveCardTestApp/Expected/skype.v1.0.Scenarios.FoodOrder.json
source/uwp/AdaptiveCardTestApp/Expected/windows-notification.v1.0.Scenarios.FoodOrder.json
source/uwp/AdaptiveCardTestApp/Expected/windows-timeline.v1.0.Scenarios.FoodOrder.json

Add schema ref to foodorder.json

---

schemas/adaptive-card.json

Mark media sources as required in the schema

---

source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer.xcodeproj/project.pbxproj

fixes compilation error looking for missing jsons

updates json files changes

---

source/dotnet/Library/AdaptiveCards.Rendering.Html/AdaptiveCards.Rendering.Html.csproj
source/dotnet/Library/AdaptiveCards.Rendering.Wpf.Xceed/AdaptiveCards.Rendering.Wpf.Xceed.csproj
source/dotnet/Library/AdaptiveCards.Rendering.Wpf/AdaptiveCards.Rendering.Wpf.csproj
source/dotnet/Library/AdaptiveCards/AdaptiveCards.csproj

Update nuget package metadata to have Microsoft as the author and the proper links

Update the nuget metadata for .NET packages

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/TextInputRenderer.java

fixes issue 2280

---

source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer/ACVTableViewController.m
source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer/ViewController.m

- removed host config json files from selection
- sorted sample jsons
- prevent app from rendering when input json is null or empty when apply button is touched.

updated ios sample app

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/ContainerRenderer.java

This PR fixes the issue that container layout cannot get rendered successfully.
[Issue #2308](https://github.com/Microsoft/AdaptiveCards/issues/2308)

[Android]Fix container layout issue (#2308)

---

source/uwp/Visualizer/ViewModel/DocumentViewModel.cs

Otherwise, the card can be garbage collected and actions would not work.

Have the visualizer hold on to the RenderedAdaptiveCard.

---

source/shared/cpp/ObjectModel/ActionParserRegistration.h
source/shared/cpp/ObjectModel/ActionSet.cpp
source/shared/cpp/ObjectModel/ActionSet.h
source/shared/cpp/ObjectModel/AdaptiveBase64Util.h
source/shared/cpp/ObjectModel/BaseActionElement.cpp
source/shared/cpp/ObjectModel/BaseActionElement.h
source/shared/cpp/ObjectModel/BaseCardElement.h
source/shared/cpp/ObjectModel/ChoiceSetInput.h
source/shared/cpp/ObjectModel/ColumnSet.h
source/shared/cpp/ObjectModel/Container.h
source/shared/cpp/ObjectModel/DateInput.h
source/shared/cpp/ObjectModel/ElementParserRegistration.h
source/shared/cpp/ObjectModel/FactSet.h
source/shared/cpp/ObjectModel/Image.h
source/shared/cpp/ObjectModel/ImageSet.h
source/shared/cpp/ObjectModel/Media.h
source/shared/cpp/ObjectModel/NumberInput.h
source/shared/cpp/ObjectModel/OpenUrlAction.h
source/shared/cpp/ObjectModel/ShowCardAction.h
source/shared/cpp/ObjectModel/SubmitAction.h
source/shared/cpp/ObjectModel/TextBlock.h
source/shared/cpp/ObjectModel/TextInput.h
source/shared/cpp/ObjectModel/ToggleInput.h
source/shared/cpp/ObjectModel/ToggleVisibilityTarget.cpp
source/shared/cpp/ObjectModel/UnknownElement.h

Assorted cleanup for cppcoreguidelines regressions.

Fix up some cppcore issues that have crept in

---

source/uwp/Renderer/lib/AdaptiveOpenUrlAction.cpp
source/uwp/Renderer/lib/AdaptiveShowCardAction.cpp
source/uwp/UWPUnitTests/ObjectModelTests.cs
source/uwp/UWPUnitTests/UWPUnitTests.csproj

Cherry-pick fixes to crashing constructors to release/1.1

Cherry-pick fixes to crashing constructors to release/1.1

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACOBaseCardElement.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRBaseCardElementRenderer.mm

making changes to reflect the changes in shared model for ios

---

custom.props
source/android/adaptivecards/build.gradle
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/TextInputRenderer.java
source/android/build.gradle

Remove the hard-coded black color from Android enabling dark themes for Android.

Cherry-pick Remove hardcoded color in Android Input (#2245)

---

source/uwp/Renderer/AdaptiveCardRenderer.vcxproj
source/uwp/Renderer/AdaptiveCardRenderer.vcxproj.filters
source/uwp/Renderer/idl/AdaptiveCards.Rendering.Uwp.idl
source/uwp/Renderer/lib/AdaptiveActionParserRegistration.cpp
source/uwp/Renderer/lib/AdaptiveElementParserRegistration.cpp
source/uwp/Renderer/lib/AdaptiveToggleVisibilityActionParser.cpp
source/uwp/Renderer/lib/AdaptiveToggleVisibilityActionParser.h
source/uwp/Renderer/lib/Util.h
source/uwp/UWPUnitTests/ParserRegistration.cs

Update to parser registration change (#2233) to account for types that were added since the original PR.

Updates to parser registration for new types

---

source/nodejs/adaptivecards-designer/src/card-designer-surface.ts
source/nodejs/adaptivecards-designer/src/card-designer.ts
source/nodejs/adaptivecards-designer/src/containers/host-container.ts
source/nodejs/adaptivecards-designer/src/containers/timeline/timeline-container.ts
source/nodejs/adaptivecards-designer/src/designer-peers.ts

Add verticalContentAlignment to Container and AdaptiveCard

Make Timeline a fixed height container

---

source/dotnet/Library/AdaptiveCards.Rendering.Html/AdaptiveCardRenderer.cs
source/dotnet/Library/AdaptiveCards.Rendering.Wpf/AdaptiveColumnSetRenderer.cs
source/dotnet/Library/AdaptiveCards/AdaptiveColumnSet.cs
source/dotnet/Test/AdaptiveCards.Test/SerializationTests.cs

Completes this work item: https://github.com/Microsoft/AdaptiveCards/issues/2375

[.NET][WPF][HTML] Add columnset style support

---

source/shared/cpp/ObjectModel/ParseUtil.cpp

fixed compiler warning

---

source/dotnet/Library/AdaptiveCards.Rendering.Html/AdaptiveCardRenderer.cs
source/dotnet/Samples/AdaptiveCards.Sample.Html/Program.cs

Bugfix for #2389 
`tabindex = "0"` makes media focusable according to its position.
Changes to the Javascript in `Program.cs` just move the code to activate the media into the `activateMedia()` function. Then have that be called when the "click" event occurs of if the Spacebar is pressed (when focused on).
Also updated the event listener for inline actions. Apparently, `keycode` is deprecated ([ref](https://developer.mozilla.org/en-US/docs/Web/Events/keydown)).
```
{
"speak": "<s>Your  meeting about \"Adaptive Card design session\"<break strength='weak'/> is starting at 12:30pm</s><s>Do you want to snooze <break strength='weak'/> or do you want to send a late notification to the …
```

[.NET] Tab and Activate HTML Media

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/AdaptiveCardRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/ColumnRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/ContainerRenderer.java

For some reason, a merge was not made correctly and it introduced previous changes, this fixes the compilation errors

[Android] Fix build errors

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/GenericImageLoaderAsync.java

The new updated PR: Support local content image load.

Updated: Support local content image load

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/AdaptiveCardRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/ColumnRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/ColumnSetRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/ContainerRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/registration/CardRendererRegistration.java

Completes this work item: https://github.com/Microsoft/AdaptiveCards/issues/2360

[Android] Add bleed property support

---

source/nodejs/adaptivecards-designer/README.md

missing brackets

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards.xcodeproj/project.pbxproj

fixes build break

---

source/dotnet/Library/AdaptiveCards.Rendering.Html/AdaptiveCardRenderer.cs
source/dotnet/Library/AdaptiveCards.Rendering.Wpf/AdaptiveRichTextBlockRenderer.cs
source/dotnet/Library/AdaptiveCards/AdaptiveParagraph.cs
source/dotnet/Library/AdaptiveCards/AdaptiveRichTextBlock.cs
source/dotnet/Library/AdaptiveCards/AdaptiveTextRun.cs
source/dotnet/Library/AdaptiveCards/AdaptiveTypedElementConverter.cs
source/dotnet/Test/AdaptiveCards.Rendering.Html.Test/HtmlRendererTests.cs
source/dotnet/Test/AdaptiveCards.Test/SerializationTests.cs

[.NET] Flatten RichTextBlock object model

---

custom.props
source/dotnet/Library/AdaptiveCards.Rendering.Html/Properties/AssemblyInfo.cs
source/dotnet/Library/AdaptiveCards.Rendering.Wpf.Xceed/Properties/AssemblyInfo.cs
source/dotnet/Library/AdaptiveCards.Rendering.Wpf/Properties/AssemblyInfo.cs
source/dotnet/Library/AdaptiveCards/Properties/AssemblyInfo.cs

Updates for package signing and versioning

---

source/dotnet/Library/AdaptiveCards.Rendering.Html/AdaptiveCards.Rendering.Html.csproj
source/dotnet/Library/AdaptiveCards.Rendering.Wpf.Xceed/AdaptiveCards.Rendering.Wpf.Xceed.csproj
source/dotnet/Library/AdaptiveCards.Rendering.Wpf/AdaptiveCards.Rendering.Wpf.csproj
source/dotnet/Library/AdaptiveCards/AdaptiveCards.csproj

(cherry picked from commit 9583989fc57c2ca300a211649ceb1ae1af99303b)

Adding the proper copyright for .NET packages (#2277) (#2278)

---

source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer.xcodeproj/project.pbxproj
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards.xcodeproj/project.pbxproj
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRRichTextBlockRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRTextBlockRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRView.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/Util.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/Util.mm

iOS implementation of what's implemented in rebecch/italicsandstrike branch for uwp.

rich text block mod2 + italic & strikethrough

---

samples/Tests/RichTextBlock.TextRun.SelectActions.json
source/dotnet/Library/AdaptiveCards.Rendering.Wpf/AdaptiveRichTextBlockRenderer.cs
source/dotnet/Library/AdaptiveCards/AdaptiveTextRun.cs
source/dotnet/Test/AdaptiveCards.Test/SerializationTests.cs

Adds select action support to text runs for the .NET WPF renderer.
How verified: Updated object model tests and manually verified card in visualizer.
#2530

[.NET WPF] Select actions on text runs

---

source/dotnet/Library/AdaptiveCards.Rendering.Html/AdaptiveCardRenderer.cs
source/dotnet/Library/AdaptiveCards.Rendering.Wpf/AdaptiveRichTextBlockRenderer.cs
source/dotnet/Library/AdaptiveCards.Rendering.Wpf/AdaptiveTextBlockRenderer.cs
source/dotnet/Library/AdaptiveCards/AdaptiveTextBlock.cs
source/dotnet/Library/AdaptiveCards/AdaptiveTextRun.cs
source/dotnet/Library/AdaptiveCards/IAdaptiveTextElement.cs
source/dotnet/Test/AdaptiveCards.Rendering.Html.Test/HtmlRendererTests.cs
source/dotnet/Test/AdaptiveCards.Test/SerializationTests.cs

Add support for italics and strike through to .NET.
How verified: Updated unit test and manual validation.
#2669

[.NET] Add italics and strike through

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/DateInputRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/DatePickerFragment.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/TextInputRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/TimeInputRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/TimePickerFragment.java
source/android/build.gradle
source/android/gradle/wrapper/gradle-wrapper.properties
source/android/mobile/build.gradle
source/android/mobile/src/main/java/io/adaptivecards/adaptivecardssample/MainActivityAdaptiveCardsSample.java
source/android/mobilechatapp/build.gradle

Includes this two commits: 
* https://github.com/microsoft/AdaptiveCards/pull/2258
* https://github.com/microsoft/AdaptiveCards/pull/2330
This had already been merged:
* https://github.com/microsoft/AdaptiveCards/pull/2402

[Android] Updates for version1.1.1

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/registration/CardRendererRegistration.java

Fixes #2790 on Android.
Test card run in visualizer with debugger attached

[Android] Add warnings around fallback

---

custom.props

I had to update this version number so android can have a 1.1.1 release

Update version for android release

---

source/android/adaptivecards/src/main/java/io/adaptivecards/objectmodel/ContainerBleedDirection.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/ContainerRenderer.java
source/shared/cpp/ObjectModel/Enums.h

Fixes this issue: https://github.com/microsoft/AdaptiveCards/issues/2706 
The cards added or modified in v1.2/Elements were rendered and this is the result

[Android] Bleed all directions

---

source/ios/AdaptiveCards/ADCIOSVisualizer/resources/sample.json

fixes issue #2982 
updated sample host config file
how verified:
verified with sample adaptive cards jsons.

updated sample host config file

---

source/android/README.md

Removes extra lines from end of file that made no sense

[Android] Update readme.md

---

source/uwp/Renderer/lib/XamlBuilder.cpp

Use compact transport controls (#2987)

---

source/nodejs/adaptivecards-site/themes/adaptivecards/package-lock.json
source/nodejs/package-lock.json
source/nodejs/package.json

[TS] Update npm package versions

---

source/shared/cpp/AdaptiveCardsSharedModel/AdaptiveCardsSharedModelUnitTest/MarkDownUnitTest.cpp
source/shared/cpp/ObjectModel/MarkDownBlockParser.cpp
source/shared/cpp/ObjectModel/MarkDownParsedResult.cpp
source/shared/cpp/ObjectModel/MarkDownParsedResult.h

fixes issue #3000 
how verified; updated and tested with shared model tests.

fixes issue #3000

---

source/community/reactnative/Contributors.md

Updated Contributors.md entries

---

source/nodejs/adaptivecards-designer-app/dist/containers/webchat-container.css
source/nodejs/adaptivecards-designer/src/designer-peers.ts
source/nodejs/adaptivecards/src/card-elements.ts
source/nodejs/spec-generator/package-lock.json

Fixes https://github.com/microsoft/AdaptiveCards/issues/3066
Manually tested

[TS] Fully disable input validation

---

source/nodejs/adaptivecards-designer/README.md

monacoEditorLoaded -> monacoModuleLoaded

---

source/android/adaptivecards/src/androidTest/java/io/adaptivecards/objectmodel/ChoiceSetInputPropertiesTest.java
source/android/adaptivecards/src/androidTest/java/io/adaptivecards/objectmodel/DateInputPropertiesTest.java
source/android/adaptivecards/src/androidTest/java/io/adaptivecards/objectmodel/NumberInputPropertiesTest.java
source/android/adaptivecards/src/androidTest/java/io/adaptivecards/objectmodel/TestUtil.java
source/android/adaptivecards/src/androidTest/java/io/adaptivecards/objectmodel/TextInputPropertiesTest.java
source/android/adaptivecards/src/androidTest/java/io/adaptivecards/objectmodel/TimeInputPropertiesTest.java
source/android/adaptivecards/src/androidTest/java/io/adaptivecards/objectmodel/ToggleInputPropertiesTest.java

[Android] Add unit tests for inpu elements

---

source/nodejs/adaptivecards-fabric/package.json
source/nodejs/adaptivecards-fabric/webpack.config.js

enable local debugging of the fabric lib with npm start

---

source/uwp/Renderer/idl/AdaptiveCards.Rendering.Uwp.idl
source/uwp/Renderer/lib/AdaptiveToggleVisibilityAction.h
source/uwp/Renderer/lib/XamlBuilder.cpp

How verified: Compiled and ran UWP tests

[UWP] Update AdaptiveCards.Rendering.Uwp.idl to modern idl

---

source/uwp/AdaptiveCardTestApp/AdaptiveCardTestApp.csproj
source/uwp/UWPTestLibrary/UWPTestLibrary.csproj
source/uwp/UWPUnitTests/UWPUnitTests.csproj
source/uwp/Visualizer/AdaptiveCardVisualizer.csproj

[UWP] Update C# project references for security

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/ActionLayoutRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/registration/CardRendererRegistration.java

Adds the null check in a consequent check as it started failing again
This is needed for 1.2.1

[Android] Fix fallback again

---

source/dotnet/Build/CopySignFiles.cmd

[.NET] Update CopySignFiles.cmd for build changes

---

source/dotnet/Build/CopySignFiles.cmd

[.NET] Update CopySignFiles.cmd for build changes (#3284)

---

custom.props

Update custom props

---

source/community/reactnative/package-lock.json
source/community/reactnative/package.json
source/community/reactnative/yarn.lock

Reactnative/yarn update - update jest version to remove vulnerabilites

---

source/dotnet/Library/AdaptiveCards.Rendering.Wpf.Xceed/XceedAdaptiveCardRenderer.cs
source/dotnet/Samples/WPFVisualizer/MainWindow.xaml
source/dotnet/Samples/WPFVisualizer/MainWindow.xaml.cs

Added a checkbox to the visualizer and confirmed that it works as expected.
Fixes #3265

[.NET WPF] Add a checkbox to visualizer to toggle usage of Xceed renderers

---

source/uwp/Renderer/lib/TextHelpers.cpp
source/uwp/Renderer/lib/TextHelpers.h

Fixes #3341
Originally regressed by #3308
Verified with test app

[UWP] Fix link underlining

---

source/nodejs/adaptivecards/src/utils.ts
source/nodejs/package-lock.json

The check in getStringValue was returning the default (undefined) value for zero as well as for unset. Updated the check to check against undefined so that it won't trigger for zero values.
Fixes #3237
How Verified: Confirmed in designer that card from #3237 now renders as expected.

[JavaScript] Fix check in getStringValue

---

.github/ISSUE_TEMPLATE/feature_request.md

- New specific template for feature requests
- Allows for adding default labels/assignees

Update issue templates to include a new Feature Request template

---

SECURITY.MD

Adding a new SECURITY.MD file to our repo per Msft OSS guidelines.
Preview for the .md file

Adding Security.md per Microsoft OSS guidelines

---

source/ios/tools/IOSFeed/IOSFeed.cs

Changed finally clause to catch, so error handling case get activated only when failed.
used it to publish.

updated exception handling

---

.editorconfig
source/nodejs/adaptivecards-designer-app/dist/containers/outlook-container.css
source/nodejs/adaptivecards-designer-app/src/app.ts
source/nodejs/adaptivecards-designer/index.html
source/nodejs/adaptivecards-designer/previewFeatures.html
source/nodejs/adaptivecards-designer/src/adaptivecards-designer.css
source/nodejs/adaptivecards-designer/src/card-designer-surface.ts
source/nodejs/adaptivecards-designer/src/card-designer.ts
source/nodejs/adaptivecards-designer/src/designer-peers.ts
source/nodejs/adaptivecards-designer/src/shared.ts
source/nodejs/adaptivecards-fabric/package-lock.json
source/nodejs/adaptivecards-site/package-lock.json
source/nodejs/adaptivecards-site/themes/adaptivecards/layout/designer.ejs
source/nodejs/package-lock.json

Fixes https://github.com/microsoft/AdaptiveCards/issues/3503
- Fix broken Undo/Redo feature: please consult the issue for more detail. The logic has been updated to update the undo stack as the JSON editor changes instead of when changes are applied to the underlying card object
- Split the `GlobalSettings.previewFeaturesEnabled` flag into `GlobalSettings.enableDataBindingSupport`, `GlobalSettings.showDataStructureToolbox`, `GlobalSettings.showSampleDataEditorToolbox` and `GlobalSettings.showVersionPicker`
- Fix minor accessibility warnings when running a Fast Pass with the [Accessibility Insights for Web](https://accessibilityinsights.io/) extension
- Hide the "go full screen" button by default. This feature should really be completely removed, but just hiding it will endure no breaking …

[Designer] Bug fixes and minor enhancements

---

source/nodejs/adaptivecards-site/pages/_posts/2019/Community-Call-October.md

Blog post for the October community call

Blog post for the October community call

---

source/dotnet/Library/AdaptiveCards/Rendering/AdaptiveHostConfig.cs

fixed #3506
adjusted obsolete messages to reflect the current state
checked that correct obsolete message appear when obsolete properties were used.

[.NET] Updated obsolete messages

---

source/nodejs/adaptivecards/src/card-elements.ts
source/nodejs/package-lock.json

Fixes https://github.com/microsoft/AdaptiveCards/issues/3564
Fixes https://github.com/microsoft/AdaptiveCards/issues/3563
- Reverted to **stretch** as the default column width.
- Only render the default **"Title"** value for a Fact's title in the designer
These fixes impact Teams and are somewhat urgent. A new npm package should be generated once they are merged.
Verified manually in both adaptivecards-designer-app and in adaptivecards-visualizer

[TS] Regression fixes

---

source/nodejs/adaptivecards-designer/src/designer-peers.ts
source/nodejs/adaptivecards/src/card-elements.ts
source/nodejs/adaptivecards/src/shared.ts

Fixes https://github.com/microsoft/AdaptiveCards/issues/3580
This PR integrates the fix into release/1.2
Accept decimal numbers for column width

[TS] Fix weight col. width reg. (1.2 integration)

---

source/nodejs/adaptivecards-designer/src/designer-peers.ts
source/nodejs/adaptivecards/src/card-elements.ts
source/nodejs/adaptivecards/src/shared.ts

Fixes https://github.com/microsoft/AdaptiveCards/issues/3580
Accept decimal numbers for column width

[TS] Fix weighted column width regression

---

source/nodejs/adaptivecards-site/themes/adaptivecards/source/js/script.js

1. Ran website and confirmed Samples page loads without any console errors

[Website] Remove arrow functions to support legacy browsers

---

samples/v1.2/Tests/choice_default_value.json
samples/v1.2/Tests/choice_set.json
samples/v1.2/Tests/choice_set_with_wrap.json
samples/v1.2/Tests/newline_card.json
samples/v1.2/Tests/newline_card_r.json
source/android/adaptivecards/src/androidTest/java/io/adaptivecards/objectmodel/TextBlockPropertiesTest.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/BaseActionElementRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/action/ActionElementRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/ChoiceSetInputRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/RendererUtil.java

Contains fixes:
| Issue | Issue # | PR # |
|---|---|---|
| Button icons placed on the left of the title are pushed out of the button, icon size not honored | #3543 | https://github.com/microsoft/AdaptiveCards/pull/3547 |
| Spacing within Choice sets not rendered | #3554 | https://github.com/microsoft/AdaptiveCards/pull/3594 |
| Newline Character ("\n") inside TextBlock not rendered | #3531 | https://github.com/microsoft/AdaptiveCards/pull/3599 |
| For Choice sets with compact style, when no option is explicitly pre-selected, first option gets pre-selected | #3605 | https://github.com/microsoft/AdaptiveCards/pull/3615 |

Android changes for 1.2.4 patch

---

source/nodejs/adaptivecards/src/card-elements.ts

Fixes https://github.com/microsoft/AdaptiveCards/issues/3600
The parsing logic was adding null columns to column set, which could happen as columns fail to parse and need to fallback.

[TS] Fix column fallback regression

---

source/nodejs/adaptivecards/src/card-elements.ts

Integrates https://github.com/microsoft/AdaptiveCards/pull/3645
Integrates https://github.com/microsoft/AdaptiveCards/pull/3621
integrates https://github.com/microsoft/AdaptiveCards/pull/3601
Integration of several bug fixes from master
Verified manually in adaptivecards-designer-app and adaptivecards-visualizer

[TS] Integrate bug fixes from master into release/1.2

---

source/community/reactnative/src/components/containers/container.js
source/community/reactnative/src/models/container-model.js
source/community/reactnative/src/utils/util.js
source/community/reactnative/src/visualizer/payloads/payloads/Container.MinHeight.json
source/community/reactnative/src/visualizer/payloads/payloads/index.js

Implemented and handled the minHeight property for the container
Added the Container.minHeight.json in the payload for validation.
This feature is related to:
https://github.com/microsoft/adaptivecards/issues/2293

Implemented the minheight property for the container

---

source/community/reactnative/src/components/containers/column.js
source/community/reactnative/src/components/containers/columnset.js
source/community/reactnative/src/components/containers/container-wrapper.js

Background image is hide by column background

Background image is hide by column background

---

source/nodejs/adaptivecards-site/README.md

1. Including PreRequisite section around repo bootstrap linking to root readme
2. Cleaning up build commands to use lerna to be consistent with root readme and removing redundant steps
1. Manually tested out the instructions locally with a clean enlistment.

Site readme updates

---

source/nodejs/adaptivecards-designer-app/src/app.ts
source/nodejs/adaptivecards-templating/src/expression-parser.ts

Fixes https://github.com/MicrosoftDocs/AdaptiveCards/issues/251
- Actually create a copy of the expression nodes which were previously overwritten causing the same data object to be reused for all items in an array
- Introduce toString to support basic explicit conversion of numbers into string
Verified in:
- adaptivecards-designer-app
- Web site running locally
Card payload:
```json
{
"body": [
{
"items": [
{
"columns": [
{
"width": "auto",
"items": [
{
"text": "{if(changePriceRatio >= 0, '▲', '▼')}",
"color": "{if(changePriceRatio >= 0, 'good', 'attention')}"
}
]
},
{
"width": …
```

[Designer/templating] Fixes + add toString

---

samples/HostConfig/cortana-skills-dark.json
samples/HostConfig/cortana-skills-light.json

Updating host configs for the Cortana in Windows host configs
We've changed the colors and wanted to update the online designer to reflect the changes.
Ran the website

Update Cortana in Windows Host Configs

---

source/nodejs/ac-typed-schema/package-lock.json
source/nodejs/adaptivecards-controls/package-lock.json
source/nodejs/adaptivecards-designer-app/package-lock.json
source/nodejs/adaptivecards-designer/package-lock.json
source/nodejs/adaptivecards-fabric/package-lock.json
source/nodejs/adaptivecards-site/package-lock.json
source/nodejs/adaptivecards-site/themes/adaptivecards/package-lock.json
source/nodejs/adaptivecards-templating/package-lock.json
source/nodejs/adaptivecards-visualizer/package-lock.json
source/nodejs/adaptivecards/package-lock.json
source/nodejs/package-lock.json
source/nodejs/package.json
source/nodejs/spec-generator/package-lock.json

Security updates for node package dependencies

[JS] Node package security updates

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/BackgroundImageLoaderAsync.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/GenericImageLoaderAsync.java

Fixes #3869
This is just a cherry-pick from this https://github.com/microsoft/AdaptiveCards/pull/3393

[Android] Fix first element changing place with background image

---

source/community/reactnative/src/adaptive-card.js
source/community/reactnative/src/models/base-model.js
source/community/reactnative/src/models/model-factory.js
source/community/reactnative/src/utils/host-config.js
source/community/reactnative/src/visualizer/payloads/payloads/AdaptiveCard.Requires.Fallback.json
source/community/reactnative/src/visualizer/payloads/payloads/index.js
source/community/reactnative/src/visualizer/renderer.js

* Fallback and requires properties on elements #2019

[ReactNative] Added requires/fallback support

---

source/community/reactnative/src/adaptive-card.js

Fixed issues related to keyboard

Fixed keyboard issues

---

source/community/reactnative/README.md
source/community/reactnative/src/adaptive-card.js
source/community/reactnative/src/visualizer/renderer.js

Implemented the props to handled the adaptive card container style

Implemented the props to handled the adaptive card container style

---

source/community/reactnative/src/components/actions/action-button.js
source/community/reactnative/src/components/inputs/choice-set/check-box.js
source/community/reactnative/src/components/inputs/choice-set/choice-set-input.js
source/community/reactnative/src/components/inputs/date-input.js
source/community/reactnative/src/components/inputs/input.js
source/community/reactnative/src/components/inputs/picker-input.js
source/community/reactnative/src/components/inputs/time-input.js
source/community/reactnative/src/styles/style-config.js
source/community/reactnative/src/utils/constants.js
source/community/reactnative/src/utils/enums.js
source/community/reactnative/src/utils/theme-config.js

Added theme config capability for below elements
1. input
2. button
3. choice Set
4. date picker
5. time picker
The adaptive card developer will have full control over these elements with respect to `styling`.

Reactnative/themeconfig 2.1

---

source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer.xcodeproj/project.pbxproj
source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizerTests/ADCIOSVisualizerTests.mm
source/ios/AdaptiveCards/ADCIOSVisualizer/TestFiles/ActionSet.Inputs.Tests.json
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRActionSetRenderer.mm

Fixed #3939
Submit actions didn't gather all inputs if the action was defined  inside ActionSet
1. added a new unit test
2. tested with sample app
3. run all unit tests

Fixed inputs not passed while used in ActionSet

---

source/nodejs/ac-typed-schema/package-lock.json
source/nodejs/adaptivecards-controls/package-lock.json
source/nodejs/adaptivecards-fabric/package-lock.json
source/nodejs/adaptivecards-site/themes/adaptivecards/package-lock.json
source/nodejs/adaptivecards-templating/package-lock.json
source/nodejs/adaptivecards/package-lock.json
source/nodejs/package-lock.json

Update node dependencies in master for security.
* built clean
* quick sanity check running locally

[JS] Update node dependencies in master

---

source/dotnet/Samples/ImageRendererServer/ImageRendererServer.csproj

Cherry-pick of 40f1c5e to `release/1.2`

[NET] Add reference to get security fix for ImageRendererServer sample (#3983)

---

source/nodejs/ac-typed-schema/package-lock.json
source/nodejs/adaptivecards-controls/package-lock.json
source/nodejs/adaptivecards-designer-app/package-lock.json
source/nodejs/adaptivecards-designer-app/package.json
source/nodejs/adaptivecards-designer/package-lock.json
source/nodejs/adaptivecards-site/package-lock.json
source/nodejs/adaptivecards-site/themes/adaptivecards/package-lock.json
source/nodejs/adaptivecards-visualizer/package-lock.json
source/nodejs/adaptivecards-visualizer/package.json
source/nodejs/adaptivecards/package-lock.json
source/nodejs/package-lock.json
source/nodejs/package.json

Update node dependencies in the `release/1.2` branch
* built locally
* sanity check against local build

[JS] Update node dependencies in release/1.2

---

source/tools/hostConfig/scss-to-json/package-lock.json
source/tools/hostConfig/scss-to-json/package.json

`npm audit fix` for scss-to-json
* built and run locally

[JS] Update deps for scss-to-json

---

source/nodejs/adaptivecards-designer-app/package-lock.json
source/nodejs/adaptivecards-designer/package-lock.json
source/nodejs/adaptivecards-designer/package.json
source/nodejs/adaptivecards-templating/package-lock.json
source/nodejs/adaptivecards-templating/package.json
source/nodejs/adaptivecards-visualizer/package-lock.json
source/nodejs/adaptivecards/package-lock.json
source/nodejs/package-lock.json

Point nodejs projects to public [`adaptive-expressions`](https://www.npmjs.com/package/adaptive-expressions) library rather than the prerelease version.
* local build
* draft pipeline build for this PR (to be published when PR is merged)

[JS] Update to public AEL library version

---

source/dotnet/Library/AdaptiveCards.Templating/AdaptiveCards.Templating.csproj
source/dotnet/Test/AdaptiveCards.Templating.Test/AdaptiveCards.Templating.Test.csproj

Replaces nuget source for AEL to public nuget feed
Ran the unit tests & verified with samples

Updated Nuget Package Version for AEL

---

source/community/reactnative/src/components/containers/column.js
source/community/reactnative/src/components/elements/image.js
source/community/reactnative/src/utils/util.js

Refactored Image size calculation

Refactored Image size calculation 

---

source/community/reactnative/src/components/elements/image.js

1) Fixed image issues in ImageSet
2) Fixed spacing issue

Fixed issues in image component

---

source/community/reactnative/src/adaptive-card.js
source/community/reactnative/src/components/containers/container-wrapper.js
source/community/reactnative/src/components/elements/background-image.js
source/community/reactnative/src/models/container-model.js
source/community/reactnative/src/utils/constants.js
source/community/reactnative/src/utils/enums.js
source/community/reactnative/src/visualizer/payloads/payloads/BackgroundImage.Cover.MinHeight.json
source/community/reactnative/src/visualizer/payloads/payloads/BackgroundImage.Repeat.MinHeight.json
source/community/reactnative/src/visualizer/payloads/payloads/BackgroundImage.RepeatVertically.MinHeight.json
source/community/reactnative/src/visualizer/payloads/payloads/BackgroungImage.RepeatHorizontally.MinHeight.json
source/community/reactnative/src/visualizer/payloads/payloads/index.js

1. Handled the background Image for the corner cases as per the schema or background image
2. Apply minHeight for the Adaptive card root level.
3. Handled the "cover" mode for the background image.

Handled the background Image for the corner cases

---

source/nodejs/adaptivecards-designer/src/containers/cortana/cortana-container.ts

No related issue
Update the Cortana skills containers in the designer to support AC 1.2

[Designer] Cortana skills container to 1.2

---

source/dotnet/Library/AdaptiveCards.Templating/AdaptiveCards.Templating.csproj
source/dotnet/Library/AdaptiveCards.Templating/AdaptiveCardsTemplateVisitor.cs
source/dotnet/Library/AdaptiveCards.Templating/AdaptiveTemplateException.cs
source/dotnet/Library/AdaptiveCards.Templating/docs/AdaptiveCardsTemplate.md
source/dotnet/Test/AdaptiveCards.Templating.Test/TestTransform.cs

Added AdaptiveTemplateException Class.
1. All unit tests are ran and passed.
2. Added a new unit test for testing invalid test case.

Adaptive Template SDK Exception Class

---

source/tools/hostConfig/scss-to-json/package-lock.json
source/tools/hostConfig/scss-to-json/package.json

Small incremental package updates for `scss-to-json`.

[JS] Updates for some dev tool dependencies

---

source/nodejs/adaptivecards/src/card-elements.ts

Fixes #4027 in release/1.2 (manual port of 5b09745d3e67cda9145c0c896e1ebab08cb1fae9 from PR #4045)
* local build/reverification

[JS] Port fix for aria-current

---

source/community/reactnative/package.json

Updated version

---

samples/v1.2/Tests/Column.InvalidWidth.json
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/AdaptiveWarning.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/ColumnRenderer.java

Co-authored-by: shalinijoshi19 <shalinij@microsoft.com>
Co-authored-by: Paul Campbell <paulcam@microsoft.com>
This is the cherry pick of PR #3868

Cherry Pick - [Android] Default to auto width for non valid width values #3868

---

source/nodejs/adaptivecards/src/card-elements.ts

Fixes #3914 in release/1.2 (this is also the PR)
Fixes #2240 in release/1.2 (PR #4059)
See also: PR #4080
Fix `Action.OpenUrl` links and buttons to have `role="link"`
* local build and inspection

[JS] Manual port of aria link role fixes

---

samples/v1.2/Elements/RichTextBlock.json
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRRichTextBlockRenderer.mm

Fixes #3953 in `release/1.2`
Manual port of fix in a7cec85(PR #3987).
* local build
* verified via test cards

Fixed RichTextBlock's TextRun's Color Issue (#3987)

---

source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer.xcodeproj/project.pbxproj
source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizerTests/ADCIOSVisualizerTests.mm
source/ios/AdaptiveCards/ADCIOSVisualizer/TestFiles/ActionSet.Inputs.Tests.json
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRActionSetRenderer.mm

Fixes #3939 in `release/1.2`
Manual port of fix in 8836f4975ea2c48fb90e29307e097ddeba5ef48a (PR #3962).
* local build
* local unit test

manual port of fix for inputs not passed while used in ActionSet (#3962)

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRIBaseCardElementRenderer.h

Fixes #3908 in `release/1.2`
Manual port of fix in 2b2aaeec35c557ee06bb3eec303caa9823cd0747 (PR #3912).
* local build
* local test cards

updated render interface (#3912)

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRInputNumberRenderer.mm

Fixes #3863 in `release/1.2`
Manual port of fix in 3bcc6f3f6f837282bb3a771c14f4f1adf9978c3f (PR #3879).
* local build
* verified against test cards

updated numpad to have a decimal point (#3879)

---

source/community/reactnative/README.md
source/community/reactnative/package.json
source/community/reactnative/src/visualizer/payloads/data-binding/adaptive-card-schema.json
source/community/reactnative/src/visualizer/payloads/data-binding/container.json
source/community/reactnative/src/visualizer/payloads/data-binding/food-order.json
source/community/reactnative/src/visualizer/payloads/data-binding/stock-update.json
source/community/reactnative/src/visualizer/renderer.js

* [JS][Templating] Integrate with AEL https://github.com/microsoft/AdaptiveCards/issues/3901
Replace in-built expression parser and evaluator with Adaptive Expressions in ReactNative Renderer

[ReactNative][Templating] Integrate with AEL in ReactNative Renderer

---

.github/workflows/pic2card_build.yml
README.md

Pic2card github action to build and test each change/PR, and added build status badge in the Readme.

pic2card github actions

---

source/nodejs/adaptivecards-site/themes/adaptivecards/scripts/helper-code-and-card.js

Fixes VSO #24081573
Previous aria labels just said "Copy code", which isn't really descriptive enough.
@matthidinger -- could you take a quick look to make sure what I picked makes sense?
* local build and devtools

[Site] Update copy code aria label

---

samples/v1.2/Tests/MultipleActionSets.json
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/action/ActionSetRenderer.java

Fixes #4115 
Previously failed to show multiple actionset's in the same columnset.
Manual verification w/ the following payloads (the latter is from the linked issue).
```
{
"version": "1.2",
"body": [
{
"columns": [
{
"items": [
{
"type": "ActionSet",
"actions": [
{
"type": "Action.Submit",
"title": "Action.Submit1"
}
]
},
{
"type": "ActionSet",
"actions": [
{
"type": "Action.Submit",
"title": "Action.Submit2"
}
]
}
]
}
]
}
]
}
```
```
{
"body": [
{
"columns": [
{
"width": 80,
"items": [
{
"text": "ADA",
"id": "title_main",
"horizontalAlignment": "Left", …
```

[Android] Show all ActionSet's in column

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/ChoiceSetInputRenderer.java

Wrap ChoiceSet properly (#4234)

---

samples/v1.2/Tests/MultipleActionSets.json
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/action/ActionSetRenderer.java

* Adjust ActionSet container height to fit contents
* Add test card
Fixes #4115 
Cherry-pick from main

[Android] Show all ActionSet's in column (#4181)

---

source/shared/cpp/ObjectModel/ParseUtil.cpp

Fixes #4202 
Original PR: #4203

[UWP] Cherry pick JSON parsing performance improvements

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/TextBlockRenderer.java

Patches #4262 to v1.2 (fixes #3702)

[Android] Don't render empty text blocks

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/BaseActionElementRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/action/ActionElementRenderer.java
source/android/adaptivecards/src/main/res/values/attrs.xml
source/android/mobile/src/main/res/drawable/show_card_arrow.xml
source/android/mobile/src/main/res/values-v21/styles.xml
source/android/mobile/src/main/res/values/styles.xml

[Android] Support native styling for Action.ShowCard

---

source/uwp/Visualizer/HostConfigs/DefaultHostConfig.json

VSO #23713870
I missed the UWP Visualizer default hostconfig when I made my update pass. This just ports important bits from our `sample.json` over to the visualizer.
* local build/run

[UWP] Update UWP Visualizer default hostconfig

---

specs/DesignDiscussions/InputLabels.md

Updated the input label spec to contain the latest plan, and to move extraneous information to the appendix. It was not my intent with this change to make any changes to what is in plan for the release, so let me know if something seems inaccurate or not consistent with your understanding of what is in plan for this version

[Spec] Update Input Label Spec to improve readability and consistency

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards.xcodeproj/project.pbxproj
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRInputNumberRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRTextNumberField.xib

Fixed #4466 
Changed the number pad to include punctuation, and added corresponding XIB to make the input field configurable.
Ran the comparable input cards for regression.

added xib for numeric text field

---

source/shared/cpp/AdaptiveCardsSharedModel/AdaptiveCardsSharedModelUnitTest/MarkDownUnitTest.cpp
source/shared/cpp/ObjectModel/MarkDownBlockParser.cpp
source/shared/cpp/ObjectModel/MarkDownBlockParser.h
source/shared/cpp/ObjectModel/MarkDownParsedResult.cpp
source/shared/cpp/ObjectModel/MarkDownParsedResult.h

Cherry-pick #4481 from main to release/1.2
No conflicts

[Shared] Fix Markdown parse issue

---

samples/v1.2/Tests/ImageSizing.json
source/android/adaptivecards/build.gradle
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/ImageRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/ImageSetRenderer.java

Cherry-pick #4380, #4461 from main to release/1.2
Significant conflicts, resolved manually.

[Android] Image and ImageSet sizing fixes

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRImageRenderer.mm

adjusted height anchor constraint (#4367)

---

custom.props
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/Util.java

Updating custom.props to 2.0.0

Updating version to 2.0.0 for nuget release

---

schemas/1.3.0/adaptive-card.json
schemas/host-config.json
schemas/src/actions/Action.ShowCard.json
schemas/src/actions/Action.Submit.json
schemas/src/actions/Action.ToggleVisibility.json
specs/HostConfig.md
specs/elements/Action.ShowCard.md
specs/elements/Action.ToggleVisibility.md

Schema updates for #4391
Updated the schema files to document input issues called out in #4391. Included link to docs page with more details on Input Validation.

[Schema docs] Update schema to call out input validation issues and link to documentation.

---

source/android/mobile/src/main/java/io/adaptivecards/adaptivecardssample/MainActivityAdaptiveCardsSample.java
source/android/mobilechatapp/src/main/java/com/example/mobilechatapp/MainActivity.java

Cherry-pick of #3193 into release/1.2
No conflicts. Clean cherry-pick.

[Android] Value from toggle input not being retrieved

---

samples/Templates/Scenarios/ShowCardWizard.data.json
samples/Templates/Scenarios/ShowCardWizard.template.json

Fixes #4539
The speculative fix (#4540) didn't work, so this actually splits the card up to do full templating (rather than binding against an empty data JSON).

[Samples] Update ShowCardWizard template card to use full databinding

---

samples/Templates/Scenarios/ExpenseReport.template.json
samples/Templates/Scenarios/WeatherLarge.template.json

Fixes VSO #23940361
Related #4383
When I fixed the original bug (#4383), I forgot to replicate the changes over to the templated card versions. This fixes that.
* local build and validation

[Samples] Update templated samples for accessibility

---

source/pic2card/mystique/arrange_card.py
source/pic2card/mystique/config.py
source/pic2card/mystique/design_objects_template.py
source/pic2card/mystique/extract_properties.py
source/pic2card/mystique/group_design_objects.py
source/pic2card/mystique/predict_card.py
source/pic2card/tests/tests.py

- **Image size values** are fixed relatively using the threshold values extracted using the cluster analysis of each **image object's size ( width and height) : input image size (width and height)** ratios.
- **Column width values** are fixed relatively using the threshold values extracting using the analysis of **mid-point distance of each column objects**.
-  Moved the **column width fixing functionality** inside the **property extraction class**.

Image size and Column width properties are fixed relatively using thresholds.

---

source/pic2card/mystique/default_host_configs.py
source/pic2card/mystique/extract_properties.py
source/pic2card/mystique/utils.py

- Updated font size and weight thresholds 
- Text padding function added in utils for font size extraction

[pic2card] Updated Font size and weight thresholds (#26)

---

samples/v1.0/Elements/Input.ChoiceSet.json
samples/v1.0/Scenarios/CalendarReminder.json
samples/v1.0/Scenarios/InputForm.json
samples/v1.0/Scenarios/Inputs.json

User/almedina ms/samples update2

---

schemas/host-config.json
specs/HostConfig.md

Partial fix for #4580
Fixed some mistakes in the host config schema introduced by #4581

[Schema] Fix issues in host config input schema

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/BaseActionElementRenderer.java

This is a cherry-pick of the chevron fix for Android from this pull request #4566

Android chevron fix cherry-pick

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/BaseActionElementRenderer.java
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRShowCardTarget.mm

cherry-picked 1.2.12 fixes

---

schemas/host-config.json
specs/HostConfig.md

Cherry pick of #4696 to `release/20.08`

[Schema] Fix issues in host config input schema (#4696)

---

source/nodejs/adaptivecards-designer/package.json
source/nodejs/adaptivecards-designer/src/adaptivecards-designer.css
source/nodejs/adaptivecards-designer/src/base-tree-item.ts
source/nodejs/adaptivecards-designer/src/card-designer-surface.ts
source/nodejs/adaptivecards-designer/src/tree-view.ts

Fixes VSO 24096574
Partially fixes VSO 24096354, 24096574
Expose the "Card Structure" panel to accessibility tooling and add keyboard shortcuts.

[Designer] Make Card Structure panel keyboard accessible

---

custom.props

Update release/1.2 package version

---

source/android/adaptivecards/build.gradle

Fixes pom missing some information

Fix pom generation for 20.08

---

source/android/adaptivecards/build.gradle

Fix pom generation for 1.2

---

samples/Templates/Scenarios/FlightDetails.template.json

Related PR #4736
Missed a small error in `FlightDetails.template.json` in prior PR
* local build and testing against PR build

[Samples] Fix mistake in Flight Details template

---

source/nodejs/adaptivecards-site/themes/adaptivecards/layout/_partial/section-details-item.ejs

ADO 24130051
This text is not header text, so removing h5 tag.

[Site][Accessibility] Change h5 to p

---

samples/Templates/Scenarios/FlightDetails.template.json

ADO 24110322 (reactivated)
The non-templated sample is accessible, but the templated version is not. Updating to match.

[Sample][Accessibility] Update templated sample

---

source/nodejs/adaptivecards-site/themes/adaptivecards/source/js/script.js

ADO 24094745
Changes the colors in ```script.js``` file to match the colors we had modified in the host config samples. The website uses the colors defined in this file rather than the ones in the hostconfig files under the samples folder
The fix was verified checking the pr website

[Website] Update hostconfig container colors in script.js file

---

samples/Templates/Scenarios/FlightDetails.template.json
samples/v1.2/Scenarios/FlightDetails.json

ADO 24110322
Instead of the hacky two ActionSet fix, this is a text change to avoid overflow in small cards. The ideal underlying fix is #4715 

[Sample][Accessibility] Shorten action text in FlightDetails

---

custom.props

bump custom.props to 2.2.0

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRInputLabelView.xib

Updating Error Message Color to Red from Purple
1. relevant test cards have been run.

error message color update

---

source/dotnet/Library/AdaptiveCards/Rendering/AdaptiveRenderArgs.cs

Save Container Card Id in RenderArgs constructor (#4864)

---

source/pic2card/mystique/arrange_card.py
source/pic2card/mystique/config.py
source/pic2card/mystique/default_host_configs.py
source/pic2card/mystique/extract_properties.py
source/pic2card/mystique/extract_properties_abstract.py
source/pic2card/mystique/font_properties.py
source/pic2card/mystique/group_design_objects.py
source/pic2card/mystique/predict_card.py
source/pic2card/mystique/utils.py

- Added morphological operations to obtain thickness of font 
- Added plug-in functionality for font properties and property extraction
- Added abstract classes for property extraction
- Removed the redundant calling of pytesseract api for getting ocr text and font size property

[pic2card] font weight improvised

---

source/nodejs/adaptivecards-designer-app/src/app.ts
source/nodejs/adaptivecards-designer/README.md
source/nodejs/adaptivecards-designer/src/adaptivecards-designer-standalone.ts
source/nodejs/adaptivecards-designer/src/adaptivecards-designer.css
source/nodejs/adaptivecards-designer/src/open-image-dialog.ts
source/nodejs/adaptivecards-designer/src/pic2card.ts

Updated the pic2card details in  adaptive cards designer README file and handled error scenario on service failure.
Related issue: https://github.com/microsoft/AdaptiveCards/issues/4708

Pic2card designer Better Error messages and Readme updates

---

source/community/reactnative/src/components/actions/action-button.js
source/community/reactnative/src/models/action-model.js
source/community/reactnative/src/styles/style-config.js
source/community/reactnative/src/visualizer/payloads/payloads/Action.NoBody.json

Support for [ActionStyle](https://adaptivecards.io/explorer/Action.Submit.html) for action models. Positive and Destructive Styles added as per version 1.2.
* Add style property for Action elements which can hold positive or destructive as values as per ActionStyle schema.
* Verify the button being highlighted to accent color for Positive value and attention color for Destructive value as provided in hostConfig

Added 1.2 ActionStyle support for Action models

---

source/nodejs/adaptivecards-designer/.env
source/nodejs/adaptivecards-designer/README.md
source/nodejs/adaptivecards-designer/src/adaptivecards-designer.css
source/nodejs/adaptivecards-designer/src/card-designer.ts
source/nodejs/adaptivecards-designer/src/catalogue.ts
source/nodejs/adaptivecards-designer/src/dialog.ts
source/nodejs/adaptivecards-designer/src/open-image-dialog.ts
source/nodejs/adaptivecards-designer/src/open-sample-dialog.ts
source/nodejs/adaptivecards-site/pages/privacy/index.md

Pic2card review fixes PR

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/ChoiceSetInputRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/TextInputRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/ToggleInputRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/customcontrols/IValidatedInputView.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/customcontrols/ValidatedCheckBox.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/customcontrols/ValidatedCheckBoxLayout.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/customcontrols/ValidatedEditText.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/customcontrols/ValidatedInputLayout.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/customcontrols/ValidatedRadioGroup.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/customcontrols/ValidatedSpinnerLayout.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/inputhandler/BaseInputHandler.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/inputhandler/ComboBoxInputHandler.java
source/android/adaptivecards/src/main/res/drawable/adaptive_choiceset_compact_background.xml
source/android/adaptivecards/src/main/res/drawable/adaptive_choiceset_compact_background_invalid.xml
source/android/adaptivecards/src/main/res/drawable/adaptive_choiceset_expanded_background.xml
source/android/adaptivecards/src/main/res/drawable/adaptive_choiceset_expanded_background_invalid.xml
source/android/adaptivecards/src/main/res/values/attrs.xml
source/android/mobile/src/main/res/values-v21/styles.xml

[Android] Update input error visual cue rendering to support custom background drawables 2

---

source/nodejs/adaptivecards-designer-app/src/app.ts
source/nodejs/adaptivecards-designer/README.md
source/nodejs/adaptivecards-designer/src/open-image-dialog.ts
source/nodejs/adaptivecards-designer/src/pic2card.ts

Pic2card Privacy path configuration review changes

Pic2card: Option to pass privacy link via settings.

---

source/community/reactnative/src/components/elements/label.js
source/community/reactnative/src/components/elements/text-block.js
source/community/reactnative/src/models/element-model.js
source/community/reactnative/src/utils/markdown-formatter.js
source/community/reactnative/src/visualizer/payloads/payloads/TextBlock.Accessibility.json
source/community/reactnative/src/visualizer/payloads/payloads/index.js

Added accessibility support for TextBlock element.
* Add altText attribute for TextBlock
* Verify card using Accessibility Reader

Added accessibility support for TextBlock element

---

source/nodejs/adaptivecards-designer-app/src/app.ts
source/nodejs/adaptivecards-designer/README.md
source/nodejs/adaptivecards-designer/src/open-sample-dialog.ts

Adding check for configuring pic2card option

Adding check for configuring pic2card option

---

source/nodejs/adaptivecards-designer-app/src/app.ts
source/nodejs/adaptivecards-designer/README.md
source/nodejs/adaptivecards-designer/src/open-image-dialog.ts
source/nodejs/adaptivecards-designer/src/open-sample-dialog.ts

- Enabled when users sets the property.

[Pic2card]  By default hide the pic2card new card card

---

source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer.xcodeproj/project.pbxproj
source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer/ACRCustomSubmitTargetBuilder.h
source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer/ACRCustomSubmitTargetBuilder.mm
source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer/ViewController.m
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards.xcodeproj/project.pbxproj
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACFramework.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACOBaseActionElement.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACOBaseActionElement.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACOInputResults.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACOInputResults.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRActionDelegate.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRAggregateTarget.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRAggregateTarget.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRInputLabelView.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRInputLabelView.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRRegistration.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRRegistration.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRTargetBuilder.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRTargetBuilderDirector.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRTargetBuilderDirector.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRView.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRViewPrivate.h

Added Event Handler Registration (#4943)

---

source/nodejs/adaptivecards-site/themes/adaptivecards/scripts/generator-adaptiveassets.js

Cherry-pick schema change to 20.10

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRChoiceSetViewDataSourceCompactStyle.mm

Fixed #4982 
Added placeholder message to voiceover
1. Tested with existing 1.3 cards

fixed placeholder not being read

---

source/android/adaptivecards/build.gradle
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/BackgroundImageLoaderAsync.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/ColumnRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/ColumnSetRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/ContainerRenderer.java

Moves #4760 
Manually cherry-picks the necessary changes to port the fix to auto column width 
The fix was verified manually in the 1.2 branch

Manual cherrypick of auto column width fix

---

custom.props
source/android/adaptivecards/gradle.properties

Update package version  to 2.3.0 for release

---

custom.props

Updates custom props to 1.2.13

Custom props update for 1.2 release

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/BaseActionElementRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/Util.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/inputhandler/CheckBoxSetInputHandler.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/inputhandler/ComboBoxInputHandler.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/inputhandler/RadioGroupInputHandler.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/inputhandler/TextInputHandler.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/inputhandler/ToggleInputHandler.java
source/android/mobile/src/main/java/io/adaptivecards/adaptivecardssample/CustomObjects/CardElements/CustomInput.java

Cherry-pick of #5026 into release/20.10 for Android patch 2.3.1
Clean cherry-pick, no conflicts

[Android] Avoid erratic scrolling on submit

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/layout/StretchableInputLayout.java

Ports #5041
Fixes accessibility behaviour for expanded choice sets

[Android] CherryPick #5041 

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/GenericImageLoaderAsync.java
source/android/mobilechatapp/build.gradle

[Android] Set density only when non-null

---

samples/HostConfig/sample.json
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/TextBlockRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/TextRendererUtil.java

Cherrypick of PR #4776 into release/1.2

Cherrypick of #4776

---

source/nodejs/adaptivecards-designer/src/card-designer.ts
source/nodejs/adaptivecards-designer/src/dialog.ts
source/nodejs/adaptivecards-designer/src/open-image-dialog.ts

Co-authored-by: Davakumar <39776642+Davakumar@users.noreply.github.com>
Accessibility tests and contrast related fixes.

[pic2card] Accessibility test related changes.

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRColumnRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRImageRenderer.mm

ADO https://microsoft.visualstudio.com/OS/_queries/edit/29575787/?triage=true
ADO https://microsoft.visualstudio.com/OS/_queries/edit/29254714/?triage=true
Added alt text to Image
Added grouping to Column
https://github.com/microsoft/AdaptiveCards/blob/main/samples/v1.2/Scenarios/Agenda.json
https://github.com/microsoft/AdaptiveCards/blob/main/samples/v1.0/Elements/Image.Style.json
1. New unit tests that were added if any. If none were added please add a quick line explaining why not; accessibility issues are reproducible in the above sample cards.
2. Existing relevant unit/regression tests that you ran; N/A as it adds the new capability.
3. Manual scenario verification if any; ***Do include .gif's or screenshots of the …

Added accessibility label to Image

---

source/pic2card/mystique/config.py
source/pic2card/mystique/extract_properties.py
source/pic2card/mystique/font_properties.py
source/pic2card/mystique/predict_card.py

Used UUID of the design objects to collect the font weights into a list to compare and categorize them using normal distribution

[Pic2card] Replaced Font weight thresholds with dynamic thresholds

---

source/community/reactnative/package.json
source/community/reactnative/src/utils/formatText.js
source/community/reactnative/src/utils/markdown-formatter.js

Resolved the below security warning
1. Useless regular-expression character escape
2. Incomplete string escaping or encoding

Resolved the security warning

---

.github/workflows/pic2card_build.yml
source/pic2card/commands/generate_card_using_python_client.py
source/pic2card/mystique/predict_card.py
source/pic2card/mystique/utils.py
source/pic2card/requirements/requirements.txt
source/pic2card/tests/base_test_class.py
source/pic2card/tests/test_layout.py

* Removed the requests library.
* Fixed the test discovery issue due to filename.
* Used std HTTP client for testing.

[pic2card] Dependency issue fixes

---

source/android/adaptivecards/build.gradle
source/android/adaptivecards/gradle.properties
source/android/mobile/src/main/res/raw/importer_card.json

Updated version and license for the distributed binary. Note this does not cover our source code, which remains under the MIT license.

[Android] Bump minor 2.4.0, and reference to new binary EULA

---

source/nodejs/adaptivecards-designer/README.md
source/nodejs/adaptivecards-designer/cdn.html
source/nodejs/adaptivecards-designer/index.html
source/nodejs/adaptivecards-designer/noHosts.html
source/nodejs/adaptivecards-designer/previewFeatures.html
source/nodejs/adaptivecards-site/package-lock.json
source/nodejs/adaptivecards-site/package.json
source/nodejs/adaptivecards-site/themes/adaptivecards/layout/_partial/footer.ejs

Clean cherry-pick of #5194 
No conflicts.

[Site] Fix missing expression library dep (#5194)

---

source/nodejs/adaptivecards-designer/src/adaptivecards-designer.css
source/nodejs/adaptivecards-designer/src/open-image-dialog.ts

Highlight the checkbox boundary. Accessibility fix.

---

source/pic2card/mystique/card_layout/objects_group.py
source/pic2card/tests/test_layout.py

[pic2card] row-column merging conditions optimization

---

source/nodejs/adaptivecards-designer/src/adaptivecards-designer.css

button border color fix related to accessibility fix.

Border color fix.

---

source/community/reactnative/src/components/actions/action-button.js
source/community/reactnative/src/components/actions/select-Action.js
source/community/reactnative/src/visualizer/renderer.js

Added the title as a parameter in onExecuteAction for the submit action. 
Cross verified and confirmed the same action in native platforms.

Added the title in the submit action

---

source/community/reactnative/src/components/actions/action-button.js
source/community/reactnative/src/components/actions/select-Action.js
source/community/reactnative/src/components/containers/container-wrapper.js
source/community/reactnative/src/components/containers/container.js
source/community/reactnative/src/components/elements/background-image.js
source/community/reactnative/src/components/elements/image.js
source/community/reactnative/src/components/elements/media.js
source/community/reactnative/src/components/inputs/choice-set/choice-set-input.js
source/community/reactnative/src/components/inputs/input.js
source/community/reactnative/src/components/inputs/picker-input.js
source/community/reactnative/src/components/inputs/toggle-input.js
source/community/reactnative/src/models/action-model.js
source/community/reactnative/src/models/container-model.js
source/community/reactnative/src/models/input-model.js
source/community/reactnative/src/visualizer/payloads/payloads/Accessibility.json
source/community/reactnative/src/visualizer/payloads/payloads/Action.Title.json
source/community/reactnative/src/visualizer/payloads/payloads/MediaInColumnSet.json
source/community/reactnative/src/visualizer/payloads/payloads/index.js
source/community/reactnative/src/visualizer/payloads/scenarios/input-form.json

Added accessibility support for all adaptive card elements such as image, media, actions, various input types, and containers. Please find below the property details.
- Property name - **_`altText`_** 
This text will be treated as a description of the particular element/container.

Added accessibility support for all adaptive card elements

---

source/community/reactnative/src/components/inputs/input.js

Added the condition for handling the max length for the input text field

Added the condition fopr handling the maxlength for the input textfield

---

source/nodejs/adaptivecards-controls/src/dropdown.ts

VSO 23940376
Role and aria were a little off for our toolbar dropdown controls leading to incorrect reading of state in narrator.

[Designer] Update role and aria for toolbar dropdown menus

---

samples/Templates/Scenarios/Restaurant.template.json

Fix whoopsie in Restaurant template that came in with #5265 (also fix formatting).
* local build

[Samples] Fix alt attribute in restaurant template

---

source/community/reactnative/src/components/actions/action-button.js
source/community/reactnative/src/components/elements/image.js
source/community/reactnative/src/components/elements/label.js
source/community/reactnative/src/components/elements/text-block.js
source/community/reactnative/src/visualizer/custom-action-button.js
source/community/reactnative/src/visualizer/custom-image.js
source/community/reactnative/src/visualizer/custom-text-block.js
source/community/reactnative/src/visualizer/payloads/payloads/CustomActionButton.Rendering.json
source/community/reactnative/src/visualizer/payloads/payloads/CustomImage.Rendering.json
source/community/reactnative/src/visualizer/payloads/payloads/CustomTextBlock.Rendering.json
source/community/reactnative/src/visualizer/payloads/payloads/index.js
source/community/reactnative/src/visualizer/renderer.js

Added the extensibility for the custom text block component

Added the extensibility for the custom text block, Image and ActionButton component

---

source/nodejs/adaptivecards-designer-app/package-lock.json
source/nodejs/adaptivecards-designer/package-lock.json
source/nodejs/adaptivecards-site/package-lock.json
source/nodejs/adaptivecards/package-lock.json
source/nodejs/adaptivecards/src/card-elements.ts
source/nodejs/adaptivecards/src/shared.ts
source/nodejs/adaptivecards/src/utils.ts

- Fixes https://github.com/microsoft/AdaptiveCards/issues/5302
- Fixes https://github.com/microsoft/AdaptiveCards/issues/4847
- Fixes https://github.com/microsoft/AdaptiveCards/issues/5249
- Fixes https://github.com/microsoft/AdaptiveCards/issues/5315
- Code was attempting to call `toString()` on `undefined` when a ChoiceSet input had no selection
- `TextBlock.maxLines` is now handled using the non-standard `--webkit-line-clamp` CSS property. While non-standard, this property is supported across all browsers, except IE. In IE, the renderer will fall back to the old behavior. This change fixes two bugs:
- Because line clamping takes care of truncation, the renderer doesn't need to specify explicit line heights anymore, which leads to Markdown headings not being cut off anymore
- Truncated …

Fix exception with multiselect ChoiceSet, ellipsis with maxLines in TextBlock and truncated Markdown headers

---

source/community/reactnative/src/components/elements/element-wrapper.js
source/community/reactnative/src/components/inputs/choice-set/choice-set-input.js
source/community/reactnative/src/components/inputs/input-label.js
source/community/reactnative/src/components/inputs/input.js
source/community/reactnative/src/components/inputs/picker-input.js
source/community/reactnative/src/components/inputs/text-input.js
source/community/reactnative/src/components/inputs/toggle-input.js
source/community/reactnative/src/models/input-model.js
source/community/reactnative/src/utils/constants.js
source/community/reactnative/src/utils/enums.js
source/community/reactnative/src/visualizer/payloads/payloads/Input.Label.json
source/community/reactnative/src/visualizer/payloads/scenarios/input-form.json

Completed input validation based on the new Requirement. Please find below details:
1. Removed **`validation`** property and it's child properties.
2. New Property Added 
**`isRequired`** and **`errorMessage`** property for all the inputs.
**`regex`** property for `Input.Text`
Please find the detailed spec [here](https://github.com/microsoft/AdaptiveCards/blob/0d3aaa99a40eae8036935b1cab54127bf252c121/specs/DesignDiscussions/InputValidation.md).

Completed Input Validation

---

source/community/reactnative/package.json
source/community/reactnative/src/adaptive-card.js

Removed the style for the select action

Removed the style for the selectaction

---

source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer/ViewController.m

N/A
Updated the rendered AdaptiveCards' width to vary to the device's width.
N / A
Verified with a simulator and a device.

updated width of the card for sample app

---

source/community/reactnative/README.md
source/community/reactnative/src/adaptive-card.js
source/community/reactnative/src/components/actions/action-button.js
source/community/reactnative/src/components/actions/action-wrapper.js
source/community/reactnative/src/utils/host-config.js
source/community/reactnative/src/visualizer/renderer.js

This PR consist of the below changes,
1. Added the "contentContainerStyle" as props in the adaptive card and updated the readme file for the same.
2. Handled the actionAlignment of the button component from the host config.

Added the content container style as aadaptive card props and Handled the actionAlignment

---

source/community/reactnative/src/components/actions/action-button.js
source/community/reactnative/src/components/actions/select-Action.js
source/community/reactnative/src/utils/constants.js
source/community/reactnative/src/visualizer/payloads/payloads/Accessibility.json

Added **`accessibilityRole`** for the componenets _`selectAction`_ and _`Actions`_.

Added accessibility role for button and select action components

---

source/pic2card/README.md
source/pic2card/TRAINING.md
source/pic2card/swagger.yaml

- Swagger api documentation
- Readme updates.

Readme update

---

source/community/reactnative/README.md
source/community/reactnative/__test__/__snapshots__/adaptive-card.test.js.snap
source/community/reactnative/package.json
source/community/reactnative/src/adaptive-card.js
source/community/reactnative/src/components/actions/action-button.js
source/community/reactnative/src/components/actions/action-wrapper.js
source/community/reactnative/src/components/actions/select-Action.js
source/community/reactnative/src/utils/constants.js
source/community/reactnative/src/utils/host-config.js
source/community/reactnative/src/visualizer/payloads/payloads/Accessibility.json
source/community/reactnative/src/visualizer/renderer.js

✅ Added the **_contentContainerStyle_** as props in the adaptive card and updated the readme file for the same.
✅ Handled the `actionAlignment` of the button component from the host config.
✅ Added **_accessibilityRole_** for the components _`selectAction`_ and _`Actions`_.

Reactnative/release 2.2.5

---

source/nodejs/adaptivecards-designer/src/designer-peers.ts
source/nodejs/adaptivecards/src/card-elements.ts

Fixes VSO #30909723
Simple change - button was titled `X`, but it should be more descriptive. I chose `Remove`.
* local build, narrator

[Designer] Update peer button name from "X" to "Remove"

---

source/nodejs/adaptivecards-site/themes/adaptivecards/scripts/helper-code-and-card.js
source/nodejs/adaptivecards-site/themes/adaptivecards/source/css/style.css
source/nodejs/adaptivecards-site/themes/adaptivecards/source/js/script.js

Fixes VSO 30959686
There's no audible or visual indication that invoking the copy button on the samples page has performed any action. This fixes that.

[Site] Emit status messages on copy button invoke

---

source/nodejs/adaptivecards-site/themes/adaptivecards/layout/_partial/footer.ejs
source/nodejs/adaptivecards-site/themes/adaptivecards/layout/_partial/home-section.ejs
source/nodejs/adaptivecards-site/themes/adaptivecards/layout/_partial/section-details-item.ejs
source/nodejs/adaptivecards-site/themes/adaptivecards/layout/index.ejs
source/nodejs/adaptivecards-site/themes/adaptivecards/source/css/style.css

Fixes VSO 30960561
Rework heading structure of website index... also rework styling to make it appear visually the same.
...
...
* local build, devtools, narrator, accinsights

[Site] Update header structure on homepage to make more sense

---

source/nodejs/adaptivecards-designer/src/designer-peers.ts

Updates to PR #5419 for feedback that came in after merge
Remove unnecessary sets to aria-label that were not needed after updates to my original fix.
Inspected elements and confirmed correct behavior in narrator.

Additional PR feedback for #5419

---

source/nodejs/adaptivecards-controls/src/adaptivecards-controls.css
source/nodejs/adaptivecards-designer-app/dist/containers/outlook-container.css
source/nodejs/adaptivecards-designer-app/dist/containers/teams-container-dark.css
source/nodejs/adaptivecards-designer-app/dist/containers/teams-container-light.css
source/nodejs/adaptivecards-designer/src/adaptivecards-designer.css
source/nodejs/adaptivecards-designer/src/containers/cortana/cortana-container-dark.css
source/nodejs/adaptivecards-designer/src/containers/cortana/cortana-container-light.css
source/nodejs/adaptivecards-designer/src/containers/outlook/outlook-container.css
source/nodejs/adaptivecards-designer/src/containers/teams/teams-container-dark.css
source/nodejs/adaptivecards-designer/src/containers/teams/teams-container-light.css
source/nodejs/adaptivecards-visualizer/css/outlook.css
source/nodejs/adaptivecards-visualizer/css/teams.css

The fix for #5359 got part of the media query wrong, so some styling wasn't being applied outside of High Contrast mode.
* local build

[Designer] Fix broken media query

---

source/nodejs/adaptivecards-designer-app/dist/containers/bf-image-container.css
source/nodejs/adaptivecards-designer-app/dist/containers/cortana-container.css
source/nodejs/adaptivecards-designer-app/dist/containers/outlook-container.css
source/nodejs/adaptivecards-designer-app/dist/containers/skype-container.css
source/nodejs/adaptivecards-designer-app/dist/containers/teams-container-dark.css
source/nodejs/adaptivecards-designer-app/dist/containers/teams-container-light.css
source/nodejs/adaptivecards-designer-app/dist/containers/timeline-container.css
source/nodejs/adaptivecards-designer-app/dist/containers/toast-container.css
source/nodejs/adaptivecards-designer-app/dist/containers/webchat-container.css
source/nodejs/adaptivecards-designer/src/containers/bf-image/bf-image-container.css
source/nodejs/adaptivecards-designer/src/containers/cortana-classic/cortana-container.css
source/nodejs/adaptivecards-designer/src/containers/cortana/cortana-container-dark.css
source/nodejs/adaptivecards-designer/src/containers/cortana/cortana-container-light.css
source/nodejs/adaptivecards-designer/src/containers/default/adaptivecards-defaulthost.css
source/nodejs/adaptivecards-designer/src/containers/notifications/toast-container.css
source/nodejs/adaptivecards-designer/src/containers/outlook/outlook-container.css
source/nodejs/adaptivecards-designer/src/containers/skype/skype-container.css
source/nodejs/adaptivecards-designer/src/containers/teams/teams-container-dark.css
source/nodejs/adaptivecards-designer/src/containers/teams/teams-container-light.css
source/nodejs/adaptivecards-designer/src/containers/timeline/timeline-container.css
source/nodejs/adaptivecards-designer/src/containers/webchat/webchat-container.css
source/nodejs/adaptivecards-designer/src/designer-peers.ts
source/nodejs/adaptivecards-designer/src/shared.ts
source/nodejs/adaptivecards/src/card-elements.ts
source/nodejs/adaptivecards/src/controls/constants.ts
source/nodejs/adaptivecards/src/controls/index.ts
source/nodejs/adaptivecards/src/controls/menu-item.ts
source/nodejs/adaptivecards/src/controls/popup-control.ts
source/nodejs/adaptivecards/src/controls/popup-menu.ts
source/nodejs/adaptivecards/src/serialization.ts

Finalizes implementation of https://github.com/microsoft/AdaptiveCards/issues/4715
- Adds designer support for schema "1.5 (Preview)"
- Adds designer support for `Action.mode`
- Adds secondary action promotion to primary on execution. It works this way:
- Actions are only promoted if there is at least one spot they can be promoted to. That isn't the case when all actions in a set are secondary (and thus only the overflow button is displayed)
- When promoted, an action replaces the last primary action (the one right before the overflow button) and the action it replaces is moved to the overflow menu at the old spot of the newly promoted action
- Secondary ShowCard actions are always promoted
- Secondary non-ShowCard actions are never promoted
- Primary non-ShowCard actions that happen to …

[JS] Action.mode designer support + promote secondary action to primary on execute

---

source/community/reactnative/src/components/containers/container.js
source/community/reactnative/src/models/model-factory.js

This PR consist of the below,
1. Handled the unknown and fallback element
2. Handled the spacing and separator style

Handled the unknown and fallback element

---

source/pic2card/commands/generate_bleu_score.py

- Added a **bleu score** metric collection for layout comparisons
- Overall **accuracy** for the new test images set = **87.86%**

[pic2card] Metrics for layout structure comparison

---

source/community/reactnative/src/components/actions/action-button.js
source/community/reactnative/src/components/actions/select-Action.js
source/community/reactnative/src/components/elements/rich-text-block.js
source/community/reactnative/src/components/inputs/input.js
source/community/reactnative/src/components/registration/registry.js
source/community/reactnative/src/models/action-model.js
source/community/reactnative/src/models/model-factory.js
source/community/reactnative/src/utils/constants.js
source/community/reactnative/src/utils/enums.js
source/community/reactnative/src/visualizer/payloads/payloads/Universal.Action.json
source/community/reactnative/src/visualizer/payloads/payloads/Universal.Inline.Action.json
source/community/reactnative/src/visualizer/payloads/payloads/Universal.Select.Action.json
source/community/reactnative/src/visualizer/payloads/payloads/index.js
source/community/reactnative/src/visualizer/renderer.js

Implemented the **universal action model** and handled the type - **action.execute**
[https://adaptivecards.io/explorer/Action.Execute.html](https://adaptivecards.io/explorer/Action.Execute.html)
[https://docs.microsoft.com/en-us/adaptive-cards/authoring-cards/universal-action-model](https://docs.microsoft.com/en-us/adaptive-cards/authoring-cards/universal-action-model)

Implemented the universal action model and Handled the type - action.execute

---

samples/v1.5/Elements/Column.Rtl.json
samples/v1.5/Elements/Container.Rtl.Json
samples/v1.5/Test/RtlTestCard.json
source/uwp/Renderer/idl/AdaptiveCards.Rendering.Uwp.idl
source/uwp/Renderer/lib/AdaptiveCard.cpp
source/uwp/Renderer/lib/AdaptiveColumn.cpp
source/uwp/Renderer/lib/AdaptiveColumn.h
source/uwp/Renderer/lib/AdaptiveColumnRenderer.cpp
source/uwp/Renderer/lib/AdaptiveContainer.cpp
source/uwp/Renderer/lib/AdaptiveContainer.h
source/uwp/Renderer/lib/AdaptiveContainerRenderer.cpp
source/uwp/Renderer/lib/AdaptiveRenderContext.cpp
source/uwp/Renderer/lib/AdaptiveRenderContext.h
source/uwp/UWPUnitTests/ObjectModelTests.cs

Fixes #5488 
Fixes #5489 
Add RTL support to UWP
samples/v1.5/Elements/Column.Rtl.json
samples/v1.5/Elements/Container.Rtl.Json
samples/v1.5/Test/RtlTestCard.json
- New Unit tests to validate object model changes for RTL
- New sample cards validated in the visualizer

[UWP] Add RTL support to UWP

---

source/nodejs/ac-typed-schema/package-lock.json
source/nodejs/ac-typed-schema/package.json
source/nodejs/aclint/package-lock.json
source/nodejs/adaptivecards-aaf-testapp/package-lock.json
source/nodejs/adaptivecards-designer-app/package-lock.json
source/nodejs/adaptivecards-designer/package-lock.json
source/nodejs/adaptivecards-fabric/package-lock.json
source/nodejs/adaptivecards-site/package-lock.json
source/nodejs/adaptivecards-visualizer/package-lock.json
source/nodejs/adaptivecards/package-lock.json
source/nodejs/package-lock.json
source/nodejs/spec-generator/package-lock.json

Updated package dependencies via audit
* local build and smoke test

[JS] Lerna-audit updates for JS packages

---

source/community/reactnative/README.md
source/community/reactnative/src/adaptive-card.js
source/community/reactnative/src/components/actions/action-button.js
source/community/reactnative/src/components/actions/action-wrapper.js
source/community/reactnative/src/visualizer/renderer.js

This PR consist below changes,
1. Aligned the button action items as per the Web Platform working model.
2. Introduced new property to handle the adaptive card Scroll Enabled property.

Handled the cardScrollEnabled property and Aligned the button action as per the Web Platform

---

source/community/reactnative/src/components/actions/action-button.js
source/community/reactnative/src/components/actions/select-Action.js
source/community/reactnative/src/components/inputs/input.js
source/community/reactnative/src/components/inputs/toggle-input.js
source/community/reactnative/src/models/action-model.js
source/community/reactnative/src/utils/constants.js
source/community/reactnative/src/visualizer/payloads/payloads/Action.IsEnabled.json
source/community/reactnative/src/visualizer/payloads/payloads/SelectAction.IsEnabled.json
source/community/reactnative/src/visualizer/payloads/payloads/index.js

This PR consist of the below changes:
1. Updated the alignment of toggle input as same as native platform.
2. Handled isEnabled property for action type, select action, and inline action - [https://github.com/microsoft/AdaptiveCards/issues/4670](https://github.com/microsoft/AdaptiveCards/issues/4670)

Toggle input alignment and Handle isEnable property for action type

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards.xcodeproj/project.pbxproj

iOS changes
- added the new shared model header

[iOS] Added a new shared model header

---

.pipelines/android-daily.yml
source/android/adaptivecards/build.gradle

Cherry-pick #5767 into release/21.04

[Chore] Make Android version build number optional

---

source/android/adaptivecards/gradle.properties

Version bump to 2.8.0 for 21.04 beta release

[Android] Version bump minor 2.8.0

---

source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer/ACRChatWindow.mm
source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer/CustomTextBlockRenderer.mm
source/ios/AdaptiveCards/ADCIOSVisualizer/resources/sample.json
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACOHostConfig.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRFactSetRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRRichTextBlockRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRTextBlockRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRView.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/UtiliOS.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/UtiliOS.mm
source/shared/cpp/ObjectModel/TextBlock.cpp
source/shared/cpp/ObjectModel/TextElementProperties.cpp

Fixed #5632 
1. in addition to #5632, fixed a minor issue in populating font family issue.

[iOS] Text Styles Changes

---

source/nodejs/ac-typed-schema/package-lock.json
source/nodejs/aclint/package-lock.json
source/nodejs/adaptivecards-controls/package-lock.json
source/nodejs/adaptivecards-designer-app/package-lock.json
source/nodejs/adaptivecards-designer/package-lock.json
source/nodejs/adaptivecards-fabric/package-lock.json
source/nodejs/adaptivecards-site/package-lock.json
source/nodejs/adaptivecards-visualizer/package-lock.json
source/nodejs/adaptivecards/package-lock.json
source/nodejs/package-lock.json
source/nodejs/package.json
source/nodejs/spec-generator/package-lock.json

This is the set of changes for `main` -- I should have a set incoming for `release/21.04` shortly if they're not directly cherry-pickable.
Note that this includes a major version upgrade to [`lerna@4.0.0`](https://github.com/lerna/lerna/releases/tag/v4.0.0). The breaking changes don't appear to have impacts to us as CLI consumers, but it's probably worth keeping an eye on.

[JS] Update node dependencies

---

source/nodejs/adaptivecards-designer/package-lock.json
source/nodejs/adaptivecards-site/package-lock.json
source/nodejs/adaptivecards-templating/package-lock.json
source/nodejs/adaptivecards/package-lock.json
source/nodejs/package-lock.json

Looks like the `hosted-git-info` node package has been updated, so we should take that update as well...
* local build

[JS] Update `hosted-git-info` package deps

---

source/community/reactnative/src/components/inputs/date-input.js
source/community/reactnative/src/components/inputs/time-input.js

Fixed double rendering of DateTime picker control in android release build.

Fixed double rendering of DateTime picker control in android

---

source/pic2card/mystique/card_layout/bbox_utils.py
source/pic2card/mystique/card_layout/container_group.py
source/pic2card/mystique/card_layout/ds_helper.py
source/pic2card/mystique/card_layout/objects_group.py
source/pic2card/mystique/card_layout/row_column_group.py
source/pic2card/mystique/config.py
source/pic2card/mystique/metrics/cosine_similarity.py
source/pic2card/mystique/predict_card.py
source/pic2card/tests/test_layout.py

- Row-column grouping conditions simplified.
- De-coupled image-set grouping from row-column conditions.
- Bleu Score increased to: **89.16%**

[pic2card] Upgrade row grouping conditions

---

samples/v1.5/Elements/Table.json
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACORenderContext.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACORenderContext.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRContainerRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRContentStackView.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRTableCellView.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRTableView.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRTextBlockRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRView.mm

references #5724 
Updated padding & Added heading & accessibility

[iOS] Table Changes 3 / 3

---

source/nodejs/adaptivecards-aaf-testapp/package-lock.json
source/nodejs/adaptivecards-controls/package-lock.json
source/nodejs/adaptivecards-designer-app/package-lock.json
source/nodejs/adaptivecards-designer/package-lock.json
source/nodejs/adaptivecards-extras-designer/package-lock.json
source/nodejs/adaptivecards-extras/package-lock.json
source/nodejs/adaptivecards-fabric/package-lock.json
source/nodejs/adaptivecards-site/package-lock.json
source/nodejs/adaptivecards-templating/package-lock.json
source/nodejs/adaptivecards-visualizer/package-lock.json
source/nodejs/adaptivecards/package-lock.json
source/nodejs/package-lock.json

Update node dependencies to address vulnerabilities.
* local build and manual site check

[JS] Update node deps

---

source/pic2card/README.md
source/pic2card/requirements/requirements-dev.txt

Added Code Coverage Measure using **coverage** pip module

[pic2card] code coverage measure

---

source/community/reactnative/src/components/containers/column.js
source/community/reactnative/src/components/containers/columnset.js
source/community/reactnative/src/components/containers/container-wrapper.js
source/community/reactnative/src/components/elements/element-wrapper.js
source/community/reactnative/src/utils/constants.js
source/community/reactnative/src/visualizer/payloads.js
source/community/reactnative/src/visualizer/payloads/payloads/Image.Size.json
source/community/reactnative/src/visualizer/payloads/scenarios/calendar-invite.json
source/community/reactnative/src/visualizer/payloads/scenarios/flight-itinerary.json

This PR consists of the below changes.
1. Updated the margin for the container styles.
2. Handled the separator and spacing for the container, column set, column, and wrappers.
3. Handled the vertical alignment for the column set.
4. Handled the alignment and size for the image component.
5. Added the payloads for flight itinerary and Calendar invite in the payloads.

Updated the alignment and margin styles for the container, columnSet, column, wrappers and image component

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards.xcodeproj/project.pbxproj
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCardsTests/AdaptiveCardsTests.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCardsTests/AdaptiveCardsTextBlockTests.mm

* Fixed compilation issues for iOS
* added header search path
* removed a shell script

[iOS] fixed compilation issue for unit test

---

source/community/reactnative/src/components/containers/container-wrapper.js

Handled the bleed property. On the web, it's not having conditions for the first and last elements. so removed this condition from the react-native.

Handled the bleed property

---

.github/CONTRIBUTING.md
schemas/README.md
specs/README.md
specs/SpecTemplate.md

Clone of [#6068](https://github.com/microsoft/AdaptiveCards/pull/6068). This PR updates the contribution guidelines. Some checks are failing in the last PR due to it coming from a forked repo.

Added contribution guidelines to new PR from main repo

---

source/nodejs/adaptivecards-designer-app/package.json

Removed dependencies on extras as the packages are not owned by AdaptiveCards on npm

Removed the dependencies on extras

---

source/community/reactnative/src/components/inputs/toggle-input.js
source/community/reactnative/src/utils/enums.js
source/community/reactnative/src/utils/theme-config.js

Adds theming support to Toggle input's Switch component.

Theming suppor to Input.Toggle

---

.pipelines/android-ci.yml
.pipelines/uwp-ci.yml
custom.props
source/dotnet/Library/AdaptiveCards.Rendering.Html/AdaptiveCards.Rendering.Html.csproj
source/dotnet/Library/AdaptiveCards.Rendering.Wpf/AdaptiveCards.Rendering.Wpf.csproj
source/dotnet/Library/AdaptiveCards.Templating/AdaptiveCards.Templating.csproj
source/dotnet/Library/AdaptiveCards.Templating/AdaptiveCardsTemplateVisitor.cs
source/dotnet/Library/AdaptiveCards.Templating/docs/AdaptiveCardsTemplate.md
source/dotnet/Library/AdaptiveCards/AdaptiveCards.csproj
source/dotnet/Library/AdaptiveCards/IgnoreEmptyItemsConverter.cs
source/dotnet/Library/AdaptiveCards/docs/AdaptiveCards.md
source/dotnet/Test/AdaptiveCards.Rendering.Html.Test/AdaptiveCards.Rendering.Html.Test.csproj
source/dotnet/Test/AdaptiveCards.Templating.Test/AdaptiveCards.Templating.Test.csproj
source/dotnet/Test/AdaptiveCards.Templating.Test/TestTransform.cs
source/dotnet/Test/AdaptiveCards.Test/AdaptiveCards.Test.csproj
source/dotnet/Test/AdaptiveCards.Test/SerializationTests.cs
source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer.xcodeproj/project.pbxproj

Fixes #6212, Fixes #2148, Fixes #5963, Fixes #5575
Port of fixes in preparation of shipping `2.7.2` .NET package updates
* local build and tests, spot checking of rendering in WPF visualizer

[.NET] Port patch fixes to release branch

---

source/nodejs/adaptivecards-react/package.json

Fix for some incorrect fields in package.json

Fix package.json fields for adaptivecards-react

---

custom.props
source/nodejs/adaptivecards/package.json

Update package versions for release/21.08

---

.pipelines/ios-release.yml
source/ios/tools/AdaptiveCards.podspec

added flag for exluding 32-bit slice

[iOS] removed 32-bit slice

---

.pipelines/ios-release.yml
source/ios/tools/AdaptiveCards.podspec

Added podspec log
* podspec is not logged & hard to debug when encountered error. re-added the printing podspec.
* made sure 32-bit simulator is not built.
N/A
N/A

Updated podspec & iOS yml

---

.pipelines/ios-release.yml
source/ios/tools/AdaptiveCards.podspec

* Added podspec log
Added podspec log
* Fixed Typo on yml
* Update ios-release.yml
* [iOS] removed 32-bit slice (#6304)
* Addressed review feedback

Updated podspec & iOS yml (#6302)

---

source/shared/cpp/ObjectModel/TableCell.cpp
source/shared/cpp/ObjectModel/TableRow.cpp

Added internal id assignment to TableRow & TableCell as need in iOS for vertical/horizontal content alignment and header row. Feel free to change the PR.
Manually ran Table json to check for the above-mentioned properties.

[shared] table update

---

samples/v1.5/Elements/AdaptiveCard.Rtl.json

Fixes #6492
Adds a sample card for AdaptiveCard.Rtl.json to be used in the schema explorer on the website

[Samples] Add card level rtl property sample

---

samples/v1.5/Test/Input.ChoiceSet.FilteredStyle.TestCard.json

Fixed #6468 
Test card for Input.ChoiceSet.FilteredStyle
Logged following bugs
https://github.com/microsoft/AdaptiveCards/issues/6515
https://github.com/microsoft/AdaptiveCards/issues/6513
https://github.com/microsoft/AdaptiveCards/issues/6514

[Sample] Added Sample For Input.ChoiceSet.FilteredStyle

---

source/nodejs/adaptivecards-designer/src/card-designer-surface.ts
source/nodejs/adaptivecards/src/card-elements.ts
source/nodejs/adaptivecards/src/card-object.ts

Added carousel page id upon action invocation.

Added carousel page id

---

source/nodejs/adaptivecards/src/carousel.ts

Use AddEventListeners and fix focus event not firing

---

source/nodejs/tests/ui-tests/src/ui-tests.test.ts

Add a timeout for test start up

[JS] Changes for CI to succeed

---

source/nodejs/adaptivecards-ui-testapp/adaptivecards-ui-testapp.css
source/nodejs/adaptivecards-ui-testapp/index.html
source/nodejs/adaptivecards-ui-testapp/src/adaptivecards-ui-testapp.css
source/nodejs/adaptivecards-ui-testapp/webpack.config.js
source/nodejs/adaptivecards/src/adaptivecards.css
source/nodejs/adaptivecards/src/carousel.ts

* Adds new css class to handle width of cards inside a carousel
* Add css to the ui test app

Fix minor Css changes for carousel

---

source/nodejs/adaptivecards-aaf-testapp/package.json
source/nodejs/adaptivecards-designer-app/package.json
source/nodejs/adaptivecards-designer/package.json
source/nodejs/adaptivecards-extras-designer/package.json
source/nodejs/adaptivecards-extras/package.json
source/nodejs/adaptivecards-react/package.json
source/nodejs/adaptivecards-site/package.json
source/nodejs/adaptivecards-templating/package.json
source/nodejs/adaptivecards-ui-testapp/package.json
source/nodejs/adaptivecards/package-lock.json
source/nodejs/adaptivecards/package.json

Updates the adaptivecards package version for release as it has to be a major version update

Update AdaptiveCards package version for release

---

source/nodejs/adaptivecards/README.md

Update `README.md` to note CSS breaking change.

[JS] Update README.md for breaking changes

---

source/dotnet/Library/AdaptiveCards.Rendering.Html/Properties/AssemblyInfo.cs
source/dotnet/Library/AdaptiveCards.Rendering.Wpf.Xceed/Properties/AssemblyInfo.cs
source/dotnet/Library/AdaptiveCards.Rendering.Wpf/Properties/AssemblyInfo.cs
source/dotnet/Library/AdaptiveCards.Templating/Properties/AssemblyInfo.cs
source/dotnet/Library/AdaptiveCards/Properties/AssemblyInfo.cs

Cherry pick from 75d78114b4e9d442986ab1c8b48402641a1cc188
* Update public key name
* Fix name
* Test path
* Test path
* Test path
* Test path
* Test path
* Test path
* Update key to right key

[Infrastructure][.NET] Update public key location for signing (#6589)

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards.xcodeproj/project.pbxproj
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRColumnSetRenderer.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRContentHoldingUIView.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRImageProperties.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRImageProperties.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRImageRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRMediaRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRMediaTarget.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/PrivateHeaders/UtiliOS.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/UtiliOS.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCardsTests/ACRImagePropertiesTests.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCardsTests/AdaptiveCardsTests.mm
source/ios/tools/AdaptiveCards.podspec

During testing https://github.com/microsoft/AdaptiveCards/pull/6863, found that two ratios has to become one. Otherwise,  some images won't get displayed.

[ios] updated round off logic

---

samples/HostConfig/berlin-dark.json
samples/HostConfig/berlin-light.json
source/nodejs/adaptivecards-designer/src/containers/berlin/berlin-container-dark.css
source/nodejs/adaptivecards-designer/src/containers/berlin/berlin-container-light.css

Updating Berlin host config and adding styling for carousel control and media.

Updating Berlin host configs and adding carousel style

---

.pipelines/js-ci.yml

remove node 14 dependency

---

source/ios/tools/AdaptiveCards.podspec

podspec update for 2.8.5 release

ios v2.8.5 release spec updated

---

samples/HostConfig/berlin-dark.json
samples/HostConfig/berlin-light.json
source/nodejs/adaptivecards-designer/src/containers/berlin/berlin-container-dark.css
source/nodejs/adaptivecards-designer/src/containers/berlin/berlin-container-light.css

Minor updates to the berlin container:
- making carousel control background transparent
- adding light font for light theme
- adding dark font for dark theme

Minor style updates for Berlin container

---

source/nodejs/adaptivecards-site/pages/_posts/2019/Community-Call-December.md

#6437 
Add a title to the `iframe` element in the December 2019 blog post
Accessibility insights for web no longer raises a failure for the iframe component.

Add title to iframe component in December 2019 blog post

---

source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizerUITests/ADCIOSVisualizerUITests.mm

* added missing 'swipe up' command in the prior check-in

added swipe up

---

source/nodejs/adaptivecards-site/pages/_posts/2019/Community-Call-June.md
source/nodejs/adaptivecards-site/pages/_posts/2019/Community-Call-March.md
source/nodejs/adaptivecards-site/pages/_posts/2019/Community-Call-May.md
source/nodejs/adaptivecards-site/pages/_posts/2019/Community-Call-October.md
source/nodejs/adaptivecards-site/pages/_posts/2019/Community-Call-September.md

#6437 
Add a title to the `iframe` elements in the following blog posts
- March 2019
- May 2019
- June 2019
- September 2019
- October 2019
Accessibility insights for web no longer raises a failure for the iframe component.

Add titles to iframe elements

---

source/nodejs/adaptivecards-designer/src/containers/berlin/berlin-container-dark.css
source/nodejs/adaptivecards-designer/src/containers/berlin/berlin-container-light.css

Adding rounded corners to container control in Berlin config.

Adding rounded corners to container

---

source/android/adaptivecards/CMakeLists.txt
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards.xcodeproj/project.pbxproj

Fix android and ios build for closed captions

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRTextBlockRenderer.mm

Fixed #7009 
Fixed VO to announce rotor controls and misspelled words.
https://github.com/microsoft/AdaptiveCards/blob/main/samples/v1.2/Scenarios/ExpenseReport.json
1. Unit tests are run
2. sample cards are examined for TextBlock / RichTextBlock / Input Labels

fixed vo announcing misspelled words

---

source/ios/tools/AdaptiveCards.podspec

Update podspec for ios release

update podspec for ios release

---

source/dotnet/Library/AdaptiveCards.Templating/AdaptiveCardTemplate.cs
source/dotnet/Library/AdaptiveCards.Templating/AdaptiveCardsTemplateResult.cs
source/dotnet/Library/AdaptiveCards.Templating/AdaptiveCardsTemplateVisitor.cs
source/dotnet/Library/AdaptiveCards.Templating/docs/AdaptiveCardsTemplate.md
source/dotnet/Test/AdaptiveCards.Templating.Test/TestTransform.cs

Cherry picked changes for the next release. Includes:
* https://github.com/microsoft/AdaptiveCards/issues/7433
* https://github.com/microsoft/AdaptiveCards/issues/6630
* https://github.com/microsoft/AdaptiveCards/issues/6680
* https://github.com/microsoft/AdaptiveCards/issues/6854
- Unit tests
- Checked all templates in Sample/Templates folder with the WPF Visualizer

Cherry pick changes for .NET Templating 1.3.0

---

source/dotnet/Library/AdaptiveCards.Templating/AdaptiveCardsTemplateSimpleObjectMemory.cs
source/dotnet/Library/AdaptiveCards.Templating/AdaptiveCardsTemplateVisitor.cs
source/dotnet/Test/AdaptiveCards.Templating.Test/TestTransform.cs

cherry picked .Net template changes.

Updated Template (#7485)

---

source/dotnet/Library/AdaptiveCards.Templating/AdaptiveCardsTemplateSimpleObjectMemory.cs
source/dotnet/Library/AdaptiveCards.Templating/AdaptiveCardsTemplateVisitor.cs
source/dotnet/Test/AdaptiveCards.Templating.Test/TestTransform.cs

Fixed #7570 
1. Moved serialization from AdaptiveCardsTemplateSimpleObjectMemory to Expand to ensure serialization is done for json object as well. 
2. refactored & clean up the manual serialization.
1.New Unit test is added & verified.
2. Existing relevant unit/regression tests were performed.

updated & cleaned serialization

---

samples/v1.2/Scenarios/ExpenseReport.json
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/BaseActionElementRenderer.java

Fixes https://github.com/microsoft/AdaptiveCards/issues/6260
Adds announcements for all elements that changed visibility in the card after a toggle visibility action has been pressed using its Id values.
Tested through talkback

[a11y] Add code to announce items that changed visibility

---

source/nodejs/adaptivecards-designer/src/containers/berlin/berlin-container.ts

Update the default target version for berlin containers.
Verified manually on the Adaptive Cards Designer.

[Designer] Update container default target version

---

source/nodejs/adaptivecards-designer/src/containers/berlin/berlin-container-dark.css
source/nodejs/adaptivecards-designer/src/containers/berlin/berlin-container-light.css
source/nodejs/adaptivecards-designer/src/containers/berlin/berlin-container.ts

Fixes #6906 
Updating the styling of the berlin containers.
Verified manually on the AdaptiveCards designer.

[Designer] Update container styling

---

.pipelines/android-ci.yml

Disabling the android pipeline since there is an issue with the emulator.

Disable android pipeline

---

source/nodejs/adaptivecards-react-testapp/package-lock.json
source/nodejs/adaptivecards-react-testapp/package.json
source/nodejs/adaptivecards-site/package-lock.json
source/nodejs/adaptivecards-site/package.json

Looks like this might help resolve the last remaining issues, but I haven't tested more thoroughly than to verify that the `hexo-reading-time` plugin is generating reading times (you can see this on blog posts) and that the service worker gets installed. :shipit:

Updates for Anna's `lerna` branch

---

source/ios/tools/AdaptiveCards.podspec
source/shared/cpp/AdaptiveCardsSharedModel/AdaptiveCardsSharedModelUnitTest/MarkDownUnitTest.cpp
source/shared/cpp/ObjectModel/MarkDownBlockParser.cpp
source/shared/cpp/ObjectModel/MarkDownBlockParser.h

* Fixed the link parser
* revert clang-format changes
* added unit test & more changes
* updated comment
* clang-format fix

Fixed the hard crash at link parser (#7817)

---

log
source/nodejs/adaptivecards/src/card-elements.ts

removed the restriction
need to enforce rule of preventing nested Carousel.

removed the restriction

---

source/nodejs/adaptivecards/src/card-elements.ts
source/nodejs/adaptivecards/src/carousel.ts
source/nodejs/adaptivecards/src/registry.ts

Remove additional singleton logic since it was for the carousel.

Remove additional singleton logic

---

source/nodejs/adaptivecards/src/carousel.ts
source/nodejs/adaptivecards/src/utils.ts

fixed selection action event firing with swiper events

---

.pipelines/js-release.yml

(cherry picked from commit 99297d8e24e949646d115a319f874cc00a26f51e)

Update js-release.yml to use npm 8.11.0

---

source/dotnet/Library/AdaptiveCards.Rendering.Wpf/AdaptiveColumnSetRenderer.cs
source/dotnet/Library/AdaptiveCards.Rendering.Wpf/AdaptiveRenderContext.cs

fixes #7934 , fixes #7935 
These two issues are highly related.  One was found as the symptom of the other. Though, I can separate this into two PRs if desired.
1. When executing a ToggleVisibilty action, if a target Id does not exist in the card, a null-ref exceptions occurs. And in the case of the WPFVisualizer, the app crashes. This seems a little undesirable. I've updated the offending code to first check if the Id is in the dictionary and just log a warning if it is no.
2. Columns with a height='stretch' are not being tracked in the dictionary. Consequently, you cannot toggle their visibility. (And without the first fix, you just get a crash.) Note: Columns with height='auto' are being track in AdaptiveRenderContext.Render(), however, this looks like it might just be a happy …

[WPF] Fixes for Missing Target Ids

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRMediaRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRMediaTarget.mm

Fixed #6293 
Instructed VO to announce 'media loading' in the beginning of the media playback.
https://github.com/microsoft/AdaptiveCards/blob/main/samples/v1.1/Scenarios/ProductVideo.json
Manually verified the scenario

a11y media bug fix

---

.pipelines/js-release.yml

Fixes release job to push into npmjs
Added a new service connection where auth token is used rather than username + password

Fix npm release pipeline

---

samples/v1.0/Elements/Action.Submit.json
samples/v1.0/Elements/Input.Number.json

Fixes #7914
Added the `label` property to input controls since the samples were missing a visual label.
Verified manually on the Adaptive Cards Schema Explorer.

[Web Accessibility] Add labels to inputs in samples

---

source/dotnet/Library/AdaptiveCards/AdaptiveAction.cs
source/dotnet/Library/AdaptiveCards/AdaptiveCollectionElement.cs
source/dotnet/Library/AdaptiveCards/AdaptiveColumnSet.cs
source/dotnet/Library/AdaptiveCards/AdaptiveContainer.cs
source/dotnet/Library/AdaptiveCards/docs/AdaptiveCards.md
source/dotnet/Test/AdaptiveCards.Test/AdaptiveActionTests.cs
source/dotnet/Test/AdaptiveCards.Test/AdaptiveCardApiTests.cs

https://microsoft.visualstudio.com/OS/_workitems/edit/41838288
* Updated AdaptiveCollectionElement to implement IEnumerable in order to make search & iteration of AdaptiveTypedElement convenient. 
* Added a few test Utilities.
* Added a method to find an element for given id.
* Added a method that injects key value pair to AdaptiveCard using AdditionalProperites.
* This method helps reduce the burden of having to write AdaptiveCard payload string which is error prone & requires much focus to write. 
* To write an expected payload, one can write a card using objects, then inject the new properties using the method. The method will return a serialized JSON card.
* Implemented `isEnabled` property 
Samples are in v1.5.
1. New …

implemented isEnabled

---

source/dotnet/Library/AdaptiveCards/AdaptiveAction.cs
source/dotnet/Library/AdaptiveCards/AdaptiveActionMode.cs
source/dotnet/Library/AdaptiveCards/AdaptiveWarning.cs
source/dotnet/Library/AdaptiveCards/IgnoreDefaultStringEnumConverter.cs
source/dotnet/Library/AdaptiveCards/docs/AdaptiveCards.md
source/dotnet/Test/AdaptiveCards.Test/AdaptiveActionTests.cs

https://microsoft.visualstudio.com/OS/_workitems/edit/41839333
Implemented 'Mode' to Actions
We have sample cards in v1.5.
1. Unit tests are added

Added 'Mode' to Actions

---

source/dotnet/Library/AdaptiveCards/AdaptiveCollectionElement.cs
source/dotnet/Library/AdaptiveCards/AdaptiveTextBlockStyle.cs
source/dotnet/Test/AdaptiveCards.Test/AdaptiveActionTests.cs
source/dotnet/Test/AdaptiveCards.Test/AdaptiveCardApiTests.cs
source/dotnet/Test/AdaptiveCards.Test/Utilities.cs

https://microsoft.visualstudio.com/OS/_workitems/edit/41839444
* Updated the converter to create warning when invalid enumeration values are encountered.
* Added unit test.
* Created Utility class for common utility functions.
samples/V1.5
1. New unit test is added.

Updated TextBlockStyle JSONConverter

---

source/dotnet/Library/AdaptiveCards/AdaptiveAction.cs
source/dotnet/Library/AdaptiveCards/docs/AdaptiveCards.md
source/dotnet/Test/AdaptiveCards.Test/AdaptiveActionTests.cs
source/dotnet/Test/AdaptiveCards.Test/AdaptiveInputTests.cs
source/dotnet/Test/AdaptiveCards.Test/Utilities.cs

https://microsoft.visualstudio.com/OS/_workitems/edit/41839355
Added tooltip support to .Net.
A minor update to test utilites.
https://github.com/microsoft/AdaptiveCards/blob/main/samples/v1.5/Elements/Action.Submit.Tooltip.json
1. New unit tests that were added if any.

implemented tooltip

---

samples/Templates/Scenarios/Agenda.template.json
samples/Templates/Scenarios/ApplicationLogin.template.json
samples/Templates/Scenarios/CalendarReminder.template.json
samples/Templates/Scenarios/ExpenseReport.template.json
samples/Templates/Scenarios/FlightDetails.template.json
samples/Templates/Scenarios/FlightItinerary.template.json
samples/Templates/Scenarios/FlightUpdate.template.json
samples/Templates/Scenarios/FlightUpdateTable.template.json
samples/Templates/Scenarios/FoodOrder.template.json
samples/Templates/Scenarios/ImageGallery.template.json
samples/Templates/Scenarios/OrderConfirmation.template.json
samples/Templates/Scenarios/RestaurantOrder.template.json
samples/Templates/Scenarios/Solitaire.template.json
samples/Templates/Scenarios/SportingEvent.template.json
samples/Templates/Scenarios/StockUpdate.template.json
samples/Templates/Scenarios/WeatherCompact.template.json
samples/Templates/Scenarios/WeatherLarge.template.json
samples/v1.0/Scenarios/FlightItinerary.json
samples/v1.0/Scenarios/StockUpdate.json
samples/v1.2/Scenarios/Agenda.json
samples/v1.2/Scenarios/FlightDetails.json
samples/v1.5/Scenarios/ApplicationLogin.json
samples/v1.5/Scenarios/ExpenseReport.json
samples/v1.5/Scenarios/FlightUpdateTable.json
samples/v1.5/Scenarios/OrderConfirmation.json
samples/v1.5/Scenarios/RestaurantOrder.json

Update enums to be lowercase to maintain consistency in the samples.
Resolves PR comments: https://github.com/microsoft/AdaptiveCards/pull/8010#discussion_r1017223610
Verified on the AdaptiveCards site.

[Samples] Update enum values for consistency

---

source/dotnet/Samples/WPFVisualizer/AdaptiveCards.Sample.WPFVisualizer.csproj
source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizerUITests/ADCIOSVisualizerUITests.mm
source/nodejs/adaptivecards-ui-testapp/src/file-retriever-utils.ts
source/nodejs/tests/ui-tests/src/ui-tests.test.ts
source/uwp/AdaptiveCardTestApp/AdaptiveCardTestApp.csproj
source/uwp/PerfApp/PerfApp.vcxproj
source/uwp/Renderer/lib/AdaptiveTableRenderer.cpp
source/uwp/UWPUITestApp/UWPUITestApp.csproj
source/uwp/UWPUnitTests/UWPUnitTests.csproj
source/uwp/Visualizer/AdaptiveCardVisualizer.csproj

Update test apps to reference the correct file paths for samples.
Added v1.5 samples to the UWP Visualizer since all of the samples have been moved.
Issue rendering the table element: https://github.com/microsoft/AdaptiveCards/issues/8051

[Samples]Update test apps samples

---

scripts/upm/meta-files/AdaptiveCards/AdaptiveCollectionWithContentAlignment.cs.meta
scripts/upm/meta-files/AdaptiveCards/AdaptiveHorizontalContentAlignment.cs.meta
scripts/upm/meta-files/AdaptiveCards/AdaptiveTable.cs.meta
scripts/upm/meta-files/AdaptiveCards/AdaptiveTableCell.cs.meta
scripts/upm/meta-files/AdaptiveCards/AdaptiveTableColumnDefinition.cs.meta
scripts/upm/meta-files/AdaptiveCards/AdaptiveTableRow.cs.meta
scripts/upm/meta-files/AdaptiveCards/ColumnWidthConverter.cs.meta

New source files where recently added to the .NET library. This change adds the associate .meta files for the UPM packaging.
Ran external Azure pipeline which checks for missing or orphaned .meta files.

Add .Meta Files for New Source Files

---

custom.props

Updated custom prop to 3.0.0 for .net AdaptiveCards nuget package.

updated custom prop for .net AdaptiveCards nuget release

---

source/android/adaptivecards/src/AdaptiveCardObjectModel.i

Fix android pipeline for shared model changes to support new choices.data object in Input.ChoiceSet

[TypeAheadSearch][Choices.Data]Shared model changes for android

---

.pipelines/templates/ios-ci-template.yml

N/A
ios ci pipeline is failing due to xcode version. Updated the pipeline yml for this change.
N/A
N/A

Updated Xcode version

---

.pipelines/templates/ios-ci-template.yml
custom.props

Update custom.props so the correct version of UWP object model is published.
Note: Updated to v1.1.0 since there are new features

[UWP] Update custom.props for object model release

---

custom.props
source/uwp/Build/CopySignFiles.cmd
source/uwp/NuGet/AdaptiveCards.Rendering.Uwp.nuspec

Cherry-pick object model nuget changes fro release branches to main.

[UWP] Cherry-pick object model nuget changes

---

source/uwp/Build/CopySignFiles.cmd
source/uwp/NuGet/AdaptiveCards.Rendering.Uwp.nuspec

Cherry-pick nuget changes for UWP release.

[UWP][Infra] Update nuget files for release (#6576)

---

.pipelines/js-ci.yml

Added task to set node & npm version to prevent build break by the version changes in the pipeline
Cherry-pick the JS pipeline fix to the uwp release branch

[Infra] Update js-ci.yml (#8311)

---

custom.props

Update the custom props version for the latest UWP renderer release.

Update custom props for UWP release

---

source/uwp/NuGet/AdaptiveCards.Rendering.Uwp.nuspec

Update the object model dependency so that both packages do not need to be installed.

[UWP] Update object model dependency

---

source/NuGet.config

Update nuget.config for failing pipelines

[Infra] Update nuget.config

---

source/nodejs/adaptivecards-site/pages/_posts/2023/Announcing-WinUI3-Renderer.md

Added blog post announcing WinUI 3 renderer release.

Added blog post for WinUI 3 announcement

---

source/uwp/winui3/NuGet/AdaptiveCards.ObjectModel.WinUI3.nuspec

Reset objectmodel version

---

custom.props
source/NuGet.config
source/uwp/NuGet/AdaptiveCards.ObjectModel.Uwp.nuspec
source/uwp/NuGet/AdaptiveCards.Rendering.Uwp.nuspec

Cherry-pick Nuget.Config update and bump nuspecs versions

---

source/nodejs/adaptivecards-designer/src/containers/teams/teams-container.ts
source/nodejs/adaptivecards-designer/src/containers/viva-connections/viva-connections-container.ts

Fixes #8487 
Update default version for teams and viva connections as they now support v1.5.
N/A
Verified that the correct version is selected when navigating to the containers.

[Designer] Update container versions

---

samples/Templates/Scenarios/WeatherLarge.template.json
samples/v1.5/Scenarios/WeatherLarge.json

Fixes #8472 
Update `selectAction` title property on the weather sample so that the description meets accessibility requirements.
Weather samples found in this PR.
Verified manually on android visualizer and generated AC website

[Samples] Update tooltip for weather sample

---

samples/Templates/Scenarios/InputsWithValidation.template.json
samples/v1.5/Scenarios/InputsWithValidation.json

Fixes #8469
Update sample to include min/max values for Input.Number label.
In PR
Validated manually on the android visualizer

[Samples] Update label for number input

---

source/nodejs/adaptivecards-aaf-testapp/package.json
source/nodejs/adaptivecards-designer-app/package.json
source/nodejs/adaptivecards-designer/package.json
source/nodejs/adaptivecards-extras-designer/package.json
source/nodejs/adaptivecards-extras/package.json
source/nodejs/adaptivecards-react/package.json
source/nodejs/adaptivecards-site/package.json
source/nodejs/adaptivecards-site/themes/adaptivecards/source/css/style.css
source/nodejs/adaptivecards-templating/package.json
source/nodejs/adaptivecards-ui-testapp/package.json
source/nodejs/adaptivecards/package-lock.json
source/nodejs/adaptivecards/package.json
source/nodejs/adaptivecards/src/serialization.ts

version updated

---

source/android/mobile/src/main/res/raw/importer_card.json

Fixed #8547, and fixed #8473
Disabled host config option as it creates too much permutations on a11y testing scenarios.

disabled host config option in sample app

---

source/uwp/winui3/NuGet/AdaptiveCards.Rendering.WinUI3.nuspec

Update nuget for the correct versions

Update nuget versions

---

source/ios/tools/AdaptiveCards.podspec

updated ios version

---

samples/Templates/Scenarios/FlightUpdateTable.template.json
samples/v1.5/Scenarios/FlightUpdateTable.json

Fixed #8456 
I made each passenger entry have its own table row.
FlightUpdateTable.json
There is a slight visual change in the UWP visualizer, but the new visual is accurate as each passenger aligns correctly with their seats.

updated sample

---

samples/v1.5/Scenarios/Agenda.json

Fixed #8457 
Updated sample images to higher contrast.
Agenda.json
Used A11y Insight tool to confirm the contrast.

updated agenda.json

---

.pipelines/clang-format-ci.yml

Updates the Node version used in the Clangformat-ci pipeline

Upgrade Node version for clang format ci

---

source/dotnet/Library/AdaptiveCards.Templating.Net6/AdaptiveCards.Templating.Net6.csproj
source/dotnet/Library/AdaptiveCards.Templating.Net6/Properties/AssemblyInfo.cs
source/dotnet/NuGet/AdaptiveCards.Templating.nuspec

Update nuget package versions for changes between testing and release

Fix outdated nuget packages

---

source/dotnet/NuGet/AdaptiveCards.Rendering.Wpf.nuspec
source/dotnet/NuGet/AdaptiveCards.Templating.nuspec
source/dotnet/NuGet/AdaptiveCards.nuspec

Update version numbers for net6 release

Update versions for Net6 release

---

source/uwp/winui3/ObjectModelCsProjection/ObjectModelCsProjection.csproj

Compile AdaptiveCards.ObjectModel.WinUI3.dll with code generation mitigations for Spectre vulnerabilities
N/A

[WinUI 3] Add ControlFlowGuard and SpectreMitigation to ObjectModel

---

source/nodejs/adaptivecards-site/themes/adaptivecards/source/web.config

Set [HTTP `Strict-Transport-Security`](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security) header for website.

[Site] Set HSTS header

---

source/nodejs/adaptivecards-aaf-testapp/package.json
source/nodejs/adaptivecards-designer-app/package.json
source/nodejs/adaptivecards-designer/package.json
source/nodejs/adaptivecards-extras-designer/package.json
source/nodejs/adaptivecards-extras/package.json
source/nodejs/adaptivecards-react/package.json
source/nodejs/adaptivecards-site/package.json
source/nodejs/adaptivecards-templating/package.json
source/nodejs/adaptivecards-ui-testapp/package.json
source/nodejs/adaptivecards/package-lock.json
source/nodejs/adaptivecards/package.json

Update the JS renderer version to 3.0.2 for release.
N/A
Verified manually.

[release] Update JS renderer version

---

source/nodejs/adaptivecards-aaf-testapp/package.json
source/nodejs/adaptivecards-designer-app/package.json
source/nodejs/adaptivecards-designer/package.json
source/nodejs/adaptivecards-extras-designer/package.json
source/nodejs/adaptivecards-extras/package.json
source/nodejs/adaptivecards-react/package.json
source/nodejs/adaptivecards-site/package.json
source/nodejs/adaptivecards-templating/package.json
source/nodejs/adaptivecards-ui-testapp/package.json
source/nodejs/adaptivecards/package-lock.json
source/nodejs/adaptivecards/package.json

Sync release branch with main.
N/A

Update JS renderer version (#8722)

---

source/nodejs/adaptivecards-site/themes/adaptivecards/source/css/extracted.css

Small update for the website's CSS to fix a slight contrast issue.
Local testing with Accessibility Insights

Fix `--blue` to be a _smidge_ darker (better contrast on `--black`)

---

source/uwp/SharedVisualizer/HostConfigs/DefaultHostConfig.json
source/uwp/SharedVisualizer/HostConfigs/DefaultHostConfigHighContrastAquatic.json
source/uwp/SharedVisualizer/HostConfigs/DefaultHostConfigHighContrastDesert.json
source/uwp/SharedVisualizer/HostConfigs/DefaultHostConfigHighContrastDusk.json
source/uwp/SharedVisualizer/HostConfigs/DefaultHostConfigHighContrastNightSky.json

Fixes #8631 
Update accent color to be slightly darker to fix contrast issues.
FlightDetails samples
Verified manually with the visualizer.

Update accent color for UWP visualizer

---

samples/Templates/Scenarios/FlightDetails.template.json
source/nodejs/adaptivecards-site/pages/_posts/2020/Community-Call-March.md
source/nodejs/adaptivecards-site/themes/adaptivecards/layout/designer.ejs

Added a few missing image alt texts for a11y.
Local build and devtools

Add missing img alt text in a few spots

---

source/nodejs/adaptivecards-controls/src/adaptivecards-controls.css
source/nodejs/adaptivecards-designer/src/adaptivecards-designer.css
source/nodejs/adaptivecards-designer/src/containers/bf-image/bf-image-container.css
source/nodejs/adaptivecards-designer/src/containers/default/adaptivecards-defaulthost.css
source/nodejs/adaptivecards-designer/src/containers/outlook/outlook-container.css
source/nodejs/adaptivecards-designer/src/containers/skype/skype-container.css
source/nodejs/adaptivecards-designer/src/containers/webchat/webchat-container.css
source/nodejs/adaptivecards-site/themes/adaptivecards/layout/index.ejs
source/nodejs/adaptivecards-site/themes/adaptivecards/source/css/style.css
source/nodejs/adaptivecards-ui-testapp/adaptivecards-ui-testapp.css
source/nodejs/adaptivecards/src/scss/adaptivecards-vars.scss

Tweak common blue background color for AA contrast -- it's a subtle change, but gets us past the automated tooling.
old:
new:

Slight tweak to common blue background/border color for contrast

---

source/uwp/SharedRenderer/lib/XamlHelpers.cpp

Fixed #8632 
Explicitly set "required" label for required input.

fixed a11y issue

---

source/uwp/Renderer/AdaptiveCardRenderer.vcxproj

fixes https://microsoft.visualstudio.com/OS/_queries/edit/48038155/?triage=true

[TSA]: Resolve XFGCHECK issue

---

samples/v1.5/Elements/Input.ChoiceSet.Filtered.json
source/uwp/AdaptiveCardTestApp/Expected/SourceCards/v1.2.Elements.Column.BackgroundImage.89f2ca4.json

fixes:
https://microsoft.visualstudio.com/OS/_workitems/edit/48037236
https://microsoft.visualstudio.com/OS/_workitems/edit/48037244
https://microsoft.visualstudio.com/OS/_workitems/edit/48037248
https://microsoft.visualstudio.com/OS/_workitems/edit/48037251
https://microsoft.visualstudio.com/OS/_workitems/edit/48037253
https://microsoft.visualstudio.com/OS/_workitems/edit/48037254
https://microsoft.visualstudio.com/OS/_workitems/edit/48037256
https://microsoft.visualstudio.com/OS/_workitems/edit/48037258
https://microsoft.visualstudio.com/OS/_workitems/edit/48037265

[TSA Fix]: Remove strings that policheck complains about

---

source/uwp/AdaptiveCardsObjectModel/AdaptiveCardsObjectModel.vcxproj
source/uwp/Renderer/AdaptiveCardRenderer.vcxproj
source/uwp/winui3/AdaptiveCardsObjectModel/AdaptiveCardsObjectModel.vcxproj
source/uwp/winui3/Renderer/AdaptiveCardRenderer.vcxproj

#8780 
Adds [ControlFlowGuard](https://learn.microsoft.com/en-us/windows/win32/secbp/control-flow-guard), [Spectre](https://learn.microsoft.com/en-us/cpp/build/reference/qspectre?view=msvc-170) and enable [DEBUG:FIXUP](https://learn.microsoft.com/en-us/cpp/build/reference/debugtype-debug-info-options?view=msvc-170) flags for UWP and WinUI3 dlls

[Infra] Fix bugs opened by the pipeline

---

source/nodejs/adaptivecards/src/scss/adaptivecards-default.scss

Fixes #8818
Fix invalid color value
- Build CSS file with `npm run generate-css`
- Include the file `adaptivecards.css` in a page
- Validate the CSS file
- Inspect hover state of the .ac-pushButon component

Fix invalid color value

---

.pipelines/uwp-ci.yml
.pipelines/winui3-ci.yml

[Cherry-pick] [Maintenance]: Migrate NugetRestore@1 to NugetCommand (#8841)

---

source/nodejs/adaptivecards/src/card-elements.ts

Move accessibility fix to website release branch.

[Cherry-pick] Remove tab index from nested inputs (#8848)

---

source/shared/cpp/ObjectModel/ColumnSet.cpp
source/shared/cpp/ObjectModel/ColumnSet.h
source/uwp/AdaptiveCardsObjectModel/idl/AdaptiveCards.ObjectModel.Uwp.idl
source/uwp/SharedObjectModel/lib/AdaptiveColumnSet.cpp
source/uwp/SharedObjectModel/lib/AdaptiveColumnSet.h
source/uwp/SharedRenderer/lib/AdaptiveColumnSetRenderer.cpp
source/uwp/winui3/AdaptiveCardsObjectModel/idl/AdaptiveCards.ObjectModel.WinUI3.idl

https://microsoft.visualstudio.com/OS/_workitems/edit/50998939
Added horizontal alignment property to ColumnSet
Ran unit tests and manually verified.

Added horizontal alignment

---

source/nodejs/adaptivecards/package-lock.json
source/nodejs/adaptivecards/package.json
source/nodejs/adaptivecards/src/card-elements.ts

Checking this changes on behalf of @Farcemolina 
Fixes a11y issues, please check commit message.

Add trusted types support

---

source/dotnet/Library/AdaptiveCards.Rendering.Wpf.Net6/AdaptiveCards.Rendering.Wpf.Net6.csproj
source/dotnet/NuGet/AdaptiveCards.Rendering.Wpf.nuspec
source/dotnet/Samples/AdaptiveCards.Net6.Sample.ImageRender/AdaptiveCards.Net6.Sample.ImageRender.csproj
source/dotnet/Samples/WPFVisualizerNet6/AdaptiveCards.Sample.WPFVisualizer.Net6.csproj
source/dotnet/Samples/WPFVisualizerNet6/MainWindow.xaml.cs

Updating some outdated dependencies (also unbreak NET6 build).

[.NET] Update dependencies and unbreak net6 build

---

source/uwp/AdaptiveCardTestApp/AdaptiveCardTestApp.csproj
source/uwp/PerfApp/PerfApp.vcxproj
source/uwp/UWPUITestApp/UWPUITestApp.csproj
source/uwp/UWPUnitTests/UWPUnitTests.csproj
source/uwp/Visualizer/AdaptiveCardVisualizer.csproj

Rotating certs to fix uwp ci pipeline

[Infra] Updating uwp pipeline

---

source/nodejs/adaptivecards-designer/src/containers/webchat/webchat-container.ts

Duplicate of #9113 so that we can run pipelines.

Update webchat supported version in designer

---

source/nodejs/README.md
source/nodejs/adaptivecards-designer/CONTRIBUTING.md
source/nodejs/adaptivecards-designer/README.md
source/nodejs/adaptivecards-site/README.md

Updating documentation for designer and website

---

source/dotnet/Samples/ImageRendererServer/Controllers/RenderController.cs
source/dotnet/Samples/ImageRendererServer/ImageRendererServer.csproj

For CodeQL SFI Item - Validating known URI for SSRF SFI using antiSSRF

Validating known URI for SSRF SFI using antiSSRF
