microsoft/AdaptiveCards

source/uwp/Renderer/lib/XamlBuilder.cpp

UWP was accidently adding a column spacer before the first column in
column sets, resulting in incorrect padding appearing on the left of the
first column, as described in issue #340
Simply added an if check that skips adding the spacer if a column hasn't
been added yet. Tested and verified changes using Visualizer.

Fix UWP padding in first column

---

source/uwp/Renderer/lib/XamlBuilder.cpp

In the UWP renderer, if you're using an image with "person" style, and
you don't manually specify the size of the image, it was failing to
render, as described in issue #331. Non-person images render fine
without the style provided.
Code was forgetting to set the stretch behavior when image size was set
to Default inside the person logic branch of the code. Just had to add
that line so it included Default size.
Verified behavior in Visualizer. Now a "person" image behaves identically to a normal image when size is not specified.

Fix UWP person images that don't have size set

---

source/uwp/Renderer/lib/XamlBuilder.cpp

Enabling TrimSideBearings to ensure that regardless of the font size,
the left of the text is consistently in line with each other, fixing
issue #357
Simply had to assign that property (and moved the code to obtain
ITextBlock2 to the top since it's used in two places now)
Verified changes using Visualizer, text is now always flush to the left, pixel perfect!

Ensure UWP text elements are perfectly left aligned

---

source/uwp/Renderer/lib/XamlBuilder.cpp

The UWP ComboBox defaults horizontal alignment to left, whereas in the
compact ChoiceSet picker, it's desired that the picker displays
full-width just like text boxes, as described in issue #337
Simply assigned HorizontalAlignment to Stretch on the ComboBox to fix
this. Verified changes with Visualizer.
**Before**
**After**

Fix UWP ComboBox not stretching width

---

source/shared/cpp/ObjectModel/AdaptiveCard.cpp
source/shared/cpp/ObjectModel/BaseActionElement.h
source/shared/cpp/ObjectModel/Column.cpp
source/shared/cpp/ObjectModel/ColumnSet.cpp
source/shared/cpp/ObjectModel/Container.cpp
source/shared/cpp/ObjectModel/Fact.cpp
source/shared/cpp/ObjectModel/FactSet.cpp
source/shared/cpp/ObjectModel/HttpAction.cpp
source/shared/cpp/ObjectModel/Image.cpp
source/shared/cpp/ObjectModel/ImageSet.cpp
source/shared/cpp/ObjectModel/InputChoice.cpp
source/shared/cpp/ObjectModel/InputChoiceSet.cpp
source/shared/cpp/ObjectModel/InputToggle.cpp
source/shared/cpp/ObjectModel/OpenUrlAction.cpp
source/shared/cpp/ObjectModel/ParseUtil.cpp
source/shared/cpp/ObjectModel/ParseUtil.h
source/shared/cpp/ObjectModel/ShowCardAction.cpp
source/shared/cpp/ObjectModel/SubmitAction.cpp
source/shared/cpp/ObjectModel/TextBlock.cpp

Parser was being too permissive with missing required properties. Parser will now throw if a required property is missing. It will keep ignoring extra fields, and allow for missing optional fields.

Shared Parser now understands Optional and required properties in the schema

---

source/shared/cpp/ObjectModel/AdaptiveCard.cpp
source/shared/cpp/ObjectModel/Column.cpp
source/shared/cpp/ObjectModel/ColumnSet.cpp
source/shared/cpp/ObjectModel/Container.cpp
source/shared/cpp/ObjectModel/Fact.cpp
source/shared/cpp/ObjectModel/FactSet.cpp
source/shared/cpp/ObjectModel/Image.cpp
source/shared/cpp/ObjectModel/ImageSet.cpp
source/shared/cpp/ObjectModel/ImageSet.h
source/shared/cpp/ObjectModel/InputChoice.cpp
source/shared/cpp/ObjectModel/InputChoiceSet.cpp
source/shared/cpp/ObjectModel/InputDate.cpp
source/shared/cpp/ObjectModel/InputNumber.cpp
source/shared/cpp/ObjectModel/InputText.cpp
source/shared/cpp/ObjectModel/InputTime.cpp
source/shared/cpp/ObjectModel/InputToggle.cpp
source/shared/cpp/ObjectModel/OpenUrlAction.cpp
source/shared/cpp/ObjectModel/ParseUtil.cpp
source/shared/cpp/ObjectModel/ParseUtil.h
source/shared/cpp/ObjectModel/ShowCardAction.cpp
source/shared/cpp/ObjectModel/SubmitAction.cpp
source/shared/cpp/ObjectModel/TextBlock.cpp
source/uwp/Renderer/lib/AdaptiveCard.cpp

UWP renderer also now uses the DeserializeFromString method rather than doing its own thing to render a card from a string.

Fix DeserializeFromString

---

source/shared/cpp/ObjectModel/ShowCardAction.cpp
source/shared/cpp/ObjectModel/ShowCardAction.h
source/shared/cpp/ObjectModel/SubmitAction.cpp
source/shared/cpp/ObjectModel/SubmitAction.h

Some Action classes had title as member variables. This is now part of the BaseActionElement class.

Fix Action Titles in shared model

---

source/shared/cpp/ObjectModel/Enums.cpp
source/shared/cpp/ObjectModel/Enums.h
source/shared/cpp/ObjectModel/ParseUtil.cpp
source/shared/cpp/ObjectModel/ParseUtil.h
source/shared/cpp/ObjectModel/SubmitAction.cpp
source/shared/cpp/ObjectModel/SubmitAction.h
source/uwp/Renderer/idl/AdaptiveCards.XamlCardRenderer.idl
source/uwp/Renderer/lib/AdaptiveSubmitAction.cpp
source/uwp/Renderer/lib/AdaptiveSubmitAction.h

Added the DataJson property to the UWP object model. DataJson returns a string of the JSON, consistent with the .NET version of the library that has a DataJson property.
Tested with visualizer app and Notifications Visualizer, confirmed that the "data" property is now being passed through and accessible by renderer hosts.
Fixes #387

UWP: Added DataJson property to Action.Submit

---

source/uwp/Renderer/lib/XamlBuilder.cpp

The boolean logic for auto/stretch was inverted. When dev specified stretch, auto was being assigned, and vice versa.
Fixed the boolean logic (also added check to invalidate negative star size entries) and verified changes using UWP Visualizer and Notifications Visualizer with all of the sample payloads
Before
After

Fixed UWP column auto/stretch behavior

---

source/uwp/Renderer/lib/XamlBuilder.cpp

Boolean logic for assigning subtle vs normal text color was inverted, so normal text was getting subtle color and vice versa. Reversed this logic to fix that problem.

Fixed UWP subtle vs normal colors being inverted

---

source/shared/cpp/ObjectModel/HostConfig.cpp

Padding property of AdaptiveCardConfig wasn't being parsed since it wasn't first obtaining the JSON value of property "padding" before attempting to deserialize the padding values.
Updated it to match the other sections of code which also parse spacing.
Confirmed with Visualizer that padding specified in JSON host config is now respected instead of ignored.

Fix UWP parsing of HostConfig card padding

---

source/shared/cpp/ObjectModel/Enums.cpp
source/shared/cpp/ObjectModel/HostConfig.cpp
source/uwp/Renderer/lib/XamlBuilder.cpp

This pull request addresses two issues: (1) Shared model wasn't parsing the actions property in HostConfig, and (2) UWP renderer wasn't properly displaying actions that were set to stretch (and also fixed up the vertical display behaviors too).
1) Parsing the actions property, that was a super simple one. The line of code to call parse actions was simply missing. Also noticed a subsequent bug where the mapping of inlineEdgeToEdge enum to string was missing so added that too.
2) For the buttons, the images below illustrate it best.
When HostConfig set to Horizontal, Stretch, the renderer used to be displaying this...
After my first fixes, it correctly displayed this
But notice there's extra padding on the left and right of the buttons. That's because for the button spacing, the code is …

Fix stretch behavior on UWP rendered actions

---

source/website/wwwroot/samples/cards/Stock Update.json

strech => stretch
Noticed a `Invalid column size: strech` when reading through the samples. http://imgur.com/a/lsAbP   Hence, this minor fix to the typo.

Fixed an ultra minor typo

---

source/shared/cpp/ObjectModel/SharedAdaptiveCard.cpp
source/uwp/Renderer/lib/XamlBuilder.cpp
source/uwp/Renderer/lib/XamlBuilder.h

Also ensures that UWP doesn't add separation padding above the actions if the body is empty. Tested/verified changes in the UWP Visualizer.
Addresses #545 #548 
Tested/verified fixes with UWP Visualizer with both body elements and no body elements, all good!

Make body optional

---

source/dotnet/Library/AdaptiveCards.Html/Rendering/HtmlRenderer.cs

Render the TextInput with <textarea> instead of <p>. The class is ac-input and ac-textinput to match the client renderer.

Render TextInput with textarea element

---

source/uwp/Renderer/lib/XamlBuilder.cpp
source/uwp/Renderer/lib/XamlBuilder.h
source/uwp/Renderer/lib/XamlHelpers.h

Fixes #540
Inputs and actions are silently ignored per current desired behavior and will just not show up in the resulting card.

Check for SupportInteractivity setting before rendering inputs

---

source/shared/cpp/ObjectModel/ChoiceSetInput.cpp
source/shared/cpp/ObjectModel/Column.cpp
source/shared/cpp/ObjectModel/ColumnSet.cpp
source/shared/cpp/ObjectModel/FactSet.cpp
source/shared/cpp/ObjectModel/Image.cpp
source/shared/cpp/ObjectModel/Image.h
source/shared/cpp/ObjectModel/ImageSet.cpp
source/shared/cpp/ObjectModel/ParseUtil.h

Updated the shared model so that columns don't require a type property (since their type is implicit) and images inside ImageSet don't require a type property. Facts and ChoiceInputs already didn't require the type property.
Also refactored fact/choicesetinput code to use the new shared method for parsing an array of single type.
Tested/verified all changes in UWP Visualizer app for ChoiceSet, ColumnSet, FactSet, ImageSet, and normal inline images both with and without types specified, all worked correctly.

Shared Model: Optional type property on Set children

---

source/dotnet/AdaptiveCards.sln
source/dotnet/Library/AdaptiveCards.Html/HtmlTag.cs
source/dotnet/Library/AdaptiveCards.Html/MarkdownToHtmlTagConverter.cs
source/dotnet/Library/AdaptiveCards.Html/Rendering/HtmlRenderer.cs
source/dotnet/Test/AdaptiveCards.Html.Test/AdaptiveCards.Html.Test.csproj
source/dotnet/Test/AdaptiveCards.Html.Test/HtmlRendererTests.cs
source/dotnet/Test/AdaptiveCards.Html.Test/MarkdownToHtmlTagConverterTests.cs

The markdown processor has the ability to return XHTML, so I'm leveraging that to parse the returned markup and convert it into full-fidelity HtmlTag objects. Doing so lets me remove the LiteralTag class and the IHtmlTag interface, and therefore have all returned objects be of type HtmlTag. With this change, it becomes possible to post-process the HtmlTag objects outside of the AdaptiveCards renderer project and actually be able to touch everything in the object tree.
Also added unit tests for the markdown rendering to ensure that the conversion operates as expected, and that the HtmlTag.ToString() is working correctly.

Remove LiteralTag and convert markdown into full HtmlTag objects

---

source/uwp/Renderer/lib/AsyncOperations.h
source/uwp/Renderer/lib/IImageLoadTrackerListener.h
source/uwp/Renderer/lib/IXamlBuilderListener.h
source/uwp/Renderer/lib/ImageLoadTracker.cpp
source/uwp/Renderer/lib/ImageLoadTracker.h
source/uwp/Renderer/lib/XamlBuilder.cpp
source/uwp/Renderer/lib/XamlBuilder.h

Exceptions thrown while building the Xaml tree were not being caught and reported to the async operation. This resulted in the Async operation never completing.
This change adds two error results to the async operation:
Image Loading related Errors
All other XamlBuilder errors.
This will be overhauled once we switch the renderer to return a RenderResult instead of the Xaml elements directly.

Stop UWP renderer from crashing due to Image loading/XamlBuilder exceptions.

---

source/uwp/Renderer/lib/XamlBuilder.cpp

Fixes #616. Simply had to assign horizontal alignment stretch.
**BEFORE**
**AFTER**
Note that at very wide sizes, the time picker will reach a max width and stop growing. Not sure there's an easy way to fix that (I believe that's a limitation in the time picker itself). Plus it seems like we have a TODO to support displaying placeholder text on the time picker, which would require creating a brand new control, so that new control would support super wide widths... no need to invest time in making the time picker we have today support ultra-wide sizes.

Fix UWP date/time not stretching full width

---

source/uwp/Renderer/idl/AdaptiveCards.XamlCardRenderer.idl
source/uwp/Renderer/lib/AsyncOperations.h
source/uwp/Renderer/lib/XamlCardRendererComponent.cpp
source/uwp/Renderer/lib/XamlCardRendererComponent.h

Adding SetFixedDimensions to the XAML card renderer component so that we  can get timeline image renderer off the XAML builder to use the public APIs directly.

Add SetFixedDimensions to the Xaml Card Renderer

---

source/uwp/Renderer/lib/Util.cpp
source/uwp/Visualizer/DocumentView.xaml
source/uwp/Visualizer/GenericDocumentView.xaml
source/uwp/Visualizer/GenericDocumentView.xaml.cs
source/uwp/Visualizer/HostConfigs/DefaultHostConfig.json
source/uwp/Visualizer/MainPage.xaml
source/uwp/Visualizer/MainPage.xaml.cs
source/uwp/Visualizer/ViewModel/DocumentViewModel.cs
source/uwp/Visualizer/ViewModel/GenericDocumentViewModel.cs
source/uwp/Visualizer/ViewModel/HostConfigEditorViewModel.cs
source/uwp/Visualizer/ViewModel/MainPageViewModel.cs
source/uwp/Visualizer/XamlCardVisualizer.csproj

This fixes #667 where colors specified in host config get rendered incorrectly in UWP renderer.
As part of this I also added a host config editor to the UWP Visualizer so we can test host config changes.
For the incorrect colors, UWP was parsing as ARBG, which is incorrect, it's supposed to be ARGB
That results in colors like this
```c
std::string alphaString = colorString.substr(1, 2);
INT32 alpha = strtol(alphaString.c_str(), nullptr, 16);
std::string redString = colorString.substr(3, 2);
INT32 red = strtol(redString.c_str(), nullptr, 16);
// GREEN should be parsed here
std::string blueString = colorString.substr(5, 2);
INT32 blue = strtol(blueString.c_str(), nullptr, 16);
std::string greenString = colorString.substr(7, 2);
INT32 green = strtol(greenString.c_str(), nullptr, 16);
``` …

Fix UWP host config color parsing and add host config editor to UWP Visualizer

---

source/shared/cpp/ObjectModel/SharedAdaptiveCard.cpp
source/shared/cpp/ObjectModel/SharedAdaptiveCard.h

This change makes the throws clause conditional depending on whether we are compiling for android or Windows. The throws clause is needed for SWIG to generate the correct exception specification, but it causes build errors in the Windows codebase.

Conditional throw statement (Build error in windows with it, build error in Android without it)

---

samples/v1.0/Elements/Image.Style.json
source/shared/cpp/ObjectModel/Enums.cpp
source/shared/cpp/ObjectModel/Enums.h
source/shared/cpp/ObjectModel/HostConfig.cpp
source/shared/cpp/ObjectModel/HostConfig.h
source/shared/cpp/ObjectModel/Image.cpp
source/shared/cpp/ObjectModel/TextBlock.cpp
source/uwp/Renderer/idl/AdaptiveCards.XamlCardRenderer.idl
source/uwp/Renderer/lib/AdaptiveColorConfig.cpp
source/uwp/Renderer/lib/AdaptiveColorConfig.h
source/uwp/Renderer/lib/AdaptiveFontSizesConfig.cpp
source/uwp/Renderer/lib/AdaptiveFontSizesConfig.h
source/uwp/Renderer/lib/Util.cpp
source/uwp/Renderer/lib/XamlBuilder.cpp

Address issue #630.  Rename normal to default, but support "normal" in cards where we do today to preserve back compat.

Rename normal to default

---

source/dotnet/Library/AdaptiveCards.Html/Rendering/HtmlRenderer.cs
source/dotnet/Library/AdaptiveCards.Xaml.Shared/Rendering/XamlUtilities.cs
source/dotnet/Library/AdaptiveCards/ActionBase.cs
source/dotnet/Library/AdaptiveCards/CardElement.cs
source/dotnet/Library/AdaptiveCards/ChoiceSet.cs
source/dotnet/Library/AdaptiveCards/FactSet.cs
source/dotnet/Samples/WPFVisualizer/MainWindow.xaml.cs

Obsolete attribute added to Speak property on ActionBase, CardElement, ChoiceSet and FactSet.  
HtmlRenderer and WPFVisualizer still support .Speak on these types for backward compatibility (should maybe show/speak something about them being deprecated?).

Deprecate Speak (except on AdaptiveCard) in dotnet

---

source/shared/cpp/ObjectModel/HostConfig.cpp
source/uwp/Visualizer/HostConfigs/DefaultHostConfig.json

Fixes #730. Spacing property wasn't getting parsed in HostConfig.Actions.Spacing, meaning hosts couldn't control the vertical spacing between the body and the actions
Added in the one line of code to parse that, and tested/verified changes with UWP visualizer...
```json
"actions": {
"maxActions": 5,
"spacing": "default",
```
```json
"actions": {
"maxActions": 5,
"spacing": "extraLarge",
```
I also updated some values in the default HostConfig JSON which had incorrect property names, the text colors work now

Fix shared model not parsing ActionsConfig Spacing

---

source/shared/cpp/ObjectModel/HostConfig.cpp
source/uwp/Visualizer/HostConfigs/DefaultHostConfig.json

Fixes #732
One-line fix. Tested and verified with UWP Visualizer. After the changes...
I also updated the UWP Visualizer's default HostConfig JSON payload with a nicer looking separator color

Fix shared model not parsing separator hostConfig

---

source/uwp/Renderer/lib/DefaultResourceDictionary.h
source/uwp/Renderer/lib/XamlBuilder.cpp
source/uwp/Renderer/lib/XamlBuilder.h

Designer feedback was that hit targets should be styled the same as list view items are. Plus the hit targets need to split the vertical spacing between rows evenly, in order to provide padding around items. Definitely looks better now :)
- Created a custom `HitTarget` style for Button in `DefaultResourceDictionary.h` that styles the button similar to a ListViewItem
- Use the `spacing` on the current element to assume the same spacing on the next element and make the touch target expand its height vertically halfway between row items
(In future we should improve that behavior to actually figure out the next item's spacing, but this is good enough for now and it can be considered a bug that when different spacings are used, things get funky)
Used …

UWP polish hit target visuals

---

source/uwp/Renderer/lib/Vector.h

ComPtr::Attach() and Detach() Do not increase or decrease the refcount. Changed MakeWrap to increase the refcount during insertion to the vector,
Verified by testing the creation of object model elements and adding them into containers. Previously this would cause an access violation during destruction that is no longer present.

Fix ref-counting issue in UWP renderer Ivector implementation

---

source/dotnet/Test/AdaptiveCards.Test/AdaptiveCardSerializationTests.cs
source/dotnet/Test/AdaptiveCards.Test/AdaptiveCards.Test.csproj

We didn't have any unit tests that tested the dotnet library's serialization to JSON. Added a simple one that validates it can serialize and then it can deserialize and get back what it originally had.

Add unit test for dotnet card serializing

---

source/dotnet/Library/AdaptiveCards.Rendering.Wpf/AdaptiveTextBlockRenderer.cs

Change made to binding measure block to correctly size the rendered textblock

Fix on issue #878 AdaptiveTextBlock rendering size

---

source/nodejs/adaptivecards/src/card-elements.ts

New choices are appended to existing choices on ReplaceElement. Clear the old ones first.

Fix appending choices to existing ChoiceSetInput on ReplaceElement

---

source/shared/cpp/ObjectModel/ActionParserRegistration.cpp
source/shared/cpp/ObjectModel/AdaptiveCardParseException.cpp
source/shared/cpp/ObjectModel/AdaptiveCardParseException.h
source/shared/cpp/ObjectModel/ElementParserRegistration.cpp
source/shared/cpp/ObjectModel/Enums.h
source/shared/cpp/ObjectModel/ParseUtil.cpp
source/shared/cpp/ObjectModel/ParseUtil.h
source/uwp/Renderer/idl/AdaptiveCards.Uwp.idl
source/uwp/Renderer/lib/AdaptiveCard.cpp
source/uwp/Renderer/lib/AdaptiveCardParseResult.cpp
source/uwp/Renderer/lib/AdaptiveCardParseResult.h
source/uwp/Renderer/lib/AdaptiveCardRendererComponent.cpp
source/uwp/Renderer/lib/AdaptiveRenderContext.cpp
source/uwp/Renderer/lib/XamlBuilder.cpp

Wires up parser errors from the shared model to the UWP renderer. Warnings pending.

Add parser errors to shared model

---

source/nodejs/adaptivecards-visualizer/src/app.ts
source/nodejs/adaptivecards-visualizer/src/containers/bf-image.ts
source/nodejs/adaptivecards-visualizer/src/containers/headless.ts
source/nodejs/adaptivecards-visualizer/src/containers/host-container.ts
source/nodejs/adaptivecards-visualizer/src/containers/outlook.ts
source/nodejs/adaptivecards-visualizer/src/containers/skype.ts
source/nodejs/adaptivecards-visualizer/src/containers/teams.ts
source/nodejs/adaptivecards-visualizer/src/containers/timeline.ts
source/nodejs/adaptivecards-visualizer/src/containers/toast.ts
source/nodejs/adaptivecards-visualizer/src/containers/webchat.ts
source/nodejs/adaptivecards/src/card-elements.ts
source/nodejs/adaptivecards/src/rendercard.ts
source/nodejs/adaptivecards/src/utils.ts

*This is an updated approach to PR #791 -- creating a new PR since the render callback behavior is no longer desired.*
Updates the TypeScript renderer so that multi-line `TextBlock` elements get truncated and show ellipses, instead of overflowing with no indication that there is more content. Uses the `updateLayout()` function to trigger truncation.
This approach includes the following changes:
- Changes the signature of the `AdaptiveCard.render()` function to take an optional `HTMLElement` argument, which the card is then rendered into (as opposed to just returning an `HTMLElement` containing the card -- we need at least some control over when the card is rendered into the DOM so we can execute JS afterwards)
- This matches the way it's done in React with the `ReactDOM.render()` method, …

Show ellipses when truncating TextBlocks due to maxLines

---

source/uwp/Renderer/idl/AdaptiveCards.Rendering.Uwp.idl
source/uwp/Renderer/lib/AdaptiveCardRendererComponent.cpp
source/uwp/Renderer/lib/AdaptiveCardRendererComponent.h
source/uwp/Renderer/lib/AdaptiveChoiceInput.cpp
source/uwp/Renderer/lib/AdaptiveChoiceSetInput.cpp
source/uwp/Renderer/lib/AdaptiveColumn.cpp
source/uwp/Renderer/lib/AdaptiveColumnSet.cpp
source/uwp/Renderer/lib/AdaptiveContainer.cpp
source/uwp/Renderer/lib/AdaptiveDateInput.cpp
source/uwp/Renderer/lib/AdaptiveFact.cpp
source/uwp/Renderer/lib/AdaptiveFactSet.cpp
source/uwp/Renderer/lib/AdaptiveImage.cpp
source/uwp/Renderer/lib/AdaptiveImageRenderer.cpp
source/uwp/Renderer/lib/AdaptiveImageRenderer.h
source/uwp/Renderer/lib/AdaptiveImageSet.cpp
source/uwp/Renderer/lib/AdaptiveNumberInput.cpp
source/uwp/Renderer/lib/AdaptiveSeparator.cpp
source/uwp/Renderer/lib/AdaptiveTextBlock.cpp
source/uwp/Renderer/lib/AdaptiveTextInput.cpp
source/uwp/Renderer/lib/AdaptiveTimeInput.cpp
source/uwp/Renderer/lib/AdaptiveToggleInput.cpp
source/uwp/Renderer/lib/AsyncOperations.h
source/uwp/Renderer/lib/RenderedAdaptiveCard.cpp
source/uwp/Renderer/lib/RenderedAdaptiveCard.h
source/uwp/Renderer/lib/XamlBuilder.cpp
source/uwp/Renderer/lib/XamlBuilder.h

Image renderer needs to share the same XamlBuilder as the AdaptiveCardRenderer, otherwise the XamlBuilder's image tracking capabilities and the settings to allow xaml to load the images do not sync correctly.
Fixes #991

Use shared xamlBuilder in image renderer

---

source/nodejs/adaptivecards-visualizer/src/containers/bf-image.ts
source/nodejs/adaptivecards-visualizer/src/containers/headless.ts
source/nodejs/adaptivecards-visualizer/src/containers/host-container.ts
source/nodejs/adaptivecards-visualizer/src/containers/outlook.ts
source/nodejs/adaptivecards-visualizer/src/containers/skype.ts
source/nodejs/adaptivecards-visualizer/src/containers/teams.ts
source/nodejs/adaptivecards-visualizer/src/containers/timeline.ts
source/nodejs/adaptivecards-visualizer/src/containers/toast.ts
source/nodejs/adaptivecards-visualizer/src/containers/webchat.ts
source/nodejs/adaptivecards/src/card-elements.ts

Looks like a previous commit changed the code in host-config.ts to look for `default` instead of `normal` in text color definitions without changing the hard-coded host config values. This PR updates those values so that text colors work as expected in the visualizer again (especially noticeable for the Windows Notification and Timeline containers).

Change text color definition keys from normal to default

---

source/nodejs/adaptivecards-visualizer/src/containers/timeline.ts
source/nodejs/adaptivecards/src/card-elements.ts
source/nodejs/adaptivecards/src/enums.ts
source/nodejs/adaptivecards/src/utils.ts

Updates the TypeScript renderer to enable automatically truncating content that overflows the bottom of a fixed height card. The truncation logic is triggered in the `updateLayout()` method of the `AdaptiveCard` class, though it could be easily moved to the base container class if we ever want to be able to handle content overflows on any container, not just the bottom of the card. (This isn't really necessary at the moment since there's no notion of fixed height containers yet).
The default behavior for when an element overflows the bottom of the card is to hide the entire element. Two new methods are added to the `CardElement` class (`truncateOverflows()` and `undoOverflowTruncation()`) for elements that want to override this behavior (e.g. for TextBlocks, these methods are overridden …

Truncate bottom overflows for fixed height cards

---

source/nodejs/adaptivecards/src/card-elements.ts

Fixes an issue in the TypeScript renderer where single-line TextBlocks (with `wrap: false`) wouldn't truncate properly if Markdown wasn't used:
The issue occurred because the only place where `text-overflow: ellipsis` got added to TextBlocks was hidden behind a check for `if (element.firstElementChild instanceof HTMLElement)`.

Fix single line text overflow when Markdown isn't used

---

source/shared/cpp/ObjectModel/AdaptiveCardParseException.cpp
source/shared/cpp/ObjectModel/AdaptiveCardParseException.h
source/shared/cpp/ObjectModel/MarkDownBlockParser.cpp
source/shared/cpp/ObjectModel/MarkDownHtmlGenerator.cpp
source/uwp/Renderer/lib/AdaptiveCard.cpp

The GetMessage name conflicts with an OS wide macro.
Added explicit casts to some of the markdown code.
Some auto formatting that removes trailing spaces.

Changes required for OS repo build

---

source/shared/cpp/AdaptiveCardsSharedModel/AdaptiveCardsSharedModelUnitTest/MarkDownUnitTest.cpp
source/shared/cpp/ObjectModel/MarkDownBlockParser.cpp
source/shared/cpp/ObjectModel/MarkDownParser.cpp

Fixed the following issues.
- When empty string is presented, MD doesn't handle it properly 
- it will now return "\<p\>\</p\>"
- When hyphen is present in the middle of string, MD eats up chars when
hyphen is not part of list marker.

fixed Txt Blck empty string and hyphen issue

---

source/nodejs/adaptivecards/src/__tests__/host-config/image_set_config.spec.ts
source/nodejs/adaptivecards/src/host-config.ts

Fixes an issue with TypeScript ImageSetConfig json parsing logic where maxImageHeight property wouldn't parse correctly because of typo. 
```javascript
var imageSizeJson = {
imageSize: 10,
maxImageHeight: 50
}
var imageSetConfig = new ImageSetConfig(imageSizeJson);
// imageSetConfig.maxImageHeight === "maxImageHeight" - it should be 50 instead
```
```javascript
var imageSizeJson = {
imageSize: 10,
maxImageHeight: 50
}
var imageSetConfig = new ImageSetConfig(imageSizeJson);
// imageSetConfig.maxImageHeight === 50
```
#1130

Bug: ImageSetConfig - max image height

---

source/shared/cpp/ObjectModel/HostConfig.cpp

We had a wrong condition check on when to fall back to default value for font-family. As a result we ignore the font family given in the host config.
Corrected the condition check to respect host config or fall back to default.
Using iOS Visualizer, verify that font changes per host config.

Fix to respect font-family in host config

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRImageRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRViewController.mm

We did down-sample the image to exactly fit the width/height of the container frame. However, this is bad for retina display where we can show image beautifully with higher resolution (x2 or x3) in the same visible size.
Stop downsampling and let UIImageView resize as appropriate. This way images are rendered beautifully respecting the resolution of the original image.
Added constraints for width/height so UIImageView is fit to the intended size of the frame.
Using iOS Visualizer, test all templates and see images are clearer, and that width/height are retained.

iOS: Show image with higher resolution

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRFactSetRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRTextBlockRenderer.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRTextBlockRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRViewController.mm

We specified stroke width with such a value as 1, 0, or -2 to change thickness of the text. This works to make font thicker, but does not make it thinner.
Also that way does not really respect the font weight you specify in host config with a granular value like 200, 400, or 600.
Specify font weight for real.
Note that I did not change the existing helper to tell the stroke width except for renaming of function name for clarity.
Using iOS Visualizer, check TextBlock.Weight template (and all other TextBlock ones and more) and see text looks good with appropriate weight.
- lighter weight
- default weight
- bolder weight

iOS: Respect font weight to render text in lighter weight

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRImageRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRSeparator.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRTextBlockRenderer.mm

- column overflows if the width is set to "auto"
this is expected behavior, but this should not cause other UI elements to be compressed.
- updated compression resistance to UIImageView.
- separator gets correct spacing value read from host config
- removed unnecessary system call from TextBlockRenderer.

Fixed column overflows issue

---

source/android/build.gradle

Fixing our android builds on our build servers.

Add the google source to properly download gradle on a build machine

---

source/nodejs/adaptivecards/src/card-elements.ts
source/nodejs/adaptivecards/src/text-formatters.ts

Adds lang property to all Adaptive elements
Only parsed for AdaptiveCard, but technically lang can be overridden on a per-element basis in code
Valid lang format is 2 or 3 alpha characters, case insensitive

[TypeScript] Add lang support

---

source/ios/AdaptiveCards/ADCIOSVisualizer/resources/sample.json
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRContentStackView.mm
source/shared/cpp/ObjectModel/HostConfig.cpp
source/shared/cpp/ObjectModel/HostConfig.h

NYI. We have schema for borderColor/borderThickness, but have not made it on iOS.
Parse from JSON and apply when rendering Container elements.
Using iOS Visualizer, verify:
- The default style (without borderColor/Thickness) has no border
- The emphasis style (with borderColor/Thickness) has border.

iOS: Support borderColor/borderThickness for Container

---

source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer/ViewController.m
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRActionDelegate.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRViewController.mm

This is to notify app of the rendering completion of an adaptive card. Using this, app can show the card only after it gets fully available.
TextBlock rendering is a heavy task in iOS. It gives noticeable delay for users in hundreds milliseconds. We do render TextBlock elements async (which alone is good), but it is slow enough for users to notice they are being rendered. It looks messy so you may want to hide it while rendering is in progress. 
Provided didLoadElements, a new optional method in ACRActionDelegate.
When app implements this, we notify rendering complete by calling this back to app. Then app can handle to show/hide the adaptive card which has just been rendered completely.
The new method applies to not only TextBlock/Image/ImageSet but all other elements (which are rendered …

iOS: Notify rendering completion

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRViewController.mm

We make NSMutableAttributedString call in background thread. It may cause crash because NSMutableAttributedString is not thread-safe.
https://stackoverflow.com/questions/37029891/ios-crash-nsmutableattributedstring
https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/AttributedStrings/Tasks/CreatingAttributedStrings.html
Actually, we see a crash frequently on an iPhone X device.
Moved the NSMutableAttributedString to main thread.
iOS Visualizer works fine, render the test templates.

iOS: Fix crash on TextBlock rendering

---

source/shared/cpp/ObjectModel/Container.cpp

Per discussion with Matt, update the code to make the items collection not required in a container. This fixes #1168.

Make items not required for containers

---

source/shared/cpp/ObjectModel/Enums.cpp

Changes exception throwing for returning the default value when a string cant be mapped to an enum value

Unsupported strings should return default values

---

source/nodejs/adaptivecards/src/enums.ts

This is to ensure maximum compatibility with apps that use an older version of TypeScript

Replace ContainerStyle string enum with class + static fields

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRActionOpenURLRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRActionShowCardRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRActionSubmitRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRButton.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRButton.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRView.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRView.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRViewPrivate.h

Adds support for rendering actions that include an icon above or left of the title. 
Issue: https://github.com/Microsoft/AdaptiveCards/issues/1279
Original thread: https://github.com/Microsoft/AdaptiveCards/issues/389

Icon for Actions support in iOS

---

source/dotnet/Test/AdaptiveCards.Test/AllPayloadTests.cs

The addition of images on actions has added iconUrl to actions. The dotNet render issues a warning for the unknown element. For the time being disable the no warning on the specific payload until the feature is added.

Remove validation of images on actions until it is implemented.

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRViewController.mm

We wrongly called the render method in viewDidLoad. This resulted in double rendering of the same adaptive card, and multiple unnecessary calls to viewLoadElements.
This reproduces with renderAsViewController.
Do not call render in viewDidLoad.
Using a custom app, renderAsViewC renders the adaptive card with no dupulication.
Using the Visualizer app, adaptive cards are rendered as previous.

iOS: Do not call render at viewDidLoad

---

source/android/adaptivecards/src/main/cpp/objectmodel_wrap.cpp
source/android/adaptivecards/src/main/java/io/adaptivecards/objectmodel/AdaptiveCardObjectModelJNI.java
source/android/adaptivecards/src/main/java/io/adaptivecards/objectmodel/DateTimePreparser.java
source/shared/cpp/ObjectModel/DateTimePreparser.cpp
source/shared/cpp/ObjectModel/DateTimePreparser.h
source/uwp/Renderer/lib/DateTimeParser.cpp
source/uwp/Renderer/lib/DateTimeParser.h

Profiling showed that the locale functions were taking a significant amount of time during rendering. Updated the date time parser code to not call locale functions until we actually encounter a date. This change results in a ~20-25% reduction in the overall render time.

Reduce calls to expensive locale functions

---

source/uwp/Renderer/lib/ErrorHandling.h

While doing code analysis I noticed that our RETURN_IF_FAILED macro is wrong.
`RETURN_IF_FAILED(GetValue())` would expand to:
```cpp
if(FAILED(GetValue())
{
return GetValue();
}
```
This could have some side effects when calling the code twice.
Also, after the change, our binary size has decreased by 22K.

Prevent RETURN_IF_FAILED from executing the same statement twice

---

source/shared/cpp/AdaptiveCardsSharedModel/AdaptiveCardsSharedModelUnitTest/MarkDownUnitTest.cpp
source/shared/cpp/ObjectModel/MarkDownBlockParser.cpp
source/shared/cpp/ObjectModel/MarkDownHtmlGenerator.cpp
source/shared/cpp/ObjectModel/MarkDownHtmlGenerator.h
source/shared/cpp/ObjectModel/MarkDownParsedResult.cpp
source/shared/cpp/ObjectModel/MarkDownParsedResult.h
source/shared/cpp/ObjectModel/MarkDownParser.cpp
source/shared/cpp/ObjectModel/MarkDownParser.h
source/uwp/Renderer/lib/HtmlHelpers.cpp
source/uwp/Renderer/lib/HtmlHelpers.h
source/uwp/Renderer/lib/XamlBuilder.cpp

Profiling showed significant time spent in msxml. Updated code to not create the xml document if the text doesn't have markdown in it. Thanks to Joseph for the update to the markdown parser to allow me to detect this. Change results in ~15% improvement in renderer performance.

 Don't create the xml document if there's no html

---

source/uwp/Renderer/lib/AdaptiveTextBlock.cpp
source/uwp/Renderer/lib/Util.cpp

The GetSharedModel failed when retrieving the language when it was empty (I wonder if some other modules may fail because of the same)
Bug: https://github.com/Microsoft/AdaptiveCards/issues/1407

[UWP] Fix break when language is not specified

---

source/uwp/Renderer/idl/AdaptiveCards.Rendering.Uwp.idl
source/uwp/Renderer/lib/AdaptiveCard.cpp
source/uwp/Renderer/lib/AdaptiveCard.h
source/uwp/Renderer/lib/CustomActionWrapper.cpp
source/uwp/Renderer/lib/CustomActionWrapper.h
source/uwp/Renderer/lib/CustomElementWrapper.cpp
source/uwp/Renderer/lib/CustomElementWrapper.h
source/uwp/Renderer/lib/Util.cpp
source/uwp/Renderer/lib/Util.h
source/uwp/Renderer/lib/Vector.h

Implemented AdaptiveCard.GetResourceUris. This included replacing our implementation of vector in Vector.h with the version from Win2D in order to support vectors of runtime classes.
Vector code taken from:
https://github.com/Microsoft/Win2D/blob/master/winrt/inc/Vector.h
Implements #1322

Implement GetResourceUris at the UWP layer

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRView.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/CMakeLists.txt

fixes issues for #1419 where when UIImage size is zero, app crashes.

fix for #1419

---

source/uwp/AdaptiveCardTestApp/ViewModels/TestResultViewModel.cs

Missing null check in the comparison of roundtripped json hashed led to issues where test results were not displayed correctly.

Add missing null check to UWP test app

---

source/shared/cpp/AdaptiveCardsSharedModel/AdaptiveCardsSharedModel/AdaptiveCardsSharedModel.vcxproj
source/shared/cpp/ObjectModel/Image.cpp

Bump warning level to `W4` and make warnings errors. Fix issue found by `W4`. Note that we disable `C4702` because of issues in jsoncpp.

W4 warnings for shared cpp

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/AdaptiveCardRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/action/ActionElementRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/inputhandler/ComboBoxInputHandler.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/FactSetRenderer.java

1. Fix spacing between two buttons . It should follow the hostConfig property for spacing between two buttons [#1432](https://github.com/Microsoft/AdaptiveCards/issues/1432)
2. Fix the spacing between the buttons layout and the last card element . This should also follow the host config  property [#1432](https://github.com/Microsoft/AdaptiveCards/issues/1432)
3. Add horizontal scroll view to make buttons scrollable  in case they exceed the width available [#1426](https://github.com/Microsoft/AdaptiveCards/issues/1426). 
4. Fix a bug in multiple choice input where title is returned instead of returning the value when Action.Submit button is pressed [#1449](https://github.com/Microsoft/AdaptiveCards/issues/1449).
5. Fix fact set rendering issue where the content is clipped …

Fix Button spacing issues and add horizontal scroll view in case actions orientation is horizontal . 

---

source/shared/cpp/AdaptiveCardsSharedModel/AdaptiveCardsSharedModel/AdaptiveCardsSharedModel.vcxproj
source/shared/cpp/ObjectModel/DateTimePreparser.cpp
source/shared/cpp/ObjectModel/MarkDownHtmlGenerator.cpp
source/shared/cpp/ObjectModel/MarkDownHtmlGenerator.h
source/shared/cpp/ObjectModel/MarkDownParsedResult.cpp
source/shared/cpp/ObjectModel/MarkDownParsedResult.h
source/shared/cpp/ObjectModel/jsoncpp.cpp
source/shared/cpp/ObjectModel/pch.h

In this change, we enable automatic checking of a subset of cppcore guidelines checks. As we make further progress, we can turn on further checks by adding them to the list in `pch.h`.

Turn on automatic cppcore guidelines checking

---

source/shared/cpp/ObjectModel/SharedAdaptiveCard.cpp
source/uwp/Renderer/idl/AdaptiveCards.Rendering.Uwp.idl
source/uwp/Renderer/lib/AdaptiveCardRendererComponent.h
source/uwp/Renderer/lib/CustomActionWrapper.cpp
source/uwp/Renderer/lib/CustomElementWrapper.cpp
source/uwp/Renderer/lib/Util.cpp
source/uwp/Renderer/lib/Util.h
source/uwp/Renderer/lib/WholeItemsPanel.cpp
source/uwp/Renderer/lib/XamlBuilder.cpp

This doesn't affect the OSS version, but keeps the code synchronized.

Put back RenderCardAsXamlAsync for Windows internal builds.

---

source/shared/cpp/ObjectModel/DateTimePreparser.cpp

This is the fix to this https://github.com/Microsoft/AdaptiveCards/issues/1371
It looks like the method wcsftime didn't work in SDK 19 always returning a "%" which in turn messed the string to integer conversion and made the program crash, I changed the function to strftime which is the same function, with the only difference that the former uses single byte chars

[Android] Fix to time preparsing returning invalid value

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/FactSetRenderer.java

The issue before the fix was that the text in some factsets would not wrap correctly, so the text would be clipped https://github.com/Microsoft/AdaptiveCards/issues/1472
The issue after the fix is that cards like StockUpdate dont render the text at all for the fact values http://adaptivecards.io/samples/StockUpdate.html
So we'll remove the fix until we find a reliable fix for this

[Android] Remove untrustable fix for fact set wrapping issue

---

source/shared/cpp/ObjectModel/SharedAdaptiveCard.cpp
source/uwp/Renderer/idl/AdaptiveCards.Rendering.Uwp.idl
source/uwp/Renderer/lib/AdaptiveCardRendererComponent.h
source/uwp/Renderer/lib/CustomActionWrapper.cpp
source/uwp/Renderer/lib/CustomElementWrapper.cpp
source/uwp/Renderer/lib/Util.cpp
source/uwp/Renderer/lib/Util.h
source/uwp/Renderer/lib/WholeItemsPanel.cpp
source/uwp/Renderer/lib/XamlBuilder.cpp

- Adds back the RenderCardAsXamlAsync only for Windows internal consumption
- Fixes a few namespace issues when building for Windows internal consumption.

Add RenderCardAsXamlAsync back to our IDL for Windows internal

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRContentStackView.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRIContentHoldingView.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRShowCardTarget.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRShowCardTarget.mm

corrected to desired behavior:
show only one show card at a time when show card button is touched.

show only one showcard at a time

---

source/shared/cpp/ObjectModel/pch.h

Simple fix for #1550 -- Only include cppcorecheck headers when compiling with MS toolchain.

Add MSC directive to prevent cppcorecheck build failures on non-VS builds

---

source/shared/cpp/ObjectModel/BaseInputElement.cpp
source/shared/cpp/ObjectModel/ChoiceSetInput.cpp
source/shared/cpp/ObjectModel/DateTimePreparsedToken.cpp
source/shared/cpp/ObjectModel/DateTimePreparser.cpp
source/shared/cpp/ObjectModel/SharedAdaptiveCard.cpp
source/shared/cpp/ObjectModel/pch.h

This PR turns on member variable initialization checking (part of cppcorecheck). Also, fixes up instances of missing initialization. Please double-check the defaults here to make sure they make sense. :)

Enable member init checks and fix errors

---

source/shared/cpp/ObjectModel/ParseUtil.cpp
source/shared/cpp/ObjectModel/ParseUtil.h

A class consisting of public static methods, private ctor/dtor, and no state should just be a namespace.

Make `ParseUtil` a namespace

---

source/dotnet/Build/SignNugetConfig.xml
source/dotnet/Library/AdaptiveCards.Rendering.Wpf/AdaptiveCardRenderer.cs
source/dotnet/Library/AdaptiveCards.Rendering.Wpf/AdaptiveRenderContext.cs

This helps catch exceptions in async calls that might tear down the process.

[.NET] Prevent async exceptions from tearing down the process

---

source/shared/cpp/ObjectModel/BaseActionElement.cpp
source/shared/cpp/ObjectModel/BaseActionElement.h
source/shared/cpp/ObjectModel/BaseCardElement.cpp
source/shared/cpp/ObjectModel/BaseCardElement.h
source/shared/cpp/ObjectModel/ChoiceSetInput.cpp
source/shared/cpp/ObjectModel/Column.cpp
source/shared/cpp/ObjectModel/ColumnSet.cpp
source/shared/cpp/ObjectModel/Container.cpp
source/shared/cpp/ObjectModel/DateInput.cpp
source/shared/cpp/ObjectModel/Enums.cpp
source/shared/cpp/ObjectModel/FactSet.cpp
source/shared/cpp/ObjectModel/Image.cpp
source/shared/cpp/ObjectModel/ImageSet.cpp
source/shared/cpp/ObjectModel/MarkDownHtmlGenerator.cpp
source/shared/cpp/ObjectModel/MarkDownParsedResult.cpp
source/shared/cpp/ObjectModel/Media.cpp
source/shared/cpp/ObjectModel/NumberInput.cpp
source/shared/cpp/ObjectModel/OpenUrlAction.cpp
source/shared/cpp/ObjectModel/ParseUtil.cpp
source/shared/cpp/ObjectModel/ShowCardAction.cpp
source/shared/cpp/ObjectModel/SubmitAction.cpp
source/shared/cpp/ObjectModel/TextBlock.cpp
source/shared/cpp/ObjectModel/TextInput.cpp
source/shared/cpp/ObjectModel/TimeInput.cpp
source/shared/cpp/ObjectModel/ToggleInput.cpp
source/shared/cpp/ObjectModel/pch.h

There are effectively two class of error that we have in our codebase that was caught by `CPPCORECHECK_DECLARATION_WARNINGS`:
* [I.22: Avoid complex initialization of global objects](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#i22-avoid-complex-initialization-of-global-objects)
This check is a good one -- it ensures that global variable initialization is only done with `constexpr`s - meaning that there's no concern about the order in which global variables init. Unfortunately, the checker has a bug where it sees function-static variables as global, so basically all of `Enums.cpp` shows up as hits. I reviewed static variable use in this file and then disabled the check in that file's scope.
* [ES.84: Don't (try to) declare a local variable with no …

Enable CPPCORECHECK_DECLARATION_WARNINGS and fix errors

---

source/shared/cpp/ObjectModel/AdaptiveCardParseException.cpp
source/shared/cpp/ObjectModel/AdaptiveCardParseException.h
source/shared/cpp/ObjectModel/AdaptiveCardParseWarning.cpp
source/shared/cpp/ObjectModel/AdaptiveCardParseWarning.h
source/shared/cpp/ObjectModel/BaseActionElement.cpp
source/shared/cpp/ObjectModel/BaseActionElement.h
source/shared/cpp/ObjectModel/BaseCardElement.cpp
source/shared/cpp/ObjectModel/BaseCardElement.h
source/shared/cpp/ObjectModel/json/json.h
source/shared/cpp/ObjectModel/jsoncpp.cpp
source/shared/cpp/ObjectModel/pch.h

Per core [guidelines](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#example-good-5), if explicitly declaring a dtor to make it `virtual`, just declare the rest as `default`. Also, don't declare a default dtor if you're not going to have anything in it. :)

Enable "rule of five" checker, fix errors

---

source/shared/cpp/ObjectModel/AdaptiveCardParseException.h
source/shared/cpp/ObjectModel/BaseActionElement.h
source/shared/cpp/ObjectModel/BaseCardElement.h
source/shared/cpp/ObjectModel/BaseInputElement.h
source/shared/cpp/ObjectModel/ChoiceSetInput.h
source/shared/cpp/ObjectModel/Column.h
source/shared/cpp/ObjectModel/ColumnSet.h
source/shared/cpp/ObjectModel/Container.h
source/shared/cpp/ObjectModel/DateInput.h
source/shared/cpp/ObjectModel/FactSet.h
source/shared/cpp/ObjectModel/Image.h
source/shared/cpp/ObjectModel/ImageSet.h
source/shared/cpp/ObjectModel/MarkDownBlockParser.h
source/shared/cpp/ObjectModel/MarkDownHtmlGenerator.h
source/shared/cpp/ObjectModel/Media.h
source/shared/cpp/ObjectModel/MediaSource.h
source/shared/cpp/ObjectModel/NumberInput.h
source/shared/cpp/ObjectModel/OpenUrlAction.h
source/shared/cpp/ObjectModel/ShowCardAction.h
source/shared/cpp/ObjectModel/SubmitAction.h
source/shared/cpp/ObjectModel/TextBlock.h
source/shared/cpp/ObjectModel/TextInput.h
source/shared/cpp/ObjectModel/TimeInput.h
source/shared/cpp/ObjectModel/ToggleInput.h
source/shared/cpp/ObjectModel/UnknownElement.h
source/shared/cpp/ObjectModel/pch.h

There are quite a few checks that are enabled with `CPPCORECHECK_CLASS_WARNINGS`. Most of these warnings are around class hierarchy and virtual functions:
- Don't hide functions
- If a derived class has a function that hides a non-`virtual` function from its base class, it implies that either the function should be `virtual`, or it should perhaps have a different name. In our case, it seems that we just needed to mark the base functions as `virtual`.
- Always use `override` when applicable
- Improves class structure comprehension when read
- Use only one of `virtual`, `override`, or `final`
- `override` implies `virtual`, and `final` implies `override` -- prefer using only the most relevant keyword to improve legibility.
- note that the guidelines …

Enable all cppcorecheck class warnings and fix errors

---

source/shared/cpp/AdaptiveCardsSharedModel/AdaptiveCardsSharedModelUnitTest/AdaptiveCardsSharedModelUnitTest.vcxproj
source/shared/cpp/AdaptiveCardsSharedModel/AdaptiveCardsSharedModelUnitTest/stdafx.cpp
source/shared/cpp/AdaptiveCardsSharedModel/AdaptiveCardsSharedModelUnitTest/stdafx.h

Just a couple tweaks to the VS unit test config to allow generating code coverage numbers from our tests.

Enable unit test code coverage in Debug Win32 builds

---

source/uwp/Renderer/lib/XamlBuilder.cpp

My previous change accidentally disabled media controls. Changed the layering of the Xaml elements so that disabling the play button click on the poster doesn't disable the controls on the media element.

Fix media controls

---

source/nodejs/adaptivecards/src/__tests__/components/text_block.spec.ts

Just a test (passes currently) to ensure that we transfer text as-is to HTML, including Unicode.
Addressing the question posed at https://github.com/Microsoft/AdaptiveCards/issues/1645

[TS] added a test to ensure Unicode/Emoji support

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/ActionLayoutRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/AdaptiveCardRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/IActionLayoutRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/registration/CardRendererRegistration.java

Fix for https://github.com/Microsoft/AdaptiveCards/issues/1541
And for this https://github.com/Microsoft/AdaptiveCards/issues/1424

[Android] Add custom renderer for actions and actionlayouts

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards.xcodeproj/project.pbxproj

While Submitting the Teams App to app store we were getting the following error 
**ERROR ITMS-90668: "Invalid Bundle Executable. The executable file 'TeamSpaceApp.app/Frameworks/AdaptiveCards.framework/AdaptiveCards' contains incomplete bitcode. To compile binaries with complete bitcode, open Xcode and choose Archive in the Product menu."**
Enable BitCode is set to yes in Adaptive Cards , but it is putting marker bit code not the actual one. 
To fix the issue we added one more property in User Defined Setting BITCODE_GENERATION_MODE = bitcode;

BitCode Added in Project configuration

---

source/dotnet/Library/AdaptiveCards.Rendering.Wpf.Xceed/XceedNumberInput.cs

XceedNumberInput.Render was setting numberPicker.Minimum to input.Max.  This fixes it to set numberPicker.Maximum instead.

Fix bug in XceedNumberInput.Render

---

source/shared/cpp/ObjectModel/SharedAdaptiveCard.cpp

Increase the information in the error message when version fails to parse, and mark version as required in order to get a more specific error message. Doing this to help track down the root cause of reports that cards are failing to parse due to an invalid version.

Increase the information in the version error message 

---

source/uwp/Renderer/idl/AdaptiveCards.Rendering.Uwp.idl
source/uwp/Renderer/lib/AdaptiveMediaEventInvoker.cpp
source/uwp/Renderer/lib/AdaptiveMediaEventInvoker.h
source/uwp/Renderer/lib/MediaHelpers.cpp
source/uwp/Renderer/lib/RenderedAdaptiveCard.cpp
source/uwp/Renderer/lib/RenderedAdaptiveCard.h
source/uwp/Renderer/lib/XamlBuilder.cpp
source/uwp/Visualizer/ViewModel/DocumentViewModel.cs

Remove the MediaEnded event, rename MediaPlay to MediaClicked, and don't send MediaClicked for the inline playback case.

Media event changes

---

source/shared/cpp/AdaptiveCardsSharedModel/AdaptiveCardsSharedModelUnitTest/AdaptiveCardsSharedModelUnitTest.vcxproj
source/shared/cpp/AdaptiveCardsSharedModel/AdaptiveCardsSharedModelUnitTest/AdaptiveCardsSharedModelUnitTest.vcxproj.filters
source/shared/cpp/AdaptiveCardsSharedModel/AdaptiveCardsSharedModelUnitTest/ParseUtilTest.cpp
source/shared/cpp/ObjectModel/ParseUtil.cpp

Add in some `ParseUtil` unit tests. Remove unneeded handling of `std::out_of_range` exception in a couple of spots.

Add ParseUtil tests

---

source/xamarin/AdaptiveCards.Rendering.Xamarin.Android.Sample/AdaptiveCards.Rendering.Xamarin.Android.Sample.csproj
source/xamarin/AdaptiveCards.Rendering.Xamarin.Android.Sample/packages.config
source/xamarin/AdaptiveCards.Rendering.Xamarin.Android/AdaptiveCards.Rendering.Xamarin.Android.csproj
source/xamarin/AdaptiveCards.Rendering.Xamarin.Android/packages.config

It seems that the current version of the Xamarin build downloader package that we are using is having download issues. This updates the package to the latest one which seems to resolve those issues and has our CI builds for Android succeed again.

Update the Xamarin download package to the latest one to fix build failures

---

source/shared/cpp/AdaptiveCardsSharedModel/AdaptiveCardsSharedModel/AdaptiveCardsSharedModel.vcxproj
source/shared/cpp/AdaptiveCardsSharedModel/AdaptiveCardsSharedModelUnitTest/ExplicitDimensionTest.cpp
source/shared/cpp/ObjectModel/DateTimePreparser.cpp
source/shared/cpp/ObjectModel/DateTimePreparser.h
source/shared/cpp/ObjectModel/Enums.h
source/shared/cpp/ObjectModel/HostConfig.h
source/shared/cpp/ObjectModel/Image.cpp
source/shared/cpp/ObjectModel/MarkDownBlockParser.cpp
source/shared/cpp/ObjectModel/MarkDownHtmlGenerator.cpp
source/shared/cpp/ObjectModel/MarkDownParser.cpp
source/shared/cpp/ObjectModel/Media.h
source/shared/cpp/ObjectModel/MediaSource.cpp
source/shared/cpp/ObjectModel/SharedAdaptiveCard.cpp
source/shared/cpp/ObjectModel/Util.cpp
source/shared/cpp/ObjectModel/pch.h

Enable the following checks:
* [CPPCORECHECK_BOUNDS_WARNINGS](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#probounds-bounds-safety-profile)
- The check that we had the most errors in deals with unchecked bounds access via `operator[]`. When indexing into a container type via `[]`, no bounds checking occurs, making it easy to walk off the end of, say, a `std::vector<>`. Access via `at()` **is** bounds checked and will throw if an attempt is made to retrieve an element at an invalid index. The fix is to switch to using `at()` when possible.
* [CPPCORECHECK_OWNER_POINTER_WARNINGS, CPPCORECHECK_RAW_POINTER_WARNINGS, and CPPCORECHECK_SHARED_POINTER_WARNINGS](http://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#r-resource-management)
- …

More cppcore changes

---

source/dotnet/Library/AdaptiveCards.Rendering.Html/AdaptiveCardRenderer.cs
source/dotnet/Library/AdaptiveCards.Rendering.Wpf/AdaptiveColumnSetRenderer.cs

Not sure if double unit makes sense for pixel (e.g., `50.3px`) and also for weighted proportion (already in use)
For testing, you can use the payload below. I noticed the payload provided in the [epic](https://github.com/Microsoft/AdaptiveCards/issues/1026) does not have `"type": "Column"` anywhere and the .NET renderer throws an error for it. Is that something missing from the .NET renderer? 
```
{
"body": [
{
"columns": [
{
"width": "50px",
"items": [
{
"url": "http://3.bp.blogspot.com/-Xo0EuTNYNQg/UEI1zqGDUTI/AAAAAAAAAYE/PLYx5H4J4-k/s1600/smiley+face+super+happy.jpg",
"size": "stretch"
}
]
},
{
"width": …
```

added handler for column width in pixels

---

source/android/adaptivecards/src/AdaptiveCardObjectModel.i

Add the GetResources API to android
Solves this: https://github.com/Microsoft/AdaptiveCards/issues/1658

[Android] GetResourceUris API

---

source/uwp/Renderer/lib/Util.cpp

**NOTE**: This change affects all color hex values, including ones in host config and image's background color in payload
Added a check to use color only when its format is `#AARRGGBB`. Otherwise, simply ignore it

added fallback for invalid color

---

source/dotnet/Library/AdaptiveCards/AdaptiveCard.cs
source/dotnet/Library/AdaptiveCards/AdaptiveSubmitAction.cs
source/dotnet/Library/AdaptiveCards/AdaptiveTextBlock.cs
source/dotnet/Library/AdaptiveCards/Rendering/AdaptiveHostConfig.cs
source/dotnet/Library/AdaptiveCards/StrictIntConverter.cs
source/dotnet/Test/AdaptiveCards.Test/AllPayloadTests.cs
source/dotnet/Test/AdaptiveCards.Test/XmlSerializationTests.cs

The `.NET` parser has the same bug as reported in the original issue. This is the default behavior of NewtonSoft. So we just need a custom Integer converter with stricter rule that disallows String to be accepted for all Int attributes

Disallow Strings to Ints

---

source/dotnet/Library/AdaptiveCards.Rendering.Html/AdaptiveCardRenderer.cs
source/dotnet/Test/AdaptiveCards.Rendering.Html.Test/HtmlRendererTests.cs

This style attribute is redundant and causes a `TextBlock` to consume all available space in a `Column`

removed TextBlock's 100% height

---

source/shared/cpp/AdaptiveCardsSharedModel/AdaptiveCardsSharedModelUnitTest/AdaptiveCardParseExceptionTest.cpp
source/shared/cpp/AdaptiveCardsSharedModel/AdaptiveCardsSharedModelUnitTest/AdaptiveCardsSharedModelUnitTest.vcxproj
source/shared/cpp/AdaptiveCardsSharedModel/AdaptiveCardsSharedModelUnitTest/AdaptiveCardsSharedModelUnitTest.vcxproj.filters
source/shared/cpp/AdaptiveCardsSharedModel/AdaptiveCardsSharedModelUnitTest/ParserRegistrationTest.cpp
source/shared/cpp/ObjectModel/ActionParserRegistration.cpp

Bolster code coverage for `ActionParserRegistration`, `ElementParserRegistration`, `AdaptiveCardParseWarning`, and `AdaptiveCardParseException`. Fix logic flaw in `ActionParserRegistration::RemoveParser()` where a caller can remove known parsers, but can't remove custom parsers. Also throw when attempting to remove a known action parser, to be consistent with `ElementParserRegistration`.

Introduce parser registration, parser warning, and parser error tests

---

source/uwp/Renderer/lib/XamlBuilder.cpp

Change #1525 changed the vertical alignment of images to VerticalAlignment_Top. This caused the background image not to stretch to the size of the card. This fix explicitly sets the background image to VerticalAlignment_Stretch.

[UWP] Set background image alignment to stretch

---

source/shared/cpp/AdaptiveCardsSharedModel/AdaptiveCardsSharedModelUnitTest/ImageBackgroundColorTest.cpp
source/shared/cpp/ObjectModel/Util.cpp

A few issues got missed in PR that needed fixing:
* An `Image` with no `backgroundColor` set would trigger a parse warning because `""` doesn't fit the expected format
* Minor typo in warning string
* Missing a `const`
* Needed to use `at(index)` instead of `[index]`
I also added a unit test for the `backgroundColor`-not-specified case.

Fix a couple issues with background color that slipped past PR

---

source/dotnet/Library/AdaptiveCards.Rendering.Wpf/AdaptiveImageSetRenderer.cs

Fixed the .NET WPF renderer to use imageSet's imageSize like other renderers

use imageSize in imageSet to override all individual image sizes

---

samples/Tests/IconsInSomeActions.json
samples/Tests/NotificationCard.json

affected cards are based on activity reminder card.
however, those cards do not have data fields unlike the activity reminder card, so it's confusing especially during debugging.
added data for consistency.

added data fields for action.submit

---

custom.props
source/dotnet/Library/AdaptiveCards.Rendering.Html/AdaptiveCards.Rendering.Html.csproj
source/dotnet/Library/AdaptiveCards.Rendering.Wpf.Xceed/AdaptiveCards.Rendering.Wpf.Xceed.csproj
source/dotnet/Library/AdaptiveCards.Rendering.Wpf/AdaptiveCards.Rendering.Wpf.csproj
source/dotnet/Library/AdaptiveCards/AdaptiveCards.csproj
source/dotnet/RunAllTests.ps1
source/dotnet/Samples/AdaptiveCards.Sample.Html/AdaptiveCards.Sample.Html.csproj
source/dotnet/Samples/AdaptiveCards.Sample.ImageRender/AdaptiveCards.Sample.ImageRender.csproj
source/dotnet/Samples/ImageRendererServer/ImageRendererServer.csproj
source/dotnet/Test/AdaptiveCards.Rendering.Html.Test/AdaptiveCards.Rendering.Html.Test.csproj
source/dotnet/Test/AdaptiveCards.Test/AdaptiveCards.Test.csproj

Enable auto-versioning of our DLLs and packages. This leverages our internal build infrastructure to automatically stamp the packages and dlls with the build version taken from the `custom.props` files as well as the build number that produced the binaries.

Add support for auto-versioning

---

source/uwp/Renderer/lib/XamlBuilder.cpp

Fixed the bug when an `Input.ChoiceSet` has multiple specified values, it should not pre-select any option, whereas right now the option with the biggest value is selected.
**Expanded:**
- Payload:
```
{
"body": [
{
"value": "1,3",
"isMultiSelect": false,
"style": "expanded",
"choices": [
{
"title": "value 1",
"value": "1"
},
{
"title": "value 2",
"value": "2"
},
{
"title": "value 3",
"value": "3"
}
],
"id": "4"
}
]
}
```
- Before:
- After:
**Collapsed:**
```
{
"body": [
{
"value": "1,3",
"choices": [
{
"title": "value 1",
"value": "1"
},
{
"title": "value 2",
"value": "2"
},
{
"title": "value 3",
"value": "3"
}
],
"id": "4"
}
]
}
```
- Before
- After

ignore multiple specified values in cases when only 1 is accepted

---

source/dotnet/Library/AdaptiveCards.Rendering.Html/AdaptiveCardRenderer.cs
source/dotnet/Library/AdaptiveCards.Rendering.Wpf/AdaptiveImageRenderer.cs
source/dotnet/Library/AdaptiveCards/AdaptiveImage.cs
source/dotnet/Library/AdaptiveCards/HashColorConverter.cs
source/dotnet/Library/AdaptiveCards/StrictIntConverter.cs
source/dotnet/Library/AdaptiveCards/WarningLoggingContractResolver.cs
source/dotnet/Test/AdaptiveCards.Test/AllPayloadTests.cs
source/dotnet/Test/AdaptiveCards.Test/SerializationTests.cs

This adds supports for BackgroundColor on images in the .NET renderer.
As per spec, only #AARRGGBB and #RRGGBB colors are accepted and this is enforced at the object model level.
I had to connect up the warnings to a new converter, since the color is coming is a string, it has to be specifically specified for the field and cannot be a generic type converter.

Add support for BackgroundColor on images in .NET

---

source/dotnet/Test/AdaptiveCards.Test/AllPayloadTests.cs

Tests cards that were not parsed properly because features were missing but are working now.
I'm also expanding some of our test coverage for .NET to make sure that we understand which failures are expected and force the inclusion of the tests once features are implemented.

Remove the tests that were excluded for unsupported features in .NET.

---

source/android/build.gradle

We were missing a reference to the Google project repos, so we were at the mercy of our build system having already populated the libraries we need.

Fix up android CI build

---

source/dotnet/Library/AdaptiveCards.Rendering.Wpf/AdaptiveXamlMarkdownRenderer.cs

The dotnet WPF renderer was rendering ordered lists as unordered lists. This fixes that. :)

Ordered list support for WPF renderer

---

THIRD-PARTY-NOTICES.TXT

Add a 3rd party notices file that we can use to setup the appropriate attributions.

Add 3rd party notices file for FullScreenVideoLayout in Android Renderer

---

source/android/adaptivecards/src/main/cpp/objectmodel_wrap.cpp
source/android/adaptivecards/src/main/java/io/adaptivecards/objectmodel/AdaptiveCardObjectModelJNI.java
source/android/adaptivecards/src/main/java/io/adaptivecards/objectmodel/MarkDownParser.java
source/android/adaptivecards/src/main/java/io/adaptivecards/objectmodel/RemoteResourceInformation.java
source/dotnet/Library/AdaptiveCards/AdaptiveCard.cs
source/dotnet/Library/AdaptiveCards/RemoteResourceInformation.cs
source/dotnet/Test/AdaptiveCards.Test/AdaptiveCardApiTests.cs
source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizerTests/ADCIOSVisualizerTests.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACORemoteResourceInformation.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACORemoteResourceInformation.mm
source/shared/cpp/AdaptiveCardsSharedModel/AdaptiveCardsSharedModelUnitTest/ResourceInformationTests.cpp
source/shared/cpp/ObjectModel/BaseActionElement.cpp
source/shared/cpp/ObjectModel/Image.cpp
source/shared/cpp/ObjectModel/Media.cpp
source/shared/cpp/ObjectModel/MediaSource.cpp
source/shared/cpp/ObjectModel/RemoteResourceInformation.h
source/shared/cpp/ObjectModel/SharedAdaptiveCard.cpp
source/uwp/Renderer/idl/AdaptiveCards.Rendering.Uwp.idl
source/uwp/Renderer/lib/AdaptiveCard.cpp
source/uwp/Renderer/lib/AdaptiveRemoteResourceInformation.cpp
source/uwp/Renderer/lib/AdaptiveRemoteResourceInformation.h
source/uwp/Renderer/lib/Util.cpp

ResourceType was intended to indicate the type of a resource for which we didn't have an author provided mimeType. This has proved to be confusing, so updated the code to just set the mimeType to "image" for image types.

Remove Resource Type from the RemoteResourceInformation structure

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/layout/FullscreenVideoLayout.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/layout/FullscreenVideoView.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/MediaRenderer.java
source/android/mobilechatapp/src/main/java/com/example/mobilechatapp/MainActivity.java

Fixes this issue: https://github.com/Microsoft/AdaptiveCards/issues/1897

[Android] Move time Handler initialization away from card rendering

---

source/android/adaptivecards/src/main/cpp/objectmodel_wrap.cpp
source/android/adaptivecards/src/main/java/io/adaptivecards/objectmodel/AdaptiveCard.java
source/android/adaptivecards/src/main/java/io/adaptivecards/objectmodel/AdaptiveCardObjectModelJNI.java
source/android/adaptivecards/src/main/java/io/adaptivecards/objectmodel/MarkDownParser.java
source/dotnet/Library/AdaptiveCards/AdaptiveCardConverter.cs
source/shared/cpp/AdaptiveCardsSharedModel/AdaptiveCardsSharedModelUnitTest/EverythingBagel.cpp
source/shared/cpp/ObjectModel/SharedAdaptiveCard.cpp
source/shared/cpp/ObjectModel/SharedAdaptiveCard.h

Added speak to fallback card in .NET and Shared Model. Logic shown in table below:
Text pre-defined? | Speak pre-defined? | Result
------------------- | --------------------- | ------
N | N | Text = Speak = default
N | Y | Text = default, Speak = **SPEAK**'s defined val
Y | N | Text = Speak = **TEXT**'s defined val
Y | Y | Each to their own pre-defined val
Also made fallback card have language.
* **SharedModel**: if lang not defined, pass on as empty/not-defined and have renderer deal with it
* **.NET**: at parse time, if lang not defined, set to `CultureInfo.CurrentCulture.TwoLetterISOLanguageName`
This one seems a little odd, so let me know what your thoughts are.

Speak and Language for Fallback Card

---

source/uwp/Renderer/lib/XamlBuilder.cpp

Even though we don't render the title on SelectActions, we should be setting the AutomationProperties so that we can have accessibility software (screen-readers) be able to get information about the action.
This enables narrator to be able to read the information from the SelectAction button

Setting the UIAutomationProperties.Name for SelectAction from the title.

---

source/uwp/Renderer/lib/XamlBuilder.cpp

Even though we don't render the title on SelectActions, we should be setting the AutomationProperties so that we can have accessibility software (screen-readers) be able to get information about the action.
Moving this to our 1.1 branch for the Windows build

Setting the UIAutomationProperties.Name for SelectAction from the title

---

source/shared/cpp/ObjectModel/SharedAdaptiveCard.cpp
source/shared/cpp/ObjectModel/SharedAdaptiveCard.h
source/shared/cpp/ObjectModel/ShowCardAction.cpp
source/uwp/Renderer/AdaptiveCardRenderer.vcxproj
source/uwp/Renderer/AdaptiveCardRenderer.vcxproj.filters
source/uwp/Renderer/idl/AdaptiveCards.Rendering.Uwp.idl
source/uwp/Renderer/lib/AdaptiveCard.cpp
source/uwp/Renderer/lib/AdaptiveCard.h
source/uwp/Renderer/lib/AdaptiveTemplater.cpp
source/uwp/Renderer/lib/AdaptiveTemplater.h
source/uwp/UWPTestLibrary/RenderTestHelpers.cs
source/uwp/Visualizer/DocumentView.xaml
source/uwp/Visualizer/ViewModel/DocumentViewModel.cs

Separate templating from parsing at the API layer, and add an additional panel to the visualizer to show the result of applying templating.

[UWP v2.0 prototype] Separate json templating from parsing and add templating panel to visualizer

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRView.mm

This PR is a fix for issue : https://github.com/Microsoft/AdaptiveCards/issues/2138
Root Cause :- If a custom image renderer is implemented , than the code for background image setting was disabled.
Fix :- Removed the check for CustomImageRenderer implementation.

custom image renderer check removed

---

source/android/adaptivecards/build.gradle
source/android/build.gradle
source/android/gradle/wrapper/gradle-wrapper.properties
source/android/mobile/build.gradle
source/android/mobile/src/main/java/io/adaptivecards/adaptivecardssample/MainActivityAdaptiveCardsSample.java
source/android/mobilechatapp/build.gradle

Updates to the NDK cause build breaks in older versions of gradle. The only way to get us building is for users to downgrade the NDK version, which isn't optimal. This change upgrades us to a newer version of gradle which doesn't have problems with the newer NDK version.

Upgrade to new gradle version to fix NDK break

---

source/nodejs/adaptivecards-visualizer/src/containers/host-container.ts
source/nodejs/adaptivecards-visualizer/src/containers/outlook.ts
source/nodejs/adaptivecards/src/card-elements.ts
source/nodejs/adaptivecards/src/host-config.ts

This change allows the use of `<mark></mark>` in **TextBlock**.
This feature is disabled by default and needs to be explicitly turned by the host that needs it by setting `AdaptiveCard.allow.allowMarkForTextHighlighting = true`.
This feature is necessary to unblock an Outlook scenario. It will become unnecessary and will be deprecated when inline text runs are supported (https://github.com/Microsoft/AdaptiveCards/issues/1933)
This change also fixes a bug where the right foreground color would not always be applied.

[HTML] Add support for <mark> to highlight text in TextBlock

---

source/dotnet/Library/AdaptiveCards.Rendering.Wpf/AdaptiveTextBlockRenderer.cs

It looks like we were changing the HorizontalAlignment property which defines the positioning of the element (https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/alignment-margins-and-padding-overview) instead of changing the text position
Fixes this: https://github.com/Microsoft/AdaptiveCards/issues/1009

[WPF] Fix text alignment issue

---

source/uwp/Renderer/lib/XamlBuilder.cpp

UWP was making the column with negative ratios a column with 1* for width so the width is changed to auto as WPF and Javascript do
Fixes this: https://github.com/Microsoft/AdaptiveCards/issues/1914

[UWP] Make the negative ratio behaviour consistent

---

source/dotnet/Library/AdaptiveCards.Rendering.Html/AdaptiveCardRenderer.cs
source/dotnet/Library/AdaptiveCards.Rendering.Html/AdaptiveRenderContext.cs
source/dotnet/Library/AdaptiveCards.Rendering.Wpf/AdaptiveCardRenderer.cs
source/dotnet/Library/AdaptiveCards/ColorUtil.cs
source/dotnet/Library/AdaptiveCards/HashColorConverter.cs

Merges the two methods for .NET into a shared one. The added class also includes the color validation used by the parsing process.
Fixes this: https://github.com/microsoft/adaptivecards/issues/2120

Add class to validate and parse colors

---

source/dotnet/Library/AdaptiveCards/AdaptiveTypedElementConverter.cs
source/dotnet/Test/AdaptiveCards.Test/AdaptiveActionTests.cs

Bugfix for #2104.
For whatever reason, Json.net mishandles passing `null` up to an `object` (Image) expecting an `object` (SelectAction). This is because the `JsonReader` expects more tokens, but is handed an unhandled `EndObject` token and just throws an error. This all happens in `JsonSerializerInternalReader` when trying to set the properties of the `Image`.
Since we can't control anything other than the `contract` and the `converter`, it looks like the best we can do is catch the exception thrown when deserializing the Image. Then just pass up what we were able to deserialize of the Image so far.
Unfortunately, anything written after the faulty `SelectAction` is lost. This means that the following two JSON would return different AdaptiveCards. This is still different behavior from the …

Handle invalid Image.SelectAction

---

source/dotnet/Library/AdaptiveCards/AdaptiveElement.cs
source/dotnet/Test/AdaptiveCards.Test/SeparatorSpacingTests.cs

Changes the requisite for writing the separation as Strong by requiring spacing to be large and separator to be true, this doesnt modify the general behaviour for spacing so it isnt a breaking change
Fixes this: https://github.com/Microsoft/AdaptiveCards/issues/2037

[.NET] Fix separation strong issue

---

source/uwp/AdaptiveCardTestApp/Pages/TestResultsPage.xaml.cs
source/uwp/AdaptiveCardTestApp/ViewModels/RunningTestsViewModel.cs
source/uwp/AdaptiveCardTestApp/ViewModels/TestResultsViewModel.cs
source/uwp/UWPTestLibrary/RenderTestHelpers.cs
source/uwp/UWPTestLibrary/RenderedTestResult.cs
source/uwp/UWPTestLibrary/TestResultViewModel.cs
source/uwp/UWPTestLibrary/UWPTestLibrary.csproj
source/uwp/UWPUnitTests/UnitTest.cs

First step in addressing some leaks that were found.
Keep track of every RenderedAdaptiveCard that we've rendered and keep them as WeakReferences.
On exit check that they've all been cleaned up.
Current code now leaks 271 cards out of 924

Add leak testing for the AdaptiveCardTestApp.

---

schemas/adaptive-card.json

I noticed a typo in adaptive-card.json. The description of the `type` property of `Input.ChoiceSet` was ``"Must be `\"Input.ChoiceInput\"`."`` instead of ``"Must be `\"Input.ChoiceSet\"`."``

Fix Input.ChoiceSet description

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/TextInputRenderer.java

The color of input text color is hardcoded as black and cannot be changed by the client . 
Fixes the issue [2245](https://github.com/Microsoft/AdaptiveCards/issues/2245)

Remove hardcoded color in input text

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRView.mm

Background image is not being rendered in iOS if there is a custom image renderer. Happening on sample App too.
Custom image renderer check removed

Cherry-pick PR#2140 for issue #2138

---

source/dotnet/Library/AdaptiveCards/AdaptiveCard.cs
source/dotnet/Library/AdaptiveCards/AdaptiveElement.cs
source/dotnet/Test/AdaptiveCards.Test/AdaptiveCardApiTests.cs
source/dotnet/Test/AdaptiveCards.Test/ChoiceSetInputTests.cs
source/dotnet/Test/AdaptiveCards.Test/SeparatorSpacingTests.cs
source/dotnet/Test/AdaptiveCards.Test/SerializationTests.cs

[.NET] Fix separation strong issue (#2200)
Obsolete the default AdaptiveCard constructor in favor of specifying … (#2188)

Cherry picking a couple of .NET fixes for 1.1

---

source/dotnet/Library/AdaptiveCards.Rendering.Html/AdaptiveCards.Rendering.Html.csproj
source/dotnet/Library/AdaptiveCards.Rendering.Wpf.Xceed/AdaptiveCards.Rendering.Wpf.Xceed.csproj
source/dotnet/Library/AdaptiveCards.Rendering.Wpf/AdaptiveCards.Rendering.Wpf.csproj
source/dotnet/Library/AdaptiveCards/AdaptiveCards.csproj

Cherry-picking the change from 1.1 so that new (1.2) packages don't have the issue.

Adding the proper copyright for .NET packages (#2277)

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRSeparator.mm

This PR is a fix for [#2286](https://github.com/Microsoft/AdaptiveCards/issues/2286) 
Issue:
The intrinsicContentSize is passed for ACRSeparator but for some reason it is not applied, and the separator becomes small.
Fix:
We are anyways using intrinsicContentSize and setting contentCompressionResistancePriority for respective Axis which means we want it to apply the same size.
Fixing by setting a width and height constraint for the respective Axis so that separator size does not reduce.

Adding width and height anchor for separator

---

custom.props
source/dotnet/Library/AdaptiveCards.Rendering.Html/AdaptiveCardRenderer.cs

1. Cherry-picking PR #2298 to prevent concurrency on the ActionTransformers.
2. Updating the version of the package.

Backporting our .NET concurrency change

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/ActionLayoutRenderer.java

If the width of actionButtonsLayout is smaller than viewGroup, the scroll view is unnecessary.
In addition, the scroll view will leads to actionButtonsLayout's gravity not working.
Adding the width checker to fix layout issue of multiple buttons.

[Android] Fixed the actions' alignment not working in scroll view.

---

source/dotnet/Library/AdaptiveCards/AdaptiveColumnWidth.cs

Change of Stretch and Auto strings for column width to the lower versions for consistency as the other enums are actually returned as lower case values.
Fixes this: https://github.com/Microsoft/AdaptiveCards/issues/1058

[.NET] Change Auto and Stretch to lower case versions 

---

source/uwp/Renderer/lib/AdaptiveOpenUrlAction.cpp
source/uwp/Renderer/lib/AdaptiveShowCardAction.cpp
source/uwp/UWPUnitTests/ObjectModelTests.cs
source/uwp/UWPUnitTests/UWPUnitTests.csproj

Added basic unit testing to the UWP object model. Constructed each type and set and validated properties. 
Fixed bugs in the constructors of OpenUrlAction and ShowCardAction that prevented these types from being constructed.

Add UWP object model tests and fix bugs

---

source/uwp/Renderer/lib/AdaptiveActionSet.cpp
source/uwp/Renderer/lib/AdaptiveActionSet.h
source/uwp/Renderer/lib/AdaptiveActionSetRenderer.cpp
source/uwp/Renderer/lib/AdaptiveActionSetRenderer.h
source/uwp/Renderer/lib/AdaptiveCardRendererComponent.cpp
source/uwp/Renderer/lib/AsyncOperations.h
source/uwp/Renderer/lib/XamlBuilder.cpp

Making sure that all references are done as `AdaptiveNamespace.`

Fixing references hardcoding the namespace to `AdaptiveCards::Rendering::Uwp`

---

source/android/adaptivecards/src/main/cpp/objectmodel_wrap.cpp
source/android/adaptivecards/src/main/java/io/adaptivecards/objectmodel/AdaptiveCardObjectModelJNI.java
source/android/adaptivecards/src/main/java/io/adaptivecards/objectmodel/ChoiceSetInput.java
source/android/adaptivecards/src/main/java/io/adaptivecards/objectmodel/SubmitAction.java
source/android/adaptivecards/src/main/java/io/adaptivecards/objectmodel/ToggleInput.java
source/shared/cpp/ObjectModel/SubmitAction.cpp
source/shared/cpp/ObjectModel/SubmitAction.h
source/uwp/Renderer/lib/AdaptiveSubmitAction.cpp
source/uwp/UWPUnitTests/ObjectModelTests.cs

Two fixes to data for Action.Submit:
- When the action is created by the API, the data object got set even if there was no data, leading to "data" : null appearing in the json when serialized
- When the data object was passed from the UWP layer to the shared model, it was treated as a string rather than a json object. This lead to it being escaped when serialized, resulting in extra escape characters in the resultant json.

Fix API issues surrounding Action.Submit data

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/ActionLayoutRenderer.java

Reverts Microsoft/AdaptiveCards#2301
This must be reversed because ShowCard actions show problems and the width is not actually calculated

Revert "[Android] Fixed the actions' alignment not working in scroll view."

---

source/uwp/Renderer/lib/AdaptiveActionInvoker.cpp
source/uwp/Renderer/lib/AdaptiveActionInvoker.h
source/uwp/Renderer/lib/AdaptiveMediaEventInvoker.cpp
source/uwp/Renderer/lib/AdaptiveMediaEventInvoker.h
source/uwp/Renderer/lib/AdaptiveRenderContext.cpp
source/uwp/Renderer/lib/AdaptiveRenderContext.h
source/uwp/Renderer/lib/RenderedAdaptiveCard.h

Because the RenderedAdaptiveCard holds on to the root of the tree.
The ClickHandler for the action button hangs on to the ActionInvoker.
This creates a cycle causing the whole AdaptiveCard and XAML tree to leak.
By switching to a WeakRef on the ActionInvoker, this will allow the RenderedAdaptiveCard to be released and the whole tree to go away.
Also setting the RenderContext to use a weakRef on the RenderedAdaptiveCard to prevent another leak.
With the change #2249, we are now leak free in the AdaptiveCardTestApp.

Change RenderResults to be WeakReferences

---

source/nodejs/adaptivecards/src/card-elements.ts
source/nodejs/adaptivecards/src/utils.ts

Fix a regression introduced by full bleeding support. Works better than before though thanks to the full bleeding implementation: now separators will bleed into the first parent that has padding instead of only into their direct parent. This produces more predictable results.
Try this payload:
```
{
"body": [
{
"text": "First element of the card"
},
{
"separator": true,
"text": "Second element of the card"
},
{
"separator": true,
"items": [
{
"text": "First element in the Container with default style"
},
{
"separator": true,
"text": "Second element in the Container with default …
```

Fix alwaysBleedSeparators half broken after recent changes.

---

source/uwp/AdaptiveCardTestApp/Pages/StartPage.xaml
source/uwp/AdaptiveCardTestApp/Pages/StartPage.xaml.cs
source/uwp/AdaptiveCardTestApp/Pages/TestResultsPage.xaml
source/uwp/AdaptiveCardTestApp/Pages/TestResultsPage.xaml.cs

Make start page host config and test headers clickable to toggle selection. Also add a new button on the results page to allow users to start over again without having to relaunch app.

Add two small features to the UWP test app

---

source/uwp/AdaptiveCardTestApp/Pages/TestResultsPage.xaml.cs
source/uwp/AdaptiveCardTestApp/ViewModels/TestResultsViewModel.cs
source/uwp/Renderer/lib/AdaptiveActionInvoker.cpp
source/uwp/Renderer/lib/AdaptiveActionInvoker.h
source/uwp/Renderer/lib/AdaptiveMediaEventInvoker.cpp
source/uwp/Renderer/lib/AdaptiveMediaEventInvoker.h
source/uwp/Renderer/lib/AdaptiveRenderContext.cpp
source/uwp/Renderer/lib/AdaptiveRenderContext.h
source/uwp/Renderer/lib/RenderedAdaptiveCard.h
source/uwp/UWPTestLibrary/RenderTestHelpers.cs
source/uwp/UWPTestLibrary/RenderedTestResult.cs
source/uwp/UWPTestLibrary/TestResultViewModel.cs
source/uwp/Visualizer/ViewModel/DocumentViewModel.cs

***This is a minor breaking change***
There is reference cycle between the `RenderedAdaptiveCard`, the root `FrameworkElement`, the `ActionInvokers` and the `RenderContexts` causing the whole chain to leak.
In order to avoid this, the `ActionInvokers` and the `RenderContexts` will have a `WeakReference` to the `RenderedAdaptiveCard`.
For clients this means that the host needs to hold on to their `RenderedAdaptiveCard` if they need their actions to be invoked while the card is active. It's good practice anyway but this is forcing it.

[UWP] Fix leaking cards

---

custom.props
source/uwp/Renderer/lib/AdaptiveCardRendererComponent.cpp
source/uwp/Renderer/lib/AdaptiveCardRendererComponent.h
source/uwp/Renderer/lib/AdaptiveImageRenderer.cpp
source/uwp/Renderer/lib/AdaptiveImageRenderer.h
source/uwp/Renderer/lib/XamlBuilder.h

* Resolve issue #2341
We were tracking the references to the XamlBuilder through std::shared_ptr and ComPtr
We can only have 1 set of reference count, so consolidating to ComPtr.
Making the XamlBuilder constructor private to avoid this situation.

Do not mix ComPtr and std::shared_ptr on the same object (#2362)

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/AdaptiveCardRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/GenericImageLoaderAsync.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/IDataUriImageLoader.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/InnerImageLoaderAsync.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/action/ActionElementRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/TextInputRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/ImageRenderer.java
source/android/mobile/build.gradle
source/android/mobile/samples/v1.1/Scenarios/Image.SvgDataUri.json
source/android/mobile/src/main/java/io/adaptivecards/adaptivecardssample/ImageUtil.java
source/android/mobile/src/main/java/io/adaptivecards/adaptivecardssample/MainActivityAdaptiveCardsSample.java

We want to support svg images, so we need a width parameter sent to image loader to decide the size of the svg image.

Add maxWidth parameter for image loader to support vector images on Android.

---

source/dotnet/Library/AdaptiveCards.Rendering.Html/AdaptiveCardRenderer.cs

By adding the tabindex attribute to selectActions, they can now be navigated through with the keyboard.

Add tabindex attribute to select actions to enable keyboard naviagtion.

---

source/dotnet/Library/AdaptiveCards.Rendering.Html/AdaptiveCardRenderer.cs

NullReference exception is thrown if rendering actions with interactivity

---

source/dotnet/Library/AdaptiveCards.Rendering.Html/AdaptiveCardRenderer.cs
source/dotnet/Library/AdaptiveCards.Rendering.Html/AdaptiveRenderContext.cs
source/dotnet/Library/AdaptiveCards.Rendering.Wpf/AdaptiveCardRenderer.cs
source/dotnet/Library/AdaptiveCards.Rendering.Wpf/AdaptiveContainerRenderer.cs
source/dotnet/Library/AdaptiveCards.Rendering.Wpf/AdaptiveRenderContext.cs
source/dotnet/Library/AdaptiveCards.Rendering.Wpf/AdaptiveTextBlockRenderer.cs
source/dotnet/Library/AdaptiveCards/Rendering/ContainerStylesConfig.cs
source/dotnet/Test/AdaptiveCards.Rendering.Html.Test/HtmlRendererTests.cs

Bugfix for #2285 .
`AdaptiveRenderContext` was modified to keep track of the container style. When TextBlock text is being rendered, it now reads the value in `AdaptiveRenderContext` and bases it off that.
`ContainerStylesConfig` now has appropriate default values that match up with SharedModel.
Test for HTML was created. There is no way to make a test for WPF.

[.NET] Apply ContainerStyle Foreground Colors + default Foreground Colors

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/AdaptiveCardRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/BackgroundImageLoaderAsync.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/ColumnRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/ContainerRenderer.java

Allows background image to be repeated along the x and/or y axis. Also added background image support to containers and columns.
PR for #1292 
Spec: #477 
* Moved `BackgroundImageLoaderAsync` to its own file for public access (needed for container/column).
* Added `BackgroundImageLoaderAsync` usage in container/column
* Created `BackgroundImageDrawable` within`BackgroundImageLoaderAsync`:
* added `tileVertically` and `tileHorizontally` to handle tiling image along one axis
* overrode `draw(Canvas)` to draw background image appropriately based on background image properties (mode and vertical/horizontal alignment).

[Android] Enhanced background image support

---

source/uwp/AdaptiveCardTestApp/Pages/StartPage.xaml.cs
source/uwp/AdaptiveCardTestApp/Views/DiffView.xaml
source/uwp/AdaptiveCardTestApp/Views/DiffView.xaml.cs
source/uwp/AdaptiveCardTestApp/Views/TestResultView.xaml.cs

During my snow day I came across some issues in the UWP test app that blocked me from getting stuff done efficiently:
* My laptop runs in high DPI and I didn't want to switch to regular DPI just to run JSON serialization tests, so I added a `Run Anyway` button to the DPI warning
* It's really painful to manually inspect JSON diffs where everything is on one line. I introduced a formatting routine for the purposes of diffing to make it easier to see the differences.

Misc. test app improvements

---

source/android/adaptivecards/build.gradle
source/android/adaptivecards/src/main/cpp/objectmodel_wrap.cpp
source/android/adaptivecards/src/main/java/io/adaptivecards/objectmodel/AdaptiveCardObjectModelJNI.java
source/android/adaptivecards/src/main/java/io/adaptivecards/objectmodel/SubmitAction.java
source/android/adaptivecards/src/main/java/io/adaptivecards/objectmodel/WarningStatusCode.java
source/android/mobile/build.gradle
source/android/mobilechatapp/build.gradle
source/shared/cpp/ObjectModel/SubmitAction.cpp
source/shared/cpp/ObjectModel/SubmitAction.h
source/uwp/Renderer/lib/AdaptiveSubmitAction.cpp

Completes this issue: https://github.com/Microsoft/AdaptiveCards/issues/2381
It looks like the original method was removed and then re-added. I couldn't cherrypick the fix as @RebeccaAnne made it as it included the ChoiceSetInput wrap property. 
This PR also contains the fix for the gradle files as the keyword 'compile' and it's derivatives are now obsolete and they must be changed for 'implementation' and its derivatives

[Shared][UWP][Android] Add setDataJson(string) method

---

source/dotnet/Library/AdaptiveCards/AdaptiveNumberInput.cs
source/dotnet/Test/AdaptiveCards.Test/AdaptiveNumberInputTests.cs

Fix with tests to this issue: https://github.com/Microsoft/AdaptiveCards/issues/2478

Fix Null value handling for Min, Max, and Value in AdaptiveNumberInput

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/ActionLayoutRenderer.java

If the width of actionButtonsLayout is smaller than viewGroup, the HorizontalScrollView will leads to actionButtonsLayout alignment like "center" not working.
Adding gravity property in HorizontalScrollView to fix this issue.

[Android] Fix button alignment in horizontal not working in scroll.

---

source/uwp/AdaptiveCardTestApp/Pages/StartPage.xaml

We have more hostconfigs in the mix now, so we end up with overlapping controls. For now, just move the checkbox to the bottom.

[UWP] Make "Add to Timeline" checkbox align to bottom

---

source/uwp/Renderer/lib/XamlBuilder.cpp

Addresses UWP issue #2400 where images are not obeying the constraints of the parent container.
This causes problems where images within columns with set widths extend outside of the column bounds and get clipped.

[UWP] Fix for 2400 - Images not obeying parent container width constraints

---

source/uwp/Renderer/idl/AdaptiveCards.Rendering.Uwp.idl
source/uwp/Renderer/lib/AdaptiveRenderContext.cpp
source/uwp/Renderer/lib/AdaptiveRenderContext.h

[Link to bug item](https://github.com/Microsoft/AdaptiveCards/issues/2532 )
Exposing the user input values from any input elements in the adaptive card through the Render Context.
This is useful for custom renderers which need to know the input values of other elements in the card as a whole.
Fixes #2532

[UWP] Exposing user inputs through render context

---

source/uwp/ObjectModelProjection/ObjectModelProjection.vcxproj
source/uwp/PerfApp/PerfApp.vcxproj

In prep for enabling quicker UWP builds, we need to update our projects to be buildable on all permutations of [Release|Debug] x [x86|x64|ARM]. This fixes that. :)

Update project files to build in all configurations/platforms

---

source/uwp/Renderer/lib/AdaptiveRichTextBlock.h

Fix build break caused by the conflict between the min height and the rich text block changes

[UWP] Fix min height/rich text block build break

---

source/dotnet/Library/AdaptiveCards.Rendering.Html/AdaptiveCards.Rendering.Html.csproj
source/dotnet/Library/AdaptiveCards.Rendering.Wpf.Xceed/AdaptiveCards.Rendering.Wpf.Xceed.csproj
source/dotnet/Library/AdaptiveCards.Rendering.Wpf/AdaptiveCards.Rendering.Wpf.csproj
source/dotnet/Library/AdaptiveCards/AdaptiveCards.csproj

Fixes #2010 in `release/1.0`
(cherry picked from commit f44d396ec66980446568c93870ab91868b1888ab)

Updating the dotnet projects metadata to generate the nuget packages (#2010)

---

custom.props
source/dotnet/Library/AdaptiveCards.Rendering.Html/Properties/AssemblyInfo.cs
source/dotnet/Library/AdaptiveCards.Rendering.Wpf.Xceed/Properties/AssemblyInfo.cs
source/dotnet/Library/AdaptiveCards.Rendering.Wpf/Properties/AssemblyInfo.cs
source/dotnet/Library/AdaptiveCards/AdaptiveNumberInput.cs
source/dotnet/Library/AdaptiveCards/Properties/AssemblyInfo.cs
source/dotnet/Test/AdaptiveCards.Test/AdaptiveNumberInputTests.cs

Fixes #2480 in the 1.1 release
* Fix Null value handling for Min, Max, and Value in AdaptiveNumberInput
* address PR comments
(cherry picked from commit a5650dc)

Fix Null value handling for Min, Max, and Value in AdaptiveNumberInput (release/1.1)

---

source/dotnet/Library/AdaptiveCards/AdaptiveCard.cs
source/dotnet/Library/AdaptiveCards/AdaptiveCards.csproj
source/dotnet/Samples/XamarinFormsBotClient/AdaptiveCards.Sample.BotClient.UWP/AdaptiveCards.Sample.BotClient.UWP.csproj

Fixes #845.
There's a `TODO` and an `#ifdef` in the .NET adaptiveCards library referring to UWP. This doesn't seem to be necessary any more, as we now have a UWP implementation.

Remove references to UWP in dotnet project

---

source/dotnet/Library/AdaptiveCards/AdaptiveChoiceInputStyle.cs
source/dotnet/Library/AdaptiveCards/AdaptiveChoiceSetInput.cs

(to align with other platforms)
Fixes #2446
* existing unit tests
* sample card from linked issue in visualizers

Make `compact` the default Input.ChoiceSet style

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/BackgroundImageLoaderAsync.java

Fixes https://github.com/microsoft/AdaptiveCards/issues/2947
The issue came with the "hackish" trick to avoid containers to grow if a background image was specified even if the background was smaller, there I was adding an empty image of size 1x1 but that overrode the repeat behaviour that was using the actual set background image
Also found out that the incomplete images were not being drawn so I fixed that too
The mobile app was run and this are the results
AdaptiveCard.BackgroundImage.FillMode.json
AdaptiveCard.BackgroundImage.FillMode.Repeat.json
AdaptiveCard.BackgroundImage.FillMode.RepeatHorizontally.json
AdaptiveCard.BackgroundImage.FillMode.RepeatVertically.json
Column.BackgroundImage.json
Container.BackgroundImage.json

[Android] Fix background image repeat behaviours

---

source/nodejs/adaptivecards/src/card-elements.ts

Addresses:
- [Designer] Background image persists after new card #2945
- Incorrect method name serText in TextBlock (should be setText) #2949
Manually tested.

TS bug fixes

---

source/nodejs/adaptivecards-designer-app/dist/containers/outlook-container.css
source/nodejs/adaptivecards-designer-app/dist/containers/webchat-container.css
source/nodejs/adaptivecards-designer/src/containers/outlook/outlook-container.css
source/nodejs/adaptivecards-designer/src/containers/webchat/webchat-container.css
source/nodejs/adaptivecards-designer/src/designer-peers.ts
source/nodejs/adaptivecards/src/card-elements.ts
source/nodejs/adaptivecards/src/enums.ts

Also makes the `style` property a string for extensibility.
Hosts that want to use custom styles should declare an `.ac-pushButton.style-<custom style name>` class in their CSS file. Example:
```css
.ac-pushButton.style-myCustomStyle {
background-color: green;
color: white;
}
```

TS: Rename action.sentiment into action.style

---

source/uwp/AdaptiveCards.sln
source/uwp/UWPUnitTests/UWPUnitTests.csproj

A couple small changes:
* Remove unneeded dependency between `AdaptiveCardsVisualizer` and `ObjectModelProjection`, since it already depends on `AdaptiveCardRenderer`
* Move `UWPUnitTests` off of the .NET Native toolchain since it's just tests
This dropped builds down by 3-4 minutes of execution time :)

[UWP] Build perf improvements

---

source/nodejs/adaptivecards/src/card-elements.ts

Fixes #3007, #3009 
- Fix selectAction exception on empty ColumnSet (https://github.com/microsoft/AdaptiveCards/issues/3007)
- Hide horizontal overflow in ColumnSet (https://github.com/microsoft/AdaptiveCards/issues/3009)
Verified manually.

Cumulative ColumnSet fixes from Bug bash

---

source/nodejs/adaptivecards-controls/package-lock.json
source/nodejs/adaptivecards-controls/package.json
source/nodejs/adaptivecards-designer-app/package-lock.json
source/nodejs/adaptivecards-designer/package-lock.json
source/nodejs/adaptivecards-visualizer/package-lock.json
source/nodejs/adaptivecards/package-lock.json
source/nodejs/package-lock.json

Current `master` branch builds of nodejs fail since we shipped a new version of `adaptivecards-controls`. This is due to how we handle versioning on our internal package feed. The fix is to move master to the next minor version (`release/1.2` is still at `0.2.0`).

Update adaptivecards-controls package version

---

samples/HostConfig/webchat.json
source/nodejs/adaptivecards-designer/src/containers/webchat/webchat-container.css

Fixes #3039 
Currently, the Adaptive Card designer using Web Chat's hostconfig does not match the ultimate appearance of Adaptive Cards within the Web Chat app. 
Default buttons on the designer:
Default buttons on Web Chat:
My changes:
- Update Web Chat's sample host config
- Update `webchat-container.css`'s default font and button appearance

Update Web Chat hostconfig & designer css

---

source/uwp/AdaptiveCardTestApp/Pages/RunningTestsPage.xaml.cs
source/uwp/AdaptiveCardTestApp/Pages/TestResultsPage.xaml
source/uwp/AdaptiveCardTestApp/Pages/TestResultsPage.xaml.cs
source/uwp/AdaptiveCardTestApp/ViewModels/TestResultsViewModel.cs
source/uwp/AdaptiveCardTestApp/Views/TestResultView.xaml
source/uwp/AdaptiveCardTestApp/Views/TestResultView.xaml.cs
source/uwp/UWPTestLibrary/TestResultViewModel.cs
source/uwp/UWPUnitTests/UnitTest.cs

Several improvements to the UWP test app.
- More information in test results. Specifically, calling out the results of original comparison, json round tripping and image comparison. In addition, added a colored border to call out whether the image comparison failed:
- Ability to accept originals, jsons, or images independently, both per card and for the entire list:
- As a result of those changes, we no longer need all of the combinations of tabs on the side. Simplified that list:
- To support these changes, changed the TestStatus from an enum to class, and updated the code accordingly.
Fixes #3045

[UWP][TestApp] Usability Improvements

---

source/uwp/AdaptiveCardTestApp/Pages/RunningTestsPage.xaml
source/uwp/AdaptiveCardTestApp/ViewModels/RunningTestsViewModel.cs
source/uwp/UWPUnitTests/UnitTest.cs

Two main fixes to improve test app reliability:
- Scroll bar for test result. Sometimes images that were below the fold wouldn't fully load, leading to test failures. Adding a ScrollViewer control causes those images to load consistently.
- Reruns on failure. Rerun a failed test to allow for occasional image inconsistencies.
With these changes, all test app files are passing consistently for me (please let me know if you are seeing failures).
Fixes #3047

[UWP][TestApp] Reliability fixes

---

schemas/1.2.0/adaptive-card.json
schemas/src/elements/Column.json
schemas/src/elements/ColumnSet.json
schemas/src/elements/Container.json

Our schema description for `Column.width` was missing stating that you can use pixel widths in the columns. Fixes #3073
Also, our property descriptions of `minHeight` didn't show an example of the pixel string format in the description.
Both of these updates were made to the existing `1.2.0` schema rather than incrementing version number since these updates are strictly limited to the descriptions, and therefore won't affect anyone using the schema as CI testing

Add px to Column.width and some other schema description updates

---

source/ios/AdaptiveCards/ADCIOSVisualizer/resources/sample.json

fixes ios ci issue
the ios unit test pull down media icon from https://www.shareicon.net/ for each test.
lately, we seemed to hit their rate limit, and download speed from unit tests was severely limited.
removed the url from unit test host config.

removed play icon from hostconfig

---

source/dotnet/Library/AdaptiveCards/AdaptiveImage.cs
source/dotnet/Test/AdaptiveCards.Test/AdaptiveCardApiTests.cs
source/shared/cpp/AdaptiveCardsSharedModel/AdaptiveCardsSharedModelUnitTest/ObjectModelTest.cpp
source/shared/cpp/ObjectModel/ColumnSet.cpp
source/shared/cpp/ObjectModel/ImageSet.cpp

Update the shared model and .NET code to allow images within an image set to not explicitly specify their type.
How Verified: Ran Shared Model, UWP, and .NET tests. Added new case to shared model and .NET to cover this scenario. Manual verification in UWP and .NET visualizers.
Fixes #2848

[Shared Model] [.NET] Allow images in image set to not specify element type

---

source/ios/AdaptiveCards/ADCIOSVisualizer/resources/sample.json
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRMediaRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRView.mm

Fixes issue #3104 
there were two issues;
1. logic for disabling playIcon was properly adjusted after resource resolver changes.
2. the new resource resolver changes require new instances of UIImageViews, as UIImageView is a container of UIImage, and can't be duped.

fixes issue #3104

---

source/uwp/Renderer/AdaptiveCardRenderer.vcxproj
source/uwp/Renderer/lib/RenderedAdaptiveCard.cpp
source/uwp/Renderer/lib/XamlBuilder.cpp

Building UWP locally (x86/debug) I ran into the following error:
"'/ZI' and '/guard:cf' command-line options are incompatible"
Set DebugInformationFormat to ProgramDatabase (/Zi instead of /ZI) to avoid this conflict. 
Additionally, hit two warnings about unreachable code (now treated as errors) and fixed them.
How verified: UWP debug now builds correctly. No new test failures.

[UWP] Fix debug build

---

source/shared/cpp/ObjectModel/ToggleInput.cpp

Fixes #3224
Changes the serialize and deserialize methods for input.toggle to handle the default values for valueOn and valueOff correctly.
**This is required for the android unit tests**

Fix toggle input default values for valueOn and valueOff

---

schemas/1.2.1/adaptive-card.json
schemas/src/elements/ColumnSet.json
schemas/src/elements/inputs/Input.Toggle.json
specs/elements/ColumnSet.md
specs/elements/Input.Toggle.md

The property wasn't supposed to be on there and it was an accidental addition to the schema which none of the renderers support
* Removed the `backgroundImage` property from the schema
* Updated the `Input.Toggle.value` description since it had a new typo and was also worded very confusingly
* Generated the new `1.2.1` schema
Part of fixing issue #3249, but we need to also pull this change down to the 1.2 branch and then update the site before that's fixed. But fixing in master is the first step

Remove backgroundImage from ColumnSet

---

source/dotnet/Samples/AdaptiveCards.Sample.Html/AdaptiveCards.Sample.Html.csproj
source/dotnet/Samples/AdaptiveCards.Sample.ImageRender/AdaptiveCards.Sample.ImageRender.csproj
source/dotnet/Samples/ImageRendererServer/ImageRendererServer.csproj
source/dotnet/Test/AdaptiveCards.Rendering.Html.Test/AdaptiveCards.Rendering.Html.Test.csproj
source/dotnet/Test/AdaptiveCards.Test/AdaptiveCards.Test.csproj

These version revs had to be manually added (outside of VS), which is why they were missed.

[.NET] Add manual versioned references to System.Net.Http 4.3.1

---

source/dotnet/Build/SignConfig.xml

[.NET] Remove netstandard 1.3 from signconfig.xml

---

source/community/reactnative/README.md

Updated the readme to point to this repo. Please review and merge if it looks good to you 👍

Update react native readme

---

custom.props
source/dotnet/Build/CopySignFiles.cmd
source/dotnet/Build/SignConfig.xml
source/dotnet/Samples/AdaptiveCards.Sample.Html/Program.cs
source/uwp/Build/SignConfig.xml

Cherry-pick signing fixes and bump version.
Verified by running release pipeline without publishing

[.NET] Bring signing changes over in prep for 1.2.2

---

source/shared/cpp/AdaptiveCardsSharedModel/AdaptiveCardsSharedModelUnitTest/ElementTest.cpp
source/uwp/Renderer/lib/AdaptiveColumn.cpp

With change fee0c03191cd212ad004d16be9ae2a533589d433, pixel width and string width in the shared model are now last-writer-wins. Update `AdaptiveColumn::GetSharedModel()` to account for that. I made sure that there are no other dependencies on calling order exist in our codebase (that I can find), and marked the original bug for the shared model change as breaking. I also added missing serialization verification to shared model unit tests.
Fixes #3339.
Verified with test app

[UWP] Fix AdaptiveColumn width

---

.github/ISSUE_TEMPLATE/bug_report.md

- Follows the newer template workflow which allows for separate templates for bugs and tasks
- Allows for automatically labeling the issues as "Bugs" to kick off the internal fabric bot github workflow to get this visible on our project boards

Create a new issue template for Bug Reports

---

.github/pull_request_template.md

Attempt at trying to standardize PR descriptions via a template for guidance- both for maintainability/documentation purposes and ease of code review for reviewers. Also ensures any requirements w.r.t PR's are enforced esp. for some of the fabric bot policies that kick in for PR's.

Created a pull request template file

---

source/uwp/PerfApp/PerfApp.vcxproj
source/uwp/UWPUnitTests/UWPUnitTests.csproj

Since the unit tests bits don't ship, there's really no need to run them through the .NET Native toolchain. Should shave a minute or two off of our pipeline build times.

[UWP] Build unit tests without .NET Native

---

source/shared/cpp/ObjectModel/DateTimePreparser.cpp

Fixes #3378
Instead of running our regex against every line processed by `DateTimePreparser`, first do a quick check to see if the text contains `{{`.
Unit tests & UWP visualizer

[Shared] Improve DateTimePreparser perf

---

source/uwp/Renderer/lib/AdaptiveError.h
source/uwp/Renderer/lib/AdaptiveWarning.h

Regression from fix to #3373 in PR #3375.
I changed the default constructors for AdaptiveError and AdaptiveWarning to ones that take parameters. I forgot that this requires manually implementing the corresponding factory classes. This means that although calls to the new constructors built fine, they failed at runtime.
Fixed this by implementing factory classes for AdaptiveError and AdaptiveWarning.
Verified with local in progress custom rendering cases (for #2720).

[UWP] Add implementations of factory classes for warnings and errors

---

source/uwp/Renderer/lib/AdaptiveOpenUrlAction.cpp
source/uwp/Renderer/lib/DateTimeParser.h
source/uwp/Renderer/lib/Util.cpp
source/uwp/Renderer/lib/Util.h
source/uwp/Visualizer/ViewModel/DocumentViewModel.cs

Fixes #3398
The UWP renderer relies on the classes from stl's `codecvt` which have been deprecated. On top of that, `codecvt` is quite slow compared to platform APIs. With this change, we switch over to `MultiByteToWideChar()` and `WideCharToMultiByte()` for our charset conversion.
PerfApp and the test app. Between this change and the change that went in with #3379, we're seeing a pretty serious perf improvement:
Measurements taken on my dev machine running an x64 release build of the PerfApp. The app was run without a debugger attached.
If you've never used the UWP PerfApp before, the above screenshots might be a little confusing. I chose 50 parse iterations and 1 render iteration per card. As implemented, this means that each card will be parsed and then rendered. This happens 50 times …

[UWP] Use platform character conversion functions instead of codecvt

---

source/uwp/Renderer/AdaptiveCardRenderer.vcxproj
source/uwp/Renderer/AdaptiveCardRenderer.vcxproj.filters
source/uwp/Renderer/idl/AdaptiveCards.Rendering.Uwp.idl
source/uwp/Renderer/lib/AdaptiveActionSet.h
source/uwp/Renderer/lib/AdaptiveCardElement.cpp
source/uwp/Renderer/lib/AdaptiveCardElement.h
source/uwp/Renderer/lib/AdaptiveChoiceSetInput.h
source/uwp/Renderer/lib/AdaptiveColumn.h
source/uwp/Renderer/lib/AdaptiveColumnSet.h
source/uwp/Renderer/lib/AdaptiveContainer.h
source/uwp/Renderer/lib/AdaptiveDateInput.h
source/uwp/Renderer/lib/AdaptiveFactSet.h
source/uwp/Renderer/lib/AdaptiveImage.h
source/uwp/Renderer/lib/AdaptiveImageSet.h
source/uwp/Renderer/lib/AdaptiveMedia.h
source/uwp/Renderer/lib/AdaptiveNumberInput.h
source/uwp/Renderer/lib/AdaptiveRequirement.cpp
source/uwp/Renderer/lib/AdaptiveRequirement.h
source/uwp/Renderer/lib/AdaptiveRichTextBlock.h
source/uwp/Renderer/lib/AdaptiveTextBlock.h
source/uwp/Renderer/lib/AdaptiveTextInput.h
source/uwp/Renderer/lib/AdaptiveTimeInput.h
source/uwp/Renderer/lib/AdaptiveToggleInput.h
source/uwp/Renderer/lib/AdaptiveUnsupportedElement.h
source/uwp/Renderer/lib/Util.cpp
source/uwp/Renderer/lib/Util.h
source/uwp/Renderer/lib/XamlBuilder.cpp
source/uwp/UWPUnitTests/FallbackTests.cs
source/uwp/UWPUnitTests/ObjectModelTests.cs
source/uwp/UWPUnitTests/ParserRegistration.cs

Fixes #3409 
Changed the MeetsRequirements function on IAdaptiveCardElement to a Requirements property. This has two benefits:
1. This removes the burden on custom element renderers needing to implement the MeetsRequirements function. There's no expectation that this method would be different on different elements, so this doesn't need to be a per-element implementable function.
2. Allows callers to set element requirements programmatically in the case where they are building the object model. In the previous API design, there was no way for a caller to add a requirement to an element using the object model API.
Object model and functional UWP unit tests (opened #3418 and #3420 for existing issues). Ran the test app.

[UWP] Change MeetsRequirements method to Requirements property

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRRichTextBlockRenderer.mm

fixes #3362 
iOS renderer lacks visual cue for rich text with submit action.
visual cue is added via NSAttributed text as underline.
The underline color is set same as foreground color of the text following the example of WPF renderer.
sample cards were used to test the changes.

Added visual cue for rich text submit action

---

source/uwp/Renderer/lib/AdaptiveActionParserRegistration.cpp
source/uwp/Renderer/lib/AdaptiveActionParserRegistration.h
source/uwp/Renderer/lib/AdaptiveElementParserRegistration.cpp
source/uwp/Renderer/lib/AdaptiveElementParserRegistration.h
source/uwp/Renderer/lib/Util.cpp
source/uwp/Renderer/lib/Util.h
source/uwp/UWPUnitTests/ParserRegistration.cs

Fixes #3427
In order to store custom parsers from UWP callers in the shared model, a wrapper class (```SharedModelElementParser```) is used to implement the shared model parser base class (```BaseCardElementParser```). This wrapper class holds a pointer to the UWP level parser registration for the wrapped type (either action or element).
The bug was that when this wrapper class was called back, instead of using the existing UWP level parser registration, it created a new one to pass to the UWP custom parser. This new registration did not include the UWP level parser registrations, and so it appeared to the callback as if the custom registrations were missing.
- Registered the element and action parsers with the shared model under a known guid. This allows the callback in the UWP interface …

[UWP] Ensure correct parser registrations are passed to custom parsers

---

source/dotnet/Library/AdaptiveCards.Rendering.Html/AdaptiveCards.Rendering.Html.csproj
source/dotnet/Library/AdaptiveCards.Rendering.Wpf/AdaptiveCards.Rendering.Wpf.csproj
source/dotnet/Library/AdaptiveCards/AdaptiveCards.csproj
source/dotnet/Samples/WPFVisualizer/AdaptiveCards.Sample.WPFVisualizer.csproj
source/dotnet/Samples/WPFVisualizer/packages.config

Fixes #3413 
Per original bug, in 1.2 we introduced a hard dependency on `Newtonsoft.Json` >= 12.0.2. This isn't strictly necessary, as we don't rely on 12.X features. Here we set the minimum to 11.0.2, which is the version being targeted by BotFramework. To facilitate this, the WPFVisualizer project has been migrated away from a `packages.config` file to `<PackageReference />` entries in the csproj.
VS/CI build

[.NET] Relax Newtonsoft.Json version requirements

---

source/nodejs/adaptivecards-designer/src/card-designer.ts

Fixes https://github.com/microsoft/AdaptiveCards/issues/3458
Please refer to the issue for a full description. Applications embedding the designer can now handle two new events:
- **onActiveHostContainerChanged**: triggered when the user selects another host application in the toolbar
- **onCardPayloadChanged**: triggered when the card has changed, whether via drag/drop or as the JSON is manually modified
Verified manually

Add two events to designer

---

source/dotnet/Library/AdaptiveCards/AdaptiveCard.cs
source/dotnet/Library/AdaptiveCards/AdaptiveCardConverter.cs
source/dotnet/Samples/WPFVisualizer/MainWindow.xaml.cs
source/dotnet/Test/AdaptiveCards.Test/AdaptiveCardApiTests.cs

Fixes #3376
Allows .NET folks to supply a callback to run when a missing or empty `version` field is encountered. The callback takes no parameters and must return an `AdaptiveSchemaVersion`, which represents the version to use for parsing.
Manual validation with Visualizer through debugger. New unit tests.

[.NET] Add new OnDeserializingMissingVersion callback

---

source/nodejs/adaptivecards-designer-app/src/app.ts
source/nodejs/adaptivecards-designer/README.md
source/nodejs/adaptivecards-designer/src/adaptivecards-designer-standalone.ts
source/nodejs/adaptivecards-designer/src/card-designer.ts
source/nodejs/adaptivecards-designer/src/strings.ts

Fixes https://github.com/microsoft/AdaptiveCards/issues/3487
Please refer to issue.
Added a global Strings class with static members that hold the default values of various strings used by the designer. In the future, more strings will be moved to that class.
Verified manually using designer-app.

Add ability to customize toolbox titles

---

source/uwp/Renderer/lib/ElementTagContent.cpp
source/uwp/Renderer/lib/ElementTagContent.h
source/uwp/Renderer/lib/RenderedAdaptiveCard.cpp

Found during investigation of #3425 but doesn't fully fix that issue.
Storing the parent element in the element tag leads to the following circular reference:
ParentElement->ChildElement->ElementTag->ParentElement
Fixed this issue by storing a weak reference to the parent element in the tag. 
Ran UWP test app and unit tests. Repro on a locally modified version of code showed that this used to cause a leak and now doesn't.

[UWP] Fix cirucular reference in element tag

---

source/uwp/Renderer/lib/AdaptiveImageRenderer.cpp

Fixed as part of the investigation for #3425. This seems to be the largest part of the leak, but there is still a leak in that scenario after this fix.
The imageOpened lambdas in SetAutoSize were taking strong references to the image or ellipse item and its parent. This lead to a circular reference which caused these items to leak. Updated the lambdas to take weak references instead to break the circular reference and avoid the leak.
Confirmed no new failures in the UWP test app. Manual verification that the memory leak is gone in a local scenario where it had previously repro'd.

[UWP] Fix circular reference in ImageOpened lambda for Auto sized image handling

---

source/uwp/Renderer/lib/ActionHelpers.cpp

Fixes #3527
While investigating alternatives for a partner team, I noticed that ActionSet buttons lack appropriate accessibility information, particularly when an `iconUrl` is present. Most accessibility tools will decide that if there's a single text child of a button, that the text child must be the name. However, if there's >1 child, it gives up. Consider this:
```json
{
"version": "1.1",
"body": [
{
"type": "ActionSet",
"actions": [
{
"type": "Action.Submit",
"title": "action!",
"iconUrl": "data:image/png;base64,[...]="
}
]
}
]
}
```
Accessibility Insights will show this as not having a name. Similarly, Narrator will read it simply as "button".
The fix is to explicitly add the action title as the accessible name for the button control when it's built.
Verified …

[UWP] Add accessible names to all action buttons

---

source/dotnet/Library/AdaptiveCards/AdaptiveCard.cs
source/dotnet/Library/AdaptiveCards/AdaptiveCardConverter.cs
source/dotnet/Library/AdaptiveCards/AdaptiveFallbackConverter.cs
source/dotnet/Library/AdaptiveCards/AdaptiveInlinesConverter.cs
source/dotnet/Library/AdaptiveCards/AdaptiveTypedBaseElementConverter.cs
source/dotnet/Library/AdaptiveCards/AdaptiveTypedElement.cs
source/dotnet/Library/AdaptiveCards/AdaptiveTypedElementConverter.cs
source/dotnet/Library/AdaptiveCards/IgnoreEmptyItemsConverter.cs
source/dotnet/Library/AdaptiveCards/ParseContext.cs
source/dotnet/Library/AdaptiveCards/WarningLoggingContractResolver.cs
source/dotnet/Test/AdaptiveCards.Test/AdaptiveCardApiTests.cs

fixes #3509, fixes #3541 
ParseContext was a static class, and it caused synchronization issue during parsing in multi-threaded environments.
- this changes include:
1. Made ParseContext non static class
2. Added an instance of ParseContext to WarningLoggingContractResolver.
- so client's custom Json contract resolver may not work.
- we already don't allow custom Json contract resolver if FromJson() API is used
3. Fixed the issue where internalIds are not being set for elements
4. Added concurrency unit test for parsing
1. Concurrency unit tests were added and verified it.
2. All existing unit tests were passed
3. Run all of the fallback json tests cards and ran some of the relevant cards such as showcard

Parse Context Update

---

source/nodejs/adaptivecards/src/card-elements.ts

Fixes https://github.com/microsoft/AdaptiveCards/issues/3564
Fixes https://github.com/microsoft/AdaptiveCards/issues/3563
This PR integrates fixes from master.
- Reverted to **stretch** as the default column width.
- Only render the default **"Title"** value for a Fact's title in the designer
These fixes impact Teams and are somewhat urgent. A new npm package should be generated once they are merged.
Verified manually in both adaptivecards-designer-app and in adaptivecards-visualizer

[TS] Regression fixes

---

source/nodejs/adaptivecards-site/themes/adaptivecards/source/web.config

Fixes #3588
This is necessary so that Azure serves our static font files (for font-awesome). I updated the web.config on the CI server directly and confirmed this resolves the errors seen at https://adaptivecards.io

update web.config to serve static font files

---

source/uwp/Renderer/lib/XamlBuilder.cpp
source/uwp/Renderer/lib/XamlBuilder.h

Fixes #3591
Related #3555 
There was another scenario where an action was being reported as a `button` rather than a `link` to accessibility. The fix is to instantiate the appropriate `LinkButton` for `selectAction`s of type `Action.OpenUrl`. I also looked for other instances where this would be appropriate, but found none.
Unit tests, Visualizer+AccInsights, and TestApp

[UWP] OpenUrl selectActions appear as links to accessibility

---

source/uwp/Build/SignNugetConfig.xml

#3595  Related Issue
[UWP] Symbols incorrectly published for UWP.
The UWP renderer is native code which is unsupported by the nuget symbol server. Currently the release process nuget packs with the Symbols flag to generate a separate symbols.nupkg that is uploaded to that server.
If we remove that from the pipeline, this config file still expects to find it. So we need to remove this reference.
1. n/a.
2. n/a
3. n/a, need to make this change before changing the pipeline.

Remove symbols nuget package signing reference

---

custom.props

Update `release/1.2` branch version to 1.2.5 in prep for next patch.

Move release/1.2 branch to 1.2.5

---

source/uwp/Renderer/AdaptiveCardRenderer.vcxproj

For this issue: https://github.com/microsoft/AdaptiveCards/issues/3606
This flag is needed for mandatory static analysis as part of our process.
Fixes #3606 
Our compliance process requires binaries to be built with /profile to generate additional context for mandatory static analysis.
This should not change our dll from its existing state [Documented here](https://docs.microsoft.com/en-us/cpp/build/reference/profile-performance-tools-profiler?view=vs-2019)
Note: The documentation specifies that the program image will be affected by a "relocation section"- however this is caused by the implied /FIXED:NO flag. /FIXED:NO is the default for msbuild, so we were generating that anyway.
No unit testing. I built locally with this flag and passed it through the static analysis tool and where …

Adding /profile linker option

---

samples/v1.2/Tests/newline_card.json
samples/v1.2/Tests/newline_card_r.json
source/android/adaptivecards/src/androidTest/java/io/adaptivecards/objectmodel/TextBlockPropertiesTest.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/RendererUtil.java

Fixes #3531 
Due to some preprocessing done in Android to support Markdown we translate the text strings into HTML, this causes \n or \r to be ignored. For this solution, \n and \r are replaced by <br/> as that's HTML's the new line 
Manual testing was performed with the provided card and this is the result
As the TextBlock.Markdown card also contained /r the card was also tested 
A unit test was also added to check the correct management of '\n' characters during preprocessing

[Android] Add support for new lines in TextBlock

---

samples/v1.2/Tests/choice_default_value.json
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/ChoiceSetInputRenderer.java

Fixes #3605 
Overrides the base behaviour of the ArrayAdapter to handle default empty values in such a way where the empty option is the default value but it's not a selectable value afterwards
The scenario was tested manually using the attached payload yielding this result
On the first image we can see that the empty value is "selected"
On the second image we can see that the empty value is not an option
On the third image we can see the selected non-empty element

[Android] Add empty options support for ChoiceSet

---

source/nodejs/adaptivecards/src/card-elements.ts

Fixes https://github.com/microsoft/AdaptiveCards/issues/3617#event-2808512127
ShowCard was always re-rendered, losing the values in the `<input>` elements. This fix reuses the previously rendered ShowCard if possible.
Verified manually in adaptivecards-visualizer

[TS] Fix collapsed ShowCard losing input values

---

source/nodejs/adaptivecards/src/card-elements.ts

Fixes https://github.com/microsoft/AdaptiveCards/issues/3523
When a `TextRun` in a `RichTextBlock` had an empty text property, its internal render code would output `null` (by design) but the RichTextBlock would fail to test for that and attempt to append null to its child collection, generating an uncaught exception that caused the card to fail to render.
Test payload:
```
{
"body": [
{
"text": "This text should be displayed"
},
{
"type": "RichTextBlock",
"inlines": [
{
"type": "TextRun"
}
]
}
],
"$schema": "http://adaptivecards.io/schemas/adaptive-card.json"
}
```
Verified manually in adaptivecards-designer-app as well as https://adaptivecardsci.z5.web.core.windows.net/pr/3645/designer

[TS] Fix RichTextBlock rendering bug

---

source/nodejs/adaptivecards-site/_config.yml

Updating the website's roadmap links to the new [roadmap tab in product board](https://portal.productboard.com/adaptivecards/1-adaptive-cards-features/tabs/5-roadmap)
Using the test website deployment

Updating adaptivecards.io homepage's roadmap links to the "roadmap" tab on productboard

---

source/nodejs/adaptivecards-designer/README.md
source/nodejs/adaptivecards-designer/src/constants.ts
source/nodejs/adaptivecards-site/themes/adaptivecards/layout/designer.ejs

Reverted the designer package default payload back to the original one (without templating)
Made the site load the templated default card so adaptivecards.io retains the current experience. I should have done it this way in the first place, whoops.

Designer pre-publish, minor changes

---

source/tools/hostConfig/json-to-scss/package-lock.json

Build server is reporting a failure in this file, but I'm not sure why. Seeing if this helps
##[warning]Could not parse Jtokens from C:\BA\7861\s\source\tools\hostConfig\json-to-scss\package-lock.json file.

for some reason this file is "unable to parse" in the build server

---

source/uwp/Renderer/idl/AdaptiveCards.Rendering.Uwp.idl
source/uwp/UWPUnitTests/RenderTests.cs
source/uwp/UWPUnitTests/RendererRegistration.cs

Fixes #3709 
Two issues here:
1) The renderer needs to run on the UI thread rather than the main test thread, so the test happens in a dispatcher. Unfortunately, exceptions thrown there cause the UWP test infrastructure to abort the test. Updated the test to catch the exception and throw it on the main test thread so it is reported properly as a test failure. Also updated other tests with the same pattern.
2) A bug in the update to modern idl caused WholeItemsPanel to lose it's inheritance from Panel. This broke the test function GetAllDescendants, because that function casts all elements in the tree as UIElement, and WholeItemsPanel no longer successfully cast. Added that inheritance back.
RendererRegistration tests now pass successfully.

[UWP] Fix RendererRegistration error handling and fix inheritance issue with WholeItemsPanel

---

source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizerTests/ADCIOSVisualizerTests.mm

Fixes #3444 
* added tests  parsing and rendering of all sample cards
* made sure all cards were being tested
* there are failures which were expected; verified that test indeed work
* result of parsing & rendering were all within the expectation.

added test to parse and render all sample cards

---

source/uwp/UWPTestLibrary/TestResultViewModel.cs
source/uwp/UWPUnitTests/UnitTest.cs

Fixes: #3719
Updated the unit tests that runs all files to not require image comparisons to match. Image comparison is not stable enough to run as an automated blocking test at this time, and this change decouples stabilizing the test app from getting a basic rendering pass of all files into CI.
A file will pass for the unit test if it 
1. Is expected to fail, and does
2. It is expected to succeed and does, and the expected round tripped json is unchanged
3. It is a new file, and renders successfully.
Unit test suite passes consistently

[UWP] Remove image comparison from unit tests

---

source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizerTests/ADCIOSVisualizerTests.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRView.mm

Fixes #3741 
action target build director needs a host config.
when user doesn't provide user host config, default host config is provided
the presence of default host config was ignored, and only checked for the presence of user host config.
added unit test, and verified before and after change, and the change performed as expected.

Fixed #3741

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/GenericImageLoaderAsync.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/action/ActionElementRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/ImageRenderer.java
source/android/mobile/src/main/java/io/adaptivecards/adaptivecardssample/CustomObjects/Media/CustomImageLoaderForButtons.java
source/android/mobile/src/main/java/io/adaptivecards/adaptivecardssample/MainActivityAdaptiveCardsSample.java
source/android/mobile/src/main/res/layout/content_main_activity_adaptive_cards_sample.xml

Fixes #3775 
Changes the accessibility of the styleBitmap method to be usable by anyone using a resource resolver to load images and style them accordingly to the context where the images are renderered. 
Custom rendered was added to the Sample Application. Picture below

[Android] Change styleBitmap accesibility in ImageLoaders to public

---

source/shared/cpp/AdaptiveCardsSharedModel/AdaptiveCardsSharedModelUnitTest/MarkDownUnitTest.cpp
source/shared/cpp/ObjectModel/MarkDownHtmlGenerator.cpp

Fixes #3776 
This PR fixes the crash reported by #3776. The crash happens while unwrapping ```<p>``` tags from the text. There was missing ```</p>``` tags. Fix was made to shared MarkDownParser code. The parser code returns immediately when it sees that a given token is marked as Head. This only happens to emphasis and strong emphasis tokens. If a string is a single emphasis (*) and strong emphasis (**), a token can be both head and tail, so returning from translation upon seeing the tag is marked head is a programming error. 
Added unit tests to cover those cases.
Inspected all codes to make sure that only emphasis and strong emphasis tokens exhibit this behavior.

Fixed Issue #3776, Crashing While Unwrapping Paragraph Tag

---

source/uwp/Renderer/lib/XamlHelpers.cpp

Fixes #3777 
The additional tab stop is caused by the custom TileControl which hosts the background image. Because this is not intended as an interactive control, set IsEnabled to false to remove the tab stop.
Manually verified additional tab stop is no longer present using [AdaptiveCard.BackgroundImage.FillMode.Cover.json](https://github.com/microsoft/AdaptiveCards/blob/master/samples/v1.2/Elements/AdaptiveCard.BackgroundImage.FillMode.Cover.json)

[UWP] Set background image tile control to IsEnabled false to avoid generating extraneous tab stops

---

source/uwp/Visualizer/DocumentView.xaml
source/uwp/Visualizer/GenericDocumentView.xaml
source/uwp/Visualizer/MainPage.xaml
source/uwp/Visualizer/ViewModel/GenericDocumentViewModel.cs

Fixes #3771 
Fixes #3772
Two fixes related to tab order in the UWP visualizer:
1. Tab order went json panel->rendered card->grid splitter, when json panel->grid splitter->rendered card would be more appropriate. Changed the order of those two elements in xaml to update this ordering.
2. The error panel was included in the tab order even though it is not interactive. Set IsEnabled to false to indicate to xaml that the error panel should not have a tab stop.
Manually confirmed tab order now behaves as expected in these cases.

[UWP][Visualizer Accessibility] Tab Order Fixes

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRActionSetRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRContentHoldingUIScrollView.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRContentHoldingUIScrollView.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/UtiliOS.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/UtiliOS.mm

Fixed ActionSet having extra height.
This is a back port from release/1.2 branch.
fixed #3784 
There was an extra view between base elements and actions causing the view's expansion.
Verified that extra view was removed.
Worked with the Teams mobile to confirm it.

ActionSet refactoring & Extra View Removal.

---

source/uwp/Renderer/lib/ElementTagContent.cpp
source/uwp/Renderer/lib/ElementTagContent.h
source/uwp/Renderer/lib/WholeItemsPanel.cpp
source/uwp/Renderer/lib/WholeItemsPanel.h
source/uwp/Renderer/lib/XamlHelpers.cpp

Fixes #3819
The WholeItemsPanel keeps track of which items have been marked as `"height":"stretch"` in order to render them properly. In order to do this, the code was stashing an identifier in the `AccessKey` property of the xaml elements (#1377). Unfortunately, that was causing access keys to show up in the UI when the user presses 'Alt'.
Updated the code to use the `Tag` property to handle this internal tracking, as that is a place for custom data that won't have a UI impact. Because we're already using the Tag property for a variety of purposes, added the `IsStretchable` property to the existing `ElementTagContent` type.
Confirmed that the card from bug #3819 no longer generates an access key. Verified existing VerticalStretch cards still render correctly.

[UWP][Accessability] Use element tag instead of access key for internal tracking

---

source/uwp/Visualizer/MainPage.xaml
source/uwp/Visualizer/MainPage.xaml.cs

Fixes #3827 
Fixes #3831 
Change the Hostconfig button from a toggleButton to a regular button as it doesn't behave as a toggle button.
The fix was applied to the Visualizer application and testing if the application presented the same behaviour but the narrator didn't.
The gif below shows the behaviour
As work was already being done with the HostConfig button, the middle panel accessibility was also fixed. Now it can be accessed through keyboard input as can be seen below:

[UWP][Accessibility] Change toggle button to regular button

---

source/uwp/Visualizer/TabView.xaml

Fixes #3832
Fixes #3834
Add name property for all close buttons in the visualizer app in the left panel. The ones next to the Card name
The visualizer app was executed and the elements were examined using the Accessibility insights application to see that the button now has the name property set.
This also fixes the issue where list items would not have a descriptive name. This is fixed as shown below

[UWP] Add name for close button

---

samples/v1.2/Tests/ChoiceSet.UnclippedText.json
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRChoiceSetViewDataSource.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRChoiceSetViewDataSource.mm

Fixes https://github.com/microsoft/AdaptiveCards/issues/3804
Fixes height calculation for text labels in choice sets which allows text not to be clipped any more. 
The fix was verified manually and the test json was added to the test folder, below the result can be seen:

[iOS] Fix clipped text in non-compact ChoiceSet

---

source/nodejs/adaptivecards-designer-app/src/app.ts
source/nodejs/adaptivecards-templating/src/adaptivecards-templating.ts
source/nodejs/adaptivecards-templating/src/expression-parser.ts
source/nodejs/adaptivecards-templating/src/shared.ts
source/nodejs/adaptivecards-templating/src/template-engine.ts

Fixes https://github.com/microsoft/AdaptiveCards/issues/3688
Currently, two things happen:
- When the `$when` clause fails to evaluate, an exception is thrown which causes the whole card to not render
- When the `$when` clause evaluates to a non-boolean value, it is considered to be `true`
With this PR, the behavior becomes:
- When the `$when` clause fails to evaluate, it is considered to be `false`
- When the `$when` clause evaluates to a non-boolean value, it is considered to be `false`
In turn this means that an invalid $when clause will now cause the element on which it is defined to be dropped, but the card will still render.
Currently, when an expression refers to a field that isn't defined (doesn't have a value) in the data context, it often evaluates to `undefined` and the string …

[Template] Don't drop card if $when fails to eval

---

custom.props
source/uwp/Renderer/lib/ElementTagContent.cpp
source/uwp/Renderer/lib/ElementTagContent.h
source/uwp/Renderer/lib/WholeItemsPanel.cpp
source/uwp/Renderer/lib/WholeItemsPanel.h
source/uwp/Renderer/lib/XamlBuilder.cpp

* [UWP][Accessibility] Use element tag instead of access key for internal tracking.
Fixes #3819 
Cherry-Pick fix for issue #3819 for 1.2.8 patch release
1. Local build succeeded where I was able to launch the corresponding UWP visualizer, use the card from the original issue and verify that pressing "Alt" wouldn't result in a '0' key showing up.

Cherry-Pick fix for issue #3819 for 1.2.8 patch release

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRInputNumberRenderer.mm

#3863 
Number pad keyboard for Input.Number lacked decimal point key.
Changed the number pad type to the one that has a decimal point
After the update, this is how the number pad will appear.

[iOS] updated numpad to have a decimal point

---

source/nodejs/adaptivecards-templating/docs/README.md
source/nodejs/adaptivecards-templating/docs/classes/binding.md
source/nodejs/adaptivecards-templating/docs/classes/evaluationcontext.md
source/nodejs/adaptivecards-templating/docs/classes/expressionparser.md
source/nodejs/adaptivecards-templating/docs/classes/globalsettings.md
source/nodejs/adaptivecards-templating/docs/classes/template.md
source/nodejs/adaptivecards-templating/package-lock.json
source/nodejs/adaptivecards-templating/package.json
source/nodejs/adaptivecards-templating/typedoc.json
source/nodejs/adaptivecards/package.json

As per the last docs PR, this one adds doc generation support and generated docs (as two commits) to the `adaptivecards-templating` project. Note that I have not opted to make this project-wide via lerna. This is because it looks like we need to reconcile our projects before hoisting our dependencies up.

[JS] Add docs and generation support to templating library

---

source/dotnet/Library/AdaptiveCards/AdaptiveCards.csproj

This is a workaround for a [regression](https://developercommunity.visualstudio.com/content/problem/954242/appx-packaging-project-fails-with-multi-targeted-l.html) in VS2019 16.5.0. A fix (one that was recommended in the report link) has been checked in, but won't ship for a while, so this workaround will have to do for now.
* Built clean locally
* Built clean in CI

[.NET] Stub out _CheckForGenerateAppxPackageOnBuild target

---

source/nodejs/adaptivecards/src/card-elements.ts

Currently all actions get rendered as `<button>` elements with role "button". When a button opens a link, as is the case for `Action.OpenUrl`, it should have the "link" role instead.
**Important**
Just a note on the weirdness of this PR. I used a new tool to create this PR, which converted the issue into a PR rather than creating a new PR. I won't use it again, but it's why this looks weird. 👍 
Simple fix to have `OpenUrlAction` objects set `role="link"`.
* Accessibility Insights
* F12 tools
* Tests (adding shortly)

[JS][Renderer][Accessibility] Action.OpenUrl rendered buttons should have the "link" aria role

---

.github/ISSUE_TEMPLATE/config.yml

Following along the lines of the [typescript repo](https://github.com/microsoft/TypeScript/issues/new/choose) adding a redirect-only question template via config.yml that redirects the community to StackOverflow for questions.
For now, allowing for blank issues as a catch-all but eventually goal is to only enable issues that fit our allowed templates for better project management/tracking.

Adding config.yml to enable Question template

---

source/nodejs/adaptivecards-aaf/src/core.ts
source/nodejs/adaptivecards-aaf/src/invoke-activity.ts

* Removed appId property
* Renamed autoRefresh property to refresh
* Removed userIds and displayCurrentCardWhileRefreshingProperty properties inside refresh property

Changes to accommodate Schema changes

---

samples/v1.2/Elements/RichTextBlock.json
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRRichTextBlockRenderer.mm

Fixed #3953 
1. Color attribute did not applied to the end of string.
2. Updated test payload to remove space at the end; the spacing at the end enabled false negative; the look of card hasn't changed since overall text is maintained.
1. Tested all RichTextBlock json for verification.

Fixed RichTextBlock's TextRun's Color Issue

---

source/dotnet/AdaptiveCards.Visualizer.Wpf.sln

**WPF Visualizer Prerelease pipeline** is used in publishing a WPF app. It uses AdaptiveCards.Visualizer.Wpf solution that is different from AdaptiveCards solution. it doesn't build properly ATM because it doesn't have the new Template Project.
Template project is added to build the app.
It's locally tested.

Updated WPF Visualizer Prerelease pipeline

---

source/nodejs/adaptivecards/src/__tests__/components/image.spec.ts
source/nodejs/adaptivecards/src/card-elements.ts

Fixes #2235
When a card author fails to supply alt text, we actually create an img element with the alt text set to `"undefined"` rather than not set the property in the first place.
1. New unit test
2. Local repro and inspection with F12 tools

[JS] Only assign img alt text if it's supplied

---

source/uwp/Renderer/AdaptiveCardRenderer.vcxproj

An update to VS2019's SDKs breaks builds in CI. This change fixes that.
* local build
* CI build

[UWP] Fix UWP builds in master

---

source/nodejs/adaptivecards/src/card-elements.ts

Fixes #4027
For accessibility purposes, we need to apply the `aria-current` attribute to the `<option/>` that's currently selected.
Also fixed a couple of minor typos while I was in there :)
* Manually verified properties in F12 tools
* Verified speech output for Narrator
* Verified speech output for NVDA

[JS] Paint aria-current attribute on selected ChoiceSet option

---

source/uwp/Renderer/AdaptiveCardRenderer.vcxproj

The prior fix for the latest UWP build break (f318ac3652b5b616dde0a5eb0dddb6d41d882674) assumed that our build agents all had the 10.0.19xxx.0 SDK installed. It appears that this isn't the case, which exposed a shortcoming of my fix (specifically that it assumed the presence of the new SDK). The fix is to peg our version at the 10.0.18xxx.0 SDK, which should be available on all agents, and to revert the custom command change from the prior checkin.
* local build
* PR build

[UWP] Better fix for UWP build breaks

---

source/nodejs/adaptivecards/src/card-elements.ts

Fixes #2240 
Any time a card element has an `Action.OpenUrl` `selectAction`, we should assign the `link` role.
* local build and inspection

[JS] Generate correct aria role depending on Action type

---

source/nodejs/adaptivecards/src/card-elements.ts
source/nodejs/adaptivecards/src/shared.ts

Fixes #2236 in `release/1.2`
Original commit 73e12713b0a3a0b1964ee187156ccb6efa07c63d
Original PR #4020
* Local build, testing, and verification with F12 tools

[JS] Make tabIndex on root card turnoffable (#4020)

---

source/uwp/Renderer/lib/XamlBuilder.cpp

Fixes #3950 in `release/1.2`
Original PR: #4046
Original commit: e7f8c6b675d416aceede32c3bb8446b87d7d9e91
Manual port of original change (no edits required). When a `TextRun` has a `selectAction`, use the action's `title` as the accessible name, if available.
* Local build and inspection with Accessibility Insights

[UWP] Port RichTextBlock selectAction accessibility name fix

---

source/nodejs/adaptivecards/docs/classes/openurlaction.md
source/nodejs/adaptivecards/src/card-elements.ts

Unifies fixes for #3914 and #2240 
Now that we have `getAriaRole()`, it removes the need for `OpenUrlAction` to override `Action.render()`.
* Local build, verified link role continues to get applied correctly

[JS] Reconcile Action.OpenUrl rendering with getAriaRole()

---

source/nodejs/ac-typed-schema/package-lock.json
source/nodejs/aclint/package-lock.json
source/nodejs/adaptivecards-controls/package-lock.json
source/nodejs/adaptivecards-designer-app/package-lock.json
source/nodejs/adaptivecards-designer/package-lock.json
source/nodejs/adaptivecards-site/package-lock.json
source/nodejs/adaptivecards-site/themes/adaptivecards/package-lock.json
source/nodejs/adaptivecards-templating/package-lock.json
source/nodejs/adaptivecards-visualizer/package-lock.json
source/nodejs/adaptivecards/src/card-elements.ts
source/nodejs/package-lock.json
source/nodejs/spec-generator/package-lock.json

VSO #23950960
We build factsets in JS using a `<table>`. However, this has semantic meaning for screenreaders, which causes factsets to be read awkwardly. The fix (as recommended) is to set `role="presentation"` on the `<table>` element. This does not cause the screenreader to skip the content (as the child elements have no `role` set), but does cause it to treat the content normally.
* Local build
* Local inspection
* Narrator

[JS] Prevent factsets from presenting as tables for accessibility

---

source/nodejs/adaptivecards-fabric/src/__tests__/Components/Inputs/InputChoiceSetFabric.test.tsx
source/nodejs/adaptivecards-fabric/src/__tests__/Components/Inputs/InputDateFabric.test.tsx
source/nodejs/adaptivecards-fabric/src/__tests__/Components/Inputs/InputTextFabric.test.tsx
source/nodejs/adaptivecards-fabric/src/__tests__/Components/Inputs/InputTimeFabric.test.tsx
source/nodejs/adaptivecards-fabric/src/__tests__/Components/Inputs/InputToggleFabric.test.tsx

I noticed that the `adaptivecards-fabric` tests were failing in Linux. The failures are due to path case sensitivity -- fix is easy.
* Ran tests :)

[JS] Fix adaptivecards-fabric tests on Linux

---

source/nodejs/adaptivecards-designer/src/dialog.ts
source/nodejs/adaptivecards-designer/src/open-sample-dialog.ts

VSO #24068357
The open samples dialog has multiple accessibility issues. The one noted in the bug is that keyboard focus doesn't go to the dialog when it is shown. Additional fixes:
* Dialog marked up to be accessible as a dialog
* Dialog is dismissable with ESC
* Clicks outside the dialog also close the dialog
* Cards are presented as listitems in a list
* local build
* narrator
* developer tools

[Designer] Accessibility updates for designer new sample dialog

---

samples/v1.2/Elements/Action.ToggleVisibility.json

VSO #24019922
Missing `altText` on sample images in `Action.ToggleVisibility` card. Also, align newline format with the rest of the repo.
* local build and browser dev tools

[Samples] Add altText to Action.ToggleVisibility card

---

source/nodejs/adaptivecards-site/themes/adaptivecards/layout/index.ejs
source/nodejs/adaptivecards-site/themes/adaptivecards/layout/sample.ejs
source/nodejs/adaptivecards-site/themes/adaptivecards/source/css/style.css

VSO #24112626
VSO #24113398
Two small changes:
* Change "Get Started" button role to `link` since it navigates the page
* Replace slider control on the "samples" page since it doesn't play nice with high contrast modes (invisible in HC White, and only partially visible in HC Black). Now we have a big checkbox instead:
(alt: screenshot of webpage updated to use a checkbox)
* local build and inspection with browser devtools

A couple of site updates for accessibility

---

source/nodejs/adaptivecards/docs/classes/action.md
source/nodejs/adaptivecards/docs/classes/httpaction.md
source/nodejs/adaptivecards/docs/classes/openurlaction.md
source/nodejs/adaptivecards/docs/classes/showcardaction.md
source/nodejs/adaptivecards/docs/classes/submitaction.md
source/nodejs/adaptivecards/docs/classes/togglevisibilityaction.md
source/nodejs/adaptivecards/src/card-elements.ts

Fixes VSO #23940376
Expandable showcard actions lack the `aria-expanded` attribute, which is helpful for screenreaders.
* local build and devtools testing

[JS] Add aria-expanded state to showcard action button

---

source/nodejs/adaptivecards-designer/src/card-designer.ts
source/nodejs/adaptivecards-site/themes/adaptivecards/source/js/script.js

Fixes VSO #23950535
Consumes fix for #2236  (PR: #4020) on our site (designer as well as various samples).
* local build, devtools, and narrator

[Site] Opt out of tabIndex generation in samples and designer

---

source/nodejs/adaptivecards-controls/src/dropdown.ts
source/nodejs/adaptivecards-controls/src/inputwithpopup.ts
source/nodejs/adaptivecards-controls/src/popupmenu.ts
source/nodejs/adaptivecards-designer/src/toolbar.ts

Fixes VSO #24095594
Fixes VSO #24113643
Fixes VSO #24081494
A few fixes:
* The "Preview Mode" toolbar button now gets the `aria-pressed` property set appropriately set
* The toolbar dropdown menus are now marked up correctly for accessibility
* Keyboard access to peer comboboxes now works
* local build, narrator, dev tools, keyboard

[Designer] Add aria attributes to dropdown controls

---

source/nodejs/adaptivecards-site/themes/adaptivecards/source/js/script.js

Fixes #4086
Fixes VSO #23940370
The problem here shows up when the window height and scroll position are such that:
* the footer isn't visible
* the window is too short to display the entire sidebar
In this scenario, the user isn't able to access the bottom elements in the sidebar without scrolling to the bottom of the current page, which is kind of a pain. This is somewhat related to the VSO issue I mention above where the tester was `shift-tab`ing from the `Copy` button, which placed focus on the last item in the sidebar. However, since the item is stuck offscreen due to css, there's no visual indication of where the focus has gone. The actual bug is just that we weren't accounting for the case where `hiddenAfter > footerHeight` in our sidebar calculations, leading to the sidebar's …

[Site] Fix sticky sidebar math

---

source/nodejs/adaptivecards-site/themes/adaptivecards/layout/archive.ejs
source/nodejs/adaptivecards-site/themes/adaptivecards/source/css/style.css

Fixes VSO #24095883
Blog post subtitles were being emitted as links, which is unnecessary (and adds extra tabstops for screenreader users).
* local build and test

[Site] Remove superfluous link on article subtitles

---

source/nodejs/adaptivecards-controls/src/constants.ts
source/nodejs/adaptivecards-designer/src/base-tree-item.ts
source/nodejs/adaptivecards-designer/src/tool-box.ts
source/nodejs/adaptivecards-designer/src/tree-view.ts

Partially fixes VSO #24096574
A few things missing:
* Hide/show controls were not keyboard focusable/interactable
* Hide/show controls weren't marked up as `aria-expanded`
* Hide/show control aria labels didn't indicate what toolbox was being expanded/collapsed when invoked
* local build, keyboard, narrator, and devtools

[Designer] Improve show/hide accessibility and labels

---

source/nodejs/adaptivecards-site/themes/adaptivecards/layout/designer.ejs

Fixes VSO #24081771
Per advice in VSO item, removing the visualizer link from the Designer. The visualizer itself will remain up, but should have some work done per conversation (see #4180).
* local build and testing

[Site] Remove visualizer link in Designer

---

samples/v1.1/Scenarios/ProductVideo.json
source/nodejs/adaptivecards/src/card-elements.ts

Fixes VSO #24110397
* Missing `altText` in ProductVideo.json (fixed up tabs while I was there)
* Play button was missing `tabIndex=0`, so it wasn't possible to trigger media playback using only keyboard.
* local build, narrator, keyboard, devtools

[JS] Fix aria accessibility for media element

---

source/nodejs/adaptivecards/src/card-elements.ts

Fixes VSO #24019554
Before this change, each `Action` in an `ActionSet` was considered in isolation by accessibility. There was no way of knowing how many actions were on card without tabbing through all of them. With this change, screenreaders can surface count information to the user (Narrator does this).

[JS] Express action sets as collections

---

.github/workflows/pic2card_build.yml

Helps to avoid unnecessary builds, build happens only when some changes happens under `source/pic2card`

[pic2card] Path filter for github actions

---

source/nodejs/ac-typed-schema/src/markdown/generate-markdown.ts

Fixes VSO #24094341
Elements introduced after 1.0 have that fact called out on the schema explorer page. However, it's done via a heading element, which is incorrect from an accessibility standpoint:
Fix is to emit it in bold instead.
* local build, devtools

[Site] Fix markdown for version label on properties

---

source/shared/cpp/AdaptiveCardsSharedModel/AdaptiveCardsSharedModelUnitTest/MarkDownUnitTest.cpp
source/shared/cpp/ObjectModel/MarkDownBlockParser.cpp
source/shared/cpp/ObjectModel/MarkDownBlockParser.h

Fixes #4117 
Added '*' as list marker to MarkDown parser
1. New unit tests that were added
2. Existing unit tests were performed.

added '*' as a list marker

---

source/shared/cpp/AdaptiveCardsSharedModel/AdaptiveCardsSharedModelUnitTest/MarkDownUnitTest.cpp
source/shared/cpp/ObjectModel/MarkDownBlockParser.cpp
source/shared/cpp/ObjectModel/MarkDownBlockParser.h

Fixed #4117 
added '+' as a markdown list marker
1. Added new unit tests
2. Ran all existing unit tests.

added '+' as a list marker for markdown

---

source/shared/cpp/ObjectModel/AdaptiveBase64Util.cpp

Resolves #4192 
Replaces the base64 decode map with an array to improve performance.
There was a bug with the previous code which copied the decode map every time a character lookup was performed. Updating the code to not copy the map improves performance significantly - however this code goes further and replaces the map entirely with an array.
The change was manually verified by testing a number of cards that include multiple data URIs. Rendering times for the cards typically decreased from ~30ms to ~8ms.

Replace base64 decode map with an array to improve performance

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRImageRenderer.mm

Fixed #4105 
When image is not available, Image renderer does not add the empty view to the super view. This will lead to an exception when two consecutive items with stretch are present because for those two items, layout constraint is set, and both items are needed to have a common ancestor.
1. JSON sample card was ran. this card was not added to our sample cards since this scenario is only relevant to iOS.

Fixed the crash when image is not available

---

source/nodejs/adaptivecards-designer/src/shared.ts
source/nodejs/adaptivecards/src/card-elements.ts
source/nodejs/adaptivecards/src/serialization.ts

Fixes https://github.com/microsoft/AdaptiveCards/issues/3051
Fixes https://github.com/microsoft/AdaptiveCards/issues/3218
Fixes https://github.com/microsoft/AdaptiveCards/issues/3221
Adds the `underline` property to TextRun
Test payload:
```json
{
"body": [
{
"type": "RichTextBlock",
"inlines": [
{
"type": "TextRun",
"text": "Now you can have "
},
{
"type": "TextRun",
"text": "underlined text",
"underline": true
},
{
"type": "TextRun",
"text": " within a RichTextBLock"
}
]
}
]
}
```
As rendered:

[TS][Renderer] Add TextRun.underline

---

source/nodejs/adaptivecards-designer/src/adaptivecards-designer.css

Fixes VSO #24094745
The blue color we use for icons (and the error background) is a bit too light to contrast well with a white background (or white text on the blue color's background in the case of the error banner). Fix is to use a darker blue in CSS.
* local build, devtools color tooling

[Designer] Change icon and error background colors for contrast

---

source/shared/cpp/ObjectModel/BaseActionElement.h
source/shared/cpp/ObjectModel/BaseCardElement.h
source/shared/cpp/ObjectModel/BaseElement.cpp
source/shared/cpp/ObjectModel/BaseElement.h
source/shared/cpp/ObjectModel/BaseInputElement.h
source/shared/cpp/ObjectModel/Inline.cpp
source/shared/cpp/ObjectModel/Inline.h
source/shared/cpp/ObjectModel/ParseUtil.cpp
source/shared/cpp/ObjectModel/ParseUtil.h
source/shared/cpp/ObjectModel/TextRun.h
source/uwp/Renderer/lib/Util.cpp

Resolves #4217 
The ParseUtil::GetBackgroundImage throws and catches exception during 'good path' execution. This is confusing for new users of the library and goes against good programming practices. This PR replaces the try-catch with an if-else statement. There are also a number of other small fixes included in this PR:
- Ensure all PopulateKnownPropertiesSet functions are private, not protected.
- Update BaseElement::GetAdditionalProperties and Inline::GetAdditionalProperties to return a const reference instead of a value type.
- Update GetEnumValue function to use a template type parameter rather than std::function.
- Avoid use of unnecessary local variable in JsonObjectToJsonCpp for performance reasons.
Ran the existing unit tests and manually tested various cards with background …

Remove try-catch from ParseUtil::GetBackgroundImage and other small fixes

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/ChoiceSetInputRenderer.java

Fixes #4016 
Consistent spacing behavior for both wrapped and non-wrapped choiceset's.
Manual verification, screenshot below for payload attached in the linked issue.

[Cherry Pick][Android] Fix ChoiceSet wrapping

---

source/shared/cpp/ObjectModel/AdaptiveBase64Util.cpp

Fixes #4192 
Original PR: #4193

[UWP] Cherry pick base64 decode performance improvements

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRTextBlockRenderer.mm

Fixes #3702 for iOS. 
Empty string is treated as invalid, and TextBlock won't get rendered. 
1. Existing relevant unit/regression tests that you ran
2. Test Payload is tested.

Updated text block to treat empty text string as invalid

---

source/uwp/Renderer/lib/ActionHelpers.cpp
specs/elements/AdaptiveCard.md
specs/elements/Input.Text.md

Fixes #4241 
Adds a call to LinkSubmitActionToCard during inline action creation. This was an oversight as inline actions are rendered differently than regular actions
The "Input.Text.InlineAction.Label.json" was used for rendering a card that would have the behaviour to test. As can be seen in the gif below, the inputs are now validating and, though out a little bit out of the screen, a pop up dialog shows up with the retrieved inputs

[UWP] Fix inline actions not getting inputs

---

source/community/reactnative/src/components/inputs/choice-set/choice-set-input.js
source/community/reactnative/src/components/inputs/input-label.js
source/community/reactnative/src/components/inputs/input.js
source/community/reactnative/src/components/inputs/picker-input.js
source/community/reactnative/src/components/inputs/toggle-input.js
source/community/reactnative/src/models/input-model.js
source/community/reactnative/src/utils/constants.js
source/community/reactnative/src/visualizer/payloads/payloads/Input.Label.json
source/community/reactnative/src/visualizer/payloads/payloads/index.js

Handled `label` property for all the Input elements. As per the schema `label` can be either **`string, TextBlock, RichTextBlock`**, and will be inside the input root-level object.
`{
"type": "Input.Number",
"id": "Phone",
"label": {
"spacing": "none",
"color" : "warning",
"text": "Phone",
"wrap": true
}
},`

Reactnative: Label support for all the Input elements.

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/BaseActionElementRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/action/ActionElementRenderer.java
source/android/adaptivecards/src/main/res/values/attrs.xml
source/android/mobile/src/main/res/drawable/show_card_arrow.xml
source/android/mobile/src/main/res/values-v21/styles.xml
source/android/mobile/src/main/res/values/styles.xml

Fixes #4167 
Allow apps to apply native styles to any Action.ShowCard by assigning a style definition to the app theme's `R.attr.adaptiveShowCardAction` attribute. Example usage (e.g. add a chevron that visually indicates a closed or open ShowCard) added to visualizer app's `styles.xml` and `v21/styles.xml`.
Manual vertification - uncommented the example usage in visualizer `styles`. Checked compatibility w/ existing styling support (e.g. positive action, as shown below).

[Android] Support native styling for Action.ShowCard

---

source/uwp/Renderer/lib/AdaptiveTextBlockRenderer.cpp

UWP change for #3702
Updated the TextBlock renderer return early rather than constructing an empty Xaml element that takes up space in the card.
Confirmed expected behavior in the visualizer using [EmptyTextBlock.json](https://github.com/microsoft/AdaptiveCards/blob/main/samples/v1.2/Tests/EmptyTextBlock.json)

[UWP] Don't render TextBlocks with empty strings

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRTextView.mm

With iOS 13, Apple introduced a dark theme.
Changed Textview to update its text color according to the theme
Fixed #4216
How you verified the fix, including one or all of the following:  
1. regression tests were run.
2. tested and visually confirmed that the change is good by changing system theme to dark mode, and ran the repro step.

Changed Textview to Update Its Text Color Correctly According to Theme

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRInputRenderer.mm

Fixed #4215 
The current keyboard for the text field doesn't support other languages.
Changed keyboard type to default from alphanumeric
1. Ran the repro steps & verified that the change is good.

changed keyboard type to default from alphanumeric to support multi language

---

custom.props

Updating the package version number for AdaptiveCards renderer ahead of v1.2.10 release.

Update Package Version to 1.2.10

---

source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizerTests/ADCIOSVisualizerTests.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards.xcodeproj/project.pbxproj
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACFramework.h

None
ACRToggleInputView.h is a new header that owns ACRToggleInputView.xib. This change adds the header to the public header list, so it can be custom rendered when XIB is not used.
1. New unit test is added to check that the new view is available for customization.
2. Unit tests are run

added ACRToggleInputView.h to public header list

---

source/uwp/Renderer/AdaptiveCardRenderer.vcxproj
source/uwp/Renderer/AdaptiveCardRenderer.vcxproj.filters
source/uwp/Renderer/idl/AdaptiveCards.Rendering.Uwp.idl
source/uwp/Renderer/lib/pch.h
source/uwp/Renderer/packages.config

Needed in order to continue using C++/WinRT on more recent Windows SDKs.
Changes required:
* Add `Microsoft.Windows.CppWinRT` nuget package
* Remove manual calls to `mdmerge` (this is handled by cppwinrt now)
* Add missing `default_interface` directives to various renderer runtimeclasses
Some decent benefits here (apart from having access to newer cppwinrt functionality):
* When we target a new Windows SDK, we will no longer have to maintain our custom `mdmerge` build step
* Since `mdmerge` is handled automatigically, build/debug is more seamless -- the custom step is no longer run every single time
* tested converting a small piece of code over to cppwinrt style then building/testing

[UWP] Convert to nuget version of cppwinrt

---

source/dotnet/Library/AdaptiveCards.Rendering.Wpf/AdaptiveRenderContext.cs

Fixes #4270 
The issue was that trying to retrieve a value with a key that didn't exist in the dictionary threw an exception, that's why the app crashed
1. The fix was verified manually as can be seen in the gif below

[WPF] Fix cards with no inputs crashing when submitting

---

source/dotnet/Samples/WPFVisualizer/MainWindow.xaml

VSO #24112801
We left off the little bit of glue needed to associate the "Use Xceed Renderers" checkbox with the label. This fixes that :)
* local build and Accessibility Insights

[NET] Properly label xceed checkbox

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/AdaptiveCardRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/action/ActionElementRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/TextInputRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/ImageRenderer.java

Untracked issue
The issue was that we were using the method "execute" when running the download image async tasks, quoting the [official documentation](https://developer.android.com/reference/android/os/AsyncTask#execute(Params...)), this api has suffered some changes across different android api versions
> Note: this function schedules the task on a queue for a single background thread or pool of threads depending on the platform version. When first introduced, AsyncTasks were executed serially on a single background thread. Starting with Build.VERSION_CODES.DONUT, this was changed to a pool of threads allowing multiple tasks to operate in parallel. Starting Build.VERSION_CODES.HONEYCOMB, tasks are back to being executed on a single thread to avoid common application errors caused by …

[Android] Concurrent image load

---

source/nodejs/adaptivecards-designer-app/src/app.ts
source/nodejs/adaptivecards-designer/src/designer-peers.ts

Fixes https://github.com/microsoft/AdaptiveCards/issues/4348
This change makes it possible to dynamically add or remove properties to/from the designer's property sheet. For instance, here's how to remove the "Maximum lines" property for **TextBlock** elements:
```typescript
ACDesigner.DesignerPeer.onPopulatePropertySheet = (sender: ACDesigner.DesignerPeer, propertySheet: ACDesigner.PropertySheet) => {
if (sender instanceof ACDesigner.TextBlockPeer) {
propertySheet.remove(ACDesigner.TextBlockPeer.maxLinesProperty);
}
}
```

[Designer] Allow add/remove properties to/from property sheet

---

source/nodejs/adaptivecards-designer/src/data.ts

Fixes https://github.com/microsoft/AdaptiveCards/issues/4375
Currently, the designer's field picker always generated bindings using the "dot" syntax (e.g. `${myObj.a.b}`). But JSON property names can be any string. When non alpha-numerical characters are used in property names, AEL (just like JS) requires the use of the indexer syntax (e.g. `${myObj["a.b"]}`) and that's what this PR implements.
Test data payload:
```json
{
"fields": {
"System.AreaPath": "MyAgilePrj2",
"System.TeamProject": "MyAgilePrj2"
}
```
In a simple card with just a **TextBlock**, binding the text property to "System.AreaPath" should result in this:
```json
{
"version": "1.2", …
```

Generate indexer for properties with special chars

---

samples/v1.0/Scenarios/WeatherLarge.json
samples/v1.2/Scenarios/ExpenseReport.json

Fixes VSO #23713559
Fixes VSO #23703249
A couple of card sample updates:
* WeatherLarge.json was called out for bad contrast
* Switched to lighter background
* Removed `"isSubtle": true` on multiple elements
* Move High/Low temps to use `FactSet`
|Before|After|
|--|--|
|![image](https://user-images.githubusercontent.com/16614499/87587861-890e5280-c697-11ea-86e6-718e5324121b.png)|![image](https://user-images.githubusercontent.com/16614499/87587893-99bec880-c697-11ea-823d-81f030e92160.png)
* ExpenseReport.json was reported for an odd tabbing order (specifically the `ER-13052` link under `Trip to UAE` precedes the `Export as PDF` button in the tab order)
* Moved `ER-13052` link outside of the columnset
|Before|After|
|--|--|
|![image](https://user-images.githubusercontent.com/16614499/8758812 …

[Samples] Update ExpenseReport and WeatherLarge samples

---

source/dotnet/Library/AdaptiveCards.Rendering.Wpf.Xceed/XceedNumberInput.cs

Fixes #4276 
The issue was that we were using the built-in Minimum and Maximum validation that the control provided, that made the control behavior to remove any "extra" characters whenever the input was greater or smaller than the min/max values and the control lost focus. This made the user experience being odd as an user could have inputted an out of bounds number, the control would have "fixed" the input clipping it to be in bounds and then successfully submitted the issue with a value the user didn't intended to use.
The fix was verified manually by checking that the min/max validation was actually triggered on submit

Remove control validation

---

source/nodejs/adaptivecards/src/card-elements.ts
source/nodejs/adaptivecards/src/enums.ts

Fixes https://github.com/microsoft/AdaptiveCards/issues/4389
Renderer now emits a warning for required inputs that do not have a label. The warning is displayed in the designer.

Emit warning for required inputs without label

---

source/uwp/Renderer/lib/InputValue.cpp

Fixes #4421
Updated number validation logic to ensure value is a number even if min and max are not set
Validated manually in visualizer that error message is now shown for non number values.

[UWP] Fix Input.Number validation logic to ensure value is a number

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/AdaptiveWarning.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/registration/CardRendererRegistration.java
source/shared/cpp/ObjectModel/Enums.h
source/uwp/Renderer/idl/AdaptiveCards.Rendering.Uwp.idl
source/uwp/Renderer/lib/XamlHelpers.cpp

Fixes #4385
Fixes #4386
Adds a warning when an input element is required but no label was assigned so the required hint is not rendered which would provide a confusing story for card users.

[UWP][Android] Add warning for empty labels

---

source/dotnet/Library/AdaptiveCards.Rendering.Wpf/AdaptiveContainerRenderer.cs
source/dotnet/Library/AdaptiveCards/AdaptiveWarning.cs

Fixes #4388
Adds a warning when an input element is required but no label was assigned so the required hint is not rendered which would provide a confusing story for card users.

[WPF] Add warning for empty labels

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/TextInputRenderer.java

Fixes #4438
As with other platforms, inline submit actions in Android are rendered differently to regular actions so we have to manually register the inline action to the rendered card so it knows in what card it's located so it can retrieve inputs.
The fix was verified manually as can be seen below

[Android] Fix submit inline actions to retrieve inputs

---

source/uwp/Renderer/lib/CustomActionWrapper.cpp

While working on something unrelated, I noticed that some of the UWP unit tests were failing. This is the root cause (the thrown exception bubbled all the way up to the unit test, causing a failure.
* local build and tests

[UWP] Fix CustomActionWrapper's title handling

---

samples/v1.3/Tests/Input.Text.Label.Stretch.json
samples/v1.3/Tests/StretchForm.json
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/TextBlockRenderer.java

Fixes #4433 
Changes the TextBlock sizing to avoid them taking all the space due to setting the height to match parent
The fix was verified by testing manually the card as well as adding it to the cards folder for v1.3
| Before | After |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/35784165/87996342-b5b2d780-caa6-11ea-873d-f2ee2f2be196.png) | ![image](https://user-images.githubusercontent.com/35784165/87996373-d418d300-caa6-11ea-93c9-99157896d571.png) |

[Android] Fix stretch textblock claiming all visible space

---

source/dotnet/Library/AdaptiveCards.Rendering.Wpf/AdaptiveContainerRenderer.cs
source/dotnet/Library/AdaptiveCards/Rendering/LabelConfig.cs
source/dotnet/Library/AdaptiveCards/docs/AdaptiveCards.md
source/dotnet/Samples/AdaptiveCards.Sample.ImageRender/AdaptiveCards.Sample.ImageRender.csproj
source/dotnet/Samples/AdaptiveCards.Sample.ImageRender/Properties/launchSettings.json

Not being tracked (CI failure in .NET)
1. Updating the serialization behavior for the newly introduced LabelConfig.InputSpacing property to ignore default values from being written out while serializing to allow the current HTML renderer that doesn't yet support Labels to continue to work.
2. In AdaptiveContainerRenderer, fallback to working with the earlier elementForAccessibility element for inputs with null values _(appears at least the v1.0 samples fell into this category)._
3. Fixing a typo in the XML comments for the API doc
4. Including the regenerated API doc 
1. Ran RunAllTests.ps1 with defaults (samples\v1.0\scenarios) 
2. Manually ran the ImageRenderer sample for WPF, the WPF visualizer as well as the HTML Test suite, with the problem scenario files and verified they now …

Fixing .NET CI tests for feature/inputEvolution

---

source/nodejs/adaptivecards-designer-app/dist/containers/bf-image-container.css
source/nodejs/adaptivecards-designer-app/dist/containers/cortana-container.css
source/nodejs/adaptivecards-designer-app/dist/containers/outlook-container.css
source/nodejs/adaptivecards-designer-app/dist/containers/skype-container.css
source/nodejs/adaptivecards-designer-app/dist/containers/teams-container-dark.css
source/nodejs/adaptivecards-designer-app/dist/containers/teams-container-light.css
source/nodejs/adaptivecards-designer-app/dist/containers/toast-container.css
source/nodejs/adaptivecards-designer-app/dist/containers/webchat-container.css
source/nodejs/adaptivecards-designer/src/containers/bf-image/bf-image-container.css
source/nodejs/adaptivecards-designer/src/containers/cortana-classic/cortana-container.css
source/nodejs/adaptivecards-designer/src/containers/cortana/cortana-container-dark.css
source/nodejs/adaptivecards-designer/src/containers/cortana/cortana-container-light.css
source/nodejs/adaptivecards-designer/src/containers/default/adaptivecards-defaulthost.css
source/nodejs/adaptivecards-designer/src/containers/notifications/toast-container.css
source/nodejs/adaptivecards-designer/src/containers/outlook/outlook-container.css
source/nodejs/adaptivecards-designer/src/containers/skype/skype-container.css
source/nodejs/adaptivecards-designer/src/containers/teams/teams-container-dark.css
source/nodejs/adaptivecards-designer/src/containers/teams/teams-container-light.css
source/nodejs/adaptivecards-designer/src/containers/webchat/webchat-container.css
source/nodejs/adaptivecards/src/card-elements.ts
source/nodejs/adaptivecards/src/enums.ts

Fixes https://github.com/microsoft/AdaptiveCards/issues/4362
A red rectangle is now displayed around Input.Toggle and Input.ChoiceSet (in multiselect and expanded modes) when failing validation.
Test card:
```json
{
"body": [
{
"type": "Input.Toggle",
"title": "New Input.Toggle",
"id": "a",
"isRequired": true,
"errorMessage": "Invalid",
"label": "Toggle input"
},
{
"choices": [
{
"title": "Choice 1",
"value": "Choice 1"
},
{
"title": "Choice 2",
"value": "Choice 2"
}
],
"placeholder": "Placeholder text",
"isMultiSelect": true,
"id": "b",
"label": "Input.ChoiceSet w/multiselect",
"isRequired": true, …
```

Show validation error rect on Toggle and ChoiceSet

---

source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer/ViewController.m
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards.xcodeproj/project.pbxproj

Fixed #4464 
Action.Submit's data value was not displayed in the app.
Verified the test cards that they all work.

updated sample app to handle submit action better

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRInputLabelView.mm

Fixed #4387 
**NOTE**: For multiple issues resolved by this PR use the corresponding keywords **every time** in a comma-delimited list per the reference
page above.
Added warning as prescribed by #4387
Tested with relevant cards

added warnings to missing label with required input

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACOBaseActionElement.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACOBaseCardElement.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRChoiceSetCellChecked.xib
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRChoiceSetCellCompactChecked.xib
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRChoiceSetCellCompactUnchecked.xib
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRChoiceSetCellUnchecked.xib
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRChoiceSetViewDataSource.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRCustomRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRInputLabelView.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRInputRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRInputTableView.xib
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRTextInputHandler.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRTextInputHandler.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/UtiliOS.mm
source/shared/cpp/ObjectModel/MarkDownBlockParser.cpp

Fixed #4465 
Text in the input handler had a weak reference to the text propertyUITextField. But this leads to problem since the text field has a copy property set.
Verified with relevant cards.

fixed weak reference to copy property

---

source/pic2card/mystique/arrange_card.py
source/pic2card/mystique/config.py
source/pic2card/mystique/extract_properties.py
source/pic2card/mystique/group_design_objects.py
source/pic2card/mystique/predict_card.py

* Noise objects cleanup logic is changed to IOU metric
- IOU threshold = 0.5 [ therefore any for intersecting objects with IOU > 0.5, the smaller object is removed ]
- A workaround is done for the action-set and textbox overlapping - [ If there's a overlapping between a textbox and an action
set, irrespective of the IOU , the textbox object is removed by default ]
* Horizontal alignment property is added for the column-sets and it's columns.

Cleanup Pipeline logic changes and alignment property for the columnset objects.

---

source/uwp/Renderer/lib/XamlBuilder.cpp

Fixes #4489
Simple issue -- rendering certain cards would NULL AV in `XamlBuilder::WrapInTouchTarget()`. Analysis is in #4489, but suffice it to say that this is one of the easy NULL AV fixes. We just need a `nullptr` check and a reasonable default.
* local build, debug, and test payload verification

[UWP] Fix null AV when rendering a media element

---

source/dotnet/Library/AdaptiveCards/Rendering/AdaptiveRenderArgs.cs

Fixes #4515
Fixes #4514
Due to some unexpected circumstance a line of  code was not ported into main, the line cloned the parent card Id which allowed containers, columns and child cards to know the parent card where they were located
The fix was verified manually using the Wizard card

[WPF][InputEvolution] Copy ParentCardId when a RenderArgs object is cloned

---

samples/v1.2/Tests/ImageSizing.json
source/android/adaptivecards/build.gradle
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/ImageRenderer.java

Fixes #4518 
This reverts commit 805c51e0d28fc2ca8ff49ae311e0f9e85bea6f7d.
Up to this point the media element still doesn't work, going back I was able to revert the break by going to commit 120219157cc913cfde7a7cf35ff87e9405c30020 for ImageRenderer
TBD

Revert "[Android] Use ConstraintLayout for Image sizing (#4461)"

---

samples/v1.2/Tests/ImageSizing.json
source/android/adaptivecards/build.gradle
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/ImageRenderer.java

* Revert "[Android] Use ConstraintLayout for Image sizing (#4461)"
This reverts commit 805c51e0d28fc2ca8ff49ae311e0f9e85bea6f7d.
* Make media work again
* Reset imageview gravity
Fixes #4518

[CherryPick] Revert "[Android] Use ConstraintLayout for Image sizing (#4461)" (#4520)

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/NumberInputRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/inputhandler/NumberInputHandler.java

Fixes #4522 
This fix changes the comparisson behaviours to match the new use of nullable properties for value, min and max in Input.Number. Now there are null checks instead of comparissons against Integer.MIN_VALUE or Integer.MAX_VALUE constants.
The fix was verified manually and the results can be seen below:
Value set, Min/Max null/unset
Value null/unset

[Android][InputEvolution] Fix number input default behaviour

---

source/pic2card/mystique/config.py
source/pic2card/mystique/models/pth/detr_cpp/CMakeLists.txt
source/pic2card/mystique/models/pth/detr_cpp/README.md
source/pic2card/mystique/models/pth/detr_cpp/detr.cpp
source/pic2card/mystique/models/pth/detr_cpp/detr.hpp
source/pic2card/mystique/models/pth/detr_cpp/detr_infer.cpp
source/pic2card/mystique/models/pth/detr_cpp/setup.py
source/pic2card/mystique/models/pth/detr_cpp/tests.py
source/pic2card/mystique/obj_detect/__init__.py
source/pic2card/mystique/obj_detect/detr_cpp_objects.py

Detr cpp binding for python, it does the actual inference at cpp side using the torchscript trace file.
We are seeing more than  3x relative speed improvement on the model inference side.
Use this inference method by passing the environment variable to enable this inference method with pic2card pipeline.
```bash
$ ACTIVE_MODEL_NAME=pth_detr_cpp python -m app.main
```
**NOTE**: This PR doesn't include options for the production packaging like docker and all.
**Commits:-**
* creating python binding using pybind11
* Numpy to cv::Mat conversion via pybind11
* opencv cv::Mat to numpy ndarray type conversion.
* Testcase to validate the detr library
* cpp detr binding tested.
It doesn't require python torch library, instead it will be dynamically
linked to the libtorch library.
* CMakeLists …

[pic2card] Detr cpp binding for model inference

---

source/nodejs/adaptivecards-designer/src/open-sample-dialog.ts

Fixes VSO #24068357
I previously fixed a bunch of accessibility issues around the "New card" dialog, but missed setting keyboard focus on the first card in the catalog.
* local build/validation

[Designer] Set focus on first card in card catalog when it loads

---

source/nodejs/adaptivecards-designer/src/card-designer-surface.ts
source/nodejs/adaptivecards-designer/src/card-designer.ts
source/nodejs/adaptivecards/package-lock.json
source/nodejs/adaptivecards/src/card-elements.ts
source/nodejs/adaptivecards/src/serialization.ts
source/nodejs/package-lock.json

Fixes https://github.com/microsoft/AdaptiveCards/issues/4579
Fixes https://github.com/microsoft/AdaptiveCards/issues/4563
- Designer
- "Copy Card JSON" button now labeled "Copy card payload" and now has a tooltip describing what it does
- "Copy card payload" now copies the bound card and not just the template. To copy the template payload, select all in the Card Payload Editor and hit CTRL+C
- Renderer
- No more warning when `Image.height` is set to "auto" or "stretch"

[Designer] Copy bound card

---

source/nodejs/adaptivecards-site/themes/adaptivecards/layout/designer.ejs

Removed the somewhat ugly "This card uses Templating" callout, now that it's out of Preview and we've got a "Templating docs" button on the toolbar
- Tested website

Update the default card payload on the Designer

---

source/pic2card/mystique/arrange_card.py
source/pic2card/mystique/config.py
source/pic2card/mystique/debug.py
source/pic2card/mystique/extract_properties.py
source/pic2card/mystique/group_design_objects.py

- **Reduced the number of thresholds** used for column-set and columns grouping.
- **Used horizontal and vertical inclusive logic** to group the objects into a column-set or column.
- **Changes in noise removal** : along with the IOU based removal , the smaller objects [ in overlapping scenarios] which covers more than 50% of the intersection area will also be removed.
- Changed the columns and column-set alignment logic of **doing max of count of the alignments** to **choose from a** **predefined order - Left, Center, Right** in cases where the **alignments of the objects are unique**.
- for example:  if a column as 2 elements with ["Right", "Left"] as alignments, on doing max of count will pick different alignment each time, instead changed the logic  to choose in the predefined order …

[pic2card] Stabilizing columns grouping

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRShowCardTarget.mm

Fixed #4548 for iOS
Updates selected state for Buttons. Followed the logic of showing/hiding cards when the show card button is pressed.
1. Existing relevant unit/regression tests that you ran
2. ShowCardStyle.json was ran and verified the functionality.

resets selected state of button

---

source/nodejs/adaptivecards-designer/src/designer-peers.ts
source/nodejs/adaptivecards-templating/src/template-engine.ts
source/nodejs/adaptivecards/src/card-elements.ts

- Fixes https://github.com/microsoft/AdaptiveCards/issues/4620
- Fixes https://github.com/microsoft/AdaptiveCards/issues/4595
- Fixes https://github.com/microsoft/AdaptiveCards/issues/4692
- Fixes https://github.com/microsoft/AdaptiveCards/issues/4699
- `toJSON` now serializes to the version specified at the card level unless an explicit SerializationContext is specified
- The `$when` property isn't emitted anymore in an expanded template
- The `selectAction` property is now tied to schema version  1.1 and later (instead of 1.0)
- `selectAction.title` is now used as a tooltip

Templating and renderer fixes

---

samples/Templates/Scenarios/ExpenseReport.data.json
samples/Templates/Scenarios/FoodOrderWithValidation.template.json
samples/Templates/Scenarios/Inputs.template.json
samples/Templates/Scenarios/Restaurant.template.json
samples/v1.0/Scenarios/ActivityUpdate.json
samples/v1.0/Scenarios/FlightItinerary.json
samples/v1.0/Scenarios/FlightUpdate.json
samples/v1.0/Scenarios/Restaurant.json
samples/v1.0/Scenarios/SportingEvent.json
samples/v1.0/Scenarios/StockUpdate.json
samples/v1.0/Scenarios/WeatherCompact.json
samples/v1.0/Scenarios/WeatherLarge.json
samples/v1.2/Scenarios/ExpenseReport.json
samples/v1.2/Scenarios/FlightDetails.json
samples/v1.3/Scenarios/FoodOrderWithValidation.json

Fixes #4578
Updated scenario samples to match the templated and non-templated versions. 
Ensured all modified samples rendered as expected.

[Samples] Update scenario samples to ensure match between templated and non-templated versions

---

source/android/adaptivecards/build.gradle
source/android/adaptivecards/gradle.properties
source/android/build.gradle
source/android/gradle/wrapper/gradle-wrapper.properties

Cherry-pick from #4541 to release/1.2
Include dependencies in POM generation.

[Android] Cherry-pick Gradle changes

---

source/android/adaptivecards/build.gradle

Generated pom didn't have developers section, added that part

Add developers info

---

source/nodejs/adaptivecards/src/card-elements.ts

Fixes VSO 24095690
When a user puts their system in high contrast mode, their user agent will override CSS properties in order to display content in the same high contrast mode. There's no way for us (the website) to know if this is happening. The user will of course lose some of our styling cues (e.g. `TextBlock`'s `color` property). This is expected, but we are losing one critical bit of useful visual state -- container borders.
Here's what our `Container` sample card looks like:
|Normal|High Contrast Black|
|--|--|
|![image](https://user-images.githubusercontent.com/16614499/92037015-fb112880-ed25-11ea-97a4-a48a67277db3.png)|![image](https://user-images.githubusercontent.com/16614499/92036919-d0bf6b00-ed25-11ea-9104-0d630dc16414.png)|
The fix on our end is to emit an "invisible" border …

[JS] Emit "invisible" borders for containers

---

source/nodejs/ac-typed-schema/src/markdown/generate-markdown.ts

Fixes VSO 24043594
Instead of emitting "Inherited Properties" as a bold statement, we should be emitting it as a header, for accessibility purposes.
Before:
After:
* local build, devtools

[Site] Emit header tag in docs for "Inherited Properties"

---

schemas/1.3.0/adaptive-card.json
schemas/src/elements/inputs/Input.Text.json
specs/elements/Input.Text.md

Fixes #4728
Simple missing of the `version` property when `regex` was introduced on `Input.Text`.
* local build

[Schema] Add version to new regex property

---

source/nodejs/adaptivecards-designer-app/dist/adaptivecards-designer-app.css
source/nodejs/adaptivecards-designer-app/dist/containers/default-container.css
source/nodejs/adaptivecards-designer-app/dist/containers/outlook-container.1.css
source/nodejs/adaptivecards-designer-app/dist/containers/outlook-container.css
source/nodejs/adaptivecards-designer/src/containers/outlook/outlook-container.css
source/nodejs/adaptivecards-site/themes/adaptivecards/source/css/extracted.css
source/nodejs/adaptivecards-visualizer/css/outlook.css
source/nodejs/adaptivecards-visualizer/scss/outlook.scss

Fixes VSO 24066126
There are a couple of borders which fail to meet MAS 1.4.11's 3:1 contrast ratio requirement:
This change tweaks the borders to be dark enough to hit the 3:1 requirement:
* local build and color contrast testing tools

[Site] Adjust color contrast for a couple of borders

---

source/shared/cpp/ObjectModel/Enums.cpp
source/shared/cpp/ObjectModel/Enums.h
source/shared/cpp/ObjectModel/HostConfig.cpp
source/shared/cpp/ObjectModel/HostConfig.h
source/uwp/Renderer/idl/AdaptiveCards.Rendering.Uwp.idl
source/uwp/Renderer/lib/AdaptiveChoiceSetInputRenderer.cpp
source/uwp/Renderer/lib/AdaptiveDateInputRenderer.cpp
source/uwp/Renderer/lib/AdaptiveInputsConfig.cpp
source/uwp/Renderer/lib/AdaptiveInputsConfig.h
source/uwp/Renderer/lib/AdaptiveNumberInputRenderer.cpp
source/uwp/Renderer/lib/AdaptiveTextInputRenderer.cpp
source/uwp/Renderer/lib/AdaptiveTimeInputRenderer.cpp
source/uwp/Renderer/lib/AdaptiveToggleInputRenderer.cpp
source/uwp/Renderer/lib/InputValue.cpp
source/uwp/Renderer/lib/InputValue.h

UWP implementation of #4602 
Added support for focusLost and focusLostWithInput to UWP as spec'd in #4603. Change includes:
- Add `InitialiValidation` property to host config for shared model and UWP
- Wire renderContext to the InputValue classes to allow access to HostConfig
- Add support for focusLost and focusLostWithInput validation to the InputValue classes.
- Add support for keystroke validation once an input has failed initial validation.
Validated expected behavior in visualizer using existing v1.3 input cards.

[UWP] Implement focus lost validation behavior controlled by host config

---

samples/Templates/Scenarios/FlightDetails.template.json
samples/v1.2/Scenarios/FlightDetails.json

Fixes VSO 24096000
Update the FlightDetails sample to use a `RichTextBlock` in a single set of `ColumnSet`s so that screenreaders can give a more reasonable reading experience. Prior to this, rather than reading down a column, Narrator would read left to right and top to bottom (i.e. it would read SFO's time then JFK's time, then SFO's date, then JFK's date etc.)
* local build and narrator

[Samples] Update FlightDetails sample to have more logical reading order

---

source/nodejs/adaptivecards/README.md
source/nodejs/adaptivecards/src/card-elements.ts

Fixes VSO 23940376
The `aria-controls` attribute lets screenreaders know when one element controls the visibility of another element. This change adds `aria-controls` to `ToggleVisibility` actions and reflects the `aria-expanded` property on the elements that are toggled.

[JS] Paint ToggleVisibility actions with `aria-controls` attribute

---

samples/Templates/Scenarios/Restaurant.data.json
samples/Templates/Scenarios/Restaurant.template.json
samples/v1.0/Scenarios/Restaurant.json

Fixes VSO 23712499
The use of symbols rather than text leads to a suboptimal story for accessibility. Here we move to a more text-based model for the restaurant sample cards.
* Local build & narrator

[Samples] Update restaurant sample to read more naturally for a11y

---

source/nodejs/adaptivecards-designer/src/data.ts
source/nodejs/adaptivecards-designer/src/designer-peers.ts
source/nodejs/adaptivecards/src/card-elements.ts
source/nodejs/adaptivecards/src/serialization.ts

Fixes https://github.com/microsoft/AdaptiveCards/issues/4767
Fixes https://github.com/microsoft/AdaptiveCards/issues/4734
References https://github.com/microsoft/AdaptiveCards/issues/4483
- When `toJSON()` is automatically invoked via `JSON.stringify()`, it gets a parameter of type `string`. The AC renderer's implementation of `toJSON()` takes an optional parameter of type `BaseSerializationContext`. When the value of this parameter is not `undefined`, the code assumes it is of type `BaseSerializationContext` which is not the case when `toJSON()` is invoked via `JSON.stringify()`, and thus generates an exception. This PR fixes that by checking the type of the parameter `toJSON()` receives.
- The data structure generated from JSON would cause an exception when the JSON contained an empty …

[TS] Renderer and designer fixes

---

source/dotnet/Library/AdaptiveCards.Rendering.Wpf/AdaptiveTextBlockRenderer.cs
source/dotnet/Library/AdaptiveCards/AdaptiveTextBlock.cs
source/dotnet/Library/AdaptiveCards/AdaptiveTypedElement.cs
source/dotnet/Test/AdaptiveCards.Test/XmlSerializationTests.cs

references #4478
Updated WPF renderer to render a textblock only when text is given
The fix was verified manually, as in WPF we don't raise parsing errors, then it's a rendering only fix

[WPF] Change TextBlock to render only when text is not empty

---

source/dotnet/Samples/WPFVisualizer/MainWindow.xaml

ADO 24112801
Adds a label for the combo box to allow screen readers to get a name for the control. 
Fix was verified using narrator and the live properties visualizer of visual studio

[WPF] Add label for hostconfig combo box

---

samples/v1.3/Tests/customInput.json
source/uwp/Renderer/lib/AdaptiveTextInputRenderer.cpp
source/uwp/Renderer/lib/XamlHelpers.cpp
source/uwp/Visualizer/CustomElements/CustomInput.cs
source/uwp/Visualizer/ViewModel/DocumentViewModel.cs

Fixes #4812
The custom input renderer at [CustomInput.cs](https://github.com/microsoft/AdaptiveCards/blob/main/source/uwp/Visualizer/CustomElements/CustomInput.cs) wasn't handling marking the input as invalid. Updated that code to handle that functionality.
Confirmed custom element file [customInput.json](https://github.com/microsoft/AdaptiveCards/blob/main/samples/v1.3/Tests/customInput.json) now handles validation scenarios.

[UWP] Expand custom input test case to handle validation

---

source/nodejs/adaptivecards/src/card-elements.ts
source/nodejs/adaptivecards/src/utils.ts

ADO 24129943 
img in Media is presentational, and layout separators should be entirely hidden. Marking them with the appropriate aria attributes.

[JavaScript][Accessibility] presentational img and layout separator

---

source/nodejs/adaptivecards/src/card-elements.ts
source/nodejs/package-lock.json

Fixes https://github.com/microsoft/AdaptiveCards/issues/4818
**Action.ShowCard** has special handling code to allow for the correct expand/collapse user experience. So far, this special handling would be triggered internally only and not as a result of the `execute()` method being called. This lead to `execute()` having no effect on **Action.ShowCard**. This change enforces that all the logic is triggered as a result of `execute()` being called.

[TS] Handle ShowCard strictly via execute()

---

source/dotnet/Library/AdaptiveCards/AdaptiveAction.cs
source/dotnet/Library/AdaptiveCards/AdaptiveBackgroundImage.cs
source/dotnet/Library/AdaptiveCards/AdaptiveCard.cs
source/dotnet/Library/AdaptiveCards/AdaptiveChoice.cs
source/dotnet/Library/AdaptiveCards/AdaptiveChoiceSetInput.cs
source/dotnet/Library/AdaptiveCards/AdaptiveCollectionElement.cs
source/dotnet/Library/AdaptiveCards/AdaptiveContainer.cs
source/dotnet/Library/AdaptiveCards/AdaptiveElement.cs
source/dotnet/Library/AdaptiveCards/AdaptiveImage.cs
source/dotnet/Library/AdaptiveCards/AdaptiveImageSet.cs
source/dotnet/Library/AdaptiveCards/AdaptiveInput.cs
source/dotnet/Library/AdaptiveCards/AdaptiveNumberInput.cs
source/dotnet/Library/AdaptiveCards/AdaptiveRichTextBlock.cs
source/dotnet/Library/AdaptiveCards/AdaptiveTextBlock.cs
source/dotnet/Library/AdaptiveCards/AdaptiveTextInput.cs
source/dotnet/Library/AdaptiveCards/AdaptiveTextRun.cs
source/dotnet/Library/AdaptiveCards/AdaptiveToggleInput.cs
source/dotnet/Library/AdaptiveCards/AdaptiveTypedElement.cs
source/dotnet/Library/AdaptiveCards/AdaptiveTypedElementConverter.cs
source/dotnet/Samples/WPFVisualizer/MainWindow.xaml
source/dotnet/Samples/WPFVisualizer/MainWindow.xaml.cs
source/dotnet/Test/AdaptiveCards.Templating.Test/AdaptiveCards.Templating.Test.csproj
source/dotnet/Test/AdaptiveCards.Templating.Test/TestTransform.cs
source/dotnet/Test/AdaptiveCards.Test/AdaptiveCardApiTests.cs

reference #4788
1. Updated JSON attributes.
Json properties with default values were collected in additional properties by the JSON serializer.
To unwind this behavior, we used the reflection to filter properties that ended up in the additional properties this way.
The reflection can be very expensive if the card's depth is deep and has many children.
These issues seemed to have been fixed with the use of IgnoreAndPopulate option for DefaultValue handling.
1. [Ignore and IgnoreAndPopulate](https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_DefaultValueHandling.htm)
2. Changed Ignore to IgnoreAndPopulate and skipped the filtering.
3. Changed to have serialization error's flag set to handled since we do not surface the exception and wan to continue parsing.
How you verified the …

Updated dotnet Additional Properties Handling

---

source/nodejs/adaptivecards/src/card-elements.ts

Fixes #4575
This ensures that the keyboard shortcut of `Ctrl+Enter` works when an inlineAction is assigned to a `Text.Input`.

Trigger inlineAction with CTRL+Enter

---

source/nodejs/adaptivecards-designer/src/adaptivecards-designer.css
source/nodejs/adaptivecards-designer/src/dialog.ts

@golddove and I noticed a couple of issues with modal dialogs in the Designer:
* Keyboard focus wasn't returning to point of invocation when the dialog was dismissed
* Keyboard focus wasn't restricted to the dialog as it should be
* Modal dialog difficult to distinguish visually
This fixes that. Here's what modals look like now:

[Designer] Trap keyboard for modal dialogs

---

source/nodejs/adaptivecards/src/card-elements.ts

References https://github.com/microsoft/AdaptiveCards/issues/4856
When a TextRun in a RichTextBlock has its `selectAction` set, the aria-label of the generated anchor DOM element is now set to the action's `title` property, if specified.

[JS][Renderer] Use TextRun.selectAction.title as aria-label

---

source/nodejs/adaptivecards/src/strings.ts

Users of the SDK should be able to supply their own strings by modifying these properties.
No verification, just restoring previous behavior

[JavaScript] Strings shouldn't be const

---

source/nodejs/adaptivecards-controls/src/constants.ts
source/nodejs/adaptivecards-controls/src/dropdown.ts
source/nodejs/adaptivecards/package-lock.json
source/nodejs/adaptivecards/src/card-elements.ts

Fixes VSO 23940376
Two, two, two fixes in one! #4828 regressed arrow keys in key handlers since the keys are referred to as `Arrow[Up|Down]`, not `[Up|Down]`. This broke keyboard accessibility in the Designer's toolbar pickers, since you couldn't arrow through the list of options. We also fix up the aria around `ActionSet`s as well as the dropdown list. Narrator now correctly reads both the expanded/collapsed state of `Action.ShowCard` buttons as well as their positions in the list of actions.
* local build, narrator, dev tools, NVDA

[JS] Fix arrow keys and actionset aria

---

source/dotnet/Library/AdaptiveCards/Rendering/AdaptiveRenderArgs.cs

Fixes #4861
The issue was that the Container Id was not being saved when duplicating the RenderArgs object, this fix had been previously made but at some point this regression happened
The fix was verified manually

[WPF] Fix InputForm json card behaviour

---

source/nodejs/adaptivecards-controls/src/constants.ts
source/nodejs/adaptivecards-controls/src/dropdown.ts
source/nodejs/adaptivecards/package-lock.json
source/nodejs/adaptivecards/src/card-elements.ts
source/nodejs/adaptivecards/src/strings.ts

Cherry-pick #4848 and #4849 
Clean cherry-pick, no conflicts

[JavaScript] cherry-pick of #4848 and #4849 for release/20.09

---

source/uwp/NuGet/AdaptiveCards.Rendering.Uwp.nuspec

The `licenseUrl` metadata item in `.nuspec` files is [deprecated](https://docs.microsoft.com/en-us/nuget/reference/nuspec#licenseurl), and our internal tooling doesn't seem to respect it anyways. This change moves us to using the `license` directive, which *is* recognized (and already in use for our .NET packages).
* local build

[UWP] Update renderer package license expression

---

source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer.xcodeproj/project.pbxproj
source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer/CustomActionSetRenderer.h
source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer/CustomActionSetRenderer.mm
source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer/ViewController.m
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACFramework.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRActionSetRenderer.h

Fixed #4899 
This change removes warnings if the default ActionSet is subclassed to be registered as a custom base card element render. 
1. Added a code example to sample  for verification and demonstration
2. Regression test with cards with ActionSets.

Updated custom registration for ActionSet

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/BaseActionElementRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/Util.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/InputUtil.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/ValidatedEditText.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/inputhandler/BaseInputHandler.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/inputhandler/CheckBoxSetInputHandler.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/inputhandler/ComboBoxInputHandler.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/inputhandler/RadioGroupInputHandler.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/inputhandler/TextInputHandler.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/inputhandler/ToggleInputHandler.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/layout/StretchableInputLayout.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/registration/CardRendererRegistration.java
source/android/mobile/src/main/java/io/adaptivecards/adaptivecardssample/CustomObjects/CardElements/CustomInput.java

Android part of #4912 
Also fixed ADO 28382490
Set inputs' accessible text to Input element's `label` + `errorMessage` when input has been invalidated (but only `label` when input is valid).
On submit, move keyboard focus, accessibility focus, and scroll position to first invalid input. So, above accessible text is spoken for first invalid input on submit.
Video:

[Android][Accessibility] Announce label, errorMessage with inputs

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRChoiceSetViewDataSource.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRChoiceSetViewDataSourceCompactStyle.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRInputChoiceSetRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRInputDateRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRInputLabelView.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRInputLabelView.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRInputLabelView.xib
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRInputLabelViewPrivate.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRInputNumberRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRInputRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRInputTimeRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRInputToggleRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRTextView.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRToggleInputDataSource.mm

reference #4898 
Fixed the VoiceOver issue for iOS. Input's label and input field were treated as disparate units during the VoiceOver, and the input field did not provide the information contained in the input label. 
1. All Input cards in 1.3 were tested and verified.

Updated accessiblity for Inputs

---

samples/v1.2/Tests/Image.Size.Auto.json
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/BackgroundImageLoaderAsync.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/GenericImageLoaderAsync.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/Util.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/action/ActionElementRenderer.java

Fixes #4687 
A 100px x 150px image, when used in an Image Element (size auto) or a backgroundImage property (w/ tiling enabled), the image now takes up 100dp x 150dp (device-independent pixels) instead of 100px x 150px (physical pixels).
Manually checked `v1.2/Elements/Container.BackgroundImage.json`:
Also added the following test card:
```
{
"body": [
{
"url": "https://picsum.photos/300?image=882",
"size": "auto",
"altText": "Seated guest drinking a cup of coffee"
},
{
"url": "https://picsum.photos/300?image=882",
"size": "auto",
"altText": "Seated guest drinking a cup of coffee",
"width": "300",
"height": "300"
}
]
}
```
The two images have the …

[Android] Auto sized images scale to dp

---

source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer/ACRCustomSubmitTargetBuilder.mm
source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer/ViewController.m
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRActionDelegate.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRAggregateTarget.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRAggregateTarget.mm

Fixed #4890 
Added layout update notification to include custom properties, so the user of this delegate include custom properties to enable them to do things like setting an input view or a label to be focused. The sample app can scroll to the correct input view with additional param passed from the notification.
1. Tested with sample cards for regression check
2. Updated sample app to demonstrate the new feature

Updated layout notification to include properties

---

source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer.xcodeproj/project.pbxproj
source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer/ACRCustomSubmitTargetBuilder.h
source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer/ACRCustomSubmitTargetBuilder.mm
source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer/ViewController.m
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards.xcodeproj/project.pbxproj
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACFramework.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACOBaseActionElement.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACOBaseActionElement.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACOInputResults.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACOInputResults.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRActionDelegate.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRAggregateTarget.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRAggregateTarget.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRInputLabelView.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRInputLabelView.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRRegistration.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRRegistration.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRTargetBuilder.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRTargetBuilderDirector.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRTargetBuilderDirector.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRView.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRViewPrivate.h

Fixed #4888
#4888 asked for sending a ref to a button, so it can be configured on input submission. Our team's general consensus is that we need to take a long term view and review other renderers for us to change the behaviors of the existing action delegates that are common to other renderers. This PR adds a registration for event handlers aka targets in iOS builders. Users can register event handler builders as they would with the renderer.  When implemented the builder interface, the builder builds the event handler and can attach the handler to the associated button. This change also includes sample code for demonstration purposes. The demo code will turn the submit action button to green when clicked when custom rendering is enabled in the sample app.
How you verified the fix, …

Added Event Handler Registration

---

source/android/adaptivecards/build.gradle

Fixes #4964 
While this does fix the image sizes, there are still issues with `height: stretch` as you can see in the left column of the payload below. Without `height: stretch`, images are sized correctly.
This reverts commit dc01f5bc38cd269d8fe3d44ee0e0cd7b0fbe4a42.
Major version bump caused weird layouts. Switching back to old version of dependency.
`v1.2/Tests/ImageSizing.json`:

Revert "Bump constraint-layout from 1.1.3 to 2.0.1 in /source/android"

---

.pipelines/android-daily.yml
.pipelines/android-release.yml

Fixes #4972
Use Windows images to run pipelines to see if it solves Teams' issue
Also commented out the Get NDK task, as it is causing issues. Pipelines should now use the default NDK from the system image.
Will need to investigate further to see what the constraints are with NDK versions we can use/upgrade going forward.
Manual verification with Teams

[Android] Switch pipelines to use Windows hosted pools

---

.pipelines/android-release.yml

Remove pre-release tag from release pipeline.
Clean cherry-pick from release/20.09

[Android] No prerelease tag for release

---

source/nodejs/adaptivecards/package-lock.json
source/nodejs/adaptivecards/package.json
source/nodejs/package-lock.json

1. Updating results of `npm audit fix`
2. Also addressing npm release failures by removing the typeDoc compilation step for now. (it;s not liking the command line options for some reason as specified in typeDoc.json at the moment, and after fighting with it for a while decided to give up on it for now to allow release to be unblocked. These docs currently are not being published to microsoftDocs anyways).

Fixing 1 high pri vulnerability and also removing the typeDoc step from release script

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/layout/StretchableInputLayout.java

Fixes #5021 
Fixes visual cues for Input.Text with inline actions as they represent a special case of an input that doesn't set its accessibility properties in the same place the visual cues render.
The fix was verified manually
* Input.Text with Inline actions
* Verification that ChoiceSet elements work as expected

[Android] Fix input.text with inline actions

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/ChoiceSetInputRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/DateInputRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/TimeInputRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/layout/StretchableInputLayout.java

CP of #5020 (#5028 ) and #5021 (#5029 )
Fixes focus setting in Input. Time, Date and ChoiceSet and fixes visual cues for input.Text with inline actions

[Android] Cherrypick of fixes for #5020 and #5021

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRChoiceSetViewDataSource.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRChoiceSetViewDataSource.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRColumnSetRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRInputChoiceSetRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRInputLabelView.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRTextInputHandler.mm

Fixed #5023, Fixed #5024 
Input.ChoiceSet had a regression in its layout; reverted ChoiceSet Xib related update
Setting focus on Input.Text and Input.Number caused erratic scrolling behavior. Updated to have the focus to be set on InputView of input, and allowed the scrolling to be handled by the host app, and explicitly set the accessibility focus on the input handler to announce the accessibility l
https://github.com/microsoft/AdaptiveCards/blob/main/samples/v1.3/Elements/Input.ChoiceSet.ErrorMessage.json
https://github.com/microsoft/AdaptiveCards/blob/main/samples/v1.3/Elements/Input.Number.Label.json
https://github.com/microsoft/AdaptiveCards/blob/main/samples/v1.3/Elements/Input.Text.Label.json
1. Run most of the cards …

iOS input updates

---

source/android/adaptivecards/gradle.properties

Bump Android renderer version number to 2.3.1 for patch update

[Android] Bump renderer to v2.3.1

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/layout/StretchableInputLayout.java

Fixes #5039
Radio/checkbox should also have their child as m_inputView, similar to the compact choiceset fix. This allows the label to be read on the first option for accessibility.
Manual verification with Narrator.

[Android] Update accessibility issue for choicesets

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/GenericImageLoaderAsync.java
source/android/mobilechatapp/build.gradle

No linked issue.
Empty image returns null, so shouldn't attempt to scale in those cases.
`v1.2/Tests/Image.DataUri.InvalidChars.json`
Manual verification with fix. Doesn't crash.

[Android] Set density only when non-null

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRRichTextBlockRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRTextBlockRenderer.mm

ADO https://microsoft.visualstudio.com/OS/_queries/edit/29468860/?triage=true
String consisted only with the whitespace chars is being read by the voiceover as "space". Fixed the issue by making the label accessibility hidden as making it an inaccessibility item caused the voiceover to announce the label "space" regardlessly.
https://github.com/microsoft/AdaptiveCards/blob/main/samples/v1.0/Tests/Feedback.json
1. Ran the repro steps specified in ADO to verify.
2. Tested with TextBlock cards to make sure there are no regressions in the voiceover.
3. Manual scenario verification if any; ***Do include .gif's or screenshots of the testing you performed here if you think that it; N/A

Fixed the voiceover to announce 'space' when label has only whitespace chars

---

samples/v1.1/Elements/Media.Sources.json
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRMediaRenderer.mm

ADO https://microsoft.visualstudio.com/OS/_queries/edit/29527290/?triage=true
Media Source card is not accessible for iOS. Added alt text to the card, and made media element to be accessible by adding the accessible label, and changing the role as the button.
https://github.com/microsoft/AdaptiveCards/blob/main/samples/v1.1/Elements/Media.Sources.json
1. Existing relevant unit/regression tests that you ran; Media.Source.json is tested & verified.

Made media icon to be accessible element

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRActionOpenURLRenderer.mm

ADO https://microsoft.visualstudio.com/OS/_queries/edit/29139727/?triage=true
Action.OpenURL buttons should have links as the role. This change adds the link to the role.
https://github.com/microsoft/AdaptiveCards/blob/main/samples/v1.0/Elements/Action.OpenUrl.json
1. New unit tests that were added if any. was able to repro using Action.OpenUrl.json
2. Existing relevant unit/regression tests that you ran; Action.OpenUrl.json

added link to Action.OpenUrl buttons

---

source/nodejs/adaptivecards-designer-app/package-lock.json
source/nodejs/adaptivecards-designer-app/package.json
source/nodejs/adaptivecards-designer/package-lock.json
source/nodejs/adaptivecards-designer/package.json
source/nodejs/adaptivecards-site/package-lock.json
source/nodejs/adaptivecards-templating/package-lock.json
source/nodejs/adaptivecards-templating/package.json
source/nodejs/adaptivecards-templating/src/template-engine.ts

Fixes https://github.com/microsoft/AdaptiveCards/issues/5100
Works around a behavioral change in AEL introduced in version 4.10 which causes single expressions such as `${age}` to be generated as `concat` and produce strings instead of the actual type of the expression.
```
{
"$data": {
"title": "Not empty"
},
"body": [
{
"size": "Medium",
"weight": "Bolder",
"text": "Test card"
},
{
"text": "Should be visible only if title isn't empty",
"wrap": true,
"$when": "${title != ''}"
}
],
"version": "1.3"
}
```
Without this fix, the "$when" clause will incorrectly evaluate to the string "true". With the fix, it will correctly evaluate to the boolean value `true`. …

Fix break caused by AEL behavioral change in v4.10

---

source/pic2card/mystique/font_properties.py

Have updated the classify_font_weights function to handle images with empty weights and similar weights. 
Image with no textbox property : 
Image with similar weights for textbox properties identified :

[pic2card] updated classify font weight 

---

source/nodejs/adaptivecards-site/package.json
source/nodejs/adaptivecards/src/card-elements.ts

Fixes https://github.com/microsoft/AdaptiveCards/issues/5111
Reverts to emitting Input.Number.value as a string in an Action.Submit.data
```
{
"body": [
{
"type": "Input.Number",
"placeholder": "Placeholder text",
"min": 1,
"max": 10,
"value": 8,
"id": "fsd"
}
],
"actions": [
{
"type": "Action.Submit",
"title": "Action.Submit"
}
],
"version": "1.3"
}
```

[TS][Renderer] Input.Number.value as string in Action.Submit

---

samples/v1.3/Elements/Action.Submit.AssociatedInputs.json
source/uwp/Renderer/idl/AdaptiveCards.Rendering.Uwp.idl
source/uwp/Renderer/lib/AdaptiveSubmitAction.cpp
source/uwp/Renderer/lib/AdaptiveSubmitAction.h
source/uwp/Renderer/lib/RenderedAdaptiveCard.cpp
source/uwp/UWPUnitTests/ObjectModelTests.cs

UWP implementation for #5078
Consumed the associatedInputs property in UWP from the shared model. Updated the submit code to not perform validation and to return an empty inputs object when none is set.
New card added with this change at samples\v1.3\Elements\Action.Submit.AssociatedInputs.json
Updated UWP object model tests and ensured that they still run and pass. Manual validation of scenario using new sample card.

[UWP] Add support for associatedInputs none value

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRAggregateTarget.mm

Implemented #5078 for iOS
The support for `AssociatedInput` options `None` and `Auto` is added.
https://github.com/microsoft/AdaptiveCards/blob/feature/associatedInputs/samples/v1.3/Elements/Action.Submit.AssociatedInputs.json
1. Existing relevant unit/regression tests that you ran; ran all of them
3. Manual scenario verification if any; Verified with sample card.

Implemented associated input

---

source/android/adaptivecards/build.gradle
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/BaseActionElementRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/RenderedAdaptiveCard.java

Android part of #5078
When `associatedInputs` is set to `none`, we don't gather inputs or perform validation.
`v1.3\Elements\Action.Submit.AssociatedInputs.json`
Cancel:
Submit:
Manual, see screenshots above.

[Android] Support associatedInputs: none

---

source/android/adaptivecards/build.gradle
source/android/adaptivecards/gradle.properties
source/android/mobile/src/main/res/raw/importer_card.json

* [Android] Bump minor v2.4.0
* Point to new EULA
Clean cherry-pick of #5187, no conflicts.

[Android] Bump minor 2.4.0, and reference to new binary EULA (#5187)

---

source/ios/tools/AdaptiveCards.podspec

N/A
Updated the podspec not to attempt linking with arm64 binary for testing.
[more info](https://stackoverflow.com/questions/63607158/xcode-12-building-for-ios-simulator-but-linking-in-object-file-built-for-ios)
N/A
Ran the lint locally.

excluded arm64 from pod spec

---

source/nodejs/adaptivecards-designer/README.md
source/nodejs/adaptivecards-designer/cdn.html
source/nodejs/adaptivecards-designer/index.html
source/nodejs/adaptivecards-designer/noHosts.html
source/nodejs/adaptivecards-designer/previewFeatures.html
source/nodejs/adaptivecards-site/package-lock.json
source/nodejs/adaptivecards-site/package.json
source/nodejs/adaptivecards-site/themes/adaptivecards/layout/_partial/footer.ejs

Fixes #5193
Explicitly include adaptive-expression
Pending

[Site] Fix missing expression library dep

---

source/nodejs/adaptivecards/src/card-elements.ts

Fixes VSO 30864226
When a media player element is inserted into the DOM, it needs to be explicitly focused -- otherwise keyboard focus can get lost on invocation.
* local build, devtools

[JS] Focus media element after it's inserted

---

samples/v1.3/Tests/RichTextBlock.SelectActionAccessiblityTitle.json
source/dotnet/Library/AdaptiveCards.Rendering.Wpf/AdaptiveRichTextBlockRenderer.cs

.NET fix for #4856
Set the automation property name to the action title for rich text block select actions
Added new file at samples/v1.3/Tests/RichTextBlock.SelectActionAccessiblityTitle.json
Verified that narrator now reads the action title rather than the text for text run select actions in the added card.

[.NET] Set accessibility text for rich text block select actions to action title

---

source/nodejs/adaptivecards-site/themes/adaptivecards/layout/explorer.ejs
source/nodejs/adaptivecards-site/themes/adaptivecards/layout/sample.ejs

Noticed a couple typos on the website -- `intead` rather than `instead` :)

[Site] Fix a couple typos

---

source/uwp/Renderer/lib/RenderedAdaptiveCard.cpp

Fixes #5330
As part of the work to implement `"associatedInputs":"none"`, the action invoke code was refactored in such a way that OpenUrl action invokes no longer had an Inputs object. Although this object was always empty for OpenUrl types, our Visualizer depended on it being non-null. Because it's technically a breaking change (that actually broke the visualizer), I restored the old behavior where OpenUrl action invocations have an empty but non-null inputs object. 
ActivityUpdate.json scenario card
Confirmed OpenUrl button now works as expected

[UWP] Initialize empty input object for OpenUrl action invoke

---

source/uwp/Renderer/lib/ActionHelpers.cpp

Fixes #5331
As part of setting tool tips on select actions, the code to actually wire up the click handler was accidently trapped inside a `title.IsValid()` check. Moved this call out of the if statement to fix.
ExpenseReport.json scenario card
Verified toggles in Expense report card now behave as expected.

[UWP] Fixed bug where select actions without titles were not set properly

---

source/nodejs/adaptivecards-controls/src/adaptivecards-controls.css
source/nodejs/adaptivecards-designer-app/dist/containers/outlook-container.css
source/nodejs/adaptivecards-designer-app/dist/containers/teams-container-dark.css
source/nodejs/adaptivecards-designer-app/dist/containers/teams-container-light.css
source/nodejs/adaptivecards-designer/src/adaptivecards-designer.css
source/nodejs/adaptivecards-designer/src/containers/cortana/cortana-container-dark.css
source/nodejs/adaptivecards-designer/src/containers/cortana/cortana-container-light.css
source/nodejs/adaptivecards-designer/src/containers/outlook/outlook-container.css
source/nodejs/adaptivecards-designer/src/containers/teams/teams-container-dark.css
source/nodejs/adaptivecards-designer/src/containers/teams/teams-container-light.css
source/nodejs/adaptivecards-visualizer/css/outlook.css
source/nodejs/adaptivecards-visualizer/css/teams.css

Fixes VSO 30866987
There are a few places where our CSS styling doesn't play nice with High Contrast mode. Thankfully, we have a [new standard](https://blogs.windows.com/msedgedev/2020/09/17/styling-for-windows-high-contrast-with-new-standards-for-forced-colors/) we can use to implement fixes. It's only supported by default in Edge at the moment, but is implemented/off-by-default in Chrome and FireFox. It's the best we have for now -- hopefully those defaults will change at some point.
1. Keyboard focus now visible in dropdown menus
2. Expanded expandable buttons now show as selected
3. Toggled toggleable buttons in the designer now show as active
Partly covered by `FoodOrder.json`
* local build

[JS] Fix dropdown control and host container high contrast

---

samples/v1.3/Tests/HtmlSpaces.json
source/dotnet/Library/AdaptiveCards.Rendering.Wpf/AdaptiveTextBlockRenderer.cs
source/dotnet/Library/AdaptiveCards/Rendering/RendererUtilities.cs

Fixes #4679 
Added handling of &nbsp, &ensp, and &emsp by replacing them with the corresponding unicode characters.
Added sample card at https://github.com/microsoft/AdaptiveCards/blob/main/samples/v1.3/Tests/HtmlSpaces.json
Confirmed using above sample card that the three html entities appear as expected in the rendered card.

[.NET] Handle HTML space entities

---

samples/v1.3/Tests/Action.Submit.AssociatedInputs.CaseInsensitive.json
source/nodejs/adaptivecards/src/card-elements.ts

Fixes #5260
Updated the string comparison to run the card value through `toLowerCase()` before comparing it to `"none"`
Added new card [Action.Submit.AssociatedInputs.CaseInsensitive.json](https://github.com/microsoft/AdaptiveCards/blob/main/samples/v1.3/Tests/Action.Submit.AssociatedInputs.CaseInsensitive.json)
Validated against above card and other variations that the auto and none values are handled correctly regardless of casing.

[JS] Ensure associatedInputs values are handled case insensitively

---

source/nodejs/adaptivecards-site/themes/adaptivecards/layout/_partial/footer.ejs
source/nodejs/adaptivecards-site/themes/adaptivecards/layout/_partial/section-details.ejs
source/nodejs/adaptivecards/package.json

While looking at some other a11y issues, I noticed that we have some elements on our site that are spacers, but they get read out by Narrator. This fixes that.
Also, don't generate docs automatically in build -- it adds too much noise.

[Site] Mark space-only items as role="presentation"

---

source/nodejs/adaptivecards-site/themes/adaptivecards/scripts/helper-code-and-card.js

Fixes VSO 30854543
The `Try it yourself` button in schema explorer behaves like a link (invoking it opens a new tab), so set its role accordingly.
* local build, narrator, devtools

[Site] Update role for "Try it yourself" button

---

source/nodejs/adaptivecards-site/themes/adaptivecards/layout/_partial/footer.ejs

Fixes ADO [30929352](https://microsoft.visualstudio.com/OS/_workitems/edit/30929352)
Add aria-label tag to "Read more" link to make it more descriptive
Manually verified correct behavior using narrator

[Site] Add more descriptive label to the "Read more" blog link

---

samples/v1.2/Scenarios/ExpenseReport.json

Fixes ADO [30961605](https://microsoft.visualstudio.com/OS/_workitems/edit/30961605)
Per request in the bug, expanded the altText on the expand/collapse button images to describe what was being expanded/collapsed
https://github.com/microsoft/AdaptiveCards/blob/main/samples/v1.2/Scenarios/ExpenseReport.json
Confirmed Narrator now reads the details of what is being expanded/collapsed.

[Samples] Update alttext on ExpenseReport expand collapse buttons to include more information

---

source/nodejs/adaptivecards-site/themes/adaptivecards/source/css/style.css

Partially fixes VSO 30960937
When browsing through samples in high contrast, there's no indication on the nav pane to the left as to which sample is currently being viewed. This fixes that.
Before:
After:
* local build

[Site] Fix sample selection indicator in high contrast

---

source/nodejs/adaptivecards-designer/src/card-designer.ts
source/nodejs/adaptivecards-designer/src/designer-peers.ts
source/nodejs/adaptivecards-designer/src/toolbar.ts
source/nodejs/adaptivecards/src/card-elements.ts

- Partially fixes ADO 30961076
- Fixes ADO 30868015
- Fixes ADO 30926701
- The label of the input is now read by narrator when the input gets focus.
- Note that somehow this bug seemed to already be fixed. However, I found that the fix could be streamlined and more tightly baked into the SDK, so I tweaked it.
- Narrator will however also read the placeholder text ("not set") even when the input has a valid value. This appears to be a Narrator bug.
- It is unclear that the CTRL+SHIFT+F10 keyboard shortcut is actually supposed to force showing the tooltip of a focused element. However showing the tooltips for those buttons on keyboard navigation is really to compensate for the fact the buttons do not have a label. Given the cost of showing tooltips on focus (this isn't a standard HTML5 …

[JS] Fix some accessibility issues

---

source/nodejs/adaptivecards-designer/src/card-designer.ts

Fixes ADO [30898371](https://microsoft.visualstudio.com/OS/_workitems/edit/30898371/)
Group elements for each element category (Containers, Elements, Inputs) in a div with a label so that the group heading is read out by narrator when that section is entered via tab navigation.
Confirmed expected behavior locally using narrator.

[Designer][Accessibility] Group Card Elements sections with label for accessibility

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRColumnSetRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRColumnView.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRColumnView.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRContentStackView.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRContentStackView.mm

Fixed #5269 
When a column has pixel width, and the columnset has the column as the only column, the columnset will fail to honour the column's width with the AutoLayout of iOS.
Added an empty view to be used as a filler in such a case.
```json
{
"body": [
{
"style": "emphasis",
"backgroundImage": "https://messagecardplayground.azurewebsites.net/assets/Mostly%20Cloudy-Background.jpg",
"minHeight": "400px",
"items": [
{
"minHeight": "380px"
},
{
"columns": [
{
"width": "180px",
"items": [
{
"style": "accent"
}
]
}
]
}
]
}
]
}
```
Bad image available in #5269

Fixed #5269

---

source/nodejs/adaptivecards-site/themes/adaptivecards/layout/sample.ejs
source/nodejs/adaptivecards-site/themes/adaptivecards/source/css/style.css

Fixes VSO 30961004
We currently don't do anything special aria-wise with our sample list. We should be marking the links up so that they're read with extra context (e.g. instead of "Food Order, link", it should read "Food Order, selected, 8 of 25").

[Site] Emit samples list with aria attributes

---

source/nodejs/adaptivecards-site/themes/adaptivecards/source/css/extracted.css

Fixes VSO 30941092
We have some (presumably) imported CSS that hides our feedback and github icons' text at smaller screen widths. This would make sense from a design perspective *if* we had more than the two icons. As it is, they both fit fine at smaller widths, so we shouldn't be hiding them.
* local build

[Site] Display action item text at lower screen widths

---

source/nodejs/adaptivecards-designer/src/designer-peers.ts
source/nodejs/adaptivecards/src/card-elements.ts

Partial fix for ADO [30909272](https://microsoft.visualstudio.com/OS/_workitems/edit/30909272)
Added aria-labels to describe the "..." data binding button in it's expanded and collapsed states
Verified using narrator.

[Accessibility] Add aria-labels to the data binding buttons in the designer

---

source/nodejs/adaptivecards-site/themes/adaptivecards/layout/sample.ejs
source/nodejs/adaptivecards-site/themes/adaptivecards/source/js/script.js

Fixes VSO [30943285](https://microsoft.visualstudio.com/OS/_workitems/edit/30943285)
I apologize in advance. Header and mobile nav is powered by some JS we don't own (and can't change on any reasonable time scale). There are a couple of problems with this script. The first is that it puts explicit positive `tabindex` attributes on some DOM elements when in what it considers to be a "mobile" view (this is keyed off of the window width, so it is also affected by DPI and zoom levels). Using positive `tabindex` values is considered bad practice because it's easy to get wrong. Anyways, this is the reason why the tab order is messed up in mobile. The second (relatively minor) problem is that it views the templating checkbox as a search box (it just looks for the first `<input />` in the DOM). …

[Site] Fix mobile tabindex

---

source/nodejs/adaptivecards-designer/src/designer-peers.ts
source/nodejs/adaptivecards/src/card-elements.ts

Fixes https://github.com/microsoft/AdaptiveCards/issues/4097
- Exposes the `height` property on **Input.Text** in the designer when `isMultiline` is set to `true`
- Vertically stretch **Input.Text** when its `height` property is set to `"stretch"`
```json
{
"body": [
{
"type": "Input.Text",
"placeholder": "This multiline Input.Text stretches into the available vertical space",
"isMultiline": true,
"height": "stretch"
},
{
"text": "This TextBlock is pushed to the bottom of the card",
"wrap": true
}
],
"minHeight": "200px"
}
```
As rendered:

[JS] Stretch multiline Input.Text when height = stretch

---

source/nodejs/adaptivecards/src/serialization.ts

Fixes https://github.com/microsoft/AdaptiveCards/issues/5429#event-4378437789
Boolean properties were not removed from the output JSON when they were set to their default value. This affected all boolean properties, with `separator` just being one of them.
No sample needed:
- In the designer, create a card with at least one element
- Select that element
- In the Element Properties toolbox, check the `Separator` (for example) box
- Verify that `"separator": true` is added to the JSON for that element
- Now deselect the `Separator` box
- Verify that the `"separator"` property is removed from the JSON

[JS] Remove bool props from JSON when set to default

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRInputRenderer.mm

Fixed #5348 
Changed Input.Text to stretch the input text box when it's multi-line and height is set to stretch.
```json
{
"body": [
{
"size": "Medium",
"weight": "Bolder",
"text": "Custom JSON Design Input",
"horizontalAlignment": "Center"
},
{
"text": "In addition to showing your our pre-built samples, I can submit your custom design for you.  This helps to see how it will render or to see what type of payload your app will need to process if a user hits an Action.Submit button.",
"wrap": true
},
{
"text": "One way to get design JSON to paste here is to use the \"Copy Card JSON\" button from the [Buttons and Cards …
```

Fixed #5348

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRFactSetRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRRichTextBlockRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRTextBlockRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/UtiliOS.mm
source/shared/cpp/ObjectModel/MarkDownParser.cpp
source/shared/cpp/ObjectModel/MarkDownParser.h

Fixed #5428 
We escape whenever `<`, `>`, `&` and `"`, and iOS renders the text as HTML. We don't have to render the text as HTML if we have such chars but MarkDown.
This change gives more flexibility to developers who develops on stacks that may run into issues when HTML text rendering is used.
```json
{
"type" : "AdaptiveCard",
"$schema" : "http://adaptivecards.io/schemas/adaptive-card.json",
"version" : "1.3",
"body" : [
{
"type" : "TextBlock",
"text" : "Foo & bar"
}
]
}
```
Tested that HTML text rendering is not run with the sample card.

Fixed #5428

---

source/nodejs/adaptivecards/src/card-elements.ts

Backport of fix for https://github.com/microsoft/AdaptiveCards/issues/5455 into release/21.02
For the last few releases (since October 2020 at least) Column separator rendering has been broken, with the separator lacking spacing on the right of the separation line. This was due to some logic designed for horizontal separators being applied to the a Column's vertical separator.
Find sample card in issue linked above

Fix broken separator rendering in Column

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRView.mm

Fixed #5501 
Not applying padding at zero causes the ACRView to assume default layout configuration, this isn't wrong, but it is an inconsistent behavior compared to when padding > 0. This fix applies padding even if it's zero.
Payload
```json
{
"body": [
{
"style": "accent",
"items": [
{
"height": "stretch",
"columns": [
{
"items": [
{
"text": "Some text!",
"size": "extraLarge",
"weight": "bolder",
"horizontalAlignment": "center"
}
]
}
]
}
]
}
]
}
```
Hostconfig
```json
{
"spacing" : {
"padding" : 0
}
}
```
Before Fix
After Fix

[iOS] Fixed zero padding issue around the card

---

source/community/reactnative/ios/Podfile.lock
source/community/reactnative/package.json
source/community/reactnative/src/components/inputs/choice-set/check-box.js
source/community/reactnative/src/components/inputs/choice-set/choice-set-input.js
source/community/reactnative/src/components/inputs/date-input.js
source/community/reactnative/src/components/inputs/picker-input.js
source/community/reactnative/src/components/inputs/time-input.js
source/community/reactnative/yarn.lock

This PR contains the below changes
1. Picker component migrated to - @react-native-picker/picker
2. DatePickerIOS component migrated to - @react-native-community/datetimepicker
3. DatePickerAndroid component migrated to - @react-native-community/datetimepicker
4. TimePickerAndroid component migrated to - @react-native-community/datetimepicker
5. componentWillReceiveProps() state is migrated and handled in getDerivedStateFromProps()
6. componentWillMount() state is migrated and handled in the constructor()

Migrated the deprecated and warning packages

---

source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer/ViewController.m
source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizerTests/ADCIOSVisualizerTests.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRRegistration.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRRegistration.mm

Fixed #5271 
the method that overrides default actions renderers take NSNumber as a key, it's very cumbersome to use in Swift & it's not intuitive to use. Changed it to use enum type for the default renderers.
1. Updated sample app to use the new method.
2. Added a new unit test.

[iOS]Updated action registration API

---

source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer.xcodeproj/project.pbxproj
source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer/ViewController.m
source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizerTests/ADCIOSVisualizerTests.mm
source/ios/AdaptiveCards/ADCIOSVisualizer/TestFiles/AdditionalProperties.json
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRColumnSetRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRRegistration.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRRegistration.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRRegistrationPrivate.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRView.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRViewPrivate.h

Fixed #5272 
Resource resolvers were disabled if the default renderers were overridden per the Team's request. Added two new methods, 
`- (void)setBaseCardElementRenderer:(ACRBaseCardElementRenderer *_Nullable)renderer cardElementType:(ACRCardElementType)cardElementType useResourceResolver:(BOOL)doUse`
`- (void)setActionRenderer:(ACRBaseActionElementRenderer *_Nullable)renderer actionElementType:(ACRActionType)actionElementType useResourceResolver:(BOOL)doUse`
when doUse is `YES`, resource resolver will be used for the overrides.
Also fixed a minor issue with stretch behavior for Column when the vertical alignment is set to Center.
1. New Unit tests are added
2. Checked for the regression.

[iOS] Updated resource resolver behaviors for renderer overrides

---

source/nodejs/adaptivecards-site/pages/_posts/2020/Community-Call-November.md

The asset's raw URL was relative to the feature branch instead of the main branch.

pic2card broken gif url fix

---

source/nodejs/adaptivecards-designer/src/card-designer.ts
source/nodejs/adaptivecards-designer/src/open-image-dialog.ts

Fixes VSO #30650186
After pic2card converts an image, we need to provide feedback to the user that the conversion was successful. While I was in here, I made a couple changes to manage focus.

[Designer] Accessibility changes to pic2card dialog

---

source/nodejs/adaptivecards-site/themes/adaptivecards/layout/explorer.ejs
source/nodejs/adaptivecards-site/themes/adaptivecards/layout/sample.ejs
source/nodejs/adaptivecards-site/themes/adaptivecards/source/css/style.css

Fixes VSO #30961004
Applies `aria-current` to items in the samples list. Also restructure things a bit so that the value is actually honored. Also includes a couple of small accessibility fixes for the mobile site (adding `title` to a couple of `select` elements). Lastly, fix up a misspelled word ("targetting" -> "targeting"). Note that Narrator doesn't read `aria-current`, but NVDA does the right thing.
* local build, devtools, NVDA

[Site] Set aria-current on current sample (and misc a11y fixes)

---

source/ios/AdaptiveCards/ADCIOSVisualizer/resources/filebrowserHostConfig.json
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACOAdaptiveCard.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRTextView.mm

Fixed #5558 
1. The intrinsic content size of TextView was returning its frame size, this is wrong as the frame is not dependent on the text content.
2. Increased sample app's allowed button counts to include 1.4 samples
3. Updated parser version after shared mode change.
1. Existing relevant unit/regression tests that you ran

[iOS] Updated TextView to dynamically compute the intrinsic content size

---

source/nodejs/adaptivecards-designer/src/card-designer-surface.ts
source/nodejs/adaptivecards-designer/src/designer-peers.ts
source/nodejs/adaptivecards-designer/src/shared.ts
source/nodejs/adaptivecards/src/card-elements.ts
source/nodejs/adaptivecards/src/serialization.ts

- Finalizes implementation of https://github.com/microsoft/AdaptiveCards/issues/3076
- Adds missing `AdaptiveCard.refresh.userIds` property
- Adds support for `Action.Execute` and `AdaptiveCard.refresh` in the designer
- Note that the `AdaptiveCard.authentication` property isn't surfaced in the designer, at least not at this time. This is typicall a property that a service will dynamically add to a card, not something that is "authored"
- Fixes a couple designer bugs related to serialization
```
{
"version": "1.4",
"refresh": {
"userIds": [
"john.doe@contoso.com",
"jane.doe@fabrikam.com"
],
"action": {
"type": "Action.Execute",
"id": "abc",
"verb": "refreshAction",
"data": {
"property1": "value1"
}
} …
```

[JS] Universal Action designer support + some bug fixes

---

samples/v1.5/Elements/TextBlock.Style.json
samples/v1.5/Scenarios/InputFormWithLabels.json
source/shared/cpp/AdaptiveCardsSharedModel/AdaptiveCardsSharedModelUnitTest/EverythingBagel.cpp
source/shared/cpp/AdaptiveCardsSharedModel/AdaptiveCardsSharedModelUnitTest/ObjectModelTest.cpp
source/shared/cpp/ObjectModel/Enums.cpp
source/shared/cpp/ObjectModel/Enums.h
source/shared/cpp/ObjectModel/TextBlock.cpp
source/shared/cpp/ObjectModel/TextBlock.h

Fixed #5475
Added Support for TextBlock heading to the shared model.
1. Added and ran new unit tests.
2. Ran existing unit tests

[shared] Parser support for TextBlock headings changes

---

samples/1.5/Tests/AdaptiveCard.Rtl.False.json
samples/1.5/Tests/AdaptiveCard.Rtl.True.json
samples/1.5/Tests/AdaptiveCard.Rtl.unset.json
source/nodejs/adaptivecards/src/card-elements.ts

Untracked. JS is only respecting explicit rtl: false if a parent Element has rtl: true.
This explicitly sets or unsets the dir property. Additionally, allows the browser to set text alignment based on the inherited layout direction, rather than using the card tree to determine alignment.
`v1.5\Tests\AdaptiveCard.Rtl.unset`
`v1.5\Tests\AdaptiveCard.Rtl.True`
`v1.5\Tests\AdaptiveCard.Rtl.False`
`v1.5\Tests\AdaptiveCard.Rtl.unset`, `document.dir=ltr`:
`v1.5\Tests\AdaptiveCard.Rtl.unset`, `document.dir=rtl`:
`v1.5\Tests\AdaptiveCard.Rtl.True`, `document.dir=ltr`:
`v1.5\Tests\AdaptiveCard.Rtl.True`, `document.dir=rtl`:
`v1.5\Tests\AdaptiveCard.Rtl.False`, `document.dir=ltr`:
`v1.5\Tests\AdaptiveCard.Rtl.False`, `document.dir=rtl`:

[JS] Handle explicit rtl: false

---

samples/v1.5/Elements/Column.Rtl.json
samples/v1.5/Test/RtlTestCard.json
source/dotnet/Library/AdaptiveCards.Rendering.Wpf/AdaptiveCardRenderer.cs
source/dotnet/Library/AdaptiveCards.Rendering.Wpf/AdaptiveColumnRenderer.cs
source/dotnet/Library/AdaptiveCards.Rendering.Wpf/AdaptiveContainerRenderer.cs
source/dotnet/Library/AdaptiveCards.Rendering.Wpf/AdaptiveRenderContext.cs
source/dotnet/Library/AdaptiveCards/AdaptiveCard.cs
source/dotnet/Library/AdaptiveCards/AdaptiveColumn.cs
source/dotnet/Library/AdaptiveCards/AdaptiveContainer.cs
source/dotnet/Library/AdaptiveCards/Globals.cs
source/dotnet/Test/AdaptiveCards.Test/SerializationTests.cs

Fixes #5486 
Fixes #5487
Add RTL support to container and column in .NET and WPF
samples/v1.5/Elements/Column.Rtl.json
samples/v1.5/Elements/Container.Rtl.Json
samples/v1.5/Test/RtlTestCard.json
- Unit tests to validate Serialization of new property
- Sample cards validated in the visualizer

[.NET] Add RTL support to WPF renderer

---

source/shared/cpp/AdaptiveCardsSharedModel/AdaptiveCardsSharedModelUnitTest/ObjectModelTest.cpp
source/shared/cpp/ObjectModel/ChoiceSetInput.cpp

Fixed #5513 
* Tested & Verified on UWP/.net/iOS
1. New unit test is added.
2. Run the corresponding visualizers on each platform.s

[Shared] Changed choices an optional property of Input.ChoiceSet

---

source/nodejs/adaptivecards-site/themes/adaptivecards/layout/explorer.ejs

Fixes #5642
Minor oversight -- element descriptions should be markdown processed for display
* local build

[Site] Process explorer element descriptions with markdown

---

source/dotnet/Test/AdaptiveCards.Test/SerializationTests.cs
source/nodejs/.eslintrc.js
source/nodejs/adaptivecards-controls/src/inputwithpopup.ts
source/nodejs/adaptivecards-designer/src/draggable-element.ts
source/nodejs/adaptivecards-designer/src/field-picker.ts
source/nodejs/adaptivecards-designer/src/tree-view.ts

Fixes [ADO 30910259](https://microsoft.visualstudio.com/OS/_workitems/edit/30910259)
FieldPicker sets its focus on a container view, which isn't useful for keyboard users. PR changes it to set focus on root tree item instead.
N/A
Local build:

[Designer][Accessibility] Set FieldPicker initial focus to first item

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/IOverflowActionRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/OverflowActionLayoutRenderer.java

List of secondary action views are passed while rendering the Overflow "..." action menu, So the client can display the actions at anytime.
`View onRenderOverflowAction(@NonNull ViewGroup viewGroup, @NonNull List<View> menuItemList, boolean isRootLevelActions)`

[Android] Added menu items while rendering Overflow action view.

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRChoiceSetViewDataSource.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRInputChoiceSetRenderer.mm

Fixed #5399 
- Overriden the default padding provided by default UITableViewCell
- Set proper frames to subviews in `layoutSubviews` lifecycle method
```json
{
"body": [
{
"text": "Choose specific types:",
"wrap": true
},
{
"columns": [
{
"width": "stretch",
"items": [
{
"choices": [
{
"title": "Full-time",
"value": "1"
},
{
"title": "Hourly",
"value": "2"
},
{
"title": "Agency",
"value": "3"
}
],
"placeholder": "Please choose employee type (All, Ford, or Agency)",
"id": "employee_1",
"isMultiSelect": true,
"style": "expanded",
"value": "0",
"wrap": true
}
]
},
{
"width": "stretch",
"items": [
{
"choices": [
{
"title": "Joint Venture", …
```

[iOS][ColumnSet] ChoiceSet inside ColumnSet has improper layout

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/AdaptiveCardRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/BaseActionElementRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/OverflowActionLayoutRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/action/DropdownElementRenderer.java

Dropdown item rendering is refactored, so the dropdown items can behave like primary action elements even if the client uses CustomActionRenderer.
For inline cards, rootLevelActions should be false. fixed.

[Android] Dropdown item rendering refactored.

---

source/nodejs/ac-typed-schema/package.json
source/nodejs/adaptivecards-aaf-testapp/package-lock.json
source/nodejs/adaptivecards-controls/package-lock.json
source/nodejs/adaptivecards-designer-app/package-lock.json
source/nodejs/adaptivecards-designer/package-lock.json
source/nodejs/adaptivecards-fabric/package-lock.json
source/nodejs/adaptivecards-site/package-lock.json
source/nodejs/adaptivecards-visualizer/package-lock.json
source/nodejs/adaptivecards/package-lock.json
source/nodejs/spec-generator/package-lock.json

Updated package dependencies via `lerna-audit`. Note that this also fixes spaces→tabs in ac-typed-schema's package.json
* local build

[JS] Update npm package dependencies

---

schemas/1.5.0/adaptive-card.json
schemas/host-config.json
schemas/src/elements/TextBlock.json
schemas/src/elements/inlines/TextRun.json
schemas/src/enums/TextBlockStyle.json

Fixes #5637
- Updates to Adaptive Cards schema (Adaptive cards schema is generated via a tool from source files in schemas\src)
- TextBlock properties color, fontType, isSubtle, size, weight, and style are now nullable
- TextBlock properties color, fontType, isSubtle, size, and weight are now nullable
- Update Host Config schema  
- Rename TextBlockConfig to FactSetTextConfig
- Add TextStyleConfig and TextStylesConfig
- Add FontType to FactSetTextConfig (this should have already been there but was missing)

[Schema] Schema updates for Heading Styles

---

samples/Templates/Scenarios/ActivityUpdate.template.json
samples/Templates/Scenarios/ActivityUpdateWithLabels.template.json
samples/Templates/Scenarios/CalendarReminder.template.json
samples/Templates/Scenarios/CalendarReminderWithLabels.template.json
samples/Templates/Scenarios/ExpenseReport.template.json
samples/Templates/Scenarios/ExpenseReportWithLabels.template.json
samples/Templates/Scenarios/InputForm.template.json
samples/Templates/Scenarios/InputFormWithLabels.template.json
samples/Templates/Scenarios/Inputs.template.json
samples/Templates/Scenarios/InputsWithValidation.template.json
samples/v1.0/Scenarios/ActivityUpdate.json
samples/v1.0/Scenarios/CalendarReminder.json
samples/v1.0/Scenarios/InputForm.json
samples/v1.0/Scenarios/Inputs.json
samples/v1.2/Scenarios/ExpenseReport.json
samples/v1.3/Scenarios/ActivityUpdateWithLabels.json
samples/v1.3/Scenarios/CalendarReminderWithLabels.json
samples/v1.3/Scenarios/ExpenseReportWithLabels.json
samples/v1.3/Scenarios/InputFormWithLabels.json
samples/v1.3/Scenarios/InputsWithValidation.json

[ADO 29462597](https://microsoft.visualstudio.com/OS/_workitems/edit/29462597)
Updates the scenario samples called out in the above ADO bug to use the newly introduced heading style. This will cause it to be reported correctly for accessibility.

[Samples] Update scenario samples to use heading style

---

.github/ISSUE_TEMPLATE/app_rendering_bug_report.md
.github/ISSUE_TEMPLATE/card_author_bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

N/A
Github labels aren't being applied to new issues. This PR adds commas ([see docs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/manually-creating-a-single-issue-template-for-your-repository)).

[Chore] Fix issue template labels

---

source/nodejs/adaptivecards/src/card-elements.ts

Fixes https://github.com/microsoft/AdaptiveCards/issues/5686
- A previous merge caused code that had been moved from one method to another to be exist in both methods. This PR removes the duplicated code.
- This bug applied to all inputs, not just Input.ChoiceSet
```json
{
"body": [
{
"type": "Input.Text",
"placeholder": "Placeholder text",
"label": "Text input label"
},
{
"choices": [
{
"title": "Choice 1",
"value": "Choice 1"
},
{
"title": "Choice 2",
"value": "Choice 2"
}
],
"placeholder": "Placeholder text",
"label": "ChoiceSet input label"
}
]
}
```

Fix duplicate aria-labelledby ids in inputs

---

.gitignore
Package.swift

Fixed #4875
Added Swift Package Manager support.
N/A
1. checked compilation.
2. can&will test publishing after the PR is merged.

[iOS] Added Swift Package Manager Support

---

source/android/adaptivecards/src/main/cpp/.gitattributes
source/android/adaptivecards/src/main/java/io/adaptivecards/.gitattributes

N/A
SWIG-generated files aren't useful in PR diffs, so this tells Github to auto-hide them during reviews (additionally, removes them from repo language statistics). See: [linguist-generated](https://github.com/github/linguist/blob/master/docs/overrides.md#generated-code).

[Chore] Mark SWIG files as generated

---

source/shared/cpp/AdaptiveCardsSharedModel/AdaptiveCardsSharedModelUnitTest/HostConfigTest.cpp
source/shared/cpp/ObjectModel/Enums.cpp
source/shared/cpp/ObjectModel/Enums.h
source/shared/cpp/ObjectModel/HostConfig.cpp
source/shared/cpp/ObjectModel/HostConfig.h

Fixes #5854
Now that the heading styles HostConfig changes are in, we can get `columnHeader` in.
* new unit tests

[Shared] Add columnHeader HostConfig object

---

source/nodejs/adaptivecards/src/registry.ts

Fixes https://github.com/microsoft/AdaptiveCards/issues/5863
Note this issue has not been shipped, so it isn't an actual problem (unless of course it isn't fixed before we ship)
The Table work introduced a change in how (or more accurately "when") built-in elements and actions are registered. Namely, the model is now that code files that declare an element or action are also responsible for registering them into the GlobalRegistry instead of the GlobalRegistry registering all built-in components itself. This change was made in order to remove a circular reference between `card-elements.ts` and `registry.ts` and allow the Table implementation to be segregated into its own code file, `table.ts`. The change will also facilitate a future reorganization of the code where the code for other …

[JS] Fix regressions causing GlobalRegistry not to be initialized

---

source/nodejs/adaptivecards/src/card-elements.ts

Fixes https://github.com/microsoft/AdaptiveCards/issues/5450
Action.ShowCard would always expand the action's card inline even if HostConfig was configured with `"actions.showCard.mode": "popup"`. This change fixes that.
The default card in the designer will do, but testing this also requires a HostConfig configured as described above.

[JS] Don't expand ShowCard inline in Popup mode

---

source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer/ViewController.m

Fixed #5559 
Sample app refreshes the row using the visible row property of a UIViewTable when input validation returns the result.
The visible row values are unreliable since the value gets cleared when the table is reloaded. Changed to begin and endUpdates calls.
If appropriate, please include a link to a card in one of the samples directories that can be used to validate this change. This can be an existing card or a card added with this PR.

[iOS] Fixed #5559

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/BaseCardElementRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/registration/CardRendererRegistration.java

Fixes #5464 
The wrong view was being assigned to tagContent's stretchContainer. Additionally, isVisiblity did not include a null-check before accessing stretchContainer. Fixed, so isVisibility: false doesn't cause the renderer to fail when height is Stretch.
Sample card in issue.
Manually verified sample card works as expected.

[Android] Fix isVisible: false when height is Stretch

---

source/android/gradle/wrapper/gradle-wrapper.properties

Failing Android pipelines
Bump gradle version to fix unreliable downloading of dependencies in CI.
N/A
Verified with CI runs

[Android] Bump gradle 6.1 to 6.7

---

source/community/reactnative/src/components/elements/image.js
source/community/reactnative/src/components/inputs/choice-set/check-box.js
source/community/reactnative/src/components/inputs/choice-set/choice-set-input.js
source/community/reactnative/src/components/inputs/input-label.js
source/community/reactnative/src/components/inputs/picker-input.js
source/community/reactnative/src/components/inputs/toggle-input.js

Input controls were not usable on iOS - user was blocked from selecting radio buttons, checkboxes, and switches.
Checked/unchecked state not defined for radio button and checkbox.
Validated using the cards in Visualizer app.

[React-Native] Screen reader accessibility fixes

---

source/community/reactnative/src/components/inputs/choice-set/choice-set-input.js
source/community/reactnative/src/components/inputs/picker-input.js
source/community/reactnative/src/styles/style-config.js
source/community/reactnative/src/utils/enums.js
source/community/reactnative/src/utils/theme-config.js

Added Support for the below elements:
- Picker
- DateTimePicker
Default values are below:
```css
{
picker: {
backgroundColor: "lightgrey"
borderColor: "lightgrey"
borderRadius: 5
borderWidth: 1
color: "#000000"
marginHorizontal: 2
},
dateTimePicker: {
backgroundColor: "white"
height: 260
textColor: "#000000"
width: "100%"
}
}
```

Theme config support for Picker and DateTimePicker

---

source/community/reactnative/src/components/containers/factset.js
source/community/reactnative/src/components/inputs/input-label.js
source/community/reactnative/src/components/inputs/input.js

The inline-action buttons had no role or name assigned previously. This PR adds the name, role and disabled state.
Also concatenates the Label and Asterisk in a single narration.
Also concatenate the fact set label and value into a single announcement.

Accessibility fix for inline-actions on inputs

---

source/community/reactnative/src/components/elements/background-image.js

On iOS, the background image was focussed by the screen reader even in absence of altText. This is undesirable behavior. This PR fixes that.
Verified on: Visualizer App

bg image shouldnt be focussed if altText is not present

---

samples/v1.2/Tests/Action.ToggleVisibilityExhaustive.json

Fixes #5098 
Adding simpler example to docs and moving exhaustive sample to test cases. This allows users to see the text in the buttons that was cut off in the previous example.

Adding simpler example to docs

---

source/nodejs/adaptivecards-site/themes/adaptivecards/layout/designer.ejs

Fixes #6021 
Clicking designer feedback button now links to the GitHub designer issue template
Verified to open the following page

Added designer feedback button link to the GitHub designer issue template

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/TextInputRenderer.java

Fixes #5349 
Adds extra case validation for the special case of an Input.Element having the `Multiline` property set to `true` and the `Height` set to `stretch`. The changes deal with using setMinLines instead of setLines and updating the underlying LayoutParams height to match the parent container's height.
Included in the bug description
The fix was verified by rendering the linked card in the mobile app

[Android] Update Input.Text rendering for stretched multilined elements

---

source/community/reactnative/src/components/inputs/choice-set/choice-set-input.js
source/community/reactnative/src/utils/theme-config.js

Resolved the border/background color styling issues in picker android

Resolved android picker styling issues

---

source/nodejs/adaptivecards-react/README.md
source/nodejs/adaptivecards-react/package.json

Fixing a small typo in the adaptivecards-react readme that referenced the wrong npm package

Fixing adaptivecards-react readme typo

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/ActionLayoutRenderer.java

A card has only secondary actions without any primary actions is not rendering correctly.  This issue happens only if any one of the secondary action is a `ShowCard` action type.
There may be a case where `Secondary Actions` can exist without `Primary Actions`, so to fix that size check is removed for `Primary Actions`. This ensures that the action layout container is added for `Secondary Actions` even.
```
{
"body": [
{
"size": "large",
"text": "Overflow Action Test Card",
"weight": "bolder",
"type": "TextBlock"
},
{
"text": "ActionSet **all secondary actions**",
"type": "TextBlock"
},
{
"actions": [
{
"data": {
"key": "Submit from overflow menu"
},
"title": "Action Submit",
"mode": "secondary",
"type": "Action.Submit"
},
{
"url": …
```

[Android] [Overflow Actions] Fix - Secondary Actions not rendered properly without primary actions

---

.github/ISSUE_TEMPLATE/config.yml

Enabling Blank Issues for team internal use *only*

Enabling blank issues for internal team use

---

source/dotnet/Samples/AdaptiveCards.Sample.Html/AdaptiveCards.Sample.Html.csproj
source/dotnet/Samples/WPFVisualizer.PackageProject/AdaptiveCards.Sample.WPFVisualizer.PackageProject.wapproj
source/dotnet/Samples/WPFVisualizer/AdaptiveCards.Sample.WPFVisualizer.csproj
source/dotnet/Test/AdaptiveCards.Rendering.Html.Test/AdaptiveCards.Rendering.Html.Test.csproj
source/dotnet/Test/AdaptiveCards.Templating.Test/AdaptiveCards.Templating.Test.csproj
source/dotnet/Test/AdaptiveCards.Test/AdaptiveCards.Test.csproj

Fixes #6455
This probably warrants a longer explanation, but the short of it is that the latest VS tools release breaks some Nuget tooling in some specific scenarios (that unfortunately apply to us). This appears to only have affected the `.NET Core 3.x` SDK tooling. `.NET 5` (basically the latest version of .NET Core - ask me for a .NET versioning rant sometime) is sufficiently different such that it's apparently unaffected. This change moves our .NET Core projects over to `.NET 5`. I've already updated the build pipeline to pull the `5.x` SDK. It's worth calling out that the updated projects don't impact our platform packages (just tests and the visualizer).

[.NET] Update to .NET 5

---

source/nodejs/adaptivecards/src/host-config.ts

Fixes #6613
I think that the defaults for Javascript's default HostConfig for Labels and ErrorMessage were chosen in order to make it easy to test to make sure that they were being applied correctly during development. However, they don't really make for an appealing default experience, so we're changing them to be more in line with what we'd expect most hosts want.
One place you can see the defaults in action is inside the Designer's `New Card` dialog:
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
* local build and devtools

[JS] More reasonable HostConfig label defaults

---

source/nodejs/adaptivecards/package.json

Just a minor oversight - the version of `jest` I saw recommended to fix our problems consuming the `swiper` module ended
up being a pre-release version. `jest@^27` and `ts-jest@^27` have since had full releases, so I just wanted to make sure we were requiring them specifically. For what it's worth, we weren't actually *using* the prerelease versions (see below), but all the same it's better to declare our dependency against a full-fledged release.
https://github.com/microsoft/AdaptiveCards/blob/2c3f8530556213a1a1f5ed742b62c28f24a4c24d/source/nodejs/adaptivecards/package-lock.json#L4485-L4486
* verified unit tests still pass

[JS] Pin newer `jest` and `ts-jest` dependencies for `adaptivecards`

---

source/uwp/ObjectModelProjection/ObjectModelProjection.vcxproj

Add control guard on all flavors of binaries
Fixes #6730 
**NOTE**: For multiple issues resolved by this PR use the corresponding keywords **every time** in a comma-delimited list per the reference
page above.
Enable control flow guard on ObjectModelProject.vcxproj
If appropriate, please include a link to a card in one of the samples directories that can be used to validate this change. This can be an existing card or a card added with this PR.
-<todo> Build Solution in for all platforms

[UWP]: Update ObjectModelProjection.vcxproj to have control flow guard

---

source/nodejs/adaptivecards/src/card-elements.ts

Fixes #6425
Fixes #6019
Remove the `menubar` role from `ActionCollection` (as well as `aria-posinset`, `aria-setsize`, and `role='menuitem'` from children).  This was originally part of a fix to expose actions in a set to address a different accessibility concern (see #4184) -- namely that actions in an `ActionSet` should be presented in such a way that AT can tell the user how many actions there are. The way you do that is via `aria-posinset` and `aria-setsize`, which are only applicable to a limited number of roles (`button` and `link` [not being among them](https://www.w3.org/TR/wai-aria/#aria-posinset)). There can, of course, only be one `role` applied to an element, so we must unfortunately choose to stick with `button` or `link` and remove the other attributes.
* local build, …

[JS] Remove `role='menubar'` from `ActionCollection`

---

source/nodejs/adaptivecards/src/card-elements.ts

#6810 
See #6810 for details
```JSON
{
"$schema": "https://adaptivecards.io/schemas/adaptive-card.json",
"body": [
{
"text": "[**hyperlink strong**](https://microsoft.com)"
}
]
}
```
1. Register `onAnchorClicked()` callback to SDK
2. Send a card as above
3. Expect `onAnchorClicked()` with target of `<a>` tag with `href` rather than `<strong>` tag

[JS] Fix #6810: onAnchorClicked() should pass the anchor element itself

---

source/ios/tools/AdaptiveCards.podspec

Host application is not able to find the AdaptiveCards.bundle when SDK is consumed without `UIProvider`
This fix moves the resource bundle from root spec to `AdaptiveCardsCore` spec. 
Build the product and verify that `AdaptiveCards.bundle` is present in the build directory. The consumption is done adding the pod to a podfile
pod 'AdaptiveCards' ~> 'x.x.x'
AND
pod 'AdaptiveCards/AdaptiveCardsCore' ~> 'x.x.x'
pod 'AdaptiveCards/AdaptiveCardsPrivate' ~> 'x.x.x'
pod 'AdaptiveCards/ObjectModel' ~> 'x.x.x'

Moving resource bundle to core

---

source/uwp/UWPUITests/TestHelpers.cs
source/uwp/UWPUITests/UITest.cs

Fix 2022 year issue: `Assert.AreEqual failed. Expected:<2021-07-16>. Actual:<2022-07-16>. Values for input dueDate differ`
SetDateToUIElement didn't take year and day. So remove the year from the function.

Fix uwp-ci test failure on ActivityUpdateSmokeTest

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRImageRenderer.mm

Teams application when using a subclass of ACRImageRenderer as a CustomImageRenderer, crashes on some magic ratio number, when a card of a certain payload is expanded.
Issue is being fixed by making sure that ratio is rounded of to 2 decimals, keeping the image as accurate as it can be, and avoiding a magic ratio number on which apple has some crash
{
"body": [
{
"height": "auto",
"url": "https://picsum.photos/744/84",
"altText": "Power Automate approvals logo"
},
{
"size": "large",
"weight": "bolder",
"text": "Review new SharePoint file 'AppInstallViewData.json'"
},
{
"text": "Requested by Sagar Pant <Pant.Sagar@microsoft.com>",
"wrap": true
},
{
"facts": [
{
"title": "Date Created", …

Rounding off to 2 decimals for constraint multiplier for Image Renderer

---

.pipelines/clang-format-ci.yml
source/nodejs/ac-typed-schema/package-lock.json
source/nodejs/adaptivecards-designer-app/package-lock.json
source/nodejs/adaptivecards-designer/package-lock.json
source/nodejs/adaptivecards-react-testapp/package-lock.json
source/nodejs/adaptivecards-react/package-lock.json
source/nodejs/adaptivecards-site/package-lock.json
source/nodejs/adaptivecards-templating/package-lock.json
source/nodejs/adaptivecards-ui-testapp/package-lock.json
source/nodejs/adaptivecards/package-lock.json
source/nodejs/marked-schema/package-lock.json
source/nodejs/package-lock.json
source/nodejs/package.json
source/nodejs/spec-generator/package-lock.json

Because of https://github.com/microsoft/AdaptiveCards/pull/6639, package-lock.json should be `"lockfileVersion": 2`
Look like someone is not using the last npm package.
This problem is addressed by clang-format-ci pipeline
Note: git status check is disabled by default in clang-format-launcher 0.1.4, so it will not catch package-lock issue in the future

update package-lock.json and use npm latest

---

source/nodejs/.husky/pre-commit

Because of #6895, skip the lint-staged
This need to be re-enabled after this issue is resolved.

skip npx lint-staged on the hook

---

source/nodejs/adaptivecards-designer/src/containers/viva-connections/viva-connections-container.css

This PR sets the cursor to pointer when hovering over `ColumnSet`s that are clickable (when `selectAction` is set to `Action.OpenUrl`), in Viva Connections cards in the card designer. This is in sync with changes to Viva Connections itself. This is a very minor one-line change.

[cad-designer: viva connections] Set cursor to pointer for clickable quick view ColumnSets

---

source/nodejs/adaptivecards-designer/src/card-designer.ts

#7015 
We add the hint about `ctrl+m` toggling the tab behavior to the label of the card editor.
Tested using narrator, the new label gets announced

Convey Ctrl+M shortcut key to move out of code editor

---

source/nodejs/adaptivecards-site/themes/adaptivecards/source/css/style.css

#6420 
Change the colorr of the links to be a darker blue so that the contrast ratio is now 4.5:1
Using accessibility insights on the new colour and verified that the contrast ratio is now 4.5:1

Fix luminosity ratio of links in footer of website

---

source/nodejs/adaptivecards-designer/src/help-dialog.ts

#6276 
Use heading levels `h2` and `h3` instead of `h1` and `h2`
Manually verified by opening the Help dialog after making the change

Fix heading levels for 'Card Payload and Data Sample Editors' and 'Keyboard shortcuts' headings in Help dialog

---

source/nodejs/adaptivecards-designer/src/adaptivecards-designer.css

#7013 
Use a resource color (`InactiveCaptionText`) for setting the color of the 'redo' button instead of hard coding `lightgray`. 
Manually verified by setting a high contrast theme and observing the color of the inactive redo button.

Change the color of the 'redo' button so that it is able to adopt the high contrast theme color

---

source/nodejs/adaptivecards-site/themes/adaptivecards/layout/index.ejs

#6422
The screen reader was not reading out the correct thing for the close video button. Adding an aria label fixes that.
Screen reader now says 'close video group' for the close video button

Add aria label to close video button

---

source/dotnet/Library/AdaptiveCards/AdaptiveRefresh.cs
source/dotnet/Library/AdaptiveCards/docs/AdaptiveCards.md
source/dotnet/Test/AdaptiveCards.Test/AdaptiveCardApiTests.cs

Small codefix to fix #6862 .
Solved by setting the correct naming strategy on class AdaptiveRefresh.
Added unit test to verify fix.
All tests passing.

Small codefix to fix problem described in #6862

---

source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizerUITests/ADCIOSVisualizerUITests.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRChoiceSetCompactStyleView.mm

Fixes issues where ui unit test failures.
#7114 - Bug opened to track improvement on swipe calls
https://github.com/microsoft/AdaptiveCards/pull/7100
* with input added, texts got wrapped and made the card longer.
* 'ok' button is pushed down and became hidden.
* added `swipe up` motion to the unit tests to bring up the ok button.
* added accessibility label to filtered list input.
*

fixed unit tests

---

source/nodejs/adaptivecards-designer/src/toolbar.ts

#7116 
For toolbar buttons, we now set the tab index to be -1 if it is disabled or 0 if it is enabled (so it is no longer possible to tab to it when it is disabled, but it is still possible to tab to it when it is enabled).
N/A

Tab focus can no longer land on disabled 'undo'/'redo' buttons

---

source/nodejs/adaptivecards-designer/src/adaptivecards-designer.css

Closes #7109
Adjusts the color of the designer's peer buttons (i.e. bind, close, drag) to match that of the warning/error message. This makes the color contrast 4.537:1, which is acceptable for regular text and graphical UI controls.

Adjust contrast on designer peer buttons

---

source/nodejs/adaptivecards-controls/src/dropdown.ts

Close #7117 
Updates the role of the `Select Host App` combo box in the designer from `button` to `combobox`

Update role of 'Select Host App' combobox

---

source/nodejs/adaptivecards-site/themes/adaptivecards/layout/_partial/header.ejs

#7144 
Assigning the role of 'complementary' to the `content-header` puts it under a `complementary` landmark for accessibility
N/A
Using accessibility insights, the breadcrumb bar, feedback link, github link are now under a landmark

Put the breadcrumb bar, feedback link and github link under a landmark

---

source/nodejs/adaptivecards-designer/src/card-designer-surface.ts

#7152 
Focus was mistakenly falling onto the `acd-designersurface`, despite there not being any purpose for it to be there (the control cannot be activated). This commit makes it so focus no longer can fall onto `acd-designersurface`, preventing focus from seemingly becoming 'lost' when navigating out of the adaptive card in designer mode.
N/A
Manual verification, focus no longer gets lost.

Don't let focus fall on acd-designersurface

---

source/nodejs/adaptivecards-site/themes/adaptivecards/layout/_partial/header.ejs

#7137 
Add a 1px left margin to the documentation item in the header so the focus indicator does not get cut off when the page is resized to 200%.
N/A
Manual verification, cannot repro the bug anymore

Add a 1px left margin to the Documentation item in the header

---

source/nodejs/adaptivecards-site/themes/adaptivecards/source/css/style.css

Closes #7143 
The horizontal scroll bar is appearing sometimes because the blog post titles are too long! This causes the hyperlinks in the footer to overflow and introduces a horizontal scrollbar. The fix here is to allow the hyperlinks to wrap. So if we update the `white-space` styling to `break-word`, we get it to wrap.

Allow footer hyperlinks to wrap

---

source/dotnet/Library/AdaptiveCards.Templating/AdaptiveCardsTemplateVisitor.cs
source/dotnet/Test/AdaptiveCards.Templating.Test/TestTransform.cs

Fixes #6854 
Boolean expressions were evaluating to `True`/`False` instead of `true`/`false`.  Boolean.ToString() capitalizes the string value, so we must convert to lowercase before appending to result.
Sample template:
```
{
"body": [
{
"size": "Medium",
"text": "Title is ${title != ''}"
}
],
"version": "1.5"
}
```
Sample Data:
```
{
"title": ""
}
```
Output should be "Title is false"
Verified on WPF Visualizer

[.NET Templating] Update Boolean expression evaluation

---

source/dotnet/Library/AdaptiveCards.Templating/AdaptiveCardsTemplateVisitor.cs
source/dotnet/Test/AdaptiveCards.Templating.Test/TestTransform.cs

Fixes #6680 
Commas were sometimes being added unnecessarily which resulted in invalid JSON. I updated `TemplateVisitor` to only add commas if there is an object prior and another object is about to be added.
Card:
```
{
"body": [
{
"$data": "${foo}",
"$when": "${$index==0}"
},
{
"$data": "${foo}",
"$when": "${$index>0}"
}
]
}
```
Data:
```
{
"foo": [{}, {}]
}
```
Verified manually and with the added unit tests.

[.NET Templating] Resolve commas added in wrong place

---

source/dotnet/Library/AdaptiveCards.Templating/AdaptiveCardsTemplateResult.cs
source/dotnet/Library/AdaptiveCards.Templating/AdaptiveCardsTemplateVisitor.cs
source/dotnet/Test/AdaptiveCards.Templating.Test/TestTransform.cs
source/nodejs/adaptivecards-templating/src/template-engine.ts
source/nodejs/tests/unit-tests/src/unit-tests.test.ts

Fixes #6630 
Realign expected behavior for invalid boolean expressions for $when on JS and .NET Templating platforms.
Scenarios:
- If the given string is not an expression (ex: `"$when": "notAnExpression"`)
- If the given expression is invalid/not found in data (ex: `"$when": "${invalidExpression}"`)
In both scenarios, the $when condition should evaluate to `false` (drop the element) and issue a warning.
```
{
"body": [
{
"size": "Medium",
"weight": "Bolder",
"text": "${title}",
"$when": "NotAnExpression"
}
],
"version": "1.5"
}
```
```
{
"body": [
{
"size": "Medium",
"weight": "Bolder",
"text": "${title}",
"$when": …
```

[Templating] Realign platforms on invalid $when behavior

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/FactSetRenderer.java

[Factset accessibility issue](https://github.com/microsoft/AdaptiveCards/issues/6752)
Fixes #6752  
FactSets TextViews are wrapped under multiple ViewGroups, and further nesting, like having FactSets cards view under RecyclerViews is making Android accessibility services to skip factset data for talkBack (sometimes). 
So marking these TextViews as important for accessibility explicitly
-- Newer API (for API26 and above) setScreenReaderFocusable() is used
-- Handled backward Compatibility also
**Solution reference**: [Principles for improving app accessibility](https://developer.android.com/guide/topics/ui/accessibility/principles#content-groups)
**Expense report example of Adaptive Cards Visualizer (sample app)**
```
{
"body": [
{
"style": …
```

[Android][FactSets]: Mark textViews important for accessibility explicitly

---

source/dotnet/Library/AdaptiveCards.Templating/AdaptiveCardsTemplateSimpleObjectMemory.cs
source/dotnet/Library/AdaptiveCards.Templating/AdaptiveCardsTemplateVisitor.cs
source/dotnet/Test/AdaptiveCards.Templating.Test/TestTransform.cs

Fixed #7464, Fixed #7448 
1. unescaped on data
2. serialize only if data is not json.
N/A
1. New unit test is added.
2. Verified with all existing template samples

Updated Template

---

source/nodejs/adaptivecards-designer-app/package-lock.json
source/nodejs/adaptivecards-designer/package-lock.json
source/nodejs/adaptivecards-react-testapp/package-lock.json
source/nodejs/adaptivecards-templating/package-lock.json
source/nodejs/package-lock.json

Fix pipeline error:
```
npm ERR! code EUSAGE
npm ERR! 
npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR! 
npm ERR! Invalid: lock file's acorn@7.3.1 does not satisfy acorn@8.7.1
npm ERR! Missing: acorn@7.4.1 from lock file
```
Possible reason:
1. Some package changed their dependency and force acorn@8.7.1 is used somewhere
2. Or We are using the default npm from [hosted agent](https://github.com/actions/virtual-environments/pull/5705/files) which is upgraded to npmjs from 8.5 to 8.11.
If it's the 2nd one, all dev has to run below command in local dev machine
```
npm i -g npm@8.11.0
lerna clean
lerna bootstrap
npm i
```

update package-lock.json after using npm 8.11

---

source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer/ViewController.m

Fixed #6417, Fixed #6288
I could have closed the associated issue on the ground that this is a sample app issue, but customers can face similar issues, so I'm going to document it for future reference.
Updated sample app to notify VO of layout changes triggered by toggle events.
Used Accessibility Inspector to examine each accessibility element to verify.
Used VO on iPhone 5 H/W to cross-check.

sample notifies VO of layout change with showcard toggle events

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/RendererUtil.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/TextBlockRenderer.java

Fixes #7034 
Adds some logic to verify if any links were found in TextBlocks, if so then focus can be applied to them, otherwise keyboard navigation skips them.

Add conditional for stoping in some textblocks

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRRichTextBlockRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRUILabel.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRUILabel.mm

Fixed #6283 
Added Link Attribute for VO to detect the inline actions as links.
Added a workaround for Apple Bug where iOS12 and above fails VO unless editable is set YES.
1. Verified manually with relavant cards.

added link navigation to acessibility

---

samples/v1.0/Scenarios/SportingEvent.json

Fixes https://github.com/microsoft/AdaptiveCards/issues/7033
Android supports a large set of devices, each with a different screen resolution and other display differences, as such, usually apps can pick smaller images for phones with smaller screens, AC doesn't support that, as such, even when a card is good in one phone it isn't in other phones, in the case of the sporting event card it's good in phones with better display resolutions but not accessible on small resolution phones. 
The fix is changing the size of the images in the SportingEvent card, the code accurately resizes the images shown so it's not a code issue but some screens are narrower than others so the only viable fix is updating the card.

[a11y] Update SportingEvent sample

---

source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer.xcodeproj/project.pbxproj
source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer/AdaptiveFileBrowserSource.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards.xcodeproj/project.pbxproj

Fixed issue where APP Release flag fails UIUnit test after limiting the sample scopes.
Added a new build config only for App Release flag for A11y which is based on Release config.

Updated Sample App Release Flag

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRActionOverflowRenderer.mm

Fixed #7027 
The mode button's role was wrongly assigned as a link. Removed it as the additional role isn't needed.
Manually verified it.

removed wrong role assignment

---

source/nodejs/adaptivecards-designer/src/designer-peers.ts

We needed to add `rtl` support to the designer for the following elements: `AdaptiveCard`, `Container`, `Column`, and `TableCell`.
The cards already supported `rtl`, but we needed a way to enable/disable the feature from the `Element Properties` pane.
You can now enable/disable `rtl` within the designer for the expected properties as shown below:
Verified manually in the designer.

[Designer] Add right to left support to designer

---

source/nodejs/adaptivecards/package-lock.json
source/nodejs/adaptivecards/package.json
source/nodejs/adaptivecards/src/card-elements.ts
source/nodejs/adaptivecards/src/carousel.ts
source/nodejs/adaptivecards/src/enums.ts

Fixed #7512 
* generate events of carousel page transitions initiated by clicking next navi button and prev navi button, for autoplay, and for pagenation.
* Updated swiper version to be able to listen on navi button click events.
* added the event handler hook.
| Capability      | Priority | Status |
| ----------- | ----------- | -- |
| Event for when user clicks the next arrow on the carousel | Must | Implemented |
| Event for when a user clicks the previous arrow on the carousel | Must | Implemented |
| Event for when a user navigates the carousel with the bottom dots | Must | Implemented |
| Which carousel pages did the user see vs not see | Must | Tools are provided and users to implement |
| How much time a user spent on a carousel and which page | Must | Tools are provided and users …

implemented carousel telemetry feature

---

source/nodejs/adaptivecards-designer/src/card-designer.ts
source/nodejs/adaptivecards-designer/src/open-sample-dialog.ts

Fixes #7687 
When creating a new card on the designer, you should be able to select a new card (blank or sample) with the enter key. We needed keyboard events in addition to the existing onClick events.
Verified manually on the adaptivecards-site

[Designer Accessibility] Make new card dialog more keyboard accessible

---

source/nodejs/adaptivecards-designer/src/card-designer-surface.ts

Fixes #7705 
Designer peers were not being added in the correct location when selecting `ShowCard` actions.
Verified manually on the adaptive cards site

Update handling of Actions for designer peer ordering

---

source/android/build.gradle
source/android/constants.gradle

Due to an update in the virtual environments, the default ndk version was removed making the default version used by gradle to be used (https://developer.android.com/studio/projects/install-ndk#apply-specific-version) which is a version not installed in the vm Image we use. For such reason gradle had to be updated to version 4.1.3.

[Android] Fix CI build break

---

source/nodejs/adaptivecards/src/card-elements.ts
source/nodejs/adaptivecards/src/carousel.ts

added an instance event handler

---

source/nodejs/adaptivecards/src/card-elements.ts

Fixes #7606 
When searching the card children for DOM node owner, we did not look in the actions.
Updated the method so that if it is not found in the child elements, we search the card actions before returning the card itself.
```
const card = new AdaptiveCard();
card.parse({
type: 'AdaptiveCard',
body: [
{
type: 'ActionSet',
actions: [
{
type: 'Action.OpenUrl',
title: 'Aloha!',
url: 'https://bing.com/'
}
]
}
],
actions: [
{
type: 'Action.OpenUrl',
title: 'Hello, World!',
url: 'https://bing.com/'
}
],
$schema: 'http://adaptivecards.io/schemas/adaptive-card.json',
version: '1.5'
});
const [firstButton, secondButton] = card.render().querySelectorAll('.ac-pushButton');
expect(firstButton.innerText).toBe('Aloha!');
expect(secondButton.innerText).toBe('Hello, World!');
const firstCardObject = …
```

[JS Renderer] Search card actions in findDOMNodeOwner

---

source/nodejs/adaptivecards-designer/src/containers/berlin/berlin-container-dark.css
source/nodejs/adaptivecards-designer/src/containers/berlin/berlin-container-light.css
source/nodejs/adaptivecards/src/carousel.ts

Because of the custom margins and padding on the carousel control in berlin containers, the carousel peer locations were not being calculated correctly.
The negative margins needed to be moved a level up in the DOM tree.
Verified manually in the Adaptive Cards designer.

[Designer] Update carousel styling for berlin containers

---

.pipelines/ios-app-push.yml
.pipelines/templates/ios-install-cert-template.yml

Fixed #7551 
* added a new pipeline that uses yml to publish ios app
* updated templates to use common variable name for cert.
verified that it can build & publish to appcenter.

Updated app push to use pre-existing yml templates

---

source/nodejs/adaptivecards/src/serialization.ts

Fixes https://github.com/microsoft/AdaptiveCards/issues/6631
Updated `setValue` and serialization methods so that values are not deleted from the `propertyBag` if `GlobalSettings.enableFullJsonRoundTrip === true`.
Note: Data binding will only work while in preview mode.
```
{
"version": "1.5",
"body": [
{
"text": "Image test:",
"wrap": true
},
{
"url": "https://pbs.twimg.com/profile_images/3647943215/d7f12830b3c17a5a9e4afcc370e3a37e_400x400.jpeg",
"width": "${imageSize}",
"height": "${imageSize}"
}
]
}
```
```
{
"imageSize": "100px"
}
```
Verified manually on the AdaptiveCards site

Enable data binding for the designer

---

source/nodejs/adaptivecards-designer/src/containers/berlin/berlin-container-dark.css
source/nodejs/adaptivecards-designer/src/containers/berlin/berlin-container-light.css

https://microsoft.visualstudio.com/OS/_workitems/edit/39752320
Increased hit target.
[reference](https://front-back.com/expand-clickable-areas-for-a-better-touch-experience/)
Manually verified as below
Previously the hit target was exactly the size of the bullet, with the change, the hit target is increased by 4px around the bullet. The exact size is not important as actual need is different from host app to host app.

[JS] Increased hit target of pagenation bullets

---

source/nodejs/adaptivecards-designer/src/containers/berlin/berlin-container-dark.css
source/nodejs/adaptivecards-designer/src/containers/berlin/berlin-container-light.css
source/nodejs/adaptivecards/src/scss/adaptivecards-carousel.scss

Fixed #7659 
Carousel paginations become blended to background in high contrast mode. 
This change addresses the issue by using @media and removing the high contrast changes and sets appropriate background color for pagination.
Manually verified as below.
Berlin dark
Berlin light

updated css

---

source/shared/cpp/AdaptiveCardsSharedModel/AdaptiveCardsSharedModelUnitTest/MarkDownUnitTest.cpp
source/shared/cpp/ObjectModel/MarkDownBlockParser.cpp
source/shared/cpp/ObjectModel/MarkDownBlockParser.h

Fixed #7812
1. parenthesis matching code didn't propagate the failure when there are more lpran than rpran.
2. removed popback() as it's not needed and caused the crash.
3. Added unit tests from #6922.
N/A
1. added new unit tests from #6922 & added some more for testing the change.

Fixed the hard crash at link parser

---

source/nodejs/adaptivecards-designer/src/designer-peers.ts

Fixes #7835 
When adding new pages to a carousel, we would sometimes call isVisible on a CarouselPage when it is not yet assigned to a Carousel. We needed to add a null check.
Verified manually on the designer

Add null check to parentCarousel

---

source/nodejs/adaptivecards/src/serialization.ts

Fixes #7843 
Not deleting the array property during serialization did not allow the container contents to update. We needed to delete array properties regardless of enableFullJsonRoundTrip settings.
Verified manually on the designer.
Before:
After:

Revert full JSON round trip for arrays

---

source/nodejs/adaptivecards/src/card-elements.ts
source/nodejs/adaptivecards/src/utils.ts

ttpolicy prefixed with package name
adaptivecards#markdownPassthrough
adaptivecards#restoreContents
adaptivecards#deprecatedExportedFunction

prefix adaptivecards#  for ttpolicy

---

source/nodejs/adaptivecards-site/_config.yml

Fixes #7643 
We generate html for the website using `ejs` files and by converting `md` files using `hexo-renderer-marked`. Therefore, the headings throughout the site were inconsistent.
All of the headings generated with `hexo-renderer-marked` contain a `headerlink`. See https://github.com/hexojs/hexo-renderer-marked/blob/a93ebeb1e8cc11e754630c0a1506da9a1489b2b0/lib/renderer.js#L21-L38.
Disabling `headerIds` fixes the discrepancy, and none of the headers contain links.
If we want to utilize header ids in the future, we can override the behavior `hexo-renderer-marked` (See https://github.com/hexojs/hexo-renderer-marked#extensibility). We would also need to update our `ejs` files so that all headers are consistent.

[JS Website] Disable headerIds for the markdown renderer

---

source/nodejs/adaptivecards-designer/src/adaptivecards-designer.css
source/nodejs/adaptivecards-designer/src/card-designer-surface.ts
source/nodejs/adaptivecards/src/card-elements.ts
source/nodejs/adaptivecards/src/utils.ts

Merge main to 22.09 branch and remove searchAndRemoveForbiddenElements

---

source/nodejs/adaptivecards-designer/package-lock.json
source/nodejs/adaptivecards-designer/package.json
source/nodejs/adaptivecards-extras-designer/webpack.config.js
source/nodejs/adaptivecards-extras/webpack.config.js
source/nodejs/adaptivecards-react-testapp/package-lock.json
source/nodejs/adaptivecards-react-testapp/package.json
source/nodejs/adaptivecards-react/webpack.config.js
source/nodejs/adaptivecards-site/_config.yml
source/nodejs/adaptivecards-site/package-lock.json
source/nodejs/adaptivecards-site/package.json
source/nodejs/adaptivecards-site/themes/adaptivecards/scripts/helper-properties-details.js
source/nodejs/adaptivecards-site/themes/adaptivecards/source/css/style.css
source/nodejs/adaptivecards-templating/webpack.config.js
source/nodejs/adaptivecards-ui-testapp/package.json
source/nodejs/adaptivecards/webpack.config.js
source/nodejs/lerna.json
source/nodejs/marked-schema/package-lock.json
source/nodejs/marked-schema/package.json
source/nodejs/nx.json
source/nodejs/package-lock.json
source/nodejs/package.json

As per usual, we do a round of dependency updates prior to releasing a new package. However, this time is a little different. Our beleaguered dependency, `lerna`, has undertaken active development once more! Lots of goodness (and it looks like there's more cool new stuff to come), but the biggest thing for us in this moment is that it's been totally updated to newer dependencies. This change includes both the conversion to the new major version of `lerna`, as well as a series of updates across our repo to get us up-to-date.
One really nice thing? Performing `npx lerna run build` will now use smarts and local caching to reduce build times:
Many thanks to @anna-dingler for seeing this through to the finish line (see #7818 for more info).

Update to new `lerna` version; audit package dependencies

---

.pipelines/js-release.yml

1. use npm 8.11.0. Look like the lerna requires newer npm version
2. it's not readable when error happens in bash, split it into multiple lines.

Update js-release.yml to use npm 8.11.0

---

source/nodejs/adaptivecards-designer/src/tool-box.ts
source/nodejs/adaptivecards-designer/src/toolbar.ts

Fixes #7917 
Some of the buttons in the Designer did not have an associated accessible name for Narrator.
Toolbox expand/collapse button needed to be labeled by the header text.
Toolbar buttons that only contain an icon need to specify the label.

[Designer] Assign names to icon buttons for Narrator

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRMediaRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRMediaTarget.mm

Fixed #7021 
* poster is used for activating the media, so it is an accessibility item; however with this arrangement, it makes its child elements such as media control inaccessible.
* made its parent view accessible and toggle off its a11y when media control appears, and notifies vo of view change to shift vo focus to the player control
https://github.com/microsoft/AdaptiveCards/blob/main/samples/v1.1/Scenarios/ProductVideo.json
3. Manually verified using the sample above.

fixed media control a11y issue

---

samples/v1.0/Scenarios/FoodOrder.json
samples/v1.0/Scenarios/WeatherLarge.json

Fixed #7875
Updated samples `wrap` property to true, so the text won't get clipped when the text is enlarged.

fixed words in sample getting clipped during narrator

---

source/nodejs/adaptivecards-designer/src/designer-peers.ts

Fixes #7961
Added the `initialPage` property to the `CarouselPeer`. This addition will show the new property in the Designer's Element Properties pane.
```
{
"version": "1.6",
"body": [
{
"type": "Carousel",
"initialPage": 2,
"pages": [
{
"type": "CarouselPage",
"id": "firstPage",
"items": [
{
"url": "https://picsum.photos/id/100/300/300",
"altText": "beach"
}
],
"rtl": false
},
{
"type": "CarouselPage",
"id": "secondPage",
"items": [
{
"url": "https://picsum.photos/id/110/300/300",
"altText": "sunset"
}
],
"rtl": false
},
{
"type": "CarouselPage",
"id": "thirdPage",
"items": [
{
"url": "https://picsum.photos/id/120/300/300",
"altText": "sunset"
}
], …
```

[Designer] Add the Carousel initialPage property to the designer

---

source/nodejs/adaptivecards-designer/src/toolbar.ts

Fixes #7931
For the designer's toolbar choicePicker, we were setting the picker container (holds the title and the picker) and the picker to be focusable. Only the picker needs to be focusable, so we can remove the tabIndex handling on the container.
This resolves the issue of focus being given to non-interactable elements via keyboard navigation and voice access.

[Designer Accessibility] Remove tabIndex from pickerContainerElement

---

source/nodejs/adaptivecards/src/card-elements.ts

Fixed #7976 
Image element with rendering error have been dropped in JS, but the behavior changed. This PR fixes the issue. 
```
{
"version": "1.5",
"body": [
{
"width": "72px", 
"height": "108px",
"url": "${image}",
"selectAction": {
"type": "Action.OpenUrl",
"tooltip": "${imageName}",
"url": "${games[1].pdpLink}"
}
}
]
}
```

reverted not dropping image element with rendering error

---

source/dotnet/Library/AdaptiveCards/AdaptiveTextInputStyle.cs
source/dotnet/Library/AdaptiveCards/docs/AdaptiveCards.md
source/dotnet/Test/AdaptiveCards.Test/AdaptiveInputTests.cs
source/dotnet/Test/AdaptiveCards.Test/Utilities.cs

https://microsoft.visualstudio.com/OS/_workitems/edit/41839375
* Added password style to Input.Text
https://github.com/microsoft/AdaptiveCards/blob/main/samples/v1.5/Elements/Input.Text.PasswordStyle.json
1. New unit tests that were added.

Dotnet 1.5 Input.Text Password stye

---

source/uwp/Renderer/lib/XamlHelpers.cpp

Fixes #7521
Updating input elements to set the accessible name in addition to the `labeledBy` property.
https://github.com/microsoft/AdaptiveCards/blob/5d4eab82c9dad4d49b45e17b8d86f62a48946627/samples/v1.3/Scenarios/InputsWithValidation.json
Verified on the UWP Visualizer.
Name now includes "Start time"

[UWP Renderer] Set accessible name for Inputs

---

source/nodejs/adaptivecards-designer/src/card-designer-surface.ts
source/nodejs/adaptivecards-designer/src/card-designer.ts
source/nodejs/adaptivecards-designer/src/containers/widget/widget-container-dark.css
source/nodejs/adaptivecards-designer/src/containers/widget/widget-container-light.css
source/nodejs/adaptivecards-designer/src/containers/widget/widget-container.ts
source/nodejs/adaptivecards-designer/src/strings.ts

Fixes #7958 
Removes border from Widgets Container if a background image has been set.
Also moved widget container styling changes to the WidgetContainer class.
https://github.com/microsoft/AdaptiveCards/blob/2facb28c481b7a16968158b81d2669853d689497/samples/v1.0/Scenarios/WeatherLarge.json
Verified manually on the AdaptiveCards designer.

[Designer] Remove border when background image is present and move logic to widget container class

---

source/uwp/Renderer/lib/AdaptiveChoiceSetInputRenderer.cpp

Fixes #7630 
When receiving focus via arrow keys, Radio Buttons should also be checked.
I added logic to the `PreviewKeyDown` event for Radio Buttons that:
- Checks if the up or down arrow was pressed
- Determines which radio button will receive focus next
- Set `IsChecked(true)` for that button
Can be tested with https://github.com/microsoft/AdaptiveCards/blob/45caa275735e210f27449570524d4f51a4aff40a/samples/v1.5/Scenarios/InputsWithValidation.json

[UWP Renderer] Check radio buttons when they receive focus

---

source/android/mobile/src/main/res/raw/importer_card.json

Fixes #8061 
Since we have moved samples to v1.5 and updated their names, the file paths for the samples needed to be updated.
I also removed Solitare.json (no longer supported), SimpleFallback.json (moved to elements), and ProductVideo.json (requires v1.6).
Verified manually on the visualizer.

[Android] Update the samples for the visualizer

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/layout/HorizontalFlowLayout.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/ImageSetRenderer.java

Fixes #7556 
Within the `onMeasure` method, we use the given `widthMeasureSpec` to get width.
I added an additional method `measureRequiredWidth` to sum the width of the view's children.
- If `MeasureSpec.getMode()` is `UNSPECIFIED`, we will use the calculated width.
- If `MeasureSpec.getMode()` is `AT_MOST`, we will use the calculated width only if it is less than the provided width.
- Otherwise, we will use the provided width.
```JSON
{
"version": "1.2",
"body": [
{
"columns": [
{
"width": "auto",
"items": [
{
"type": "ImageSet",
"images": [
{
"url": "https://www.webex.com/content/dam/wbx/us/images/rebrand/webex-logo.png",
"width": "50px", …
```

[Android] Calculate width for HorizontalFlowLayout

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRColumnRenderer.mm

Fixed #7903 
Added simple check that checks if a parent view of column is columnset.
verified manually with samples.

Fixed column rendering in places other than columnset

---

source/uwp/Renderer/dll/CppWinRTIncludes.h
source/uwp/Renderer/lib/ActionHelpers.cpp
source/uwp/Renderer/lib/AdaptiveActionRendererRegistration.h
source/uwp/Renderer/lib/AdaptiveActionSetRenderer.h
source/uwp/Renderer/lib/AdaptiveCardRendererComponent.cpp
source/uwp/Renderer/lib/AdaptiveCardRendererComponent.h
source/uwp/Renderer/lib/AdaptiveCardResourceResolvers.cpp
source/uwp/Renderer/lib/AdaptiveCardResourceResolvers.h
source/uwp/Renderer/lib/AdaptiveElementRendererRegistration.h
source/uwp/Renderer/lib/AdaptiveHostConfig.cpp
source/uwp/Renderer/lib/AdaptiveHostConfig.h
source/uwp/Renderer/lib/AdaptiveInputs.cpp
source/uwp/Renderer/lib/AdaptiveInputs.h
source/uwp/Renderer/lib/AdaptiveRenderArgs.cpp
source/uwp/Renderer/lib/AdaptiveRenderArgs.h
source/uwp/Renderer/lib/AdaptiveRenderContext.cpp
source/uwp/Renderer/lib/AdaptiveRenderContext.h
source/uwp/Renderer/lib/AdaptiveShowCardActionConfig.cpp
source/uwp/Renderer/lib/AdaptiveShowCardActionConfig.h
source/uwp/Renderer/lib/AdaptiveTextInputRenderer.cpp
source/uwp/Renderer/lib/AdaptiveTextInputRenderer.h
source/uwp/Renderer/lib/RenderedAdaptiveCard.cpp
source/uwp/Renderer/lib/RenderedAdaptiveCard.h
source/uwp/Renderer/lib/Util.h
source/uwp/Renderer/lib/XamlHelpers.h

N/A
Current references to the `::winrt::AdaptiveCards::Rendering::Uwp` namespace are inconsistent. Sometimes it is fully qualified, other times `Rendering::Uwp`, `Uwp`, or most often just `winrt` is used. This PR changes all references to use `winrt::`, except for with `ActionMode`, since there is a type of the same name in the ObjectModel. Here, we have an alias for the namespace, `render_xaml`, that we use in addition.
Manually tested UWP visualizer.

[UWP Renderer]: Make references to the ::winrt::AdaptiveCards::Rendering::Uwp namespace consistent

---

source/uwp/Visualizer/MainPage.xaml
source/uwp/Visualizer/MainPage.xaml.cs

Closes #8043
This PR will add shortcuts for the main interface buttons in UWP Visualizer and `AccessKeys` (alt + Accesskey) to use their functionality.
After ALT was pressed:
Tooltips:

[Accessibility|Visualizer]: Add shortcuts for interface buttons

---

source/nodejs/tests/ui-tests/src/ui-tests.test.ts

In the recent test runs `Image: Test select action can be clicked` was behaving inconsistently. The image that the test is trying to click was not loaded in time and the test failed. I believe it may be caused by network/image hosting server response time.
I've added a minimum wait to make sure image is loaded and test is consistent.

[Nodejs|UITests]: Add wait time for image load in failing test

---

source/uwp/Visualizer/AdaptiveCardVisualizer.csproj
source/uwp/Visualizer/MainPage.xaml

Fixes #8111 
Upgraded the minimum platform version so that we can add `KeyboardAcceleratorTextOverride` property to the `AppBarButton`.
Without the override text, the visualizer crashes while using Narrator.
Verified manually on the UWP visualizer with Narrator enabled.

[UWP Visualizer] Add override text for keyboard accelerator

---

source/uwp/Renderer/lib/AdaptiveContainerRenderer.cpp
source/uwp/Renderer/lib/AdaptiveTableRenderer.cpp
source/uwp/Renderer/lib/XamlHelpers.cpp

Fixes #8051
Table was not rendering because `TableCell` inherits from `IAdaptiveContainer` and `IAdaptiveContainerBase` and the container renderer casts the element to a `AdaptiveContainer`.
Updated to cast to both an `IAdaptiveContainer` and `IAdaptiveContainerBase`, then use the respective object when necessary.
https://github.com/microsoft/AdaptiveCards/blob/main/samples/v1.5/Scenarios/FlightUpdateTable.json

[UWP Renderer] Fix table rendering

---

source/uwp/Renderer/lib/AdaptiveChoiceSetInputRenderer.cpp

Fixes #8149 
Switch from `GettingFocus` event to `GotFocus` event.
https://github.com/microsoft/AdaptiveCards/blob/main/samples/v1.5/Scenarios/RestaurantOrder.json
Verified manually in UWP visualizer.

[UWP Renderer] Resolve crash in filtered choice set

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRImageSetUICollectionView.mm

Fixed #8044 
Added a ViewGroup view to hold target for actions.
```json
{
"body": [
{
"type": "ImageSet",
"images": [
{
"url": "https://adaptivecards.io/content/cats/1.png",
"selectAction": {
"type": "Action.OpenUrl",
"title": "cool link",
"url": "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
}
},
{
"url": "https://adaptivecards.io/content/cats/1.png",
"selectAction": {
"type": "Action.OpenUrl",
"title": "cool link",
"url": "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
}
}
]
}
]
}
```

Fixed imageSet select action issue

---

samples/Templates/Scenarios/FlightItinerary.template.json
samples/v1.5/Scenarios/FlightItinerary.json

Fixes #7839
Previously, we had the city name and the airport code in separate ColumnSets. This caused the focus order to be incorrect.
By consolidating these ColumnSets, we can get the correct focus order while using Narrator.
FlightItinerary.json

[Samples A11y] Consolidate ColumnSets in FlightItinerary

---

source/uwp/AdaptiveCardsObjectModel/lib/AdaptiveActionParserRegistration.cpp
source/uwp/Renderer/dll/CppWinRTIncludes.h
source/uwp/Renderer/lib/AdaptiveContainerRenderer.h
source/uwp/Renderer/lib/AdaptiveExecuteActionRenderer.h
source/uwp/Renderer/lib/AdaptiveFactSetRenderer.h
source/uwp/Renderer/lib/AdaptiveNumberInputRenderer.h
source/uwp/Visualizer/App.xaml.cs
source/uwp/Visualizer/Converters/ErrorViewModelConverters.cs
source/uwp/Visualizer/Converters/NotNullToVisibilityConverter.cs
source/uwp/Visualizer/GenericDocumentView.xaml.cs
source/uwp/Visualizer/Helpers/BindableBase.cs
source/uwp/Visualizer/Helpers/IListExtensions.cs
source/uwp/Visualizer/Helpers/PayloadValidator.cs
source/uwp/Visualizer/MainPage.xaml.cs
source/uwp/Visualizer/Properties/AssemblyInfo.cs
source/uwp/Visualizer/ResourceResolvers/MySymbolResourceResolver.cs
source/uwp/Visualizer/Settings.cs
source/uwp/Visualizer/TabView.xaml.cs
source/uwp/Visualizer/ViewModel/DocumentViewModel.cs
source/uwp/Visualizer/ViewModel/ErrorViewModel.cs
source/uwp/Visualizer/ViewModel/GenericDocumentViewModel.cs
source/uwp/Visualizer/ViewModel/HostConfigEditorViewModel.cs
source/uwp/Visualizer/ViewModel/KeyboardPressTimeCounter.cs
source/uwp/Visualizer/ViewModel/MainPageViewModel.cs

This change removes unnecessary explicit references to the `Windows::UI::Xaml` namespace. It removes unused `include`s from the AdaptiveCardsObjectModel project and `using`s from the Visualizer project. Additionally, it alphabetizes the `include`s in the Renderer's `CppWinRTIncludes.h`.
Built and ran tests.

[UWP Renderer] Clean up imports and usings in Renderer and Visualizer

---

source/nodejs/adaptivecards-site/themes/adaptivecards/source/css/style.css

Fixes #7866 
This PR contains two changes to meet high contrast requirements.
1. The `Get Started` button on the home page looks like a link since the blue background color is no longer present.
I added a border so that it is clearly a button.
2. Selected elements in the Schema Explorer navigation pane did not adopt the correct text color.
With changes:
Verified manually on the Adaptive Cards site. See above images.

[Website] Fix links and buttons in high contrast

---

samples/v1.6/Elements/Carousel.Loop.json
source/nodejs/adaptivecards/src/carousel.ts

Issue in external repository
Adds an additional schema property to `Carousel` element. `loop` will allow the card author to disable swiper looping (going from the last slide to the first slide).
`loop`
- boolean value
- defaults to `true` 
Sample card included in the PR.
Verified manually on the Adaptive Cards Designer

[JS Renderer] Add loop property to carousel

---

samples/v1.6/Elements/Image.ForceLoad.json
source/nodejs/adaptivecards/src/card-elements.ts

https://microsoft.visualstudio.com/OS/_workitems/edit/42514115
Unlike static image, animation has state. Due to caching, animation state cannot be reset. Added a forceLoad option that directs browser to fetch from the source instead of relying on its cache. 
Included in PR.
The first Image element doesn't have forceLoad property, and its animation doesn't get refreshed vs 2n image element that does.
https://user-images.githubusercontent.com/4112696/214984279-c58f8d7b-08fe-4735-80f7-f782eeadab37.mp4

added forceLoad option for image

---

source/nodejs/adaptivecards-site/themes/adaptivecards/layout/_partial/header.ejs

Fixes #7933 
When using voice access, numbers were shown for controls located under the popup.
By setting the popup window as a modal, Voice Access will recognize the popup as the foreground window and only show numbers for controls present within the popup.
**Note**: In order for this to work, focus must be on an element within the popup.
Verified manually on the AdaptiveCards site using Voice Access's "Show numbers" command.

[Website] Make UHF popup a modal

---

source/nodejs/adaptivecards-designer/src/toolbar.ts
source/nodejs/adaptivecards-site/themes/adaptivecards/layout/designer.ejs

Fixes #8167 
Added an optional parameter to the designer's `ToolbarButton`. If `isLink` is set to `true`, we will assign `role="link"` to the toolbarButton. `isLink` defaults to `false`.
This change ensures that Narrator announces buttons properly when they navigate to a new page.
Verified manually on the Adaptive Cards website.

[Designer] Add link option for toolbar buttons

---

source/nodejs/adaptivecards-site/themes/adaptivecards/layout/index.ejs

Fixes #8154 
`<ul/>` HTML elements cannot contain a `<div/>` as a child element. I restructured the lists on the homepage so that the title `<div/>` is not contained within the list.
Verified manually on the AdaptiveCards website. I also confirmed that Narrator behavior was not impacted.

[Website] Restructure lists on website homepage

---

source/nodejs/adaptivecards-designer/src/designer-peers.ts

Tracked in ADO
Added `orientation`, `heightInPixels`, and `loop` properties to the Designer.
Created new property editors and added them to the carousel property sheet.
Verified manually on the Adaptive Cards website.

[Designer] Add new carousel properties to the designer

---

source/uwp/ObjectModelProjection/ObjectModelProjection.vcxproj
source/uwp/winui3/AdaptiveCardsObjectModel/AdaptiveCardsObjectModel.vcxproj
source/uwp/winui3/ObjectModelCsProjection/ObjectModelCsProjection.csproj
source/uwp/winui3/Renderer/AdaptiveCardRenderer.vcxproj
source/uwp/winui3/RendererCsProjection/RendererCsProjection.csproj
source/uwp/winui3/SimpleVisualizer/SimpleVisualizer.csproj

#5888
The Adaptive Cards WinUI 3 renderer should support all platforms that WinUI 3 / WindowsAppSDK can run on. This change supports that by explicitly targeting the lowest supported version. This requires linking a few additional libraries, as well as setting a specific target on the ObjectModelProjection projct.
Build pipelines

[WinUI 3 Renderer] Change target platform to match WindowsAppSDK support

---

source/nodejs/adaptivecards-designer/src/containers/widget/widget-container-dark.css
source/nodejs/adaptivecards-designer/src/containers/widget/widget-container-light.css

Tracked in ADO
I added a top margin of `-27px` to the left and right carousel arrows for widget board styling.
The arrows have `top: 50%` styling, which meant the top of the arrow was centered. We needed to shift the arrow up so that the _center_ of the arrow was centered.
27 was found by taking half of the arrow height and half of the bottom margin (needed bottom margin because there is no top margin).
Verified manually in the Adaptive Cards designer.

[Designer] Fix top margin on carousel arrows

---

source/uwp/Renderer/lib/AdaptiveImageRenderer.cpp
source/uwp/Renderer/lib/XamlBuilder.h

N/A
Pass variables by const value instead of reference when the method will call `resume_foreground`. 
Verified manually

[UWP] Remove weak_ref from method headers and pass by value

---

source/dotnet/AdaptiveCards.sln
source/dotnet/Library/AdaptiveCards.Templating/AdaptiveCardTemplate.cs
source/dotnet/Library/AdaptiveCards.Templating/AdaptiveCards.Templating.csproj
source/dotnet/Library/AdaptiveCards.Templating/AdaptiveCardsTemplateVisitor.cs
source/dotnet/Library/AdaptiveCards.Templating/EvaluationContext.cs
source/dotnet/Library/AdaptiveCards.Templating/docs/AdaptiveCardsTemplate.md
source/dotnet/Library/AdaptiveCards/docs/AdaptiveCards.md
source/dotnet/Test/AdaptiveCards.Templating.Test/TestTransform.cs

Adds a `$host` parameter to the .NET Templating library (achieving parity with the `adaptivecards-templating` NPM package).
Basic idea: The app using the templating library can provide its own separate data blob to be used in the binding process. The structure of this data is not specified (similar to the root data blob that can already be supplied). This allows a host application to provide some environmental information for use by the template.

Add host parameter to AdaptiveCards.Templating

---

source/uwp/SharedVisualizer/Converters/ErrorViewModelConverters.cs
source/uwp/SharedVisualizer/Converters/NotNullToVisibilityConverter.cs
source/uwp/SharedVisualizer/CustomElements/CustomInput.cs
source/uwp/SharedVisualizer/ResourceResolvers/MySymbolResourceResolver.cs
source/uwp/SharedVisualizer/ViewModel/DocumentViewModel.cs
source/uwp/SharedVisualizer/ViewModel/GenericDocumentViewModel.cs
source/uwp/SharedVisualizer/ViewModel/HostConfigEditorViewModel.cs
source/uwp/SharedVisualizer/ViewModel/KeyboardPressTimeCounter.cs
source/uwp/SharedVisualizer/ViewModel/MainPageViewModel.cs
source/uwp/SharedVisualizer/Views/DocumentView.xaml
source/uwp/SharedVisualizer/Views/DocumentView.xaml.cs
source/uwp/SharedVisualizer/Views/ErrorTabView.xaml.cs
source/uwp/SharedVisualizer/Views/GenericDocumentView.xaml.cs
source/uwp/SharedVisualizer/Views/MainPage.xaml.cs
source/uwp/SharedVisualizer/Views/TabView.xaml.cs
source/uwp/winui3/AdaptiveCards.sln
source/uwp/winui3/Visualizer/AdaptiveCardVisualizer.csproj
source/uwp/winui3/Visualizer/App.xaml
source/uwp/winui3/Visualizer/App.xaml.cs
source/uwp/winui3/Visualizer/MainWindow.xaml
source/uwp/winui3/Visualizer/MainWindow.xaml.cs
source/uwp/winui3/Visualizer/Package.appxmanifest
source/uwp/winui3/Visualizer/Properties/launchSettings.json
source/uwp/winui3/Visualizer/app.manifest

https://github.com/microsoft/AdaptiveCards/issues/5888
This change adds a WinUI 3 version of the Adaptive Card Visualizer, matching functionality of the UWP version. A few changes needed to be made to the shared code to work with both versions of Xaml:
- The `GridSplitter` control moves to code behind. In markup, we can't change which namespace it comes from (System Xaml or WinUI 3 version) based on which version we are compiling.
- In WinUI 3, we don't have the `CoreWindow.Dispatcher`, so instead use Community Toolkit's `Microsoft.UI.Dispatching.DispatcherQueueController.DispatcherQueue.EnqueueAsync()`
- In WinUI 3, `ContentDialog`s need their `XamlRoot` to be set. To have this info, we have to cache the XamlRoot when we create the MainPageViewModel.
- In WinUI 3, `MessageDialog`s need …

[WinUI 3] Add Visualizer for WinUI 3

---

samples/v1.6/Elements/Action.Role.json
source/nodejs/adaptivecards/src/card-elements.ts
source/nodejs/adaptivecards/src/enums.ts

Progress towards #8041
Added a new property `role` to actions. The new property will allow the card author to specify an aria role for a buttons and improve their card's accessibility.
Proposal can be found here: https://github.com/microsoft/AdaptiveCards/issues/8041#issuecomment-1438924387
Added a sample card for v1.6
Verified manually in the designer with Narrator.

[JS] Add role property to actions

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/InputUtil.java

Fixes #7265
TalkBack announced `asterisk` instead of `required` when focusing on inputs.
Added `contentDescription` to input labels that includes `required` instead of `asterisk` for the default behavior.
https://github.com/microsoft/AdaptiveCards/blob/main/samples/v1.5/Scenarios/InputForm.json
Verified manually on the Android visualizer.
https://user-images.githubusercontent.com/98650930/228036498-a4582fec-8208-4314-b446-937434b3e7fa.mp4

[Android] Add content description to input labels

---

source/nodejs/adaptivecards-designer/src/containers/webchat/webchat-container.css

Fixes #8185 
Update the webchat container so that the width adjusts when the screen size is below `416px`. 
`416` was chosen because this the fixed size of the webchat container.
Sample card can be found in the issue.
Verified manually on the Adaptive Cards website.

[Designer] Update card container width for 400% zoom

---

source/uwp/Build/CopySignFilesWinUI3.cmd
source/uwp/ObjectModelProjection/ObjectModelProjection.vcxproj
source/uwp/winui3/NuGet/AdaptiveCards.ObjectModel.WinUI3.nuspec
source/uwp/winui3/NuGet/AdaptiveCards.Rendering.WinUI3.nuspec

The following changes were made to enable the release of the packages:
* Removal of ARM file references from the Nuget configs
* Addition of cmd script to perform copy of files for signing (TODO: Update scripts to have a single script)
* Updated platform toolset to make it easier to build on VS2022
* Updated nuget package versions

Fix pipeline issues for WinUI3 Release

---

README.md

Adding a release schedule for adaptive cards to the readme page.
This will serve as a schedule for ourselves and as a place where we can direct customers.

Add release schedule to readme

---

source/uwp/AdaptiveCardsObjectModel/AdaptiveCardsObjectModel.vcxproj
source/uwp/ObjectModelTest/ObjectModelTest.vcxproj
source/uwp/PerfApp/PerfApp.vcxproj
source/uwp/Renderer/AdaptiveCardRenderer.vcxproj

Update the platform toolset to v143 to match the changes made for winUI3 (https://github.com/microsoft/AdaptiveCards/pull/8459)
Change is needed for the UWP solution to build.
Confirmed that the project builds, and visualizer can be launched.

[UWP] Update platform toolset to 143

---

samples/Templates/Scenarios/InputsWithValidation.template.json
samples/v1.5/Scenarios/InputsWithValidation.json

Fixes #8187 
Add placeholder text to inputs.
InputsWithValidation.json in Samples
Verified manually on the UWP visualizer.

[Samples] Add placeholder text to inputs on InputsWithValidation.json

---

samples/Templates/Scenarios/ActivityUpdate.template.json
samples/v1.5/Scenarios/InputsWithValidation.json

Fixes #8188 
Add `"role": "button"` to `OpenUrl` actions that do not launch new windows. Since the url is not opened in the visualizer, we should not announce it as `link`.
https://github.com/microsoft/AdaptiveCards/blob/ade6c26c13be7e814a9a9eed46b69c46bdc1bda3/samples/Templates/Scenarios/ActivityUpdate.template.json
https://github.com/microsoft/AdaptiveCards/blob/ade6c26c13be7e814a9a9eed46b69c46bdc1bda3/samples/v1.5/Scenarios/InputsWithValidation.json
Verified manually on the UWP visualizer and tested with Narrator.

Add role property to samples

---

samples/Templates/Scenarios/FlightDetails.template.json
samples/v1.5/Scenarios/FlightDetails.json

Fixes #7829 
We have a decorative image within the FlightDetails sample that either needed `atlText` or no presentation. Since there is no suitable atlText and we do not have presentation modes enabled in our platform, I removed the decorative image.
FlightDetails.json from our samples

[Samples] Remove decorative image from FlightDetails sample

---

source/nodejs/adaptivecards-designer/src/containers/viva-connections/viva-connections-container-dark.css
source/nodejs/adaptivecards-designer/src/containers/viva-connections/viva-connections-container-light.css

Fixes #8369 
Fixes #8312
Updated the viva connections container to use 100% of available width if the screen size is below the desired width.
This ensures that the entire card is visible when the device resolution to 1280*1024 with 100% scale, and the Edge window has 400% zoom.
Sample cards can be found in the linked issues
Verified manually on the Adaptive Cards Designer

Update viva connections css

---

source/uwp/SharedRenderer/lib/AdaptiveTextInputRenderer.cpp
source/uwp/SharedRenderer/lib/InputValue.cpp

Fixes #8191
We need to add dynamic input validation so that all necessary information is announced by Narrator.
In `AdaptiveTextInputRenderer`:
- Validate the text each time it changes
In `InputValue`:
- Make the errorMessage a live region. I used `Assertive` so that the error is announced as soon as possible
- Whenever the errorMessage appears, we raise a `LiveRegionChanged` event so that Narrator will announce it.
https://github.com/microsoft/AdaptiveCards/blob/main/samples/v1.5/Scenarios/InputForm.json
https://user-images.githubusercontent.com/98650930/234417261-20ddb46b-8dfd-4d65-bdd5-cf6754431d13.mp4
**Note:**  This should be excluded from the v1.6 release since it is only implemented on UWP.

[UWP Renderer] Validate text inputs dynamically and make errors live regions

---

samples/v1.3/Elements/Action.Submit.json
samples/v1.3/Elements/Input.Number.json

Fixes #7914
Progress towards #7992
These samples include the `label` property for accessibility. They needed to be moved to v1.3 so that they are rendered at the correct version and the label appears.
In PR

[Samples] Move samples with label to v1.3

---

source/nodejs/adaptivecards-site/themes/adaptivecards/layout/sample.ejs

Fixes #8350 
HTML link elements cannot have `listitem` as `role`. I switched the role to `option` so that we can remove the error and the other aria properties are still valid.
This change required the parent element's role to be `listbox` and include `aria-label`
N/A
Verified manually on the samples page of our website by running the Accessibility Insights FastPass, and with Narrator.

[Website a11y] Update role for samples list on website

---

source/nodejs/adaptivecards/src/host-config.ts

Fixes #8358
Add `TextBlock` `headingLevel` to the default config. Without it, `heading-level` is not included on the HTML element, and it is required.
N/A
This can be tested by going to the `New Card` popup on the designer.
Verified manually on the `New Card` popup of the designer by running Accessibility Insights FastPass.

[AC Renderer] Add textBlock headingLevel to default config

---

source/nodejs/adaptivecards/src/adaptive-applet.ts
source/nodejs/adaptivecards/src/card-elements.ts
source/nodejs/adaptivecards/src/scss/adaptivecards-base.scss

When the user changes the text in the input field rapidly, a possibility exists that a new request might be sent when the previous request is still in progress. This is expected and the latest response must be shown in the choiceset.  We discovered a bug in a corner case that proved otherwise as the outdated results were not being cleared when the latest response came. In the current implementation, we cleared the old response only when a text change got detected which caused the bug because if the response from the old request had not come, there would be nothing to clear at that moment.
We can identify the latest request by comparing the filter sent in the request object to the text present in the input field. 
When a request is completed, we either process the freshly received choices …

Avoid outdated results in Dynamic Typeahead Input.Choiceset

---

source/uwp/SharedVisualizer/ViewModel/HostConfigEditorViewModel.cs

Fixes #8565
We cannot call AccessibilitySettings.HighContrastChanged with WinUI3 because it does not work without a core window.
Added an if block to resolve this error:
N/A
Verified manually in the WinUI3 and System.XAML visualizers

[WinUI3 Visualizer] Add if block for high contrast changed event

---

source/android/adaptivecards/build.gradle

Update NDK to 23 for react native. Teams app is crashing with latest reactnative package and will be updating NDK to 23 from 21. Need to update ndk here too
verified locally

Update NDK to 23 for react native

---

source/uwp/AdaptiveCardsObjectModel/AdaptiveCardsObjectModel.vcxproj
source/uwp/AdaptiveCardsObjectModel/packages.config
source/uwp/Renderer/AdaptiveCardRenderer.vcxproj
source/uwp/Renderer/packages.config
source/uwp/SharedRenderer/dll/CppWinRTIncludes.h
source/uwp/SharedRenderer/lib/AdaptiveImageRenderer.cpp
source/uwp/SharedVisualizer/ViewModel/DocumentViewModel.cs

Fixes #8558
Rendering an SVG in WinUI 3 is currently broken, since an access violation exception is thrown. WinUI 3 needs to use `SvgImageSource.DispatcherQueue()`, rather than UWP's `SvgImageSource.Dispatcher()`, which in WinUI 3 will always return `null`.
https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/migrate-to-windows-app-sdk/guides/threading#migrate-winrtresume_foreground-cwinrt
Also fixes an issue where the list of cards in AdaptiveCardsVisualizer wouldn't load.
If appropriate, please include a link to a card in one of the samples directories that can be used to validate this change. This can be an existing card or a card added with this PR.
Verified with AdaptiveCards/samples/v1.5/Tests/Image.Svg.json card as well as other cards containing svgs in base64.

Render SVG images in WinUI 3

---

source/nodejs/adaptivecards-designer/src/containers/outlook/outlook-container.css
source/nodejs/adaptivecards/src/scss/adaptivecards-default.scss

Fixes #8574
Updated the default button color for contrast requirements.
Schema explorer samples on website.
Verified manually

Update colors for contrast requirements

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/PrivateHeaders/ACOMediaEventPrivate.h

This prevent the missing header issue for MediaEventPrivate

Separate CocoaPods imports for MediaEventPrivate header.

---

source/nodejs/adaptivecards-designer/src/adaptivecards-designer.css
source/nodejs/adaptivecards-designer/src/card-designer.ts
source/nodejs/adaptivecards-designer/src/toolbar.ts

Fixes #8361 
Narrator needs to announce when a card payload is copied. The following changes were made:
- Add a css class `screen-reader-only` that hides the elements visually, but are still picked up by the screen reader. CSS adopted from: https://www.a11yproject.com/posts/how-to-hide-content/
- Add a `div` to the main toolbar to hold narrator alerts. Ensure that alerts are announced via `aria-live`
- When a card payload is successfully copied, add an alert to the pane
N/A - test with the generated site
Verified manually on the adaptive cards site. Verified with Narrator on Edge and Chrome. Did not work on firefox.

[Designer] Add alerts for narrator

---

source/ios/tools/AdaptiveCards.podspec
source/nodejs/ac-typed-schema/src/markdown/generate-markdown.ts
source/nodejs/adaptivecards-site/themes/adaptivecards/scripts/filter-table.js

Fixes #8360
The markdown to html generator does not include narrator support for the table title. To fix this, we need to include a custom table renderer.
Since markdown does not contain a title element, I added the following steps to detect the table title.
- Within the first header cell, append the appropriate title wrapped in braces
- When we generate the html, parse for the title within the braces
- Remove the title from the header html before returning it
The table title is then used as the `aria-label` and is announced properly by Narrator
N/A - see generated website
Verified manually on the AC site.

[Website] Custom table generator to include aria-label

---

source/nodejs/adaptivecards-site/themes/adaptivecards/layout/archive.ejs

Fixes #8541
Fixes #8542 
Remove `role="presentation"` from the links on the blog archives page. This role is invalid for the elements and caused another `tab-index` error since tab-index and presentation are not compatible.
N/A
Verified manually on the Adaptive Cards site with Accessibility Insights FastPass.

[Website] Remove presentation role from blog archives

---

source/nodejs/adaptivecards/src/card-elements.ts
source/nodejs/adaptivecards/src/controls/menu-item.ts
source/nodejs/adaptivecards/src/controls/popup-menu.ts

Fixed #8654.
As focus is moved to a menu overlay from a button, buttons aria-expanded state is not announced by voice over. moved the aria-expanded to menu item itself, where the focus is set. When menu item closes, have the focus to be back on the button with aria-expanded set to false. however, with keyboard navigation, when 'return' key is used to close the menu item, it will trigger click event on the button when the focus is back to the button. In order to stop such behavior, preventDefault() was used.
N/A

Fixed Overflow action button not announcing view chagnes

---

source/nodejs/adaptivecards/src/card-elements.ts

The `aria-required` attribute is only valid on elements (or elements with a role matching an element) that have a `required` HTML property. To specify `aria-required` on other elements violates WCAG rules.
Local build/test and Accessibility Insights verification

Remove unnecessary `aria-required` property from container element

---

source/nodejs/adaptivecards-site/themes/adaptivecards/source/css/extracted.css

The default `hljs-comment` color doesn't quite meet accessibility requirements, so pick a better color that does meet requirements:
old:
new:
local build/test + accinsights

Add `hljs-comment` color to fix contrast

---

samples/v1.0/Elements/Input.Time.json

For a11y we need to use the `label` property. This one just got missed.
designer

Switch from textblock to label in Input.Time sample

---

source/nodejs/adaptivecards-site/pages/_posts/2019/Community-Call-January.md

Simple change -- need a `title` on the `iframe` in this blog post for a11y
local build/devtools

Add missing `title` to `iframe` in blog post

---

samples/v1.1/Elements/Column.SelectAction.json
samples/v1.1/Elements/ColumnSet.SelectAction.json
samples/v1.1/Elements/Container.SelectAction.json
samples/v1.2/Tests/RichTextBlock.TextRun.SelectActions.json
samples/v1.3/Elements/Input.Text.InlineAction.json
samples/v1.5/Tests/Image.SelectAction.IsEnabled.json

This was a pretty interesting issue to track down... the [`Input.Text`](https://adaptivecards.io/explorer/Input.Text.html) `inlineAction` example's inline submit button didn't have its tooltip applied properly. However, the sample example worked just fine in the designer.
Turns out the examples are rendering with the version specified in the sample itself. I updated all of the samples referencing `tooltip` to be at least version `1.5`.
Future reference for anyone wanting to answer a question like "what is the version of all samples with the word 'tooltip' in them", here's something useful in WSL (you'll need to have `ripgrep` and `jq` available):
```sh
rg --files-with-matches tooltip | xargs -I _ sh -c "echo -n '_: ' && cat _ | jq .version"
```
sample output for above:
Local …

Fix site schema explorer render version

---

source/nodejs/adaptivecards-designer/src/adaptivecards-designer.css
source/nodejs/adaptivecards-designer/src/base-tree-item.ts
source/nodejs/adaptivecards-designer/src/card-designer.ts
source/nodejs/adaptivecards-designer/src/field-picker.ts
source/nodejs/adaptivecards-designer/src/tree-view.ts

This was a bit of a ride. Prior to this change, the Designer's treeview control is represented in the DOM by a structure something like this: 
```html
<ul role="tree">
<li role="treeitem">
<div role="treeitem">some stuff</div>
</li>
<li role="treeitem">
<div role="treeitem">
<div class="expandcollapsebutton">...</div>
<div>some more stuff</div>
</div>
<ul role="group">
<li role="treeitem"><div role="treeitem">oh look! a child item!</li>
</ul>
</li>
</ul>
```
Unfortunately, it's not valid to have `role="treeitem"` on an element unless its parent's `role` is either `group` or `tree`. It turns out that, while eliding the `role` on the `li > div` causes a11y tooling to stop complaining, it also totally breaks keyboard navigation -- the user can't actually select an element in the tree because …

[Designer] Fix treeview control accessibility

---

samples/HostConfig/viva-connections-dark.json
samples/HostConfig/viva-connections-light.json

Fixes #8714
The viva connections hosts were missing `aria-level` for textBlocks with the heading `role`. This is fixed by adding `headingLevel` to the host config.
Sample card in ticket.
Verified manually with accessibility insights.

[Designer] Add headingLevel to viva connections host config

---

source/nodejs/adaptivecards/src/card-elements.ts

Fixes #8700 
Add `role` `presentation` property to action image elements. With this change, altText is no longer required.
Sample card found in the issue.
Verified manually with accessibility insights.

[JS Actions] Update action icon role to presentation

---

source/nodejs/adaptivecards-aaf-testapp/webpack.config.js
source/nodejs/adaptivecards-controls/webpack.config.js
source/nodejs/adaptivecards-designer-app/webpack.config.js
source/nodejs/adaptivecards-designer/webpack.config.js
source/nodejs/adaptivecards-extras-designer/webpack.config.js
source/nodejs/adaptivecards-extras/webpack.config.js
source/nodejs/adaptivecards-react/webpack.config.js
source/nodejs/adaptivecards-templating/webpack.config.js
source/nodejs/adaptivecards-ui-testapp/webpack.config.js
source/nodejs/adaptivecards/webpack.config.js
source/nodejs/spec-generator/webpack.config.js

Building with NodeJS >16 yields errors complaining about deprecated hashing functions (`ERR_OSSL_EVP_UNSUPPORTED`). This is a known and intentional change in NodeJS to prevent using insecure hashing functions. It's a little overzealous in *this* case because the hashing function is just being used to break up chunks of code, but rather than having to opt everything into allowing insecure hashing functions, it's probably better to just make Webpack use a more recent function (i.e. [`xxhash64`](https://webpack.js.org/configuration/output/#outputhashfunction), the default in Webpack's next version).

[NodeJS] Update hashing algorithm for webpack

---

.pipelines/uwp-ci.yml
.pipelines/winui3-ci.yml

This change will fix failing pipelines due to:
##[error]Error: This task is deprecated. Please switch to using NuGetCommand@2's 'restore' option https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/nuget-command-v2

[Maintenance]: Migrate NugetRestore@1 to NugetCommand

---

source/uwp/SharedRenderer/lib/WholeItemsPanel.cpp

Looks like a simple mistake in the conversion to cppwinrt (`as` vs. `try_as`). The converted version would throw instead of quietly skipping the check...
**original**
https://github.com/microsoft/AdaptiveCards/blob/d6084118fe516aa1793370bda7378b7a7ccd1616/source/uwp/Renderer/lib/WholeItemsPanel.cpp#L469-L478
**converted**
https://github.com/microsoft/AdaptiveCards/blob/1dcef8c69715bd56cc4384ab2b1a80906e696922/source/uwp/Renderer/lib/WholeItemsPanel.cpp#L357-L363

[XAML] Fix for exception thrown in `WholeItemsPanel`

---

source/nodejs/adaptivecards/src/card-elements.ts

Simple addition of class to `ImageSet` element. As-is, this doesn't change anything, but it _does_ allow host applications to apply special styling to `ImageSet`s without a bunch of effort.

[NodeJS] Add `ImageSet` class to enable styling

---

source/nodejs/adaptivecards/src/card-elements.ts
source/nodejs/adaptivecards/src/controls/menu-item.ts
source/nodejs/adaptivecards/src/controls/popup-menu.ts
source/nodejs/adaptivecards/src/host-config.ts

This change adds the ability for a host to request that action overflow menus display the icons of the overflowed actions. This is off by default, but can be enabled with the new host config value `actions.showIconInOverflow`.
Before:
After:

[NodeJS] Add optional overflow menu icon rendering

---

source/nodejs/adaptivecards/src/card-elements.ts

Fixes #8733 
When hitting the Submit button, focus is sent back to the first checkbox in a multi select ChoiceSet if it is a missing required input. On receiving focus, Narrator reads information for **all** of the checkboxes within the ChoiceSet. Video of the behavior can be seen in linked issue.
Focusable elements are not meant to be nested. For compound ChoiceSets, we make the outer `div` focusable by setting a tabIndex. This is causing the unexpected behavior - When the `div` receives focus, information for all nested elements are read. This same issue is present when we _jump_ to focus on the first element within the div. When the outer `div` is not focusable, the behavior does not repro.
When focus is sent back to the first checkbox in a multi select ChoiceSet, only information for …

[NodeJS] Remove tab index from parent in compound inputs

---

source/uwp/SharedRenderer/lib/Util.cpp

UWP's `GetColorFromString` calls `strtol`, which is not locale-independent. This means that it may take a longer time than anticpated to convert a string to an int. The fix is to use [`std::from_chars`](https://en.cppreference.com/w/cpp/utility/from_chars), which is designed for parsing scenarios and is locale-invariant. While I was at it, I cleaned up the logic a bit.
This should fix ADO #45516745.

Move `GetColorFromString` away from `strtol`

---

source/uwp/SharedRenderer/lib/XamlBuilder.cpp

#8874 
The speak property is not being hooked up for UWP and WinUI3 renderers.
Setting the automation name for the card root using the speak property in the template.
Verified the fix by using the CalendarReminder sample in the Visualizer which has a speak property.
Narrator reads the speak property in the UWP and WinUI3 Visualizers.

Set automation name for root AC element in UWP/WinUI3 renderer

---

.pipelines/uwp-ci.yml

Contributors trying to create a pull request are getting hit with build failures when trying to run the uwp-ci pipeline as the access to the feed is limited to users inside a specific organization, trying to do a turn around for the build process.
Build

Add PAT usage for uwp-ci pipeline

---

source/uwp/SharedRenderer/dll/CppWinRTIncludes.h
source/uwp/SharedRenderer/lib/AdaptiveImageRenderer.cpp

#8892 
LoadFromUriAsync() gives a file not found error even if the file exists in WinUI3. Updated to read as string and parse into xml.
There is room for refactoring the SVG xml handling code. 
1. Existing test: https://github.com/microsoft/AdaptiveCards/blob/main/samples/v1.5/Tests/Image.Svg.json
2. `{
"version": "1.6",
"backgroundImage": {
"url": "https://adaptivecards.io/content/Mostly%20Cloudy-Background.jpg"
},
"body": [
{
"url": "https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/car.svg",
"size": "large"
}
],
"$schema": "http://adaptivecards.io/schemas/adaptive-card.json"
}`
Verified using the WinUI3 visualizer
1. https://github.com/microsoft/AdaptiveCards/blob/main/samples/v1.5/Tests/Image.Svg.json
2.

Update how svg image file is being read

---

source/nodejs/adaptivecards-site/package.json
source/nodejs/adaptivecards-site/themes/adaptivecards/scripts/generator-adaptiveassets.js
source/nodejs/package-lock.json

Turns out that some of my changes to site generation didn't work properly on Windows builders (I authored using WSL). Mostly this was due to path munging interacting poorly with `glob` in `generators-adaptiveassets.js`.
[Here's](https://microsoft.visualstudio.com/AdaptiveCards/_build/results?buildId=97502826&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=7cc137c2-61f2-5d65-b5f8-0e03d1af3170) a clean run showing that it works on Windows 👍🏼

[NodeJS] Fix site generation from Windows hosts

---

.pipelines/uwp-ci.yml

The `acNugetConnection` service connection being used in the `uwp-ci` job relies on a PAT to authenticate against our artifact feed. With PATs come expiry/rotation etc. - pain in the butt. But it turns out that by default if you don't specify a service connection, nuget will authenticate as the build agent, which _already_ has permissions to the feed, so we can just remove the connection altogether.

[CI] Don't use explicit service connection for nuget restore

---

source/nodejs/adaptivecards/src/card-elements.ts

Fixes #8902 
Remove innerHTML usage from dynamic typeahead feature. Now we construct the bold text with individual spans + styling.
```JSON
{
"version": "1.6",
"body": [
{
"id": "dynamicChoiceSet",
"label": "Enter the name of your team",
"placeholder": "AdaptiveCards",
"isRequired": true,
"errorMessage": "You must select a valid team",
"choices": [
{
"title": "Office",
"value": "1"
},
{
"title": "Teams",
"value": "2"
},
{
"title": "Outlook",
"value": "3"
}
],
"choices.data": {
"type": "Data.Query",
"dataset": "teamScopeInOrg",
"count": 15,
"skip": 0
}
}
]
}
```
Verified manually on the AC site. 
Example HTML:
Behavior remains the same: https://github.com/microsoft/AdaptiveCards/assets/98650930/23c9ecff-5507-4146-a064-db98b3932e62

Remove innerHTML usage from dynamic typeahead

---

source/uwp/SharedRenderer/lib/XamlBuilder.cpp

Add a style override to the root container named "Adaptive.RootContainer" so that custom margins can be applied
This style enables a host to set the margins of the container to be other than uniform.  This enables the background of the panel to bleed up into the frame for a card that may be contained in UI that provides a title bar.
Manually verified in a host that sets an OverrideStyles that contains a style with this name in its dictionary.

Add a style override to the root container named "Adaptive.RootContainer"

---

source/nodejs/adaptivecards/src/card-elements.ts

Fixes #8829
For multi select inputs, the group label is announced for each individual checkbox. We only want to announce the group label (which includes errors) for the first checkbox shown. After that, only the label directly associated with the textbox should be read.
```JSON
{
"schema": "http=//adaptivecards.io/schemas/adaptive-card.json",
"version": "1.5",
"body": [
{
"id": "",
"isVisible": false,
"separator": false,
"spacing": "default",
"bleed": false,
"items": [
{
"id": "",
"isVisible": true,
"separator": false,
"spacing": "default",
"width": "32px",
"height": "32px",
"horizontalAlignment": "center",
"size": "auto",
"style": "default",
"url": "https://localhost:4321/node_modules/myhub-viva-library/dist/LoadingSpinner_231a …
```

[JS renderer] Only add additional labels to the first checkbox in a multi select input

---

source/nodejs/adaptivecards-designer/src/adaptivecards-designer.css

Fixes #8897
Update height of the acd peer button to height of 24px because of a11y requirements.
N/A - designer issue
Will verify manually on PR site and add screenshots.

[a11y] Update acd-peerButton height to 24px

---

source/dotnet/Library/AdaptiveCards.Templating/AdaptiveCardsTemplateVisitor.cs
source/dotnet/Samples/WPFVisualizer/MainWindow.xaml.cs
source/dotnet/Test/AdaptiveCards.Templating.Test/TestTransform.cs

some template data was concatenated with string with template string inline which was unexpected.
fixe the issue by recursively calling the visit method to correctly call into correct visitor methods for each child parse tree identified.
N/A
Ran unit tests ; updated unit test and test message as it is not relevant anymore.
Ran manually examine the outputs

updated template logic to handle parse tree recursively

---

source/dotnet/Library/AdaptiveCards.Templating/AdaptiveCardsTemplateVisitor.cs

When template expression is expanded in the json value, it will double quotes wrapped.
This will fail in data binding phase as this needs to be deserialized.
Removes double quotes. We can also update parser, but this will fix this niche case.
N/A
Ran unit tests and verified manually.

remove double quotes when returned from value

---

source/dotnet/Library/AdaptiveCards.Templating/AdaptiveCards.Templating.csproj

8.0.3 System.Text.Json has a vulnerability.
Updated System.Text.Json to 8.0.4 to fix the vulnerability
N/A
Ran unit tests

updated system.json

---

source/uwp/SharedRenderer/lib/MediaHelpers.cpp
source/uwp/SharedRenderer/lib/Util.cpp
source/uwp/SharedRenderer/lib/XamlHelpers.cpp
source/uwp/UWPUnitTests/RenderTests.cs

For MSFT folks: https://microsoft.visualstudio.com/OS/_workitems/edit/52712745
Background Image with invalid URI would crash the entire app when we attempted to render it. This change addresses that and brings the behaviour on par with NodeJS renderer and drops the image in this case.  + added warning for text sources for mediasource for the similar problem.
```
{
"version": "1.6",
"backgroundImage" : "invalidURI",
"body": []
}
```
Verified locally that the BackgroundImage is being discarded as well as added unit test for this scenario.
TODO: follow up on https://github.com/microsoft/AdaptiveCards/issues/8967

[UWP/WinUI3 Renderer]: Discard Background Image if URI is not valid

---

source/dotnet/Library/AdaptiveCards.Templating/AdaptiveCardsTemplateVisitor.cs

n/a
Added pruning at $When evaluation.
There is no reason to continue evaluating the obj when the expression is evaluated to false.
Made changes to short-circuit when false.
n/a
1. Ran unit test
2. Tested manually.

updated when

---

source/dotnet/NuGet.config
source/uwp/winui3/NuGet.config

There were a couple of nuget configs not pointing to our internal nuget feeds. This fixes that.

[NuGet] Repoint to internal nuget feeds

---

source/uwp/winui3/ObjectModelCsProjection/ObjectModelCsProjection.csproj
source/uwp/winui3/RendererCsProjection/RendererCsProjection.csproj
source/uwp/winui3/SimpleVisualizer/SimpleVisualizer.csproj
source/uwp/winui3/Visualizer/AdaptiveCardVisualizer.csproj
source/uwp/winui3/WinUI3ObjectModelTest/WinUI3ObjectModelTest.csproj

Closes #9001
Any WinUI 3 apps that use Adaptive Cards and would like to update to WindowsAppSDK 1.6 will need Adaptive Cards to support CsWinrt 2.1.0+. This change updates that version. It also adds the WindowsSdkPackageVersion property, as described in   https://github.com/microsoft/CsWinRT/releases/tag/2.1.1.240807.2
N/A
Manually verified with AdaptiveCardVisualizer

Update CsWinRT for WinUI 3 renderer

---

source/uwp/AdaptiveCardsObjectModel/AdaptiveCardsObjectModel.vcxproj
source/uwp/ObjectModelProjection/ObjectModelProjection.vcxproj
source/uwp/Renderer/AdaptiveCardRenderer.vcxproj

AC is compiled with a newer vclib that may not be compatible with older vclibs.
When AC is run in Shufan's app, it runs against the older vclibs, causing a crash. 
The added preprocessor macro is an escape hatch.
The more detail can be found in [this link](https://stackoverflow.com/questions/78598141/first-stdmutexlock-crashes-in-application-built-with-latest-visual-studio)
N/A
Run sample cards.

add new preprocess macro def

---

source/uwp/AdaptiveCardsObjectModel/AdaptiveCardsObjectModel.vcxproj
source/uwp/HybridCRT.props
source/uwp/ObjectModelProjection/ObjectModelProjection.vcxproj
source/uwp/Renderer/AdaptiveCardRenderer.vcxproj
source/uwp/winui3/AdaptiveCardsObjectModel/AdaptiveCardsObjectModel.vcxproj
source/uwp/winui3/Renderer/AdaptiveCardRenderer.vcxproj

Fixes #9056
This PR follows the guidance at aka.ms/hybridcrt to switch the UWP/WinUI3 AdaptiveCard projects to use HybridCRT. This is accomplished simply by copying over the [HybridCRT.props](https://github.com/microsoft/WindowsAppSDK/blob/main/HybridCRT.props) and importing them to the appropriate projects, and specifying 	`<UseCrtSDKReferenceStaticWarning>false</UseCrtSDKReferenceStaticWarning>`
N/A

Switch WinUI3 + UWP AdaptiveCard projects to use HybridCRT

---

source/nodejs/adaptivecards-designer/src/adaptivecards-designer.css

Fixes #9013
Update color contrast on `acd-data-tree-item-additionalText` to meet requirements.
N/A
Verified manually on the website.

Update color contrast on designer

---

samples/Templates/Scenarios/ExpenseReport.template.json
samples/v1.5/Scenarios/ExpenseReport.json
source/nodejs/adaptivecards-designer/src/adaptivecards-designer.css

Fixes #8973
Fixes #8972
The ExpenseReport sample utilized ToggleVisibility which has a number of accessibility issues inherently. I refactored the sample to utilize ShowCard instead so that accessibility properties are set correctly.
New card:
Updated samples:
https://github.com/microsoft/AdaptiveCards/blob/a03d2f617cd272b05bfe6f971b19283a1902c629/samples/Templates/Scenarios/ExpenseReport.template.json
https://github.com/microsoft/AdaptiveCards/blob/a03d2f617cd272b05bfe6f971b19283a1902c629/samples/v1.5/Scenarios/ExpenseReport.json
Verified manually in the visualizer and updated confirmed that "Name" is set for the buttons via accessibility insights.

Refactor expense report sample to use showCard instead of toggleVisibility

---

source/dotnet/Library/AdaptiveCards.Templating/AdaptiveCards.Templating.csproj
source/dotnet/Test/AdaptiveCards.Templating.Test/AdaptiveCards.Templating.Test.csproj

N/A
The current version of the `Microsoft.Bot.AdaptiveExpressions.Core` package is `4.22.7`.
It is causing a strong naming issue.
Updated `Microsoft.Bot.AdaptiveExpressions.Core` Library Version
N/A
Verified using visualizer.

Updated template dependency

---

source/nodejs/adaptivecards-site/themes/adaptivecards/layout/explorer.ejs
source/nodejs/adaptivecards-site/themes/adaptivecards/layout/index.ejs

Fixes #9029
Fixes #9031
This pull request resolves two accessibility issues.
1. Add captions to the overview video on the main page of our website
2. Refactor the schema explorer index page to use `listbox` instead of `tree` roles for navigation. The previous implementation noted the full list as a tree and individual items as treeitems. This required that we implement additional keyboard functionality and that each section is collapsible. By refactoring to use `listbox`, we can simplify the keyboard navigation, and the list does not need to be collapsible.
N/A
Verified manually on the test site.

[Website][Accessibility] Refactor treeitems in schema explorer and add captions to overview video

---

source/uwp/SharedRenderer/lib/WholeItemsPanel.cpp

One of the partner teams discovered a bug that leads to a crash due to an invalid pointer read. This is regression that occurred during WRL -> Cpp/WinRT migration of the UWP codebase.
Verified locally and mentioned functionality in WholeItemsPanel works as expected now.

[Regression Fix]: Use FrameworkElement instead of empty statics for dependency property

---

source/dotnet/Library/AdaptiveCards.Templating/AdaptiveCards.Templating.csproj

https://github.com/dotnet/announcements/issues/329
Microsoft is releasing this security advisory to provide information about a vulnerability in System.Text.Json 6.0.x and 8.0.x. This advisory also provides guidance on what developers can do to update their applications to remove this vulnerability.
Package name | Affected version | Patched version
-- | -- | --
System.Text.Json | >= 8.0.0, <= 8.0.4 | 8.0.5
Updated the library to 8.0.5
N/A
Unit Tested.

Update library to fix vulnerability

---

source/uwp/SharedRenderer/lib/AdaptiveChoiceSetInputRenderer.cpp

When radio buttons are used in ChoiceSet, each ChoiceSets are grouped as one, and default value can be set only for the last ChoiceSet.
Add grouping for the radio buttons per ChoiceSet.
N/A
Manually Verified.

fixed grouping issue

---

source/nodejs/adaptivecards-designer/src/strings.ts

Fixes #9034 
Updated the accessible text to include more information for data binding buttons.
Narrator will now announce "Button Options for <property> Data Binding"
N/A
Validated on a local build of our site:

[Designer] Update data binding accessible text

---

source/uwp/SharedRenderer/lib/ActionHelpers.cpp
source/uwp/SharedRenderer/lib/ActionHelpers.h
source/uwp/SharedRenderer/lib/AdaptiveCarouselRenderer.cpp
source/uwp/SharedRenderer/lib/AdaptiveColumnRenderer.cpp
source/uwp/SharedRenderer/lib/AdaptiveColumnSetRenderer.cpp
source/uwp/SharedRenderer/lib/AdaptiveContainerRenderer.cpp
source/uwp/SharedRenderer/lib/AdaptiveImageRenderer.cpp
source/uwp/SharedRenderer/lib/AdaptiveMediaRenderer.cpp
source/uwp/SharedRenderer/lib/XamlBuilder.cpp

[task.ms/56300488](https://task.ms/56300488)
Inline Actions in UWP/WinUI3 renderers are not rendered using their respective renderer classes (like `AdaptiveExecuteActionRenderer` for example). They're rendered separately from usual `Action` codepath and they're missing link to the hosting card.
```
{
"body": [
{
"text": "You have clicked the button 0 times"
},
{
"type": "Input.Date",
"id": "CountdownDate",
"height": "stretch",
"isRequired": true,
"errorMessage": "Fill it out"
},
{
"type": "Input.Text",
"placeholder": "yoyo",
"id": "CountdownName",
"height": "stretch",
"isRequired": true,
"errorMessage": "Fill input text too"
},
{
"url": "https://adaptivecards.io/content/person_w1.png",
"selectAction": {
"type": …
```

[UWP/WinUI3 Renderer]: Add Input collection and validation for inline actions

---

source/dotnet/Library/AdaptiveCards.Templating/AdaptiveCards.Templating.csproj
source/uwp/SharedRenderer/lib/AdaptiveImageRenderer.cpp
source/uwp/SharedRenderer/lib/XamlBuilder.h

We are seeing heap corruption originating from the ResolveStream routine. All incidents point to a vector push operation where we push storeOp into m_writeAsyncOperations.
This pull request focuses on simplifying asynchronous operations and cleaning up unused code in the `AdaptiveCards::Rendering::Xaml_Rendering` namespace. The most important changes include modifying how asynchronous operations are handled and removing unnecessary member variables.
Simplification of asynchronous operations:
* [`source/uwp/SharedRenderer/lib/AdaptiveImageRenderer.cpp`](diffhunk://#diff-de9d0ba940c42728791a67c0d035838b4ab1fe530b4bc435dcaeab9efecef1b1L321-L334): Simplified the asynchronous write operation by calling `dataWriter.StoreAsync().get()` directly and removing the associated coroutine logic.
Code …

Remove a Vector

---

source/nodejs/adaptivecards-site/themes/adaptivecards/layout/archive.ejs
source/nodejs/adaptivecards-site/themes/adaptivecards/layout/designer.ejs
source/nodejs/adaptivecards-site/themes/adaptivecards/layout/explorer.ejs
source/nodejs/adaptivecards-site/themes/adaptivecards/layout/index.ejs
source/nodejs/adaptivecards-site/themes/adaptivecards/layout/post.ejs
source/nodejs/adaptivecards-site/themes/adaptivecards/layout/sample.ejs

This PR updates the AC web site to include banners prompting users to visit the new Adaptive Card Documentation Hub at https://adaptivecards.microsoft.com.

Add banners in the web site to redirect users to the new https://adaptivecards.microsoft.com AC documentation hub

---

source/uwp/winui3/SimpleVisualizer/SimpleVisualizer.csproj
source/uwp/winui3/Visualizer/AdaptiveCardVisualizer.csproj

Fixes #9102 
2 Projects contained transitive dependencies on vulnerable versions of Newtonsoft.Json caused by Newtonsoft.Json.Schema v[3.0.14](https://www.nuget.org/packages/Newtonsoft.Json.Schema/3.0.14#dependencies-body-tab). This change makes a hard dependency on the non-vulnerable version 13.03, like the rest of the project.
1. Confirmed project built.

Create hard dependency on non-Vulnerable Newtonsoft.Json for projects leveraging Newtonsoft.Json.Schema

---

source/nodejs/adaptivecards-designer/src/containers/teams/teams-container-dark.css

https://github.com/microsoft/AdaptiveCards/issues/9070
In dark mode, the color contrast ratio of 'Learn more', w.r.t background color is 2.23:1, which is less than 4.5:1
So fix the issue by changing the hyper link color
Ran the website locally and verified the contrast ratio using accessibility tool

Fixing Accessibilty color contrast ratio issue on hyper link
